### ISSUE TITLE
QC REPORTS

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#102]
giving me an empty table.
so i can't really check anything

**Comment by mei309** [comment]
you changed the function?
because by me its working

**Comment by litzvi** [comment]
Don't think so. try using my last version 3.6

**Comment by mei309** [comment]
now its not working. you changed the function

**Comment by litzvi** [comment]
I don't see any comment. what function did i change?

**Comment by mei309** [comment]
its showing by me with version 3.6

**Comment by mei309** [comment]
i cant find the difference

**Comment by litzvi** [comment]
can you please use my dump?

**Comment by mei309** [comment]
i used it.

**Comment by mei309** [comment]
maybe you did a roasting one. so i added the othor tab for it

**Comment by litzvi** [comment]
yes, i PROBABLY put in a roasting one

**Comment by litzvi** [comment]
THE ITEM DROP DOWNS IN QC ARE FILTERING BY ITEM SUPPLY GROUP - you are using getCashewItemsBasic().
It's not exactly true because it should show in raw only raw and roasted.
We need to get on the same page regarding items. try to write down all the item drop downs and exactly what we need in every one, so we can organize it better.

**Comment by mei309** [comment]
> yes, it's put in a roasting table.
> It's a receiving qc, seems like you dividing it by item. It's not correct.
> also for ws/lp it's putting in the roast checks tab.
> Anyhow, you should call it receipt_qc and roast_qc

im not dividing nothing. im using your functions getRawQualityChecks and getRoastedQualityChecks

**Comment by mei309** [comment]
> THE ITEM DROP DOWNS IN QC ARE FILTERING BY ITEM SUPPLY GROUP - you are using getCashewItemsBasic().
> It's not exactly true because it should show in raw only raw and roasted.
> We need to get on the same page regarding items. try to write down all the item drop downs and exactly what we need in every one, so we can organize it better.

ok.

**Comment by litzvi** [comment]
SO YOU MIXED UP THE RAW AND ROAST TABS OF 'New Raw Check' and 'New Roast check'

**Comment by mei309** [comment]
im using  getRawQualityChecks for the raw tab
and getRoastedQualityChecks for the roast

**Comment by mei309** [comment]
they in QualityChecks

**Comment by litzvi** [comment]
you are **adding** the wrong one

**Comment by litzvi** [comment]
I'm adding raw and your calling roast.
why don't you try to reproduce my errors?

**Comment by mei309** [comment]
its working now by me so donload my new angular
