### ISSUE TITLE
Inventory -> transfer with count

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#103]
the heading should be 'Transfer with weights' or 'Transfer with weights' not with samples.
perhaps it's clearer for them if you call it 'weighing' and not counts (counts i did for us, so we can use not only for weighing)

so I propose:
 'Transfer with weighing' heading and in menu
'weighings' in the sub header instead of Count
'

**Comment by litzvi** [comment]
also why do you display a default zero in amount?

**Comment by litzvi** [comment]
also why do you display a default zero in amount?

**Comment by litzvi** [comment]
also not showing total in Inventory item details->Item counts

**Comment by mei309** [comment]
> also why do you display a default zero in amount?
i will fix

**Comment by mei309** [comment]
> also why do you display a default zero in amount?

you giving me numberUsedUnits = 0.
you should give null or empty

**Comment by litzvi** [comment]
because it's inventory, it's correct that 0 is used. but you shouldn't show it in this context if possible.
if not possible, i'll try changing.

**Comment by mei309** [comment]
> also not showing total in Inventory item details->Item counts
> 
> that's because i changed to usedCountDifference and producedCountDifference
> so the i can later broaden the option to do counts relative to usedItems or processItems.
> now use usedCountDifference

in the new version (3.6) you changed it back?????

**Comment by litzvi** [comment]
oh sorry I wrote that I changed it back

**Comment by litzvi** [comment]
you can change the name in ProcessRow
getCountDifference or getUsedCountDifference line 124.
whatever you decide i'll change it by me

**Comment by mei309** [comment]
i dont mind so leave as now
