### ISSUE TITLE
TRANSFERS

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#105]
WHEN I TRANSFER A PO IT GIVES ME THE WASTE ALSO, WE NEED TO THINK HOW TO AVOID IT.
And it's not working either. I'll upload a dump with one po try to transfer only the w320 roast not the waste - dump_error_1
But I don't think it happened before, so see what changed by you.

**Comment by mei309** [comment]
its working by me

**Comment by litzvi** [comment]
SO i don't know what's going on. we not working the same code

**Comment by mei309** [comment]
whats up with it??

**Comment by litzvi** [comment]
i need to wait for issue 130 in order to check

**Comment by litzvi** [comment]
Still the same problem. I'll send a screenshot

**Comment by litzvi** [comment]
It also shows waste items in the count

**Comment by mei309** [comment]
> Still the same problem. I'll send a screenshot.
> my waste supply category is NONE, so you have a way to avoid it.
> Waste would probably be moved another way, not under this process.

its working to transfer only the item? or not?

**Comment by mei309** [comment]
i will avoid it by the group name

**Comment by mei309** [comment]
not by the item

**Comment by litzvi** [comment]
Why not by supply category, that's what it's made for

**Comment by mei309** [comment]
its not useful for me. the group is way better

**Comment by litzvi** [comment]
It's needed because the reason is that it's **Cashew** Transport, not because of the group

**Comment by mei309** [comment]
> It's needed because the reason is that it's **Cashew** Transport, not because of the group.
> Doing it by the group is a bandage

im using the group

**Comment by litzvi** [comment]
Do you understand why it's wrong?
