### ISSUE TITLE
QC check

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#107]
I wrote about it already and you ignored it.
When adding a Raw Check by percentage, later when editing and adding another tab i jumps to weights.

**Comment by mei309** [comment]
can you give in CashewQcRow percentage filed?

**Comment by mei309** [comment]
i didnt ignore. i did it not perfect

**Comment by litzvi** [comment]
IT'S STILL EXACTLY THE SAME

**Comment by mei309** [comment]
> can you give in CashewQcRow percentage filed?

???

**Comment by litzvi** [comment]
you have a percentage field.
in CashewItemQualityDTO:
Boolean precentage;

**Comment by mei309** [comment]
> you have a percentage field.
> in CashewItemQualityDTO:
> Boolean precentage;

is it diffecult to put it in CashewQcRow?? it will be a lot easier for me to manage the nevgtion

**Comment by litzvi** [comment]
why enforce it to be different processes in the first place? why can't we put in percentage by row?
It's way more flexible - that way you don't need to tabs in the menu for it.

**Comment by litzvi** [comment]
you can add the following 2 lines in CashewQcRow:
a field:
	private Boolean precentage;
in the construtor:
		this.precentage = precentage;

**Comment by mei309** [comment]
> why enforce it to be different processes in the first place? why can't we put in percentage by row?
> It's way more flexible - that way you don't need 2 tabs in the menu for it.
> defiantly I will also put it in CashewQcRow.
> 
> what do you say?
i want to do it but its way more complicated so it will need to wait and im not sure i will manage

**Comment by litzvi** [comment]
OK. so not now. 
You have the percentage as you asked in version 3.7

**Comment by mei309** [comment]
ALL LABELS enhancement MEANS I WILL DO IT LATER

**Comment by mei309** [comment]
and then have only one page

**Comment by litzvi** [comment]
yes. that's what i meant

**Comment by mei309** [comment]
i did it on the weight one please see if its better

**Comment by mei309** [comment]
and then i will add a nice title and remove the extra links

**Comment by litzvi** [comment]
like this it looks weird
why don't you just let them choose the beginning of the tab (with toggle button or something like that) if it's weights (default) or percentages?

**Comment by mei309** [comment]
i can't

**Comment by mei309** [comment]
we need to choose one of the options

**Comment by litzvi** [comment]
this is quite ugly.
what about have a button to add add a tab and choose in a popup?

**Comment by mei309** [comment]
i will leave the weights outside and do a popup for percentage

**Comment by mei309** [comment]
thats good?

**Comment by mei309** [comment]
check the new one i did and tell me if its better

**Comment by mei309** [comment]
look in raw weights tab

**Comment by litzvi** [comment]
The percentage test is great.
Do everything like that.
----------
Now the label says 'Edit percentage test', change to the item.
Can't add another test for percentage - so fix that too.
---
I think there should be a buttons ['Add Item test (by percentage)', 'Add Item test (by weights)'] that stay all the time (so can add multiple of every one.
After adding you have tabs for every tested item.

**Comment by litzvi** [comment]
If you don't understand, we can discuss by phone.

**Comment by litzvi** [comment]
By the way, now it's not working.
I tried to add a test with percentage and it doesen't work.

**Comment by mei309** [comment]
> ## The percentage test is great.
> Do everything like that.
> ## Now the label says 'Edit percentage test', change to the item.
> Can't add another test for percentage - so fix that too.
> I think there should be a buttons ['Add Item test (by percentage)', 'Add Item test (by weights)'] that stay all the time (so can add multiple of every one.
> After adding you have tabs for every tested item.

cannot do

**Comment by litzvi** [comment]
> cannot do
everything??

**Comment by mei309** [comment]
or i show buttons for every tested items or tabs for all i cannot do both

**Comment by litzvi** [comment]
we spoke about it already
