### ISSUE TITLE
Garbage is deleting everything in the tables

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#109]
including the numbers

**Comment by mei309** [comment]
whats the problem with that?
and if its a problem so where is it??

**Comment by litzvi** [comment]
TRY DOING A PRODUCTION PROCESS AND USE THE GARBAGES. SEE FOR YOURSELF

**Comment by mei309** [comment]
ha ok.

**Comment by litzvi** [comment]
is this fixed?

**Comment by mei309** [comment]
no. it will be done later

**Comment by mei309** [comment]
fixed

**Comment by litzvi** [comment]
not fixed in Roasted Amounts table

**Comment by mei309** [comment]
i remove the table. what else should I do?

**Comment by litzvi** [comment]
you want it to be back as in the beginning, so we can fill the data again.
you only need to remove information

**Comment by mei309** [comment]
we said to leave it for restore

**Comment by mei309** [comment]
if i give to write again we will not have the option to restore

**Comment by litzvi** [comment]
oh i forgot
