### ISSUE TITLE
Order information and management

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#11]
Can't reach order information when not in [Cashew Orders -> open ] tab
e.g. cancelled, received
From schedules can't manage.

**Comment by mei309** [comment]
added all orders tab. but you giving me everywhere ['RECEIVED', 'REJECTED'] in the order status dto.view->PoItemRow

**Comment by litzvi** [comment]
i'm getting all open, let me check

**Comment by litzvi** [comment]
perhaps you received, cancelled and then received again?
please check what happens when you add a new order and don't receive,
then when you receive and then if you cancel

**Comment by mei309** [comment]
it looks ok now.
