### ISSUE TITLE
EDITING USED FROM TABLES

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#110]
JUST A REMINDER TO ALLOW ADDING BAGS TO THE USED ITEMS.
IT'S IMPORTANT, I NEED TO DO IT ALL THE TIME, BECAUSE I MISSED A BAG, WHEN PROCESSING IN PARTS.

**Comment by mei309** [comment]
it will take time therefor it will be only on your vaction

**Comment by mei309** [comment]
its ready
