### ISSUE TITLE
Tool bar buttons

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#111]
pressing tool bar/tab button while in that tab has no reaction - should be fixed, it's bad responsiveness.

**Comment by mei309** [comment]
it looks like working in all the pages. if you see it dose something strange or if we need anothr place let me know

**Comment by litzvi** [comment]
It's not working.
for example, when in Production->New->Roasting after choosing the po,
if you choose new again, it already has the po and can't enter.

**Comment by mei309** [comment]
ok fixed

**Comment by litzvi** [comment]
Reports->full po details
tab not working while in page

**Comment by mei309** [comment]
> Reports->full po details
> tab not working while in page

you can change a po so no need

**Comment by litzvi** [comment]
don't understand. why no need? all buttons have to be responsive

**Comment by mei309** [comment]
ok
