### ISSUE TITLE
Supplier name all around

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#113]
Ahron asked to add a column of supplier name all around - received orders, inventory, processes etc.
Do only when your finished other tasks.

**Comment by mei309** [comment]
what you think about showing it with the poCode? (same cell)

**Comment by litzvi** [comment]
not a good idea. because the whole point of it, is to search from the table by supplier

**Comment by mei309** [comment]
so will you give it to me like CashewQcRow or i need to extract it from the poCode?/?

**Comment by litzvi** [comment]
it's double data, but sure i can give you.
do you want?

**Comment by mei309** [comment]
i dont mind how but i want everywhere the same

**Comment by mei309** [comment]
so decide whice one you want

**Comment by litzvi** [comment]
Receipt Row has
PoRow has

**Comment by mei309** [comment]
or everywhere we have basicPoCode and supplierName
or just a poCode

**Comment by litzvi** [comment]
> or everywhere we have basicPoCode and supplierName
this one

I only need to add for ProcessRow and InventoryRow. I'll do it now

**Comment by mei309** [comment]
when you upload a new  version let me know

**Comment by litzvi** [comment]
pushed version 3.7

**Comment by mei309** [comment]
DONE

**Comment by litzvi** [comment]
please put supplier straight after po.
and add supplier in Inventory by po

**Comment by mei309** [comment]
ok. next version you will have it

**Comment by mei309** [comment]
add in ApprovalTaskDTO for task table 
add in UserMessageDTO for massages

**Comment by litzvi** [comment]
done from version 3.9.
Be aware that their can be approvals and messages that don't have that don't have a po code at all, so I think it shouldn't be the first field.

**Comment by mei309** [comment]
add in UserMessageDTO in line 50 this.supplierName = supplierName;
you just forgot.
and then close the issue

**Comment by litzvi** [comment]
done
