### ISSUE TITLE
receipt - storageWithSamples

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#115]
you aren't setting the sampleContainerWeight field

**Comment by mei309** [comment]
i dont really understand what you mean. i have it in both

**Comment by litzvi** [comment]
just try putting in a receipt (without order) and fill in container weight for samples (a few for the average) 
then look in the database table storage_sample and you will see sampleContainerWeight is empty

**Comment by mei309** [comment]
recipit fixed
