### ISSUE TITLE
reports->full po details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#118]
checked items

Checked by | CASHEW_RECEIPT_QC
-- | --

probably because using process type instead of 'avc lab' etc.

**Comment by mei309** [comment]
yup

**Comment by mei309** [comment]
probably we should have somehow values for the processs names

**Comment by litzvi** [comment]
I added a mandatory value for ProcessType and CashewStandard, so add it in the setup tables. also might require rebuilding the database.
At the moment when I'm adding the processes in the data loader, I'm just giving the same name in a displayable manner (e.g. Cashew Receipt QC)
I don't think it's a solution For the Checked By, because processType value should describe the process type not what company checked it.

What do you think I make them all one processType and put a checkedBy field of a company or something. Do you remember why I insisted to make them different processTypes in the first place? I remember you asked me and I had a reason, just can't recall it now.

**Comment by litzvi** [comment]
perhaps I should add String checkedBy to CashewQcRow

**Comment by mei309** [comment]
> I added a mandatory value for ProcessType and CashewStandard, so add it in the setup tables. also might require rebuilding the database.
> At the moment when I'm adding the processes in the data loader, I'm just giving the same name in a displayable manner (e.g. Cashew Receipt QC instead of CASHEW_RECEIPT_QC)
> I don't think it's a solution For the Checked By, because processType value should describe the process type not what company checked it.
> 
> What do you think I make them all one processType and put a checkedBy field of a company or something. Do you remember why I insisted to make them different processTypes in the first place? I remember you asked me and I had a reason, just can't recall it now.
> Meanwhile I added a field String checkedBy, set it and get it for display.

i dont see a reason not to change.
i just remeber that  i didnt like your replay

**Comment by mei309** [comment]
if you changing we dont really need the value in processType

**Comment by litzvi** [comment]
value is used in more places, e.g display in message.  
Fits the structure of ValueEntity.
It may have more advantages, giving flexibility for future changes and displaying of processes by type.

**Comment by mei309** [comment]
so are you changing all to the same process?

**Comment by litzvi** [comment]
we can.
I don't need to change anything, just use 1 method for all.
Once everything works I'll remove the other ones

**Comment by litzvi** [comment]
please comment lines 71 - 91 in QualityChecks.java
just to see that you aren't using them by mistake.

**Comment by mei309** [comment]
addRoastedCashewCheck im using the rest not

**Comment by litzvi** [comment]
exactly. ok new version I commented
