### ISSUE TITLE
full po details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#119]
what do you think about the idea of putting everything vertically?

or have lines that can open for every process?

why did you take away the management button from checked items? you can put the button in the table.

**Comment by mei309** [comment]
or have lines that can open for every process? will do this.

**Comment by mei309** [comment]
why did you take away the management button from checked items? you can put the button in the table. will be

**Comment by litzvi** [comment]
when you prepare these reports they should be printable, we are dealing with paper people

**Comment by mei309** [comment]
i tried and it looks very strange and its easy to change so we will do it later when it will be to much

**Comment by mei309** [comment]
look in the reports and decide whichever you want.
and also see graph tab and comment about it

**Comment by litzvi** [comment]
> look in the reports and decide whichever you want.

looks good. two comments: 50% of the words in the page are "All", don't start a tab, header or anything with "All", specially not repeatedly

> and also see graph tab and comment about it

won't go into it now

**Comment by mei309** [comment]
the opening tab or the opened one?

**Comment by litzvi** [comment]
both

**Comment by mei309** [comment]
to leave both?

**Comment by litzvi** [comment]
I think the new one is enough

**Comment by mei309** [comment]
ok

**Comment by litzvi** [comment]
still have "All receiving" in the header of receipts

**Comment by mei309** [comment]
Also call 'transfer' "transport cashew" - that's what they call it in the papers.
its not necessarily true

**Comment by mei309** [comment]
i did it
