### ISSUE TITLE
Editing cleaned amounts

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#120]
edditing cleaning with cleaned in table, doing weird stuff.
changing ordinals, adding empty cells in the begining.

**Comment by mei309** [comment]
i need to reproduce it. so more details.
if might happen if i dont get it ordinal

**Comment by litzvi** [comment]
Now I give it to you in ordinal order.
if you see anything that isn't, let me know

**Comment by mei309** [comment]
its working by me just fine
