### ISSUE TITLE
Production reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#122]
add total difference (if done in a few processes

**Comment by litzvi** [comment]
In production reports, say they packed a po in a few parts, they usually write the total difference for the whole po packed.
Is it possible to do the adding by you when you group it by PO? because I'm giving you separate rows by process, regardless of po, so I don't really have where to put it. Only if it's easy

**Comment by mei309** [comment]
> In production reports, say they packed a po in a few parts, they usually write the total difference for the whole po packed.
> Is it possible to do the adding by you when you group it by PO? because I'm giving you separate rows by process, regardless of po, so I don't really have where to put it. Only if it's easy

its posible

**Comment by mei309** [comment]
ok i did it

**Comment by litzvi** [comment]
you're calculating kg and lbs the same.
I get total difference: 

Total difference
--
-68.534 KG (-68.534 LBS)

**Comment by mei309** [comment]
> you're calculating kg and lbs the same.
> I get total difference:
> 
> ## Total difference
> -68.534 KG (-68.534 LBS)

but its correct for one of them?

**Comment by mei309** [comment]
just a stupid mistake. fixed
