### ISSUE TITLE
cancel processType

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#125]
its also making problems with edit because of lazy loading and also we arent using it for qc since we put it in the testedItem

**Comment by mei309** [comment]
process.getProcessType() gives null in editAlerts in ProcessInfoDAO

**Comment by mei309** [comment]
its important

**Comment by litzvi** [comment]
sorry I don't understand

**Comment by litzvi** [comment]
> iprocess.getProcessType() gives null in editAlerts in ProcessInfoDAO

I removed it in the description, so it shouldn't make problems. (see ProcessInfoDAO.java 166,169,189,192)
It was the wrong place to determine the description anyway

**Comment by litzvi** [comment]
I'm using processType for management alerts

**Comment by mei309** [comment]
i mean we dont need the value

**Comment by litzvi** [comment]
the value is not what's causing the problems.
I already wrote the reasons I rather keep it this way in another issue
