### ISSUE TITLE
RECEIVE CASHEW - display issue

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#126]
After filling in samples, received weight and price per unit are separated (only some times).
They should be together (extra requested too?), maybe you can put them on the bottom in the first place

**Comment by mei309** [comment]
check now

**Comment by litzvi** [comment]
I think it's good enough.

**Comment by litzvi** [comment]
Another issue I just realized, in edit it doesn't show Ordered item drop down.
Do you think it's a problem? I need to add it?
