### ISSUE TITLE
com.avc.mis.beta.controllers.QcController.addCashewReceiptCheck(QualityCheck, String type)

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#127]
you aren't sending the type, but still calling this function.
change the function or send the type.
I guess the Angular and controllers aren't synchronized by me

**Comment by litzvi** [comment]
we should consider bugs priority.

**Comment by mei309** [comment]
im waiting for you to change all raw qc to the same process

**Comment by litzvi** [comment]
like I wrote in another issue, just use the same one by you.
When it will work smoothly I'll remove the other ones.
