### ISSUE TITLE
Can't add CashewStandard

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#128]
I added a mandatory value for CashewStandard.
please add it in Management->setup

**Comment by mei309** [comment]
ok added. even so its very not clear what they need to fill

**Comment by litzvi** [comment]
call it description or something

**Comment by mei309** [comment]
ok changed

**Comment by litzvi** [comment]
You're mixing up description with Standard organzion: avc123
input standard name and then Edit CashewStandards you'll see you are showing 'avc lab'

**Comment by mei309** [comment]
@Override
	public String getValue() {
		return String.format("%s", this.standardOrganization);
	}

**Comment by mei309** [comment]
in values CashewStandard

**Comment by litzvi** [comment]
oh forgot to delete.
version 4.2

**Comment by mei309** [comment]
done
