### ISSUE TITLE
Process type should display value

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#129]
in messages and tasks

**Comment by mei309** [comment]
you only giving me name

**Comment by litzvi** [comment]
I changed it, now the field is called processType (prv. processName), so please present it in messages and tasks.

**Comment by litzvi** [comment]
> you only giving me name

it was for me, now it's for you

**Comment by litzvi** [comment]
version 4.2 will have it

**Comment by mei309** [comment]
ok done

**Comment by mei309** [comment]
or i need processName in UserMessageDTO or you need to change the function 
public PoProcessDTO getProcess(int processId, ProcessName processName) {
to be without processName because i dont have a different way to get it

**Comment by mei309** [comment]
ok for now
