### ISSUE TITLE
Receiving cashew schedule - showing cancelled orders

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#13]
I think u r using Orders.findAllCashewOrderItems() which also shows cancelled orders.
Should probably use Orders.findOpenCashewOrderItems()

**Comment by mei309** [comment]
because we wanted to show the received as well. so build a function that gets recievid + open

**Comment by litzvi** [comment]
Correct, i changed the function so now cancelled orders don't appear - no need to change anything for schedule
added findAllCashewOrderItemsHistory() that includes cancelled orders - should be used for the history table
