### ISSUE TITLE
locked for edit always 

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#130]
java.security.AccessControlException: Process was closed for edit
	at com.avc.mis.beta.dao.ProcessInfoDAO.editGeneralProcessEntity(ProcessInfoDAO.java:129) ~[classes/:na]

**Comment by mei309** [comment]
after lock and edit of reciving i cant clean but i can do transfer

**Comment by mei309** [comment]
EditStatus status = getProcessRepository().findProcessEditStatus(process.getId());
		if(status != EditStatus.EDITABLE) {
			System.out.println(status); === null
			throw new AccessControlException("Process was closed for edit");
		}

**Comment by litzvi** [comment]
Sorry don't understand the order of the actions and what actions.
maybe try to number clearly what you did, so I can reproduce it.

**Comment by litzvi** [comment]
I MANAGED TO REPRODUCE. WILL CHECK LATER

**Comment by litzvi** [comment]
why are you calling edit when adding a new production?

**Comment by mei309** [comment]
> why are you calling edit when adding a new production?

a mistake. upload my angular
