### ISSUE TITLE
UNIT, UNIT AMOUNT

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#135]
What if I want to use part of a unit?
e.g. pack part of a bag

**Comment by mei309** [comment]
pack half and create a new unit for the other half

**Comment by litzvi** [comment]
It's an issue for me..so thank you 
but it will a processed item of another process. say we packed and the leaving some roasted, it will be an outcome of packing process - wrong dates etc.

**Comment by litzvi** [comment]
I think that where possible we should set unitAmount to 1  and put the weight in the numberUnits.
So in big bags, that there is only one, we will set unitAmount to 1kg and the weight in numberUnits.
So default for unitAmount will be 1 (need to set the measureUnit) and for numberUnits I'll remove the default and it has to be set.
So amounts in the table will be entered into the numberUnits and you should take care of the defaults in the normal line storages.
It will be changed in version 4.9

**Comment by litzvi** [comment]
ok done. uploaded version 4.9
you will have some changes to do but it should be apparent from the errors you'll get when you fill in the forms.

**Comment by litzvi** [comment]
still won't be able to use parts of a unit, e.g. half a kilo.
perhaps this storage form structure is restrictive and should rethink it.

**Comment by litzvi** [comment]
oops, doesn't fit with container weight. container weight is per unit with receiving bags and for big bags it would be per  line

**Comment by mei309** [comment]
dont mess it up now just go back to before

**Comment by litzvi** [comment]
It's important. if you would try filling there packing you'll see they use parts all the time.
It's not that messed up, it's mostly working. the only thing that's hurt is the container weight which they don't use for now and we need to rethink anyway.

**Comment by litzvi** [comment]
You should change the default in unit amount to 1, instead of the default in number of units. Small change, but important.

**Comment by mei309** [comment]
i changed

**Comment by litzvi** [comment]
I see you removed the default number of units.
Please make the unit amount / unit weight default 1.
also change the order, so they fill number of units first.

summery: 
1. default  unit amount =1
2. change there display order.

**Comment by mei309** [comment]
1. cannot do because then i will send empty stuff

**Comment by mei309** [comment]
let them choose only measure unit and number of units.
its not true for now

**Comment by mei309** [comment]
change there display order. ok

**Comment by litzvi** [comment]
> 1. cannot do because then i will send empty stuff

why send 1 with the measure unit

**Comment by litzvi** [comment]
> let them choose only measure unit and number of units.
> its not true for now

can you please explain

**Comment by mei309** [comment]
> > let them choose only measure unit and number of units.
> > its not true for now
> 
> can you please explain

they want 300 bags of 50 kg for example

**Comment by mei309** [comment]
> let them choose only measure unit and number of units.
> its not true for now

then it will get send to the backend even if all the rest is empty

**Comment by litzvi** [comment]
> they want 300 bags of 50 kg for example

only over there, anywhere else? if so add unitAmount field only there

>then it will get send to the backend even if all the rest is empty

you don't need to set unitAmount (it's default 1 by me). so what's getting sent?

**Comment by mei309** [comment]
Please make the unit amount / unit weight default 1.
so exactly i dont have default

**Comment by mei309** [comment]
only over there, anywhere else? if so add unitAmount field only there
meanwhile everywhere

**Comment by mei309** [comment]
after we change item i will change it

**Comment by mei309** [comment]
ok changed
