### ISSUE TITLE
SHIPPING - LOADING - Material to load

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#136]
should have production dates, in order to differentiate between different batches.

**Comment by litzvi** [comment]
also perhaps write NumberAvailableUnits for easier use

**Comment by litzvi** [comment]
when choosing items for a process, please show processDate, so can differentiate between different processes.
I'm also giving you (version 4.6) NumberAvailableUnits - I think you should display it instead of used units, i needed to calculate while filling.

**Comment by mei309** [comment]
> when choosing items for a process, please show processDate, so can differentiate between different processes.
> I'm also giving you (version 4.6) NumberAvailableUnits - I think you should display it instead of used units, i needed to calculate while filling.

i dont understand where

**Comment by litzvi** [comment]
for example, when choosing items to load to a container.
the lot i gave you is loaded in 3 different containers. 
It has a few thousand boxes packed in different processes, so when choosing what to use for a container after choosing the po. I get 3 lines to choose from, all with the same item and I can't see any difference between them, the only real difference is the packing date.

**Comment by litzvi** [comment]
about NumberAvailableUnits, you getting this field in my newest version, to display instead of NumberUsedUnits

**Comment by mei309** [comment]
> production dates

its processDate?

**Comment by mei309** [comment]
put processDate in ProductionProcessDTO so i can show on edit

**Comment by litzvi** [comment]
> put processDate in ProductionProcessDTO so i can show on edit

it has. recordedTime is processDate

**Comment by mei309** [comment]
good

**Comment by mei309** [comment]
so change the name in ProcessItemInventory to itemProcessDate

**Comment by litzvi** [comment]
looks stupid.
but ok done

**Comment by mei309** [comment]
it needs to be the same name

**Comment by mei309** [comment]
> umberAvailableUnits

you mean otherUsedUnits??

**Comment by mei309** [comment]
> about NumberAvailableUnits, you getting this field in my newest version, to display instead of NumberUsedUnits

you mean otherUsedUnits??

**Comment by litzvi** [comment]
> it needs to be the same name

i did

**Comment by litzvi** [comment]
> > about NumberAvailableUnits, you getting this field in my newest version, to display instead of NumberUsedUnits
> 
> you mean otherUsedUnits??

no. NumberAvailableUnits

**Comment by mei309** [comment]
its changing what?

**Comment by litzvi** [comment]
> its changing what?

nothing, I just added it. I think it's better to display than used units in this case.

**Comment by mei309** [comment]
> > its changing what?
> 
> nothing, I just added it. I think it's better to display than used units in this case.
> so show this instead of NumberUsedUnits

numberUsedUnits is what we using now in the process.

**Comment by mei309** [comment]
i will put it insted of otherUsedUnits

**Comment by litzvi** [comment]
NumberAvailableUnits is in StorageInventoryRow.

**Comment by mei309** [comment]
ok. we had before a field otherUsedUnits but never mind
