### ISSUE TITLE
Shipping by po

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#138]
Maybe should add a report of loadings by po

**Comment by litzvi** [comment]
Maybe LoadingRow should be different than ProcessRow, since it can be from different po's it should be grouped by po and not only by item.

**Comment by litzvi** [comment]
I changed LoadingRow to have ContainerPoItemRow instead of ProductionProcessWithItemAmount.
So now it has po for every line.
I think you should show in 'Shipping Reports' for every shipping joined lines for every po item 
(Shipment code, Recorded time,  po, item description, amount)
 - same as in export doc.

**Comment by mei309** [comment]
tell me when its ready

**Comment by litzvi** [comment]
Uploaded in version 4.7
please notice I changed the item from a string, to BasicValueEntity<Item> same as other places.
Need to fix display in ExportDoc->Loaded Items

**Comment by mei309** [comment]
look on version 4 when you get it

**Comment by litzvi** [comment]
where do i find the version again?

**Comment by mei309** [comment]
generl.service.ts

**Comment by mei309** [comment]
and i when i upload i will write the version from now

**Comment by litzvi** [comment]
> generl.service.ts

it's a very nested place to put it.
just write in the README file or somthing

**Comment by mei309** [comment]
> > generl.service.ts
> 
> it's a very nested place to put it.
> just write in the README file or somthing

OK. NO PROBLEM
