### ISSUE TITLE
Printing details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#140]
printing cuts of part of the page.
see for example qc details and try to print - it will cut of about near the testa line

**Comment by litzvi** [comment]
also after I try to print the whole top menu bar disappears.

**Comment by litzvi** [comment]
Also see to it, that po report will be printed nicely - all the pages, divided correctly

**Comment by mei309** [comment]
> also after I try to print the whole top menu bar disappears.

it needs to be that way. its printing details hopefully not the site

**Comment by mei309** [comment]
its a very lot of css so now i just trying to do it reasonably

**Comment by litzvi** [comment]
> > also after I try to print the whole top menu bar disappears.
> 
> it needs to be that way. its printing details hopefully not the site

but after I left the printing page I should get back to the site.

**Comment by litzvi** [comment]
> its a very lot of css so now i just trying to do it reasonably

sure, it's just because Ahron is very stubborn about seeing everything in paper.
So just make sure it print's the data reasonably after you finish the functionality tasks.

**Comment by mei309** [comment]
> > > also after I try to print the whole top menu bar disappears.
> > 
> > 
> > it needs to be that way. its printing details hopefully not the site
> 
> but after I left the printing page I should get back to the site.

sorry i didnt understand what you meant. fixed now.

**Comment by mei309** [comment]
> > its a very lot of css so now i just trying to do it reasonably
> 
> sure, it's just because Ahron is very stubborn about seeing everything in paper.
> So just make sure it print's the data reasonably after you finish the functionality tasks.

i will

**Comment by mei309** [comment]
> printing cuts of part of the page.
> see for example qc details and try to print - it will cut of about near the testa line

popups not working

**Comment by litzvi** [comment]
> > printing cuts of part of the page.
> > see for example qc details and try to print - it will cut of about near the testa line
> 
> popups cutting after first page

why? can it be fixed?

**Comment by mei309** [comment]
> > > printing cuts of part of the page.
> > > see for example qc details and try to print - it will cut of about near the testa line
> > 
> > 
> > popups cutting after first page
> 
> why? can it be fixed?

it was for me

**Comment by mei309** [comment]
popup fixed. just to fix nice view

**Comment by mei309** [comment]
closing since its only for me so i changed it to the frontend issues
