### ISSUE TITLE
Receiving order - indent lines

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#145]
you can indent the bag weight lines to separate them from the first line

**Comment by mei309** [comment]
i dont know what you mean

**Comment by litzvi** [comment]
here is identation

I'm the first line with item, payable amounts, price and extra button
        I'm the first line of 50kg 317 units
        I'm the second line 26kg 1 unit

**Comment by mei309** [comment]
i did something that i think you mean so give a look

**Comment by litzvi** [comment]
I explained to you on the phone. is it difficult to do it?

**Comment by mei309** [comment]
i can do it if its always in a new line

**Comment by mei309** [comment]
i did it always in a new line so it will be strange sometimes
