### ISSUE TITLE
2 items in one po

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#148]
If I have 2 items so Transfer from will show the header twice when using it.
I'll send you a screenshot

**Comment by mei309** [comment]
its different process therefor they are separate

**Comment by mei309** [comment]
i dont have a different way to do it

**Comment by mei309** [comment]
its also a  problem since they even in the same process they arent necessarily the same item

**Comment by mei309** [comment]
I SOLVED IT WHEN ITS NEW ONES BUT IF ITS 2 PROCESS IT WILL BE LIKE THIS.

**Comment by litzvi** [comment]
you can't make one permanent header for the table and add items from different processes?
if you can't at lease make some space between them
