### ISSUE TITLE
usedItem dosent have itemProcessDate

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#151]
i need it for edit

**Comment by mei309** [comment]
in UsedItemsGroupDTO

**Comment by litzvi** [comment]
you have it in UsedItemDTO, doesn't belong to the group UsedItemsGroupDTO.
different UsedItemDTO could have different itemProcessDate

**Comment by mei309** [comment]
its having only with normal usedItem but not with table view

**Comment by litzvi** [comment]
I don't understand.
can you please explain how you show the items to choose from? 
I assumed you call warehouseManagement.getInventory(..), but what if it's a table?

**Comment by mei309** [comment]
warehouseManagement.getInventory for storageRelocation

**Comment by mei309** [comment]
its giving also tables

**Comment by litzvi** [comment]
Oh yeah, so now everything is ok with the itemProcessDate?

**Comment by mei309** [comment]
yes
