### ISSUE TITLE
Relocation Report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#153]
not showing, don't know why.
I put in a relocation, showed details but when exit doesn't show.

**Comment by mei309** [comment]
> not showing, don't know why.
> I put in a relocation, showed details but when exit doesn't show.

you mean in the popup??

**Comment by litzvi** [comment]
No I mean the report is not showing.

**Comment by litzvi** [comment]
Inventory reports -> relocation

**Comment by mei309** [comment]
you had it with transfers. but anyway i added it

**Comment by litzvi** [comment]
No it wasn't!
