### ISSUE TITLE
CASHEW CLEANING

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#154]
When i edit a cleaning, 2 cleaned bags disappeared and it writes bag number 15 twice (one empty).
It's a mess, please urgently fix it.
I didn't touch it, i edited waste only

**Comment by litzvi** [comment]
It's the last 1-2 cells disappearing and 15 shows twice. I guess it has to do with the multiple 15..

**Comment by mei309** [comment]
its working totally fine by me.
please let me know how much bags you put???

**Comment by litzvi** [comment]
28 or 29

**Comment by mei309** [comment]
ok i managed to reproduce it. solved
