### ISSUE TITLE
Count

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#157]
Is there a reason count is only in a table and no option for lines?

**Comment by mei309** [comment]
its only a weight check

**Comment by mei309** [comment]
theres no reason to have 300*50

**Comment by litzvi** [comment]
but when they fill palates they might want to fill with lines for reducing pallet weight.
I just asked because it's the way you have it anywhere and wondered if there is any problem doing it in count (functionality wise).

**Comment by mei309** [comment]
> but when they fill palates they might want to fill with lines for reducing pallet weight.
> I just asked because it's the way you have it everywhere and wondered if there is any problem doing it in count (functionality wise).

not really. but you code isnt suitable for now

**Comment by litzvi** [comment]
I think my code sopurts it. just like usedItems, you have a setter for tables and a setter for storageMoves in StorageMovesGroup

**Comment by mei309** [comment]
you mixing stuff

**Comment by litzvi** [comment]
CORRECT was confused
