### ISSUE TITLE
Shipping in 2 stages

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#158]
It doesn't feel so good that first we are required to fill some details for filling the items loaded.
If it's required to fill in all at once, then should be in one page, it only makes sense to fill in 2 pages when they can be done separately.

**Comment by mei309** [comment]
but it will be a giant page

**Comment by mei309** [comment]
i will change it even so im sure you will want to change it

**Comment by litzvi** [comment]
I don't mind if it's in 2 pages as long as we can move back and forth between them without the required fields. 
Maybe like tabs, tab for general info and tab for loading.
Another option might be a pop up for General info or for the loading.

**Comment by litzvi** [comment]
please don't close without a reason! I work hard to write these issues, it's like total disrespect for my time to just close without an answer.

**Comment by mei309** [comment]
its not simple and not important now

**Comment by mei309** [comment]
and its with a lot of respect i just fixing small stuff like this for to long. and now we really dont need it

**Comment by mei309** [comment]
its ready
