### ISSUE TITLE
 Material Export edit not working after adding  

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#16]
Edit not working correctly (doesn't show produced items) form details straight after adding Material Export.

**Comment by litzvi** [comment]
actually Material Export edit isn't working, gives following error:
Cannot add or update a child row: a foreign key constraint fails (`avcdbjpa-pub1.1`.`used_items`, CONSTRAINT `FK3366xrrq8snq8pjkouq0gmlgo` FOREIGN KEY (`storage_id`) REFERENCES `storage_forms` (`id`))

**Comment by mei309** [comment]
ok. fixed for edit after add. normal from table works fine. please let me know the exact case
