### ISSUE TITLE
Relocation - tab press + landing page

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#163]
Pressing on tool bar Inventory->Relocation not working while in Relocation.
After details of relocation, landing in transfers instead of relocation.

**Comment by mei309** [comment]
Pressing on tool bar Inventory->Relocation not working while in Relocation.
what you want it to do???

**Comment by litzvi** [comment]
Go to a new relocation. same response as usual. Everywhere the same, the button/tab/tool bar always have the same result

**Comment by mei309** [comment]
ok solved
