### ISSUE TITLE
SHIPPING - materials to load

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#165]
not showing processDate
and multiple tables (when packed in multiple processes)

**Comment by litzvi** [comment]
**Also adding from another po doesn't work**

**Comment by mei309** [comment]
solved all but for now we first need to choose all pos and then add the numbers

**Comment by litzvi** [comment]
ok

**Comment by litzvi** [comment]
> solved all but for now we first need to choose all pos and then add the numbers

If so, show from what po the items are

**Comment by mei309** [comment]
ok. showing

**Comment by mei309** [comment]
> solved all but for now we first need to choose all pos and then add the numbers

not anymore. i fixed it
