### ISSUE TITLE
Editing Relocation adds a redundant empty count table

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#175]

**Comment by mei309** [comment]
ok. solved

**Comment by litzvi** [comment]
when editing Relocation from a table (e.g. before roasting) you don't give the used items.
so they are not displayed in the relocation table.

**Comment by mei309** [comment]
> when editing Relocation from a table (e.g. before roasting) you don't give the used items.
> therefore are not displayed in the relocation table, can't be edited again.

i really dont understand

**Comment by mei309** [comment]
edit is working fine for me

**Comment by litzvi** [comment]
is it possible it has to do with the old controllers?

**Comment by mei309** [comment]
> is it possible it has to do with the old controllers?

i dont think so

**Comment by litzvi** [comment]
so what do you want me to do?

**Comment by litzvi** [comment]
I'll close it for now. see how it works when you have a working version
