### ISSUE TITLE
Production Edit

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#176]
adding another bag to used items not working.
try choosing part of multiple bags (of a table) and then on edit add a bag you didn't choose before

**Comment by mei309** [comment]
i dont see no reason its happening. its getting the information and even going to the function 
public void setUsedItem(UsedItemTableDTO usedItemTable) {
and doing setUsedItems(usedItems); with usedItems of the right length

**Comment by mei309** [comment]
im sending exactly the same as new

**Comment by mei309** [comment]
and its happening also in transfer

**Comment by litzvi** [comment]
is it because your'e giving a full item instead of the BasicValueEntity that gets only id and value?

**Comment by litzvi** [comment]
also when I choose one bag, in the edit it appears twice.

**Comment by litzvi** [comment]
As I'm looking at you're edit object, I wonder why you put them in 2 groups in the first place.
If you display and send them together you'll avoid errors and it will look better.

**Comment by litzvi** [comment]
![image](https://user-images.githubusercontent.com/53637868/98105970-492fdd00-1ecb-11eb-90cd-6b61cb7dd1fc.png)

**Comment by mei309** [comment]
> is it because your'e giving a full item instead of the BasicValueEntity that gets only id and value?
> but why is it working with a new one?

no

**Comment by mei309** [comment]
im giving exactly the same as new

**Comment by mei309** [comment]
i cant see the problem

**Comment by litzvi** [comment]
can you please reply on my other comments

**Comment by mei309** [comment]
> also when I choose one bag, in the edit it appears twice.
> look ahead in the screenshot, bag number 1 appears twice

its not happening by me. i will try later again

**Comment by mei309** [comment]
??

**Comment by litzvi** [comment]
????????????????????????????
