### ISSUE TITLE
Inventory Reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#177]
Sometimes straight after adding production process, Inventory table shows empty and after sometime it shows correctly again (without doing anything).
do you have a clue what it is? It's a little hard to reproduce, so regard it only if you understand the reason.

**Comment by mei309** [comment]
which inventory table? relocation or cashew stock ?

**Comment by litzvi** [comment]
cashew stock

**Comment by mei309** [comment]
its happening only after adding a new one??

**Comment by mei309** [comment]
that sounds strange

**Comment by mei309** [comment]
i cant reproduce it

**Comment by litzvi** [comment]
OK. so let it go for now.
