### ISSUE TITLE
Status option

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#179]
Should add status option for production and shipping reports (e.g. not to show cancelled)

**Comment by litzvi** [comment]
added a status row to ProcessRow (used in reports).
if you want you can add the status column, because now it's showing cancelled processes just as other ones.
(Maybe you can just mark it with a cross)

**Comment by mei309** [comment]
we said it just goes back a stage and theres no more

**Comment by mei309** [comment]
i dont think its a good idea to put it together. i think its better or if we put it in history tab or we do a special one for canceled

**Comment by litzvi** [comment]
so it means we need a different functions for history, or will you filter it?
Anyway add history, so we can check if cancelling  is working correctly.
otherwise, add status and move it later to history.

**Comment by mei309** [comment]
for now i added it
