### ISSUE TITLE
qc roasting - poCodes not correct

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#180]
I think you are giving the same po codes as for receipt qc.
what pos do you think we should give?

**Comment by mei309** [comment]
clean + rosted

**Comment by mei309** [comment]
let me know when you do it and where is it

**Comment by litzvi** [comment]
you have those. but you aren't using them

**Comment by mei309** [comment]
i will find it

**Comment by litzvi** [comment]
you are using it for new production

**Comment by mei309** [comment]
> you are using it for new production

i dont think so

**Comment by mei309** [comment]
its ok i solved it

**Comment by litzvi** [comment]
solved? even going in to all qc pages gives an error.
try when you have only one receiving po

**Comment by mei309** [comment]
sorry i forgot to give you the new controllers
