### ISSUE TITLE
Final report 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#181]
Relocation - Amounts gained, not showing.
also shouldn't be 'Amounts gained', maybe 'difference' or something else

**Comment by litzvi** [comment]
Cleaning - it's not 'Receiving date'.
also you can separate in and out product and then write the loss.

**Comment by mei309** [comment]
> Relocation - Amounts gained, not showing.
> also shouldn't be 'Amounts gained', maybe 'difference' or something else

you dont have the new version of controllers

**Comment by mei309** [comment]
Cleaning - it's not 'Receiving date'.
ok solved

**Comment by mei309** [comment]
also you can separate in and out product and then write the loss.
next version

**Comment by mei309** [comment]
also you can separate in and out product and then write the loss.
its not simple since you dont have it by item

**Comment by litzvi** [comment]
[
![final_report-draft_1](https://user-images.githubusercontent.com/53637868/100563821-f5f65200-32f1-11eb-8ad8-c82ff9d857cc.jpg)
]

**Comment by litzvi** [comment]
is this good?
all list will be grouped by item. that was the problem right?
please draw as clear as possible what you need before i implement.

**Comment by mei309** [comment]
look at my reports controll thats what we need

**Comment by litzvi** [comment]
![report](https://user-images.githubusercontent.com/53637868/101279034-fa3ed580-37f1-11eb-8671-dc07fefd217e.gif)

**Comment by litzvi** [comment]
look in ProductionProcesses at 
getProductionSummary(ProcessName processName, Integer poCodeId)
I implemented it for production

**Comment by mei309** [comment]
we need to talk about it so call me

**Comment by mei309** [comment]
getProductionSummary its retuning empty

**Comment by litzvi** [comment]
ProductionReportLine(
productIn=[ItemAmount(item=BasicValueEntity(value=W340), amount=15876.00000000000000)], 
ingredients=null, 
productOut=[ItemAmount(item=BasicValueEntity(value=W340 CLEAN), amount=15917.00000000000000)], 
waste=[ItemAmount(item=BasicValueEntity(value=QC HOLD), amount=2.00000000000000), ItemAmount(item=BasicValueEntity(value=SCREEN), amount=23.00000000000000)], 
qc=null, 
dates=[2020-11-02, 2020-11-01])

example print out for PO14107V i inserted

**Comment by litzvi** [comment]
i didn't implement the difference yet

**Comment by mei309** [comment]
its not giving anything for relocation and receiving and loading

**Comment by mei309** [comment]
only the dates

**Comment by litzvi** [comment]
all tables (at least the dates) should be separate. 
we also need the waste.

for me
need the measure unit with amount. 
why amount and weight? should remove weight

**Comment by mei309** [comment]
this is what you giving me. just add the amount and weight to weight like everywhere
{item: {…}, amount: 15876, weight: null}

**Comment by mei309** [comment]
> its not giving anything for relocation and receiving and loading

what about this?

**Comment by litzvi** [comment]
> what about this?

YES I DIDN'T DO IT ON PURPOSE UNTIL WE SETTELED ON THE PRODUCTION

**Comment by litzvi** [comment]
Ok so now i'm always giving weight, if it's packedItem i'm also giving amount.
you should probably show them together - one in סוגריים, so amount isn't empty like it's showing now.

**Comment by mei309** [comment]
thats exactly what im asking why you arent giving amoutWithUnit??

**Comment by mei309** [comment]
if you give me it together its the easiest

**Comment by litzvi** [comment]
> thats exactly what im asking why you arent giving amoutWithUnit??

I am! from version 8.4.

**Comment by mei309** [comment]
ok done. now you can finish the other parts

**Comment by litzvi** [comment]
I added the differences and the totals in ProductionReportLine.
I'm to tired to do the other parts tonight.

another thing, I changed ReceiptRow AmountWithUnit[] to AmountWithUnit (without array) because of the packed, just for now. can set it back later, just a temporary fast fix.

**Comment by litzvi** [comment]
so please look at Cashew Reports, the totals are missing probably because it's not an array

**Comment by litzvi** [comment]
I added QC for final report. 
Please check com.avc.mis.beta.service.QualityChecks.getQcSummary(ProcessName, Integer) if it suits you.
We probably only need to show for 'avc lab' but I first want to change it to an enum so it's more structured.

**Comment by mei309** [comment]
why you dont add it in the process??

**Comment by mei309** [comment]
and also im still getting empty results in final report

**Comment by mei309** [comment]
> I added QC for final report.
> Please check com.avc.mis.beta.service.QualityChecks.getQcSummary(ProcessName, Integer) if it suits you.
> We probably only need to show for 'avc lab' but I first want to change it to an enum so it's more structured.

i dont see it

**Comment by litzvi** [comment]
> > I added QC for final report.
> > Please check com.avc.mis.beta.service.QualityChecks.getQcSummary(ProcessName, Integer) if it suits you.
> > We probably only need to show for 'avc lab' but I first want to change it to an enum so it's more structured.
> 
> i dont see it

I just pushed now

**Comment by litzvi** [comment]
> why you dont add it in the process??

don't understand

**Comment by litzvi** [comment]
> and also im still getting empty results in final report

don't remember, so please refer or explain.
I didn't put it in the final report, only the method i wrote getQcSummary(ProcessName, Integer)

**Comment by mei309** [comment]
QcReportLine should always be percentages therefore it should not have filed percentage

**Comment by mei309** [comment]
besides that its ok

**Comment by mei309** [comment]
and you still giving me 
loading:
dates: null
difference: null
ingredients: null
productIn: null
productOut: null
qc: null
totalIngredients: null
totalProductIn: null
totalProductOut: null
totalQC: null
totalWaste: null
waste: null

**Comment by litzvi** [comment]
> QcReportLine should always be percentages therefore it should not have filed percentage

it is always percentage. the field is jsonIgnore just for me

**Comment by litzvi** [comment]
> and you still giving me
> loading:
> dates: null
> difference: null
> ingredients: null
> productIn: null
> productOut: null
> qc: null
> totalIngredients: null
> totalProductIn: null
> totalProductOut: null
> totalQC: null
> totalWaste: null
> waste: null

should be fixed version 9.4

**Comment by litzvi** [comment]
did the whole Final report besides loading.
you can find it in: com.avc.mis.beta.service.ProcessInfoReader.getFinalReport(Integer)

**Comment by litzvi** [comment]
now I added loading to.
So it's finished for basic data, later we can add some statistics.

**Comment by mei309** [comment]
i dont have a normal way to show the loading.
i will show it the same as in the report.
its not a table and not a normal one that i can show like the rest

**Comment by litzvi** [comment]
there can be a few loadings for a po, and everyone can have a few items.
ok no problem

**Comment by mei309** [comment]
ok done. im closing this and if you have more stuff about the final report open a new issue
