### ISSUE TITLE
item problem

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#186]
Cannot construct instance of `com.avc.mis.beta.entities.item.Item` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information

**Comment by litzvi** [comment]
Right, you need to create one of the subclasses

**Comment by mei309** [comment]
i cannot do that.
i have no way to do it

**Comment by litzvi** [comment]
So use the subclasses methods

**Comment by mei309** [comment]
i cant since i dont know what item is it

**Comment by mei309** [comment]
it can be both

**Comment by litzvi** [comment]
Yes correct, you shouldn't be dealing with it. I'll fix it somehow.

**Comment by mei309** [comment]
let me know when you done so i can finish to check

**Comment by mei309** [comment]
via whatsapp is better

**Comment by litzvi** [comment]
ok Item isn't abstract, but removed the addItem form ValueWriter because it's just for reference.

**Comment by mei309** [comment]
ok
