### ISSUE TITLE
Production Process edit

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#188]
I can't edit cleaning process (put only some cleaned bags, then try to add more).
can't quite figure out why, seems like some id is missing (though i don't see which).
Can you see what it is?
also I realized you don't always edit the storages, seems like you giving all as if new - although it will still work, it isn't accurate.

**Comment by mei309** [comment]
org.hibernate.PersistentObjectException: detached entity passed to persist: com.avc.mis.beta.entities.processinfo.ProcessGroup
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:120) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachList

**Comment by mei309** [comment]
However, persist operation is intended for brand new transient objects and it fails if id is already assigned. In your case you probably want to call saveOrUpdate instead of persist.
if this is true its by you

**Comment by mei309** [comment]
i dont find a different problem

**Comment by litzvi** [comment]
When you are doing edit I'm not calling persist, I'll check it again. I
just assumed because before you had that problem you called edit.
Just write what controller functions you use for edit and new and I'll
check.

**Comment by mei309** [comment]
its happening in this class

**Comment by mei309** [comment]
ProductionController 
adding with addCleaningTransfer
edit with editProductionTransfer

**Comment by litzvi** [comment]
sneaky error
ok solved in version 8
