### ISSUE TITLE
relocation moves needs a measure unit??

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#189]
ConstraintViolationImpl{interpolatedMessage='Measure unit required', propertyPath=measureUnit, rootBeanClass=class com.avc.mis.beta.entities.processinfo.StorageMovesGroup, messageTemplate='Measure unit required'}

**Comment by mei309** [comment]
why we need it. used items should not need it

**Comment by litzvi** [comment]
Because we can change the form. Just put the used storage one.

**Comment by litzvi** [comment]
> why we need it. used items should not need it

it's not for usedItems it's for StorageMovesGroup.
It's possible to change if it disturbs you too much but i thought it's better to keep it because i'm giving the theoretical option to change the storage forms

**Comment by litzvi** [comment]
anyway when you are doing it from a table just set the table measureUnit

**Comment by mei309** [comment]
ok

**Comment by mei309** [comment]
its very wrong since i can have different measurements in the same storage move
