### ISSUE TITLE
UsedItemBaseDTO

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#190]
what are you giving me???
newStroage???
storage has only version and id??
you have all the stuff with storage prefix >??
why? i cant do anything with this

**Comment by litzvi** [comment]
all the storage information is already outside for display, it was double.. the storage is the one you need to give back

**Comment by litzvi** [comment]
all these are the storage fields, you asked for them outside.

//storage information - for easier access
	@EqualsAndHashCode.Exclude
	private Integer storageOrdinal;	
	@EqualsAndHashCode.Exclude
	private BigDecimal storageUnitAmount;
	@EqualsAndHashCode.Exclude
	private BigDecimal storageNumberUnits;	
	@EqualsAndHashCode.Exclude
	private BigDecimal storgeOtherUsedUnits;
	@EqualsAndHashCode.Exclude
	private BigDecimal storageContainerWeight;	
	@EqualsAndHashCode.Exclude
	private BasicValueEntity<Warehouse> storageWarehouseLocation;

**Comment by mei309** [comment]
in this class i dont need nothing outside only inside

**Comment by mei309** [comment]
this class is where im using storageid and storageversion

**Comment by mei309** [comment]
and whats new storage???

**Comment by litzvi** [comment]
oh you mean new warehouse?

**Comment by litzvi** [comment]
I don't think your using it, i just prepared an option for storage transfer, to set the new processItem with the usedItemDTOs (when you change only the storage)
look at ProcessItem->setUsedItems(UsedItemDTO[])
if you aren't using that function just ignore it

**Comment by mei309** [comment]
> oh you mean new warehouse?

public Storage getNewStorage() {
		Storage storage = new Storage();
		storage.setOrdinal(this.getStorageOrdinal());
		storage.setUnitAmount(this.getStorageUnitAmount());
		storage.setContainerWeight(this.getStorageContainerWeight());
		storage.setNumberUnits(this.getNumberUsedUnits());
		storage.setWarehouseLocation(this.getNewLocation());

		return storage;
	}

**Comment by litzvi** [comment]
yes. that's what i'm using for the function I told you.
just ignore
i'll annotate it with 	@JsonIgnore

**Comment by mei309** [comment]
> I don't think your using it, i just prepared an option for storage transfer, to set the new processItem with the usedItemDTOs (when you change only the storage)
> look at ProcessItem->setUsedItems(UsedItemDTO[])
> if you aren't using that function just ignore it

im using this function

**Comment by mei309** [comment]
but i need the details back in storage and i dont need all the prefix of storage in UsedItemBaseDTO

**Comment by litzvi** [comment]
ok so when you are using it you set the new warehouse. nothing else
like i said the getNewStorage will be 	@JsonIgnore

**Comment by litzvi** [comment]
> but i need the details back in storage and i dont need all the prefix of storage in UsedItemBaseDTO

what is prefix???

**Comment by litzvi** [comment]
you asked me to take out all the information before

**Comment by mei309** [comment]
//storage information - for easier access
@EqualsAndHashCode.Exclude
private Integer storageOrdinal;
@EqualsAndHashCode.Exclude
private BigDecimal storageUnitAmount;
@EqualsAndHashCode.Exclude
private BigDecimal storageNumberUnits;
@EqualsAndHashCode.Exclude
private BigDecimal storgeOtherUsedUnits;
@EqualsAndHashCode.Exclude
private BigDecimal storageContainerWeight;
@EqualsAndHashCode.Exclude
private BasicValueEntity storageWarehouseLocation;

**Comment by litzvi** [comment]
you asked me to do it. are you sure you aren't using it anywhere?

**Comment by mei309** [comment]
> you asked me to take out all the information before 
i did but a long time ago i changed to the inside.
sorry if i didnt tell you.

**Comment by litzvi** [comment]
ok so i'll put it all back in

**Comment by mei309** [comment]
now im using only the inside

**Comment by mei309** [comment]
only in the table view i need it outside like you have it now

**Comment by litzvi** [comment]
so you still need it outside? so i'm giving the same info twice?

**Comment by mei309** [comment]
> so you still need it outside? so i'm giving the same info twice?

no its different classes

**Comment by mei309** [comment]
im almost 100%.

**Comment by mei309** [comment]
im very sure im not using the outside of this class so for now annotate the outside and after checking you can delete it

**Comment by litzvi** [comment]
ok. i'm uploading 7.6 with both for now

**Comment by litzvi** [comment]
sorry 7.7

**Comment by litzvi** [comment]
version 7.8 has the outside storage fields commented

**Comment by mei309** [comment]
@EqualsAndHashCode.Exclude
private BasicValueEntity storageWarehouseLocation;
@EqualsAndHashCode.Exclude
private BigDecimal storageUnitAmount;

**Comment by litzvi** [comment]
I changed it by me. just uncomment lines 54-55, 62-63

**Comment by mei309** [comment]
> I changed it by me. just uncomment lines 54-55, 62-63
> and can you explain why you need them double?

for display. i cannot open endlessly

**Comment by mei309** [comment]
number of bags is outside and that is inside its diffucult to show in a table

**Comment by mei309** [comment]
93 97-100 119 123-129 uncomment too

**Comment by litzvi** [comment]
ok done
our lines are already different but probably ok

**Comment by mei309** [comment]
ok.

**Comment by mei309** [comment]
you can remove all the fields with prefix storage. i stopped using them. i removed by me and its working.
**all besides storageId**

**Comment by litzvi** [comment]
what about storgeOtherUsedUnits?

**Comment by mei309** [comment]
i dont have it in my code

**Comment by mei309** [comment]
so just comment it and close the issue

**Comment by litzvi** [comment]
i'm giving it to you so you can display available units in edit of production process.
it's the amount of used units of this storage, excluding the numberUsed by the current 'edited' process

**Comment by mei309** [comment]
we are showing available units so please change it and let me know when you do. and if you want it can also be in storage

**Comment by litzvi** [comment]
ok I'll change to numberAvailableUnits (including current) in version 8.3

**Comment by mei309** [comment]
why not to put it in the storage??

**Comment by mei309** [comment]
then it will be like when you give me storages of a po

**Comment by mei309** [comment]
if it has no difference its better otherwise just let me know

**Comment by litzvi** [comment]
I can, but you will still have to use the usedItem method because you want to exclude the current usedItem numberUnits.
e.g. you used all 317 bags in cleaning. In the edit you want to show 317 available not 0, but from the storage perspective it will be zero.

**Comment by litzvi** [comment]
> then it will be like when you give me storages of a po

you aren't getting it from StorageDTO, it's from StorageInventoryRow within ProcessItemInventory.

**Comment by mei309** [comment]
ok. done
