### ISSUE TITLE
Container Weight

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#191]
I want to delete container weight all around.
Now that we made the storage unitAmount more flexible, it isn't clear if it's referring to the whole storage or to to every unit.
For now they aren't using it anywhere (in samples it's sampleContainerWeights, which will stay).

later if we actually need it:
we can add accessWeight per storage or per processItem, which do you think is better? because for many different bags filled in a table they won't add a weight for every one(e.g. big bags or pallets) and for separate lines it will be redundant same amount.
but if used per processItem we can't use it for inventory (because part can be used etc.)

**Comment by mei309** [comment]
after they start using it we will decide about it

**Comment by litzvi** [comment]
now the information isn't right, if it stays I'll tell him not to use it.

**Comment by mei309** [comment]
i removed it everywhere.

**Comment by litzvi** [comment]
OK. I changed it to accessWeight so it will be available in case they want it.

**Comment by litzvi** [comment]
I should remove accessWeight completely from StorageBase.
it's unclear how it divides when part of the storage is used.
If they want to record without the bag weight, is to deduct it themselves

**Comment by litzvi** [comment]
done
