### ISSUE TITLE
Small changes/fixes

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#193]
1. in a receipt the 'measure  unit' shouldn't be near the 35000LBS, it should be clear on what it applies.
2.in Cashew receive details you aren't displaying 'total sample difference' and 'difference'
3. also in Cashew receive details, not displaying KG with the weights.
4. When adding a bulk item **don't** add the unit amount at all.
5. In  Transferring (spelled like this) amounts (relocation or production) 'weight unit' column should probably be after 'unit weight'.
6.

**Comment by mei309** [comment]
1. where you want it??
2. fixed.
2. i have it only in the top so i will show it between the item and sum. look in the new version
3. cannot do it if i want to give edit option

**Comment by mei309** [comment]
4. i will later connect the lines (the part that is from the fathar like measurements) so not really true

**Comment by litzvi** [comment]
> 1. where you want it??

where ever you think it's suitable

**Comment by mei309** [comment]
i dont see a better place

**Comment by litzvi** [comment]
it's a good place? is it clear? 
measure unit = KG | 35000 LBS | price

**Comment by litzvi** [comment]
Item | Process date | Weight unit | Number of units | Unit weight | Warehouse location | Number available units | Amount
-- | -- | -- | -- | -- | -- | -- | --
W320 CLEAN | Dec 8, 2020 | KG | 15876

**Comment by mei309** [comment]
i still dont have a better place. suggest a place

**Comment by litzvi** [comment]
Maybe put the 35000lb and price with a מסגרת, or put them on top with the
item and the measure unit on the next line.
Just general ideas because I'm not in front of it right now.

**Comment by mei309** [comment]
what are those fields ??

**Comment by litzvi** [comment]
ok easier to call

**Comment by litzvi** [comment]
production reports: used items, produced items, add space after the ':'

**Comment by mei309** [comment]
> production reports: used items, produced items, add space after the ':'
> you put a space before the word by mistake

the space before the item has nothing to do with me

**Comment by litzvi** [comment]
SO WHY DOES IT HAVE SPACE BEFORE?

**Comment by mei309** [comment]
> SO WHY DOES IT HAVE SPACE BEFORE?

im not finding the reason yet

**Comment by mei309** [comment]
> ok easier to call

just remind me the names you think for the fields. i forgot

**Comment by mei309** [comment]
and look on how i did it. just suggest names or if you thing a different place

**Comment by mei309** [comment]
and BTW shy storageMoveGroup has measure unit??

**Comment by litzvi** [comment]
> > ok easier to call
> 
> just remind me the names you think for the fields. i forgot

I suggested 'invoice amounts/information'

**Comment by litzvi** [comment]
> and look on how i did it. just suggest names or if you thing a different place

it's good, I think a border/frame might make it clearer. you choose

**Comment by mei309** [comment]
ok finished

**Comment by litzvi** [comment]
specifically in the payableUnits you can leave it lbs if it doesn't complicate things

**Comment by mei309** [comment]
ok.
