### ISSUE TITLE
RELOCATION -> edit from first details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#196]
doesn't show used the Transfering amounts sometimes

**Comment by mei309** [comment]
i dont understand what it dosent show

**Comment by litzvi** [comment]
it just doesn't show the part that you call **Transfering amounts**

**Comment by litzvi** [comment]
TRY TO FILL A RELOCATION WITHOUT A COUNT AND FROM THE DETAILS SHOWEN RIGHT AFTER ADDING, EDIT TO ADD THE COUNT. SEE WHAT HAPPENS.

**Comment by mei309** [comment]
did you check in production??

**Comment by mei309** [comment]
in relocation fixed. but cant see it in production

**Comment by litzvi** [comment]
had the same in production

**Comment by mei309** [comment]
i will close it since it doesn't happen by me.
