### ISSUE TITLE
Delete processes

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#198]
At least for testing give an option to delete from eclipse

**Comment by litzvi** [comment]
I have created functions in ProcessInfoWriter for permanently deleting stuff.
It's needed specially now when they put stuff in by mistake etc.

com.avc.mis.beta.service.ProcessInfoWriter.removeAllProcesses(Integer poCodeId) - remove all processes for this id
com.avc.mis.beta.service.ProcessInfoWriter.removeProcess(Integer process) - remove the given process

**Comment by mei309** [comment]
ok done. in managment
