### ISSUE TITLE
Price changed at receipt time

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#20]
price reduction in case of not sufficient amount or quality.
should be separately documented, perhaps should have a receipt price with a default as the order price.

**Comment by litzvi** [comment]
I added 2 fields in ReceiptItem:
- receivedOrderUnits
- unitPrice
This information will be used for actual payments.

I think they should both be mandatory.
by default should get the values from the order, and be changed in case of a price change (usually reduction).
And be filled normally in case of receipt without order.

**Comment by mei309** [comment]
solved without deep check

**Comment by mei309** [comment]
its not mandetory even in a order why it should be mandetory in receiving?

**Comment by litzvi** [comment]
your'e correct, the reason i wanted it mandatory is just in case there was a price in the order, because from now on the actual payment will rely on the receipt price.
anyway, i'll change it in version 2

**Comment by litzvi** [comment]
ADD IT IN RECEIPT WITHOUT ORDER, IMPORTANT OVER THERE TOO

**Comment by litzvi** [comment]
ALSO CALL IT RECEIVED WEIGHT (NOT UNIT WEIGHT)

**Comment by mei309** [comment]
ok. solved

**Comment by mei309** [comment]
> I added 2 fields in ReceiptItem:
> 
> * receivedOrderUnits
> * unitPrice
>   This information will be used for actual payments.
> 
> I think they should both be mandatory.
> by default should get the values from the order, and be changed in case of a price change (usually reduction).
> And be filled normally in case of receipt without order.

THIS IS THE REASON. CLOSE AFTER YOU SEE

**Comment by litzvi** [comment]
reason for what?
now only the receivedOrderUnits is mandatory

**Comment by mei309** [comment]
you asked somewhere why we have receivedOrderUnits and unitPrice

**Comment by litzvi** [comment]
don't remember. now I'm also using it to determine if order is only partly received.
because calculating is leaving orders open even if a fraction is missing (happens with Viet Nuts lots - although they don't have an order)
