### ISSUE TITLE
QC details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#204]
if i put in zero it's showing empty in the table.
e.g. i filled mold 0, it will show an empty cell as if it's null.

zero is different than null. 
zero means they checked and there is zero, null that they didn't check.

**Comment by mei309** [comment]
i dont think you giving me zero and anyway in angular they are both false so i dont really have a way to do it

**Comment by litzvi** [comment]
it's wrong. Ahron also told me about it

**Comment by mei309** [comment]
make sure you giving zeros and i will see what i can do

**Comment by litzvi** [comment]
I definitely am

**Comment by mei309** [comment]
ok fixed. if you see another place it dose not show 0 or boolean false let me know
