### ISSUE TITLE
Printing - very important 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#206]
Just adding it as an issue for later implementation.

- for now allow to print in landscape, most tables don't fit well vertically.

**Comment by mei309** [comment]
theres the option for it already

**Comment by mei309** [comment]
it suddenly changed and now its not nice. i will need to do a lot of work for it

**Comment by litzvi** [comment]
yes i do landscape but still doesn't fit it in the page.
for example:

**Comment by litzvi** [comment]
[Untitled Document.pdf](https://github.com/litzvi/avc-beta/files/5657350/Untitled.Document.pdf)

**Comment by mei309** [comment]
i need to fix all printing so it will wait.

**Comment by mei309** [comment]
i have a different issue on printing so i will close this one

**Comment by mei309** [comment]
and this specific one is fixed
