### ISSUE TITLE
Production -> new -> cleaning

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#207]
first drop down lets me choose a po that was cleaned already. forwards me to an empty page.
If it's my fault, please tell me what function and where you are using for the dropdown

**Comment by mei309** [comment]
i dont know. by me it isnt happening

**Comment by mei309** [comment]
warehouseManagement.getInventory(ItemGroup.PRODUCT, new ProductionUse[]{ProductionUse.RAW_KERNEL}, null, poCode);
this is what im using

**Comment by litzvi** [comment]
I'm asking about the poCodes for the first page of choosing

**Comment by mei309** [comment]
this is what im using.

**Comment by litzvi** [comment]
I'll check it later but if you put my dump and do a nèw cleaning you'll see
what I'm talking about.

**Comment by mei309** [comment]
look in inventory you will see its still there. therefor its not the drop down problem its some mistake in inventory

**Comment by litzvi** [comment]
it's not in inventory

**Comment by litzvi** [comment]
just call, i don't have a better way to describe

**Comment by mei309** [comment]
@RequestMapping("/getAllPos/{id}")
	public Set<PoCodeDTO> getAllPos(@PathVariable("id") ProductionUse item) {
		return objectTableReader.findInventoryPoCodes(new ProductionUse[]{item});
	}

**Comment by mei309** [comment]
production contriller

**Comment by litzvi** [comment]
thank you. ok solved
one of the the relocation processes (the middle one for 44952) was cancelled
i fixed it only for inventory
it's not fix by you, that's why is showing in inventory.

you aren't showing management details for relocation, so you can't really see it. that's why i asked you to show the status for the processes in reports.

**Comment by mei309** [comment]
you aren't showing management details for relocation???
i am showing. maybe you didnt put management for relocation

**Comment by mei309** [comment]
and if im right just close the issue

**Comment by litzvi** [comment]
> you aren't showing management details for relocation???
> i am showing. maybe you didnt put management for relocation

i meant in the cancelled one, check in relocation you have one cancelled

**Comment by mei309** [comment]
you wrote CANCELLED instead of CANCELED just let me know if you planning to change it or not and then it will show

**Comment by litzvi** [comment]
I wrote CANCELLED  everywhere, it's correct spelling. Actually, both spellings seem to be correct.

**Comment by mei309** [comment]
ok finished
