### ISSUE TITLE
item measure unit compatible 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#208]
i adding such a method to ProcessItem to check if it's a legal measure unit for this type of item.
you are filling the defaultMeasureUnit of the item so it's working.

	@PrePersist @PreUpdate
	public void measureUnitItemCompatiable() {
		MeasureUnit itemDefaultMU = item.getDefaultMeasureUnit();
		if(MeasureUnit.DISCRETE_UNITS.contains(itemDefaultMU) ^ MeasureUnit.DISCRETE_UNITS.contains(getMeasureUnit())) {
			if(MeasureUnit.DISCRETE_UNITS.contains(itemDefaultMU)) {
				throw new IllegalArgumentException("Discrete item can't have a weight measure unit");
			}
			else {
				throw new IllegalArgumentException("Bulk weight item can't have a Discrete measure unit");
			}
		}
	}

**Comment by litzvi** [comment]
As you can see, i have 2 static sets in MeasureUnit for DISCRETE_UNITS and WEIGHT_UNITS.
you can use it as well for showing the correct options for the type of item

**Comment by mei309** [comment]
i dont understand where you want me to use it

**Comment by litzvi** [comment]
E.G. you can do the same to restrict the dropdowns of packedItem to be only UNIT,BOX

**Comment by mei309** [comment]
not now.

**Comment by mei309** [comment]
you think its important that i do it by me even so you return a clear error??

**Comment by litzvi** [comment]
defiantly. 
you are letting them choose from 10 types, when there might only be 2 relevant

**Comment by mei309** [comment]
once they choose an item i fill automatically the measure unit therefor its not really true

**Comment by litzvi** [comment]
I can't force you

**Comment by mei309** [comment]
it's kinda work and since i fill it for them is it still necessary ?

**Comment by mei309** [comment]
if yes i will do it after we upload.
so just answer yes or no

**Comment by litzvi** [comment]
of course, any enhancement only later

**Comment by litzvi** [comment]
leave it as an enhancement, we will rethink later

**Comment by litzvi** [comment]
> once they choose an item i fill automatically the measure unit therefor its not really true

in order for example you don't.
by the way, in general order you defiantly should

**Comment by litzvi** [comment]
I think that for all packed items, you don't even allow to change the unit

**Comment by mei309** [comment]
look on elis email i think you mixed that with this.
is it possible? or do you think its the same?

**Comment by litzvi** [comment]
It's 2 different things. I'm talking about measure unit, he's talking about
he doesn't want to see most packed items in cleaning.
His problem is easy to solve. Just call only roast in roasting. And we make
50lb production use = roast

**Comment by mei309** [comment]
ok

**Comment by mei309** [comment]
ok done
