### ISSUE TITLE
LOADING DETAILS

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#209]
Add date in used item lines (itemProcessDate).
I suggest you add the date of process for the used items, otherwise same item divided in 2 lines has no meaning.

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/101564036-f29f4c80-39fc-11eb-8c02-87e67f5e3195.PNG">

**Comment by mei309** [comment]
done
