### ISSUE TITLE
Waste amounts items in production

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#21]
Waste amounts **items** drop down in production is by supply group.
should be by item category - waste.
e.g. 
 VALUE  =  FLOOR | SUPPLY GROUP = NONE   | MEASURE UNIT = LBS | CATEGORY = WASTE

**Comment by mei309** [comment]
its by category. why you thing it isnt?

**Comment by litzvi** [comment]
because my waste items are supplyCategory=NONE and not showing up, please check because i can't run it now before the fixes.

**Comment by mei309** [comment]
if Category=NONE its not waste

**Comment by litzvi** [comment]
supplyCategory = NONE
category = WASTE

**Comment by mei309** [comment]
im using getCashewItemsBasic from ValueTablesReader to get all chasew relativ items so therefor you arent seeing it.
by the way in you code supplyCategory is must.

**Comment by litzvi** [comment]
supplyCategory is must, but i have SupplyCategory.NONE value - look in the enum

**Comment by mei309** [comment]
getItemsByCategry isnt working. dose not give

**Comment by litzvi** [comment]
DO YOU HAVE ITEMS WITH WASTE CATEGORY?

**Comment by litzvi** [comment]
YOUR DROP DOWN FOR ITEMS SUPPLY CATEGORY IS MISSING VALUES (NONE - LOOK IN THE ENUM).
WE WILL NEED TO RETHINK WHAT CATEGORIES MEAN

**Comment by mei309** [comment]
DO YOU HAVE ITEMS WITH WASTE CATEGORY? yes

**Comment by litzvi** [comment]
DID YOU ADD 'NONE' TO THE DROP DOWN OF SUPPLY CATEGORY IN ITEMS

**Comment by mei309** [comment]
its not working even with cashew and general supplycategories with waste.
and i added

**Comment by litzvi** [comment]
DON'T UNDERSTAND, IT'S JUST A SIMPLE QUERY FILTERING BY CATEGORY

**Comment by mei309** [comment]
i have with waste category and its not showing up

**Comment by litzvi** [comment]
i need your controllers otherwise i can't see

**Comment by litzvi** [comment]
is it because it's coming as a list
BasicValueEntity(value=QC HOLD)
BasicValueEntity(value=SCREEN)
BasicValueEntity(value=FLOOR)?
instead of ItemDTO list?

**Comment by litzvi** [comment]
is it working by you?

**Comment by mei309** [comment]
its working by me. upload the new one

**Comment by litzvi** [comment]
great
