### ISSUE TITLE
item dropdowns (packed)

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#211]
please look in the item dropdown for packed items, see how long the names typically are. it's hard to choose, i think you should give wider space for item.

**Comment by mei309** [comment]
i changed it so its always the size of the content.
it has a side effect that if its short stuff to choose its small

**Comment by mei309** [comment]
see for example warehouse

**Comment by mei309** [comment]
and then close the issue unless you think its not good

**Comment by mei309** [comment]
> i changed it so its always the size of the content.
> it has a side effect that if its short stuff to choose its small

i can fix it the question if its nicer or not?

**Comment by litzvi** [comment]
it's perfectly ok with me
