### ISSUE TITLE
name change.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#212]
in item to change from defaultMeasureUnit to measureUnit
is it problematic ??
because im having problems with this name

**Comment by litzvi** [comment]
No problem

**Comment by mei309** [comment]
ok so i also fixed the choosing item adds measurement

**Comment by mei309** [comment]
close it after you change and see it works

**Comment by litzvi** [comment]
the change of the measure unit will cause some problem with the dump

**Comment by mei309** [comment]
> the change of the measure unit will cause some problem with the dump

ok. when you finish let me know so i can see wherelse i can implement it

**Comment by litzvi** [comment]
I changed.
didn't change in database, so no real problem with existing dumps

**Comment by mei309** [comment]
ok. finished
