### ISSUE TITLE
packing report.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#214]
you should add number of bags

**Comment by mei309** [comment]
now we have only weights

**Comment by litzvi** [comment]
not sure where you mean. in what dto do you want it

**Comment by mei309** [comment]
look on packing report. its very strange that we dont have the number of bags

**Comment by mei309** [comment]
or ProcessRow or ProductionProcessWithItemAmount

**Comment by litzvi** [comment]
I agree but it's quite cluttered, so how exactly will you show it?
Anyway, added AmountWithUnit amount to ProductionProcessWithItemAmount.

2 questions:
can I change amountWithUnit to weight for clarity ?
I don't really use the storage anymore, should we remove it since it's so cluttered?

**Comment by mei309** [comment]
I agree but it's quite cluttered. true but later i will find a way to do it nice

**Comment by mei309** [comment]
so for now its finished
