### ISSUE TITLE
itemPo

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#215]
in the useditem you have a field itempo that is only needed in loading and i would like that otherwise you should not give it, because if not i will always show it

**Comment by litzvi** [comment]
should I really change that? theoretically we can allow them to use items from 2 pos.
also by me it's the exact same dto, query and method. can still be changed by creating an extended class for loading but i'm not sure it's really necessary.

**Comment by mei309** [comment]
you will need to change it sometime. its unrealistic to do it by me.
if you want to live for now by all its ok with me

**Comment by mei309** [comment]
and dont forget that you code isnt binary code even so we can do everything with it. its a service for a specific project

**Comment by litzvi** [comment]
YES LEAVE IT FOR NOW
