### ISSUE TITLE
About Available Inventory vs. Inventory

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#216]
I decided to open an issue just to emphasis that the inventory used for choosing usedItems and the one in inventory reports are slightly different.
if a process that has used items is **pending** so the used item storage is still in inventory (so will show in inventory report).
but the storage is not available for use by another process, therefore it's not available for use (won't show in poCodes dropdown ObjectTablesReader->findInventoryPoCodes(..) and WarehouseManagement->getInventory(int))

**Comment by litzvi** [comment]
To make it clearer:
If you don't mind, please change the following method names and let me know after you change and i'll change by me too.

in WarehouseManagement.java:
getInventory(int) --> getAvailableInventory 

in ObjectTablesReader.java:
findCashewInventoryPoCodes() --> findCashewAvailableInventoryPoCodes()
findInventoryPoCodes(Integer itemId) --> findAvailableInventoryPoCodes(Integer itemId)
findInventoryPoCodes(ProductionUse[]) --> findAvailableInventoryPoCodes(ProductionUse[])

**Comment by mei309** [comment]
java functions its better you change first without changing the controllers then i can do a full change very easily

**Comment by litzvi** [comment]
that's why i suggested you change, so you don't confuse the controllers

**Comment by litzvi** [comment]
never mind, i'll change

**Comment by mei309** [comment]
ok. it seams ok.
