### ISSUE TITLE
Weight unit in qc 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#217]
it was correct before, should be after the sample weight OZ or Gram. 
This one isn't connected to the item.

Another thing, I see you put the curser in the fields by default. very nice.
If it's the same in receive sample container weight, please do it over there too - when adding an empty bag weight.

**Comment by mei309** [comment]
it was correct before, should be after the sample weight OZ or Gram.
This one isn't connected to the item. no problem. just did it generally. changed

**Comment by mei309** [comment]
Another thing, I see you put the curser in the fields by default. very nice.
i dont understand ?

**Comment by litzvi** [comment]
ok ask me when we talk because I wrote about it twice

**Comment by mei309** [comment]
ok done
