### ISSUE TITLE
storageMovedGroup

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#219]

**Comment by mei309** [comment]
relocation processDate **its for me not you**

**Comment by mei309** [comment]
storageMovedGroup mesureUnit im not really using it but im having a serious problem when i show it because its showing 2.
maybe in the dto do it json ignore

**Comment by mei309** [comment]
the second one is for you

**Comment by litzvi** [comment]
you do need to set it.

**Comment by litzvi** [comment]
![group_storage-diagram](https://user-images.githubusercontent.com/53637868/101971642-8b380580-3c65-11eb-9001-b5496b5c6eef.gif)

**Comment by litzvi** [comment]
Because I want to allow StorageMove to change the the form of the storage, including changing the measureUnit.
Therefore, we need the measureUnit in the StorageMovesGroup.
When I want to get inventory it looks somthing like this:
			+ "join pi.allStorages sf "
				+ "join sf.group sf_group "
					+ "join UOM uom "
						+ "on uom.fromUnit = sf_group.measureUnit and uom.toUnit = item.measureUnit "

ProcessItem has 'allStorages' list (Set<StorageBase>)
Storage and also StorageMove **are** StorageBase.
so 'allStorages' can also be StorageMove; As you can see I'm accessing the group to get the measureUnit, which in a StorageMove case is StorageMovesGroup, so i'm using it's measureUnit.

Removing the option to change the measureUnit, will only save setting the measureUnit but not the unitAmount, numberUnits and it will restrict the option of changing the forms of the storage during a move.

**Comment by litzvi** [comment]
I wish to find a way to avoid setting the unitAmount, numberUnits  for a move and then I'll just allow a move without any change.
But however i think of doing it, don't see a way to avoid it.

**Comment by litzvi** [comment]
We should see how to fix this whole relocation

**Comment by litzvi** [comment]
Now I do have an idea how to do it. but it's quite a bit of change all around.
So I think it's better to leave it now.

**Comment by litzvi** [comment]
> storageMovedGroup mesureUnit im not really using it but im having a serious problem when i show it because its showing 2.
> maybe in the dto do it json ignore

StorageMovesGroupDTO add @JsonIgnore to the measureUnit field. I'll add too.
If there is any problem, tell me and i'll remove the @JsonIgnore

**Comment by mei309** [comment]
in storageMoveDto itemProcessDate is always null

**Comment by mei309** [comment]
you should do it like usedItemDto
usedItemTable.setItemProcessDate(ui.getItemProcessDate());

**Comment by litzvi** [comment]
ok done

**Comment by litzvi** [comment]
> you should do it like usedItemDto
> usedItemTable.setItemProcessDate(ui.getItemProcessDate());

ok done

**Comment by litzvi** [comment]
> storageMovedGroup mesureUnit im not really using it but im having a serious problem when i show it because its showing 2.
> maybe in the dto do it json ignore

I decided to simplify storage move, so the form  can't be changed.
I removed the measureUnit from StorageMovesGroup (now i'll always refer to the origional ProcessItem measureUnit)
and storage move will only have numberUsedUnits which is the numberUnits.

If all works, i'll see how to get rid of the redundant unitAmount

**Comment by litzvi** [comment]
I checked the storage relocation (after my changes)
everything seems fine besides for the report.
It's working when I access a report from the tool bar (Inventory->reports->relocations with sample) but doesn't fetch right after doing a relocation and going out of the details page.
it's weird.. can't figure it out. 
can you please check? you need to rebuild the database.
I'm uploading version 8.6

**Comment by mei309** [comment]
ok.
