### ISSUE TITLE
fixing.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#22]
compare in tables.
pangitor with grouping.

**Comment by mei309** [comment]
compare fixed

**Comment by mei309** [comment]
for now removed pangitor from tables with groups

**Comment by mei309** [comment]
date local with local date

**Comment by mei309** [comment]
will need help from someone about the dates. i cannot manage it. wasted to much time on it already. so if you have some problem write here

**Comment by litzvi** [comment]
ok

**Comment by mei309** [comment]
closing since its only for me so i changed it to the frontend issues
