### ISSUE TITLE
cannot add item

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#220]
ConstraintViolationImpl{interpolatedMessage='Item has to have a default measure unit', propertyPath=measureUnit, rootBeanClass=class com.avc.mis.beta.entities.item.BulkItem, messageTemplate='Item has to have a default measure unit'}

**Comment by litzvi** [comment]
Are you setting measureUnit or defaultMeasureUnit?
Sorry I'm on the road so can't check.

**Comment by mei309** [comment]
just forgot to change name
