### ISSUE TITLE
supplier dto. 

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#221]
contactDetails:
addresses: null
emails: []
faxes: []
id: null
paymentAccounts: []
phones: []

**Comment by mei309** [comment]
everything is empty so why i get it??

**Comment by litzvi** [comment]
was it always this way or something changed?

**Comment by litzvi** [comment]
it's in version 8.8 i'll upload later today

**Comment by mei309** [comment]
now i know why you did it but it should be fixed (in my opinion)
Message: Received wrong id, entity can't be found in database

**Comment by mei309** [comment]
its because we cannot do edit.
i still think i should not get it back empty. its very un nice to show a label with empty fields.
so if you can fix it easily do otherwise just put back as before

**Comment by litzvi** [comment]
I think it can easily be fixed but better not to do it now because maybe I'm missing something.
I'll do it when I'm back, **meanwhile I changed back and leave the issue open**.
Anyway, I plan to later simplify this whole thing and do it like the receiving samples.

**Comment by litzvi** [comment]
version 9.0 uploaded

**Comment by litzvi** [comment]
I 

> everything is empty so why i get it??

ok fixed. hope it doesn't have side affects
