### ISSUE TITLE
giving empty results

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#222]
dates: []
difference: {amount: 0, measureUnit: "KG", value: "0 KG", filled: true}
ingredients: null
productIn: null
productOut: null
qc: null
totalIngredients: null
totalProductIn: null
totalProductOut: null
totalQC: null
totalWaste: null
waste: null

**Comment by mei309** [comment]
its a bit a problem when you give me zero in this case and also dates an empty array. it makes my stuff way more complicated

**Comment by mei309** [comment]
is it easy to fix by you?

**Comment by litzvi** [comment]
yes i will change it. hopefully later today. I have a ride to sapa

**Comment by litzvi** [comment]
I fixed it.
i.e. i assumed it's ok before, so if you encounter this problem anywhere else just let me know
version 9.1 uploaded

**Comment by litzvi** [comment]
I fixed it. Anywhere you have this problem let me know. Because I assumed
it's OK before.
Version 9.1 uploaded
