### ISSUE TITLE
Editing price in receipt after processing front end error

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#228]
try adding a price to  PO-14107V on the cloud. It's giving correct error when running locally but not on the cloud.
(I saw it in more places. e.g. not manager trying to finalize process, seems like the cloud isn't running well with the Exception settings)

**Comment by mei309** [comment]
its happening because you giving 403 error and i need it for reloading and incorrect pathas

**Comment by mei309** [comment]
wait till i find a solution

**Comment by mei309** [comment]
ok solved

**Comment by litzvi** [comment]
should I change the error?

**Comment by mei309** [comment]
I fixed it alreadySent from my Huawei phone-------- Original message --------From: litzvi <notifications@github.com>Date: Tue, Dec 29, 2020, 14:16To: litzvi/avc-beta <avc-beta@noreply.github.com>Cc: mei309 <isral309@gmail.com>, State change <state_change@noreply.github.com>Subject: Re: [litzvi/avc-beta] Editing price in receipt after processing front end error (#228)
should I change the error?
