### ISSUE TITLE
getAllChecksPyPo (lets do qc roasting)

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#23]

**Comment by litzvi** [comment]
perhaps shipping first? i need to get info about the roasting before

**Comment by litzvi** [comment]
QC roasting is ready :)
addRoastedCashewCheck in Service#QualityCheck which adds the same thing but with ProcessName = ROASTED_CASHEW_QC

I also change the name of RawItemQuality to CashewItemQuality

**Comment by litzvi** [comment]
getRawQualityChecks() now gets only the raw tests, look in the function. I can change it so you give the parameters if you prefer.

**Comment by mei309** [comment]
we will neeed to find a new way to get all the different process of checks togethor

**Comment by mei309** [comment]
and the same also for the raw. like im doing now in ReportsController. please look. that what shows in the tab reports

**Comment by mei309** [comment]
working by me

**Comment by litzvi** [comment]
getAllChecksPyPo or somthing like that. right?

**Comment by mei309** [comment]
its a bit a problem for edit but officaly something like that

**Comment by litzvi** [comment]
in edit you show only that process. what's the problem?
can you please explain exactly what you need?
what processes? what fields etc.

**Comment by mei309** [comment]
i will manage. you will see later the problem

**Comment by mei309** [comment]
just create the functions

**Comment by litzvi** [comment]
I added QualityChecks#getAllQualityChecksByPo(@NonNull Integer poCodeId), see if it suits you.

By the way you can copy the idea in your ReportsController, or do you want me to prepare a method for the PO report too?

**Comment by litzvi** [comment]
I added QualityChecks#getAllQualityChecksByPo(@NonNull Integer poCodeId), see if it suits you.

By the way you can copy the idea in your ReportsController, or do you want me to prepare a method for the PO report too?

**Comment by mei309** [comment]
By the way you can copy the idea in your ReportsController, or do you want me to prepare a method for the PO report too?
i will first try it there

**Comment by litzvi** [comment]
there is an option of 'Quote Reply'

**Comment by mei309** [comment]
thanks

**Comment by mei309** [comment]
i decided to do it process process for now

**Comment by mei309** [comment]
in po reports i get all but not in the normal one
