### ISSUE TITLE
Edit Loading - not showing not used lines

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#230]
If there are a few packings for one po, then we add loading that uses only one of them and edit.
Initially you won't see the other lines that aren't used only if you add an empty line 'add loading po#s' button it will appear, then it will disappear again if you choose the po.
Do you understand this weird behavior?

**Comment by litzvi** [comment]
another thing:
if after choosing the po you try deleting 1 number it tries sending a String instead of a number.
e.g. VAT100 after chosen try to delete 1 zero to be VAT10

**Comment by mei309** [comment]
> another thing:
> if after choosing the po you try deleting 1 number it tries sending a String instead of a number.
> e.g. VAT100 after chosen try to delete 1 zero to be VAT10

fixed

**Comment by mei309** [comment]
Initially you won't see the other lines that aren't used. BECAUSE YOU NEED TO CHOOSE THE PO.
if you add an empty line 'add loading po#s' button it will appear. IT SHOULD NOT HAPPEN BUT IM NOT MANAGING TO SEE IT.

**Comment by litzvi** [comment]
> Initially you won't see the other lines that aren't used. BECAUSE YOU NEED TO CHOOSE THE PO.
> if you add an empty line 'add loading po#s' button it will appear. IT SHOULD NOT HAPPEN BUT IM NOT MANAGING TO SEE IT.

so initially 'add loading po#s'  should be empty, not filled with the previous chosen po. 
also after adding from another po can't go back to a previous one.

**Comment by mei309** [comment]
so initially 'add loading po#s' should be empty, not filled with the previous chosen po. IT IS. PLEASE TELL ME WHERE YOU SAW IT

also after adding from another po can't go back to a previous one. YOU CAN ADD MORE AND MORE POS

**Comment by litzvi** [comment]
> so initially 'add loading po#s' should be empty, not filled with the previous chosen po. IT IS. PLEASE TELL ME WHERE YOU SAW IT
> 
> also after adding from another po can't go back to a previous one. YOU CAN ADD MORE AND MORE POS

As I said it's not working

**Comment by mei309** [comment]
please give me if you meet it again a dump so i can see. i have no clue and i cannot reproduce it

**Comment by litzvi** [comment]
OK i'll check it with the new version
