### ISSUE TITLE
Number available units

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#232]
IN LoadedItemDTO

**Comment by litzvi** [comment]
you got a grade of 100 :)

**Comment by mei309** [comment]
> you got a grade of 100 :)

where?

**Comment by litzvi** [comment]
I thought we aren't using LoadedItem for now

**Comment by mei309** [comment]
the used items of loading

**Comment by mei309** [comment]
it dosent have available units

**Comment by litzvi** [comment]
It exactly the same usedItems as in productionProcesses.
Using the same query and same setter.

**Comment by mei309** [comment]
ok. found it
