### ISSUE TITLE
change in propties

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#233]
#server.port=5000 
#spring.datasource.url=jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME} 
#spring.datasource.username=${RDS_USERNAME}
#spring.datasource.password=${RDS_PASSWORD}

# DDL generation
spring.jpa.hibernate.ddl-auto=update

 # datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ebdb?useSSL=false
##spring.cloud.gcp.sql.database-name=avcdbjpa
##spring.cloud.gcp.sql.instance-connection-name=animated-rhythm-274402:asia-southeast1:avc-beta
spring.datasource.username=root
spring.datasource.password=309864890

**Comment by mei309** [comment]
please change by you so when i upload i dont delete mine

**Comment by litzvi** [comment]
what's the change besides the password.
If you already set a password, then set a strong one.
I added the first 4 lines and changed the password..

**Comment by mei309** [comment]
the first 4 lines and i changed the database name

**Comment by mei309** [comment]
thats all

**Comment by litzvi** [comment]
done
