### ISSUE TITLE
Production Process - material

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#237]
you're only adding the group but not the usedItems. 
If you don't understand, add salt/oil then print out the ProductionProcess

**Comment by mei309** [comment]
because i cant add something that isnt a storage. you need to take care of it

**Comment by litzvi** [comment]
Off course it's a storage

**Comment by mei309** [comment]
its not possible to have all material storages to give them to choose from them.
we need to give them to choose a amount and we do the storages alone

**Comment by mei309** [comment]
if not it will be a disaster

**Comment by litzvi** [comment]
we spoke about it. I'll check tomorrow

**Comment by litzvi** [comment]
i'll close this for now, will open when we get to it
