### ISSUE TITLE
Final Report - enhancement

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#239]
I think we should add decisions for the processes to the final report.
In there current final report they sign for different stages on the whole page.

**Comment by mei309** [comment]
its easy on my part so do it when you want

**Comment by litzvi** [comment]
Ok i added com.avc.mis.beta.dto.report.ProcessStateInfo list (called processes)
it has the date also - so i'll remove the dates after you change it.

it required a change in the qc, now there is information regarding the process (time, status, approvals, checked by)
and every QcReportLine has the items checked with the quality etc.

**Comment by mei309** [comment]
let me know when you upload it

**Comment by mei309** [comment]
just do ItemQc extends ProcessStateInfo. it will make everything a lot easier.
all the rest is ok

**Comment by mei309** [comment]
its 2 arrays in an array for no reason

**Comment by litzvi** [comment]
ProcessStateInfo is for the processes, every one can have a few ItemQc.
the ProcessStateInfo is like the date before but more information.
e.g. for what they usefully put in now - one check for 2 types of items - you'll get one ProcessStateInfo and 2 ItemQc

**Comment by mei309** [comment]
> ProcessStateInfo is for the processes, every one can have a few ItemQc.
> the ProcessStateInfo is like the date before but more information.
> e.g. for what they usefully put in now - one check for 2 types of items - you'll get one ProcessStateInfo and 2 ItemQc

you giving it by process so theres no reason  you have an array of ProcessStateInfo.
just make it extend ProcessStateInfo and it will be easy to deal with

**Comment by mei309** [comment]
showing the way its now its crazy. its very hard and theres no reason

**Comment by litzvi** [comment]
don't understand. call me about it when you're free

**Comment by litzvi** [comment]
pushed Version: 9.20 with the change

**Comment by litzvi** [comment]
oh I see the same problem with Loading, it's also only one process.
I'll fix it too.

**Comment by mei309** [comment]
ok fixed by me
