### ISSUE TITLE
compare receiving and order

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#24]
in ReceiptItemRow in dto.view it will be good if you will give the receivingAmount-orderAmount

**Comment by litzvi** [comment]
you mean receivedOrderUnits field??

**Comment by mei309** [comment]
NO. a filed of the diiference

**Comment by litzvi** [comment]
I DON'T THINK SO, IT'S USUALLY ONE RECEIPT SO NO NEED TO WASTE A COLUMN FOR IT

**Comment by mei309** [comment]
no. i only want it to show in red if its less

**Comment by litzvi** [comment]
I ADDED orderBalance FIELD.

**Comment by mei309** [comment]
so it isnt good because i will show red incoorectly

**Comment by litzvi** [comment]
you can try, and we will see how often it's incorrect and how informative it is.
we can always remove it

**Comment by mei309** [comment]
ok. i put it
