### ISSUE TITLE
Add po codes before orders

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#243]
Po codes should be added separately, then when adding an order or receipt, can only choose from available pos.
Should probably add a range of numbers.
Ahron asked for this.

**Comment by mei309** [comment]
this is good

**Comment by mei309** [comment]
it will also be a good place for edit of the supplier of the po

**Comment by litzvi** [comment]
Yes of course that's part of the reason.

**Comment by litzvi** [comment]
also they can change po number if they will want - requires a structure change, since I currently don't have an id for the po.
So the id won't be automatically generated, they will put it in, we will also give them the option to add a range of numbers.

**Comment by mei309** [comment]
also they can change po number if they will want. I DONT THINK ITS A GOOD IDEA

**Comment by litzvi** [comment]
Haha, you'll be surprised but they actually do it. Off course don't let
from the front but if I add the id, we can do from the back.

**Comment by mei309** [comment]
THEY DO EVERYTHING BUT WE STILL CANNOT ALLOW EVERYTHING. WE NEED A LITTLE STRUCTURE

**Comment by litzvi** [comment]
issue 253 is dealing with it
