### ISSUE TITLE
Delete ABE10133 from pending receive 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#244]

**Comment by litzvi** [comment]
@ELIPELET  I rejected it, was that what you wanted ?
As we discussed, unfortunately now you can't make a new one because it had no order.

So @mei309 we need to delete this po completely too

**Comment by mei309** [comment]
it will be possible on the next version that will be up on Sunday to the cloud. in managment

**Comment by litzvi** [comment]
done
