### ISSUE TITLE
Cashew Orders -> rejected report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#245]
Doesn't show details for rejected receipts. Don't see why.

**Comment by mei309** [comment]
its rejected orders. we dont have rejected receipts

**Comment by mei309** [comment]
in the new way its fixed

**Comment by litzvi** [comment]
didn't understand. why wasn't it working? the reject is the receipt.
aren't you using com.avc.mis.beta.service.Receipts.findCancelledCashewReceipts() ?
go to Cashew Orders-> rejected on the app and try opening one of the lines.

**Comment by mei309** [comment]
i understand the problem and its fixed in the version i will upload tonight
