### ISSUE TITLE
Separate Orders from Receipts 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#246]
I think the orders and receipts reports should be in separate tabs in the menu, it's confusing for them.
Also we should have for every one a report with all orders/receipts (that should have a status column)

**Comment by mei309** [comment]
> I think the orders and receipts reports should be in separate tabs in the menu, it's confusing for them.
> Also we should have for every one a report with all orders/receipts (that should have a status column)

build the functions for it

**Comment by mei309** [comment]
i checked. you dont have for reciving

**Comment by mei309** [comment]
i made it ready just waiting for the function

**Comment by litzvi** [comment]
for orders, you have:

1. findOpenCashewOrders - not cancelled order and not fully received
2. findAllCashewOrders - final, pending (although we don't have pending at the moment), not cancelled
3. findAllCashewOrdersHistory - everything including cancelled

what else do you need?
I think we don't even need number 2, only open and everything

**Comment by litzvi** [comment]
receiving reports:

- findFinalCashewReceipts - only final 
- findPendingCashewReceipts - only pending
- findCancelledCashewReceipts - only cancelled

now I added (version 9.7)

- findCashewReceiptsHistory - all receipts

**Comment by litzvi** [comment]
You only need to show the status in the history table

**Comment by litzvi** [comment]
And by separating tabs, I mean in the main tool bar it should be totally separate buttons.

**Comment by mei309** [comment]
put a function findGeneralReceiptsHistory

**Comment by mei309** [comment]
and look on the new way and tell me what you think

**Comment by litzvi** [comment]
Yes the way you did is much better.

I suggest you change the tab name of 'all orders' in orders to 'History'
and in receiving to (Pending, Finalized, History)

both 'History' tables are not working.

**Comment by litzvi** [comment]
> put a function findGeneralReceiptsHistory

done version 9.9

**Comment by mei309** [comment]
> History

its not only history its all

**Comment by mei309** [comment]
why findFinalGeneralReceipts returns ReceiptItemRow and not ReceiptRow like all the others ??

**Comment by mei309** [comment]
both 'History' tables are not working. OF CASHEW IS WORKING.
ITS NOT SHOWING STATUS BECASUE YOU ARENT GIVING IT IN RECIPITROW OR IN RECIPITITEMROW

**Comment by mei309** [comment]
HISTORY OF GENERAL ISNT WORKING BECAUSE I DIDNT HAVE THE UNCTION YET

**Comment by litzvi** [comment]
> why findFinalGeneralReceipts returns ReceiptItemRow and not ReceiptRow like all the others ??

good question. fixed

**Comment by litzvi** [comment]
btw in displaying ReceiptRow, do you use receiptDate of the ReceiptRow or ReceiptItemRow?
If you use of the ReceiptRow i'm gonna add JsonIgnore in the ReceiptItemRow.

**Comment by litzvi** [comment]
> > History
> 
> its not only history its all

History is everything, if you don't like find another name or just 'All'

**Comment by mei309** [comment]
> > > History
> > 
> > 
> > its not only history its all
> 
> History is everything, if you don't like find another name or just 'All'

ok done

**Comment by mei309** [comment]
> btw in displaying ReceiptRow, do you use receiptDate of the ReceiptRow or ReceiptItemRow?
> If you use of the ReceiptRow i'm gonna add JsonIgnore in the ReceiptItemRow.

one of them is enough. if they all the same so leave it out otherwise leave in

**Comment by mei309** [comment]
> btw in displaying ReceiptRow, do you use receiptDate of the ReceiptRow or ReceiptItemRow?
> If you use of the ReceiptRow i'm gonna add JsonIgnore in the ReceiptItemRow.

by me it uses now the outer one but if you delete it will use the inner one

**Comment by litzvi** [comment]
ok thank. so i'll leave it for now
