### ISSUE TITLE
Error of information during processing data. 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#247]
Lot no: po 14468 WSLP 
 כתבו בטעות שזה אייטם W320 באמצע התהליך (בין השלב Clean item ל roast item) אי אפשר לעשות edit, גם לא maneger.
לדעתי, אולי אפשר לחסום אפשרויות אחרות לבחירה באמצע התהליך מלבד האייטם עצמו, למשל אם הpo! המדובר הוא WSLP, לא נוכל להגדיר אותו בהמשך שהוא w320 או כל אייטם אחר, נהיה חייבים להצמד לסוג אייטם שהוגדר בהזמנה או בקבלה.

**Comment by litzvi** [comment]
The reason we left it open is because you do change the item sometimes. 
We should allow more flexible edits.
meanwhile I suggest you change from the server database.

**Comment by litzvi** [comment]
@mei309 this query should work to fix this mistake:

update 
	process_groups as pg 
	join processed_items as pi 
		on pi.group_id=pg.id
set pi.item_id = 31 where pg.process_id=193 and pg.group_name is null and pi.item_id = 14;

**Comment by litzvi** [comment]
in the next version you can edit even after processing the produced items

**Comment by mei309** [comment]
changed.
