### ISSUE TITLE
CASHEW RECEIVE DETAILS DISPLEY

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#25]
RECEIVE, THEN FINALIZE FROM DETAILS PAGE.
AFTER CONFIRM, DOESN'T DISPLAY DETAILS WELL, WHY?

**Comment by mei309** [comment]
RECEIVE, THEN FINALIZE FROM DETAILS PAGE.????
AFTER CONFIRM, DOESN'T DISPLAY DETAILS WELL, WHY? solved
