### ISSUE TITLE
Loadings table not showing

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#250]
I have a case the loading table isn't showing although there are 4 loadings. (I do see it in the package from F12)
i'll attach the dump
[Dump_notShowingLoadings.zip](https://github.com/litzvi/avc-beta/files/5780407/Dump_notShowingLoadings.zip)

**Comment by mei309** [comment]
i asked you to change the name of the database already twice. I CAN'T USE YOUR DUMPS OTHERWISE

**Comment by mei309** [comment]
and the dump isnt good

**Comment by mei309** [comment]
Table 'avcdbjpa.user_roles' doesn't exist
this is what im getting for all tables respectively

**Comment by mei309** [comment]
[ebdb_addresses.zip](https://github.com/litzvi/avc-beta/files/5781021/ebdb_addresses.zip)
see the difference between the both. yours dosnt work.
and change the name of the db to ebdb

**Comment by litzvi** [comment]
> i asked you to change the name of the database already twice. I CAN'T USE YOUR DUMPS OTHERWISE

where? and to what?

**Comment by litzvi** [comment]
> Table 'avcdbjpa.user_roles' doesn't exist
> this is what im getting for all tables respectively

because it's not building the tables.
so just truncate the database

**Comment by litzvi** [comment]
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE `avcdbjpa`.`addresses`;
TRUNCATE `avcdbjpa`.`bank_accounts`;
TRUNCATE `avcdbjpa`.`bank_branches`;
TRUNCATE `avcdbjpa`.`bank_payees`;
TRUNCATE `avcdbjpa`.`banks`;
TRUNCATE `avcdbjpa`.`booked_containers`;
TRUNCATE `avcdbjpa`.`cashew_standards`;
TRUNCATE `avcdbjpa`.`cities`;
TRUNCATE `avcdbjpa`.`companies`;
TRUNCATE `avcdbjpa`.`company_contacts`;
TRUNCATE `avcdbjpa`.`company_positions`;
TRUNCATE `avcdbjpa`.`contact_details`;
TRUNCATE `avcdbjpa`.`container_loadings`;
TRUNCATE `avcdbjpa`.`contract_types`;
TRUNCATE `avcdbjpa`.`count_amounts`;
TRUNCATE `avcdbjpa`.`countries`;
TRUNCATE `avcdbjpa`.`emails`;
TRUNCATE `avcdbjpa`.`extra_added`;
TRUNCATE `avcdbjpa`.`faxes`;
TRUNCATE `avcdbjpa`.`id_information`;
TRUNCATE `avcdbjpa`.`item_counts`;
TRUNCATE `avcdbjpa`.`item_weights`;
TRUNCATE `avcdbjpa`.`items`;
TRUNCATE `avcdbjpa`.`loaded_items`;
TRUNCATE `avcdbjpa`.`order_receipts`;
TRUNCATE `avcdbjpa`.`payment_accounts`;
TRUNCATE `avcdbjpa`.`persons`;
TRUNCATE `avcdbjpa`.`phones`;
TRUNCATE `avcdbjpa`.`po_codes`;
TRUNCATE `avcdbjpa`.`po_items`;
TRUNCATE `avcdbjpa`.`po_processes`;
TRUNCATE `avcdbjpa`.`process_approvals`;
TRUNCATE `avcdbjpa`.`process_groups`;
TRUNCATE `avcdbjpa`.`process_groups_w_storages`;
TRUNCATE `avcdbjpa`.`process_life_cycle`;
TRUNCATE `avcdbjpa`.`process_management`;
TRUNCATE `avcdbjpa`.`process_types`;
TRUNCATE `avcdbjpa`.`processed_items`;
TRUNCATE `avcdbjpa`.`processes`;
TRUNCATE `avcdbjpa`.`processes_with_product`;
TRUNCATE `avcdbjpa`.`production_lines`;
TRUNCATE `avcdbjpa`.`production_process`;
TRUNCATE `avcdbjpa`.`purchase_orders`;
TRUNCATE `avcdbjpa`.`qc_cashew_items`;
TRUNCATE `avcdbjpa`.`qc_tests`;
TRUNCATE `avcdbjpa`.`receipt_items`;
TRUNCATE `avcdbjpa`.`sample_items`;
TRUNCATE `avcdbjpa`.`sample_receipts`;
TRUNCATE `avcdbjpa`.`shipment_codes`;
TRUNCATE `avcdbjpa`.`shipping_port`;
TRUNCATE `avcdbjpa`.`shippment_bookings`;
TRUNCATE `avcdbjpa`.`standard_items`;
TRUNCATE `avcdbjpa`.`storage_forms`;
TRUNCATE `avcdbjpa`.`storage_moves`;
TRUNCATE `avcdbjpa`.`storage_moves_group`;
TRUNCATE `avcdbjpa`.`storage_relocations`;
TRUNCATE `avcdbjpa`.`storage_sample`;
TRUNCATE `avcdbjpa`.`storage_transfers`;
TRUNCATE `avcdbjpa`.`storages_base`;
TRUNCATE `avcdbjpa`.`suppliers`;
TRUNCATE `avcdbjpa`.`suppliers_categories`;
TRUNCATE `avcdbjpa`.`supply_categories`;
TRUNCATE `avcdbjpa`.`transaction_processes`;
TRUNCATE `avcdbjpa`.`uom`;
TRUNCATE `avcdbjpa`.`used_item_counts`;
TRUNCATE `avcdbjpa`.`used_items`;
TRUNCATE `avcdbjpa`.`used_items_base`;
TRUNCATE `avcdbjpa`.`used_items_group`;
TRUNCATE `avcdbjpa`.`user_messages`;
TRUNCATE `avcdbjpa`.`user_roles`;
TRUNCATE `avcdbjpa`.`users`;
TRUNCATE `avcdbjpa`.`warehouse_locations`;

**Comment by litzvi** [comment]
[Uploading no_loading_report_zip.zip…]()

**Comment by litzvi** [comment]
[no_loading_report_zip.zip](https://github.com/litzvi/avc-beta/files/5781616/no_loading_report_zip.zip)

**Comment by mei309** [comment]
> I have a case the loading table isn't showing although there are 4 loadings. (I do see it in the package from F12)
> i'll attach the dump
> [Dump_notShowingLoadings.zip](https://github.com/litzvi/avc-beta/files/5780407/Dump_notShowingLoadings.zip)

its because you have empty loadings. 2 of them are without used items. i fixed it but its not really a case that should happen

**Comment by litzvi** [comment]
Yes it may happens if I delete all process by po so it deletes the used
items that are from that po but not the loading itself since the loading
isn't directly associated with the po.
So it's even more important you always show everything in the tables so
stuff don't get lost, otherwise it's very hard to find such errors.

**Comment by mei309** [comment]
I DID IT. IT COULD BE I MISSID SOMEWHERE BUT IT NEEDS TO SHOW EVERYTHING
