### ISSUE TITLE
mixing 2 po for packing 

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#251]

**Comment by litzvi** [comment]
yes! unfortunately I got this one wrong, even though we discussed it before.

**Comment by litzvi** [comment]
It's a very big change by me.. but here is a first thought suggestion.

Completely decouple the the processes (the production processes maybe also the receipt, besides for the order)
I'll search for the item po recursively through the used items until the order.
can display more than one po for item (in case it's a mix)
for the final report i can also calculate the ratio of the different POs
If we change it, you should probably let them choose add an item or po for a process.

**Comment by litzvi** [comment]
Another option would be adding a dummy po for such a process that references the 2 or more POs and displays accordingly

**Comment by litzvi** [comment]
Actually the simplest way would be to automatically set a list of pos with the ratio in every process or processItem

**Comment by mei309** [comment]
> Another option would be adding a dummy po for such a process that references the 2 or more POs and displays accordingly

THIS IS WHAT I SUGGESTED AND ITS GOOD ALSO FOR THE ITEM PROBLEM

**Comment by mei309** [comment]
> It's a very big change by me.. but here is a first thought suggestion.
> 
> Completely decouple the the processes (the production processes maybe also the receipt, besides for the order)
> I'll search for the item po recursively through the used items until the order.
> can display more than one po for item (in case it's a mix)
> for the final report i can also calculate the ratio of the different POs
> If we change it, you should probably let them choose add an item or po for a process.

THIS WILL BE TRIBBLE IN MY OPINION

**Comment by litzvi** [comment]
What item problem? And how does it help?

**Comment by mei309** [comment]
> Actually the simplest way would be to automatically set a list of pos with the ratio in every process or processItem

IT WILL STILL BE DIFFICULT TO PROCESS BOTH TOGETHER

**Comment by litzvi** [comment]
What item problem? And how does it help?

**Comment by mei309** [comment]
> > Another option would be adding a dummy po for such a process that references the 2 or more POs and displays accordingly
> 
> THIS IS WHAT I SUGGESTED AND ITS GOOD ALSO FOR THE ITEM PROBLEM

IN PROCESS WE DONT ALLOW TO USE A DIFFERENT ITEM. AND IF THEY WANT TO CHANGE THEY CAN DO IT IN THAT FORM

**Comment by mei309** [comment]
im closing since we have a new one about it
