### ISSUE TITLE
Joint id for all entities in BaseEntity

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#252]
Change the structure so all entities have auto generated id, transient to the user.
first change accordingly:
PoCode
ShipmentCode
IdCard

**Comment by litzvi** [comment]
I added an id for ShipmentCode same as I did for PoCode.
here are the commands to run on the old database (before running the new application)

alter table ebdb.shipment_codes rename column code to id;
alter table ebdb.shipment_codes add code varchar(255);
update ebdb.shipment_codes set code = id where id >= 0;
alter table ebdb.shipment_codes add constraint shipment_code_unique unique (code);

also add unique for PoCode (hibernate doesn't add by me constraints if the table exists)

alter table ebdb.po_codes add constraint po_code_unique unique (code);

**Comment by litzvi** [comment]
done and uploaded from Version: 9.16

**Comment by mei309** [comment]
ok. i dont see any reason for trouble
