### ISSUE TITLE
PoCode changes

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#253]
I added an **id** to the PoCode, so now a PoCode has an id(Integer) and Code(String).
All references to the poCode should be done to the id.
code has to be given a value - now it's a string for more flexiabilty.

PoCode needs to be added separately - you can add it in the order tab.
it probably shouldn't be given for edit, so I didn't implement edit.

I added a function to get the free po codes (free = not used for order/receipt or used and cancelled)
com.avc.mis.beta.service.ObjectTablesReader.findFreePoCodes()

**Comment by mei309** [comment]
finished

**Comment by litzvi** [comment]
great
