### ISSUE TITLE
Process with mixed pos - issue 251 cont.

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#254]
JUST A SUGGESTION
I didn't fully implement, but added a field productWeightedPos in PoProcess (we might want to move it down only to ProductionProcess later).
It's just a list of pos with their weights (e.g 0.3 po1, 0.7 po2)
It will need to be added for a process that needs it.
I left the poCode of PoProcess, so it will only need to be fetched and represented when they mix more than one po.
When choosing inventory of a po, i will be able to fetch the mixed ones to.

**Comment by mei309** [comment]
it will be a very big change i dont recommend

**Comment by mei309** [comment]
ok. i found a great way to do it. so processing 2 pos together will work fine.
the reports will be a bit tricky.
but i really dont think a 2 po system will work. or you give array of pos or you give one

**Comment by litzvi** [comment]
i added productWeightedPos in ProductionProcess
pay attention, it's in addition to the po not instead.
So either po or this list of productWeightedPos  can be set.
Don't implement it yet, just look and we will discuss it.

uploaded in version 9.19

**Comment by mei309** [comment]
ok i saw it. just to be clear i cannot set the weight

**Comment by litzvi** [comment]
Anyway, they need to set it

**Comment by litzvi** [comment]
I think I'll suggest them to add another po for when they mix. e.g. VAT-101MIX
I'll add a display field in the poCode, they can fill it with the 2 used pos.
The value will be the display if not null, otherwise just like before. 

they will have to fill the new po code in case they choose more than 1 po.
is that ok with you?

**Comment by mei309** [comment]
ok. will do but only after uploading a new version online

**Comment by litzvi** [comment]
I changed the structure of PoCode.
Now ProductionProcess can reference a MixPoCode.
I didn't implement the changes needed in the dtos, but just for getting on the same page.

**Comment by litzvi** [comment]
![codes](https://user-images.githubusercontent.com/53637868/105481056-17176580-5cd9-11eb-9526-817d52ae1d76.gif)

**Comment by litzvi** [comment]
![codes](https://user-images.githubusercontent.com/53637868/105481262-6362a580-5cd9-11eb-9dac-585d0e70435d.gif)

**Comment by litzvi** [comment]
so what i need is

- display the po code value correctly (depending on the display) in the dtos
- add the class/type to the dto
- add a dto that gets the mixPoCode pocodeIds (perhaps in all)
- function for getting MixPoCodes
- make sure the relevant ObjectTablesReader methods include MixPoCodes

**Comment by mei309** [comment]
i still dont like this way

**Comment by mei309** [comment]
all needs to be the same. therefor or a packing process has one po or a list.
a combination will make a lot of problems in the front

**Comment by litzvi** [comment]
It's one po, look at the structure

**Comment by mei309** [comment]
i dont see what i need to do

**Comment by litzvi** [comment]
- a separate place to add/edit Mixed POs
- another button in the production process to choose from mixed pos

**Comment by mei309** [comment]
im going to consider it as one po therefor those 2 arent relevant .

- another button in the production process to choose from mixed pos
- when choosing a mixed po, need to show the inventory of both(all) pos.

**Comment by mei309** [comment]
i dont see the functions to add pos together

**Comment by litzvi** [comment]
> im going to consider it as one po therefor those 2 arent relevant .

So how will you show it to them? I'm not giving it together.
so how will you know that you need to call a few pos?

**Comment by mei309** [comment]
> > im going to consider it as one po therefor those 2 arent relevant .
> 
> So how will you show it to them? I'm not giving it together.
> so how will you know that you need to call a few pos?

we need to do that in the backend not the front

**Comment by litzvi** [comment]
why not make a separate popup?
it keeps neater

**Comment by litzvi** [comment]
MixPoCode is a mix of OrderPoodes (can't mix a mix).

suggested method 

- getFreeMixPos() - gives the mixed pos that aren't used yet.
- getMixPoInventory() - gives the inventory of all underlaying pos (should be used for the process that is mixing only)

**Comment by litzvi** [comment]
the problem with this is things can't be mixed twice

**Comment by litzvi** [comment]
@mei309 what you need to do:

- let them create a mix po, choosing the underlying pos.
- let them add a production process with the mixPo code and call getMixPoInventory()
- when they edit this process you also need to call getMixPoInventory()

So you also need a flag to tell you it's a process that mixes pos

**Comment by mei309** [comment]
i can work with it. even so i think it can be useful to include in the normal free pos

**Comment by litzvi** [comment]
> i can work with it. even so i think it can be useful to include in the normal free pos

you need to create a different kind of po (MixPoCode)
You need to call inventory of the underlying pos

**Comment by litzvi** [comment]
I can add them together but it won't change the fact that you need to treat them different by you

**Comment by mei309** [comment]
mix po has Set<BasePoCode> poCodes so we just need to change the function getPoInventory() that if its not null to call it for the kids

**Comment by mei309** [comment]
you need to create a different kind of po (MixPoCode) this isnt a problem

**Comment by litzvi** [comment]
> mix po has Set poCodes so we just need to change the function getPoInventory() that if its not null to call it for the kids

no. that's not efficient

**Comment by mei309** [comment]
the other way isnt efficient by me

**Comment by litzvi** [comment]
> the other way isnt efficient by me

you mean it's not easy by you.
I'm talking about a few queries i need to make.
to know if it's mix, then to know if it's the process that's mixing

**Comment by mei309** [comment]
just add a parameter to the po and i will return that. then its very easy for both

**Comment by litzvi** [comment]
you need to set it

**Comment by mei309** [comment]
i really think you dont understand

**Comment by litzvi** [comment]
I understand. you want to make a structural change without changing anything by you

**Comment by mei309** [comment]
not at all

**Comment by mei309** [comment]
call

**Comment by litzvi** [comment]
It's too long. I'll open a new one
