### ISSUE TITLE
PORCHASE ORDERS->NEW

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#259]
SHOWS EMPTY SOMTIMES, ONLY WORKS ON THE SECOND TIME SHOOSING

**Comment by litzvi** [comment]
Also why do you have 2 add #po buttons that one doesn't work?

**Comment by mei309** [comment]
also in the new version?

**Comment by litzvi** [comment]
THIS ONE WAS FROM THE OLD ONE
