### ISSUE TITLE
Receiving cashew schedule

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#26]
NOT SHOWING STATUS, ALTHOUGH I'M GIVING YOU.
ALSO GENERAL INVENTORY, SHOWING CASHEW

**Comment by mei309** [comment]
NOT SHOWING STATUS, ALTHOUGH I'M GIVING YOU. solved.
ALSO GENERAL INVENTORY, SHOWING CASHEW. can you do functions like getInventoryTableByPo and getInventoryTableByItem from cashewReports

**Comment by litzvi** [comment]
Changed service->CashewReports class to InventoryReports.
the methods get a SupplyCategory, so you can use accordingly.

**Comment by mei309** [comment]
ok works
