### ISSUE TITLE
ADD SUPPLIER

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#260]
![image](https://user-images.githubusercontent.com/53637868/104460821-24e63000-55e1-11eb-88d3-857f4c4b776b.png)

**Comment by litzvi** [comment]
WHY IS THE SUPPLIER NOT IN THE RIGHT PLACE?

**Comment by mei309** [comment]
the form is created before the window. i didnt find a solution yet

**Comment by mei309** [comment]
ok fixed
