### ISSUE TITLE
QC DETAILS NOT SHOWING

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#261]
ENDLESS WHEEL FOR DETAILS.
AND BY THE WAY, THE PROGRAM BECAME VERY SLOW FOR EVERY PAGE IT'S FETCHING WHEN RUNNING LOCALLY

**Comment by mei309** [comment]
both arent happening by me. are you using the dump of the data of the cloud?

**Comment by mei309** [comment]
and check if it prints something out in f12

**Comment by litzvi** [comment]
RROR TypeError: Cannot read property 'forEach' of null
    at ShowDetailsComponent.set dataSource [as dataSource] (show-details.component.ts:137)
    at setInputsForProperty (core.js:10035)
    at elementPropertyInternal (core.js:9079)
    at Module.ɵɵproperty (core.js:15103)
    at QcDetailsDialogComponent_Template (qc-details-dialog.component.ts:15)
    at executeTemplate (core.js:8689)
    at refreshView (core.js:8558)
    at refreshComponent (core.js:9711)
    at refreshChildComponents (core.js:8355)
    at refreshView (core.js:8608)

**Comment by litzvi** [comment]
IT DOES GO IN, ONLY A PROBLEM FETCHING/DISPLAYING DETAILS

**Comment by litzvi** [comment]
> both arent happening by me. are you using the dump of the data of the cloud?

USING A CLEAN NEW DATABASE

**Comment by litzvi** [comment]
If you don't see the problem, try adding a qc for a brand new po (before order and receipt)

**Comment by mei309** [comment]
you tried putting in Storage(if stored) section?

**Comment by litzvi** [comment]
no

**Comment by mei309** [comment]
> RROR TypeError: Cannot read property 'forEach' of null
> at ShowDetailsComponent.set dataSource [as dataSource] (show-details.component.ts:137)
> at setInputsForProperty (core.js:10035)
> at elementPropertyInternal (core.js:9079)
> at Module.ɵɵproperty (core.js:15103)
> at QcDetailsDialogComponent_Template (qc-details-dialog.component.ts:15)
> at executeTemplate (core.js:8689)
> at refreshView (core.js:8558)
> at refreshComponent (core.js:9711)
> at refreshChildComponents (core.js:8355)
> at refreshView (core.js:8608)

this error means you retuning a processItem object that isnt an array

**Comment by mei309** [comment]
i checked all possibilities and its all working besides putting in processItems

**Comment by mei309** [comment]
ok fixed
