### ISSUE TITLE
Weird stuff going on

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#265]
i just added a storage relocation and it called edit.
other times it worked

**Comment by mei309** [comment]
not by me

**Comment by litzvi** [comment]
yes only happens some times

**Comment by mei309** [comment]
how do you know its calling edit? from f12?

**Comment by litzvi** [comment]
because it's giving an error that comes from my edit function

**Comment by mei309** [comment]
when it happens again check f12. because I dont see no reason for it to happen by me

**Comment by litzvi** [comment]
f12 gave nothing, i tried. ok i'll close it until it happens again

**Comment by mei309** [comment]
f12 gives the functions it calls for example 
349    http://localhost:4200/api/api/inventory/getCashewInventoryItem
so just see the 2 last ones if one of them is edit

**Comment by litzvi** [comment]
ok
