### ISSUE TITLE
cannot delete all po process

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#267]
java.sql.SQLSyntaxErrorException: Table 'ebdb.pruduct_weighted_pos' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.20.jar:8.0.20]

**Comment by mei309** [comment]
it happens only when i use the dump

**Comment by litzvi** [comment]
You need to run the program after you import and before you use it so it
builds that new table.

**Comment by mei309** [comment]
and when to run the sql lines that apply code to id?

**Comment by litzvi** [comment]
assuming you have the current cloud data in the database.

- run sql commands to apply id for po_codes
- run spring application

then you should be able to use normally including deleting pos

**Comment by mei309** [comment]
ok thanks
