### ISSUE TITLE
Receiving->All->Edit

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#271]
gets an error that there is no order for this po because it's a receive without an order.
you're calling com.avc.mis.beta.service.Orders.getOrder(int) with com.avc.mis.beta.controllers.OrdersController.orderDetailsPo(int).
don't understand why you are calling this function.

**Comment by mei309** [comment]
you changed some time all the receiving to be CASHEW_RECEIPT therefor i have no way to know if its with a order or not.
i need the order for the order item drop down

**Comment by litzvi** [comment]
I understand. 
I don't think it's a reason to divide the process type.
So just catch the exception if there is no order and you will know it's without an order.

**Comment by mei309** [comment]
i need it in more places. just add a field for it

**Comment by mei309** [comment]
ok fixed
