### ISSUE TITLE
ReceiptItemRow

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#276]
I added the field receivedOrderUnits- the payable units.
I think you should show that in the report instead of the order amount, since that's what i'm using to determine the status of the order.

Also, you aren't using orderBalance in ReceiptItemRow, right? if so, i'll remove it.

**Comment by litzvi** [comment]
I'll add it also to the ReceiptReportLine

**Comment by mei309** [comment]
orderBalance IM NOT USING IT

**Comment by mei309** [comment]
IM USING orderBalance TO SEE IF WE STILL MISSING SOME

**Comment by mei309** [comment]
WHAT THIS FIELD SHOULD BE "ORDER AMOUNT"?

**Comment by litzvi** [comment]
> IM USING orderBalance TO SEE IF WE STILL MISSING SOME

right, sorry forgot

**Comment by litzvi** [comment]
> WHAT THIS FIELD SHOULD BE "ORDER AMOUNT"?

don't understand

**Comment by litzvi** [comment]
I'm suggesting instead of ordeAmount, show receivedOrderUnits(=payable units)
and the orderBalance will be compared to receivedOrderUnits.

just a suggestion. what do you think?

**Comment by mei309** [comment]
i dont think its information we need in the table.
and also if we put what i should call the cloumn?

**Comment by litzvi** [comment]
the orderBalance should be relative to receivedOrderUnits not to order, that's why I'm suggesting to change. Moreover, it's suitable also for receipt without order.
you can call it: payable units

**Comment by mei309** [comment]
> the orderBalance should be relative to receivedOrderUnits not to order, that's why I'm suggesting to change. Moreover, it's suitable also for receipt without order.
> you can call it: payable units

i dont mind changing but i dont think its correct

**Comment by mei309** [comment]
ok done
