### ISSUE TITLE
ABE-10250

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#286]
can't receive.

- added an order
- cancelled the order
- made another order
- now can't except

**Comment by litzvi** [comment]
I know why. it's because there is a list when i'm only giving one in the query.
I'll fix it

**Comment by litzvi** [comment]
ok I fixed it. in the next version

**Comment by litzvi** [comment]
I think you should catch any error caused by fetching the order for the edit of receipt.
It's causing problems in case the order was cancelled, can't edit the receipt.
It's not something that should happen, but still the edit should always work

**Comment by litzvi** [comment]
Actually I should give you the order id in the receipt, so you don't need to search it by po.
Now we can have more than 1 order with the same po (if the others are cancelled), therefore it's not really safe to search by PO

**Comment by mei309** [comment]
ok. let me know when done

**Comment by litzvi** [comment]
where should I give you the po process id for editing a receipt?

1. In the order item dto i'll add a field for the processId
2. you set the po for an for an order receipt, then I of course return it in the dto of receipt.

1 makes more sense to me, I'm just worried you will say it's too nested

**Comment by mei309** [comment]
1 out of the question.
why not 
3) in the ReceiptDTO, i will need to fish it so its better in the backend

**Comment by litzvi** [comment]
> 3) in the ReceiptDTO, i will need to fish it so its better in the backend

It's 2 different places referencing the same thing, I worry it will cause bugs but I can do it

**Comment by mei309** [comment]
its or you do it in the back or i do it in the front. in both ways it might have errors.
its only one for a ReceiptDTO. we dont need for each recipitItem

**Comment by litzvi** [comment]
ok. I'm doing it from the back.
you have a filed referencedOrder - id of the order if exists in ReceiptDTO

**Comment by litzvi** [comment]
I'll block fetching order with po, just to make sure you use it.

**Comment by mei309** [comment]
i still need to search by po in case of a new receipt

**Comment by litzvi** [comment]
> i still need to search by po in case of a new receipt

yes correct

**Comment by mei309** [comment]
so you will just give me the last uncancelled one?

**Comment by litzvi** [comment]
there should only be one uncancelled at any time

**Comment by litzvi** [comment]
actually i only give you the final one

**Comment by mei309** [comment]
you have a filed referencedOrder - id of the order if exists in ReceiptDTO
YOU CAN TAKE IT OFF

**Comment by litzvi** [comment]
why? you asked for it?

**Comment by mei309** [comment]
IM GOING TO CALL BY PO SO IT DOESN'T MATTER

**Comment by mei309** [comment]
IT WAS IF WE CALL WITH THE ORDER ID

**Comment by litzvi** [comment]
The reason i did it is because say for example:

1. made an order and received
2. canceled the receipt and order
3. now you want to edit the cancelled order

So for edit you should probably call by process id.

**Comment by mei309** [comment]
ok done
