### ISSUE TITLE
Management -> items 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#287]
allow decimal point for unit weight

**Comment by litzvi** [comment]
In general wherever i use BigDecimal you should allow it

**Comment by mei309** [comment]
> In general wherever i use BigDecimal you should allow it

i try

**Comment by mei309** [comment]
you dont have an amount of decimals there

**Comment by litzvi** [comment]
i do  - AmountWithUnit is with a BigDecimal

**Comment by mei309** [comment]
how many decimals ?? 1 2 3 4 5 ???

**Comment by mei309** [comment]
decimal is after the dot

**Comment by litzvi** [comment]
yes, so they can write 3.5 LBS in a bag

**Comment by litzvi** [comment]
do 3 for now, like everywhere

**Comment by mei309** [comment]
ok done
