### ISSUE TITLE
General Orders

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#291]
We need to see how we separate po codes for cashew and general, i'll speak to the about it next time i'm there.

**Comment by litzvi** [comment]
Meanwhile let's assume we are using the same pos.
please check: 

- you can change the default currency in general order/receipt to VND
- why isn't it showing general order tables - it's showing an empty line in the report
- receive from the details, doesn't work
- general receiving report not showing at all

Start working with it and we will see how what the challenges are

**Comment by mei309** [comment]
why isn't it showing general order tables. please return the same as in cashew.
List<PoRow> findOpenGeneralOrders  to List<PoItemRow> findOpenGeneralOrders

**Comment by mei309** [comment]
receive from the details its because of the table problem

**Comment by litzvi** [comment]
> why isn't it showing general order tables. please return the same as in cashew.
> List PoRow findOpenGeneralOrders to List PoItemRow findOpenGeneralOrders
> and same in findAllGeneralOrders

use findOpenGeneralOrderItems (exists)
use findAllGeneralOrderItems (adding in Version: 9.25)
findAllGeneralOrderItemsHistory (also next version)

**Comment by litzvi** [comment]
I pushed it already

**Comment by mei309** [comment]
ok. all fixed. 
i will upload also controllers

**Comment by litzvi** [comment]
So now everything i general inventory is working?

**Comment by mei309** [comment]
ORDERS, RECIVING AND INVENTORY REPORTS

**Comment by mei309** [comment]
I DIDNT CHECK USING IT IN PRODUCTION

**Comment by mei309** [comment]
using in prudoction not working yet

**Comment by litzvi** [comment]
CAN'T ADD A PO FOR GENERAL SUPPLIER.
Either put a drop down for all suppliers or add another button for adding general suppliers and we will provide with the relevant options.

**Comment by mei309** [comment]
> CAN'T ADD A PO FOR GENERAL SUPPLIER.
> Either put a drop down for all suppliers or add another button for adding general suppliers and we will provide with the relevant options.

i put all suppliers in the drop down

**Comment by mei309** [comment]
WHY YOU OPENED IT?

**Comment by litzvi** [comment]
why do you worry about issues i leave open for myself?

**Comment by litzvi** [comment]
com.avc.mis.beta.controllers.ScheduleController.getGeneralOrdersOpen(), change to findAllGeneralOrderItems

**Comment by litzvi** [comment]
in orders report, now i'm giving a list for numberUnits, that can be of size 1.
So for an item like sugar in General orders, there won't be LOT..
Now it's not showing

**Comment by mei309** [comment]
> in orders report, now i'm giving a list for numberUnits, that can be of size 1.
> So for an item like sugar in General orders, there won't be LOT..
> Now it's not showing - error: amount undefined

fixed. should work now

**Comment by mei309** [comment]
> com.avc.mis.beta.controllers.ScheduleController.getGeneralOrdersOpen(), change to findAllGeneralOrderItems

im using now for open ones findOpenGeneralOrderItems
and for all findAllGeneralOrderItemsHistory
which one you want to change??

**Comment by litzvi** [comment]
what's not clear??
**com.avc.mis.beta.controllers.ScheduleController.getGeneralOrdersOpen(),**

**Comment by mei309** [comment]
ok done. i didnt see the schedule
