### ISSUE TITLE
Final Report - graphs

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#292]
I'm thinking what you need in order to display the graphs.

**Loss per process:** I think you have it already, the difference in ProductionReportLine.

**Product percentage (compared to order - paid) per stage:** We have the total of product and also have the receivedOrderUnits and totalReceived in receipt.
So just needs to be turned in to percentage compared to receivedOrderUnits.

**Product percentage (compared to raw station weights - real) per stage:** We have the total of product and also have the totalProductCount in cleaning.
So just needs to be turned in to percentage compared to totalProductCount.

Since we are showing the final report all the time, I think we should add the inventory if it's still not shipped - i'll add it to the final report.

**Comment by litzvi** [comment]
@mei309 waiting for your input.

**Comment by litzvi** [comment]
> Since we are showing the final report all the time, I think we should add the inventory if it's still not shipped - i'll add it to the 
> final report.

done in Version: 9.24, have a look

**Comment by mei309** [comment]
what type of graphs you think are best for it? look here at bar and line and choose. i have it ready already
https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical

**Comment by litzvi** [comment]
wow there are so many good ones, need to try and than improve.

I would go for a bar chart that has a line at say 100% and a color on the part missing or extra with the number/percentage inside.

**Comment by mei309** [comment]
i added the lost one. i need all the difference to be the same measure unit. i will upload so you can see about

**Comment by mei309** [comment]
in sunday i will finish

**Comment by litzvi** [comment]
if you write loss this way, how will you write gain?
also show the units you are showing it in. You might want to consider showing in percentage.

**Comment by litzvi** [comment]
I suggest the scale to be in percentage and the absolute weights written on the bar (this way can be written in 2 unit types)

**Comment by litzvi** [comment]
com.avc.mis.beta.dto.report.ProductionReportLine.getRatioLoss() - the ratio of (total out)/(total in)
com.avc.mis.beta.dto.report.ProductionReportLine.getProductRatioLoss() - the ratio of (product out)/(product in)

**Comment by mei309** [comment]
look at what i did.
i cannot do ***the absolute weights written on the bar*** i did it so when you on the bar you see the weights

**Comment by mei309** [comment]
> I'm thinking what you need in order to display the graphs.
> 
> **Loss per process:** I think you have it already, the difference in ProductionReportLine.
> 
> **Product percentage (compared to order - paid) per stage:** We have the total of product and also have the receivedOrderUnits and totalReceived in receipt.
> So just needs to be turned in to percentage compared to receivedOrderUnits.
> 
> **Product percentage (compared to raw station weights - real) per stage:** We have the total of product and also have the totalProductCount in cleaning.
> So just needs to be turned in to percentage compared to totalProductCount.
> 
> Since we are showing the final report all the time, I think we should add the inventory if it's still not shipped - i'll add it to the final report.

the 2 other ones i will do myself.

**Comment by mei309** [comment]
both ***Product percentage*** that you said we should do are also with the same problem that the measure unit isnt necessarily the same

**Comment by mei309** [comment]
in po 45026 packing the ratioLoss is +0.99 and the difference is -10lbs. how can it be?

**Comment by litzvi** [comment]
> in po 45026 packing the ratioLoss is +0.99 and the difference is -10lbs. how can it be?

was thinking you will show the amount not only the loss.
anyway, i changed it.
p.a. It's the **ratio**,  for displaying percentage, need to multiply by 100.

**Comment by litzvi** [comment]
will be in next version

**Comment by mei309** [comment]
> > in po 45026 packing the ratioLoss is +0.99 and the difference is -10lbs. how can it be?
> 
> was thinking you will show the amount not only the loss.
> anyway, i changed it.
> p.a. It's the **ratio**, for displaying percentage, need to multiply by 100.

im showing both.
p.a. It's the **ratio**, for displaying percentage, need to multiply by 100. I REALLY DON'T UNDERSTAND WHAT YOU MEAN

**Comment by litzvi** [comment]
>I REALLY DON'T UNDERSTAND WHAT YOU MEAN

e.g. if it lost 1% i'll give you -0.01 (the ratio) so if you show percentage you need to multiply by 100.
see the version uploaded today and let me know

**Comment by mei309** [comment]
why to make it so complicated? why you just dont give me it as -1?

**Comment by mei309** [comment]
the difference is plus and ratioLoss is minus how it can be???

**Comment by mei309** [comment]
look on po 45026

**Comment by mei309** [comment]
if its ratio its not loss. the 1-ratio is percent loss

**Comment by mei309** [comment]
and you should give it as percantage loss.

**Comment by mei309** [comment]
and give it already in percentage

**Comment by litzvi** [comment]
ok. done

**Comment by litzvi** [comment]
pushed Version: 9.38

**Comment by mei309** [comment]
i really have no clue what you trying to gain from the opposite numbers

**Comment by mei309** [comment]
why it cannot be the difference in percentage??

**Comment by mei309** [comment]
and then plus is on top and minus is in the bottom

**Comment by litzvi** [comment]
what is opposite?
it is in percentage
plus?minus?

**Comment by mei309** [comment]
now its good

**Comment by mei309** [comment]
> both _**Product percentage**_ that you said we should do are also with the same problem that the measure unit isnt necessarily the same

something about this?

**Comment by litzvi** [comment]
I'll get to it later

**Comment by litzvi** [comment]
com.avc.mis.beta.dto.report.FinalReport.getProductPercentageLoss()
a list for "cleaning", "roasting" and "packing", everyone has the percentage compared to receivedOrderUnits and receivedCount.

**Comment by litzvi** [comment]
Version: 9.40 pushed

**Comment by mei309** [comment]
i have 3 graphs in your version please look and decide if to leave the first or the 2 other ones. they are the same infromtion

**Comment by litzvi** [comment]
I think they should be in separate graphs (2,3) 
It looks bad because it's very wide so there is no proportion.

**Comment by mei309** [comment]
look now.

**Comment by litzvi** [comment]
the 2 middle ones are not working.
I don't like that you mix product and total in the same table.
you can still make the bars slimmer, so can fit more tables in the same page

**Comment by mei309** [comment]
Loss Per Process From Order + From Received(real)
ALSO IN 2 DIFFERENT TABLES??

**Comment by mei309** [comment]
> the 2 middle ones are not working.
> I don't like that you mix product and total in the same table.
> you can still make the bars slimmer, so can fit more tables in the same page

they working by me.
made smaller

**Comment by mei309** [comment]
look and comment.

**Comment by litzvi** [comment]
> Loss Per Process From Order + From Received(real)
> ALSO IN 2 DIFFERENT TABLES??

yes, don't mix it's confusing. also we will probably remove some after they decide what they want.
so better they see it separate.

**Comment by litzvi** [comment]
change names:
Total Loss Per Process -> Unaccounted Difference 
Product Loss Per Process -> Product Difference 
Loss Per Process From Order + From Received(real) -> Aggregate Difference from Receipt (Order, Real)

you can add arrows (gain, loss), to up and down directions in the graph, but don't use loss as a title.

**Comment by litzvi** [comment]
> made smaller

why not more?

**Comment by mei309** [comment]
done. i dont understand what you want by the arrows

**Comment by litzvi** [comment]
never mind
