### ISSUE TITLE
Allow selective editing of poCode

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#294]
Eli asked to allow editing PoCode supplier and contract type.
So i added com.avc.mis.beta.service.Orders.editPoCode(PoCode)
Can only edit supplier and contract type not the code.

**Comment by mei309** [comment]
NO PROBLEM.

**Comment by mei309** [comment]
let me know when you upload it

**Comment by litzvi** [comment]
it's uploaded - Version: 9.26

**Comment by mei309** [comment]
why PoCode and PoCodeDto have different variables names?

**Comment by mei309** [comment]
supplier vs supplierName
contractType vs contractTypeCode.
its very hard to do edit this way

**Comment by litzvi** [comment]
yes, that's from the old structure. let me fix it

**Comment by mei309** [comment]
LET ME KNOW WHEN YOU CHANGE THE NAMES AND WHICE ONE YOU CHANGING.
FOR ME ITS EASIER IF YOU CHANGE supplier TO supplierName
AND contractType TO contractTypeCode.

**Comment by litzvi** [comment]
I don't understand

**Comment by litzvi** [comment]
Anyway, I made a PoCodeDTO that's the same structure as PoCode.
You can get it with com.avc.mis.beta.service.Orders.getPoCode(int).
If something doesn't suit you please call because I don't understand what you mean.

**Comment by litzvi** [comment]
Version: 9.28 and uploaded

**Comment by mei309** [comment]
findAllPoCodes and more not working

**Comment by mei309** [comment]
dtos should have the same names. i cannot do edit otherwise

**Comment by mei309** [comment]
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.avc.mis.beta.entities.codes.BasePoCode` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (PushbackInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(

**Comment by mei309** [comment]
on addPoCode

**Comment by mei309** [comment]
nothing is working with po

**Comment by litzvi** [comment]
> on addPoCode

it's because BasePoCode is abstract, need to create PoCode.
We had this problem before, is there an elegant way to solve it?

**Comment by litzvi** [comment]
> dtos should have the same names. i cannot do edit otherwise

haven't i fixed it in POCodeDTO?

**Comment by litzvi** [comment]
> findAllPoCodes and more not working

works in my test

**Comment by mei309** [comment]
> > on addPoCode
> 
> it's because BasePoCode is abstract, need to create PoCode.
> We had this problem before, is there an elegant way to solve it? Maybe give the type?

we need to create the kids. we had in items

**Comment by litzvi** [comment]
I can do the same as in Items, but it's lees efficient here. I rather Make 2 functions. is that ok?

**Comment by mei309** [comment]
in items i create the kids with different functions also

**Comment by litzvi** [comment]
you do it by the type field, right?

**Comment by litzvi** [comment]
so everywhere i need to give you a type field?

**Comment by litzvi** [comment]
Ok i'll fix the add and edit methods to get PoCode (not base). If everything is fine we'll continue

**Comment by mei309** [comment]
and upload because im stock

**Comment by litzvi** [comment]
Version: 9.30 pushed

**Comment by mei309** [comment]
findAllPoCodes is giving an empty array

**Comment by litzvi** [comment]
don't know what happened.
go to line 179 in ObjectTableRepository and remove 'distinct'

**Comment by mei309** [comment]
now it shows only new ones. i do i do it should show the dump ones?

**Comment by litzvi** [comment]
oh that's why!
need to fix the dump because we don't basic etc.

**Comment by litzvi** [comment]
Sorry didn't realize you are using the dump

**Comment by mei309** [comment]
new and edit are working.

**Comment by litzvi** [comment]
let me make a script so you can use the dump

**Comment by litzvi** [comment]
if you build the new database and than only insert the data from the old one, this should work.

INSERT INTO order_po_codes (`id`)  SELECT `id` from po_codes;

**Comment by mei309** [comment]
tables arent showing the po. cant get details of anything

**Comment by litzvi** [comment]
what methods?

**Comment by mei309** [comment]
ok edit is working. the rest is about the dump and i opened a new issue
