### ISSUE TITLE
Not showing details by searching REPORTS 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#295]
We're still meeting the problem (sometimes), software doesn't always show the "reports" Immediate, only after you refresh the web page.

**Comment by mei309** [comment]
we working on it

**Comment by mei309** [comment]
it should be fixed. let me know if not. in Friday i by mistake did a small different problem that stock the software.
***VERY IMPORTENT: WHEN YOU FIRST OPEN IT BEFORE LOG IN CLOSE AND OPEN AGAIN SO YOU GET THE NEW FILES***

**Comment by mei309** [comment]
looks like its working.

**Comment by ELIPELET** [comment]
It's working now for me too.

בתאריך יום ד׳, 27 בינו׳ 2021, 13:45, מאת mei309 ‏<notifications@github.com>:
