### ISSUE TITLE
Adding PoCode not working

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#297]
I can't add a poCode with my new code.

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/105568990-73799400-5d70-11eb-82f5-7c287c571f09.PNG">

**Comment by litzvi** [comment]
Probably has to do with not fixing issue 294

**Comment by mei309** [comment]
its fixed
