### ISSUE TITLE
receive samples 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#300]
if i fill only empty bag weights or only weights of the full bags it should still work

**Comment by mei309** [comment]
it dose by me

**Comment by mei309** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/58453503/105623341-f293c880-5e53-11eb-9b03-f766371d8db7.png)
![Screenshot (5)](https://user-images.githubusercontent.com/58453503/105623352-ff182100-5e53-11eb-9f8b-ecc774dec40b.png)

**Comment by litzvi** [comment]
edit the last one and see.
also try filing in only empty bags in the popup and before sending open the popup again

**Comment by mei309** [comment]
its all working by me

**Comment by mei309** [comment]
i really dont know what else i can check

**Comment by mei309** [comment]
whats with this? it happened again?

**Comment by litzvi** [comment]
not in the meantime. so i'll close for now

**Comment by litzvi** [comment]
> whats with this? it happened again?

FILL IN ONLY EMPTY BAG WEIGHTS IN SAMPLE (NO BAGS IN THE TABLE).
SAVE.
EDIT.
EDIT SAMPLES.
DO YOU SEE THE PREVIOUS BAGS?

**Comment by mei309** [comment]
ok fixed
