### ISSUE TITLE
updating the dump

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#301]
its not working your way

**Comment by mei309** [comment]
your way eclipse->dump->sql line.
my way dump->eclipse->sql line

**Comment by mei309** [comment]
my way is working

**Comment by litzvi** [comment]
> your way eclipse->dump->sql line.

why isn't it working? what error

**Comment by mei309** [comment]
no error. just no data

**Comment by mei309** [comment]
[Dump20210125 (1).zip](https://github.com/litzvi/avc-beta/files/5878171/Dump20210125.1.zip)
this is the cloud from yesterday

**Comment by litzvi** [comment]
When you back up cloud with Server->Data Export use Advanced options and check complete-insert at the bottom.
Then run spring-boot:run (or use the same as before but comment inside of DataLoader)
Then backup data only (i think i told you already)
then run INSERT INTO order_po_codes (id) SELECT id from po_codes;

**Comment by mei309** [comment]
> INSERT INTO order_po_codes (id) SELECT id from po_codes;

this workes now

**Comment by litzvi** [comment]
So you do it this way always. ok?
eclipse->dump->sql line

**Comment by mei309** [comment]
ok
