### ISSUE TITLE
Process with mixed pos - issue 254 cont.

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#304]
here is what I have so far:

- A process references a BasePoCode - can be PoCode or MixPoCode
- MixPoCode contains a list origionPoCodes of the PoCodes combined
- MixPoCode doesn't set any of it's fields besides for display and origionPoCodes 
- MixPoCode has a field display for choosing what the value will look like (that's what i'll display everywhere)
- when calling com.avc.mis.beta.service.WarehouseManagement.getAvailableInventory(ItemGroup, ProductionUse[], Integer, Integer) with a PoCodeId of a mix, you will get the inventory of the mix, and it's ancestors.

**Comment by litzvi** [comment]
pushed * Version: 9.34, so we can start getting to it.
Not ready at all just the structure, so I can get feedback.
You use com.avc.mis.beta.service.ObjectTablesReader.findFreeMixPoCodes() for the process that's doing the mix, later it's referenced normally.

**Comment by mei309** [comment]
findFreeMixPoCodes??? how will it help me for packing??

**Comment by mei309** [comment]
and you didnt build a function to add mix po

**Comment by mei309** [comment]
its ready and should work in my part once i have the 2 functions of adding new mix and getting mix for packing

**Comment by litzvi** [comment]
> and you didnt build a function to add mix po

com.avc.mis.beta.service.Orders.addMixPoCode(MixPoCode)
com.avc.mis.beta.service.Orders.editMixPoCode(MixPoCode)

**Comment by litzvi** [comment]
> findFreeMixPoCodes??? how will it help me for packing??

you use it to get the available mixPos. 
If the user chooses one of those, when you get inventory with
com.avc.mis.beta.service.WarehouseManagement.getAvailableInventory(ItemGroup, ProductionUse[], Integer, Integer)
It should give of all underlying pos.

**Comment by litzvi** [comment]
I spoke to Ahron:

- mix is strictly only for packing with a given ratio
- inventory weights should display according to the percentage used by po
- inventory number of bags should be joined
- in the final report should show the actual number of bags, but only the relative amount of weight

**Comment by litzvi** [comment]
since they are only using it in packing, we can just let them add the new po in the same time. if you want

**Comment by mei309** [comment]
> since they are only using it in packing, we can just let them add the new po in the same time. if you want

and another we will need to change for all

**Comment by mei309** [comment]
> editMixPoCode

i dont find it

**Comment by mei309** [comment]
> > and you didnt build a function to add mix po
> 
> com.avc.mis.beta.service.Orders.addMixPoCode(MixPoCode)
> com.avc.mis.beta.service.Orders.editMixPoCode(MixPoCode)

i dont see it

**Comment by mei309** [comment]
> I spoke to Ahron:
> 
> * mix is strictly only for packing with a given ratio
> * inventory weights should display according to the percentage used by po
> * inventory number of bags should be joined
> * in the final report should show the actual number of bags, but only the relative amount of weight

since its by ratio it will need to be a process

**Comment by litzvi** [comment]
>since its by ratio it will need to be a process

why?

**Comment by mei309** [comment]
> > since its by ratio it will need to be a process
> 
> why?

it means they take an amount of every po not necessarily all

**Comment by litzvi** [comment]
yes not all.
you just let them choose from all the pos

**Comment by litzvi** [comment]
wait with the mixed pos.
still need to see how and if i can do it

**Comment by mei309** [comment]
> yes not all.
> you just let them choose from all the pos

i mean they take 50% of po one and 70% of po two

**Comment by mei309** [comment]
i implemented this. let me know if you want the new version

**Comment by mei309** [comment]
so you can play with it and see

**Comment by litzvi** [comment]
> i mean they take 50% of po one and 70% of po two

no. the process is considered 70% from po1 and 30% from po2. they are not restricted with what they take for now

**Comment by litzvi** [comment]
> i implemented this. let me know if you want the new version

I need to add the weight/ratio for generating the reports, therefore it won't even help as a demo.

**Comment by mei309** [comment]
whats the problem to do it according to used items?

**Comment by mei309** [comment]
and then we leave it as now

**Comment by litzvi** [comment]
the whole reason i'm doing it this way and not as a list of pos is so I don't need to go into the usedItems everytime.

**Comment by mei309** [comment]
closing since we have 2 different issues on this topic
