### ISSUE TITLE
a error i dont understand 

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#306]
Jan 28 04:36:20 ip-172-31-32-174 web: where
Jan 28 04:36:20 ip-172-31-32-174 web: storagebas0_.used_item_base_id in (
Jan 28 04:36:20 ip-172-31-32-174 web: ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?
Jan 28 04:36:20 ip-172-31-32-174 web: )
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [INTEGER] - [1429]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [2] as [INTEGER] - [1430]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [3] as [INTEGER] - [1431]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [4] as [INTEGER] - [1432]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [5] as [INTEGER] - [1433]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [6] as [INTEGER] - [1435]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [7] as [INTEGER] - [1436]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [8] as [INTEGER] - [1437]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [9] as [INTEGER] - [1439]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [10] as [INTEGER] - [1441]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [11] as [INTEGER] - [1442]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [12] as [INTEGER] - [1438]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [13] as [INTEGER] - [1434]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [14] as [INTEGER] - [1440]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [15] as [INTEGER] - [1447]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [16] as [INTEGER] - [1449]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [17] as [INTEGER] - [1450]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [18] as [INTEGER] - [1451]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [19] as [INTEGER] - [1446]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [20] as [INTEGER] - [1454]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [21] as [INTEGER] - [1455]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [22] as [INTEGER] - [1456]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [23] as [INTEGER] - [1457]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [24] as [INTEGER] - [1458]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [25] as [INTEGER] - [1460]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [26] as [INTEGER] - [1452]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [27] as [INTEGER] - [1459]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [28] as [INTEGER] - [1453]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.517 TRACE 31100 --- [nio-5000-exec-4] o.h.type.descriptor.sql.BasicBinder      : binding parameter [29] as [INTEGER] - [1448]
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.520  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.520  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.520  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.520  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.520  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.520  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.521  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.522  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.522  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.522  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.522  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.522  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.522  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.525  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.526  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.526  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.526  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==
Jan 28 04:36:20 ip-172-31-32-174 web: 2021-01-28 04:36:20.526  WARN 31100 --- [nio-5000-exec-4] o.h.e.i.StatefulPersistenceContext       : HHH000179: Narrowing proxy to class com.avc.mis.beta.entities.processinfo.ProcessItem - this operation breaks ==

**Comment by litzvi** [comment]
will close it for now, we will follow up on the next version, see if it happens

**Comment by litzvi** [comment]
lines 58-68 are all the things you don't want to see in the log.
but if you only direct the debug to you're logs, it will solve it.
or just comment the lines

**Comment by mei309** [comment]
> lines 58-68 are all the things you don't want to see in the log.
> but if you only direct the debug to you're logs, it will solve it.
> or just comment the lines

its made automatically by amazon

**Comment by mei309** [comment]
i will comment them by me
