### ISSUE TITLE
Message: Convertion from UNIT to KG not supported

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#308]
its in po 14760v in the cloud. and becuse of this a lot of stuff not working

**Comment by litzvi** [comment]
yes it's because he added a bulk item with default measure unit 'UNIT', therefore can't calculate the weight.
I need to block these 'illegal' items after we get general inventory correct.

anyway i changed it. looks ok now

**Comment by mei309** [comment]
ok.im closing since i think its un useful anymore
