### ISSUE TITLE
add order

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#309]
java.lang.ClassCastException: Order has to referenced a PoCode (not MixPoCode)
	at com.avc.mis.beta.service.Orders.addOrder(Orders.java:194) ~[classes/:na]

**Comment by litzvi** [comment]
correct. should not add a mixed po code in order or receipt.
it's only for processing

**Comment by mei309** [comment]
it's happening when I put a normal poSent from my Huawei phone-------- Original message --------From: litzvi <notifications@github.com>Date: Sun, Jan 31, 2021, 06:36To: litzvi/avc-beta <avc-beta@noreply.github.com>Cc: mei309 <isral309@gmail.com>, Assign <assign@noreply.github.com>Subject: Re: [litzvi/avc-beta] add order (#309)
Assigned #309 to @mei309.

**Comment by litzvi** [comment]
oh ok. should be fixed

**Comment by mei309** [comment]
let me know when it is

**Comment by litzvi** [comment]
sorry forgot to push
Version: 9.35 pushed

**Comment by mei309** [comment]
ok fixed
