### ISSUE TITLE
CASHEW INVENTORY

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#31]
CASHEW INVENTORY BY ITEM: IF ROASTING IN 2 PARTS, WILL SHOW CORRECT TOTAL STOCK BUT ONLY ONE LINE FOR TOTAL BALANCE.
ALSO SHOULD I COMBINE ALL ITEMS OF THE SAME KIND IN ONE LINE IF THEY ARE FROM THE SAME PO IN 'BY ITEM'
AND THE SAME BY PO, COMBINE SAME ITEM TOGETHER.
THINK HOW IT WILL WORK BY YOU BEFORE I CHANGE.

**Comment by mei309** [comment]
it will change only the table or all?

**Comment by mei309** [comment]
if only table so defintly do it

**Comment by litzvi** [comment]
It will change only InventoryReports (prv. CashewReports).
if you aren't using it anywhere else.. then it won't change

**Comment by litzvi** [comment]
yes you're only using it there.
i'll change it

**Comment by mei309** [comment]
assigen me when you do it

**Comment by litzvi** [comment]
i decided not to do it because we will lose process time if we will want to display it later.
if Ahron asks i'll do it
