### ISSUE TITLE
NEW SETUP ITEMS.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#311]
see my new version of setup items (under management) and if you can do a function to get the items according to that

**Comment by litzvi** [comment]
<img width="565" alt="Capture" src="https://user-images.githubusercontent.com/53637868/106411448-ee7d3180-6477-11eb-859e-57d2d04e20a0.PNG">

**Comment by litzvi** [comment]
com.avc.mis.beta.service.ValueTablesReader.getItems(ItemGroup, ProductionUse, Class<? extends Item>)

you can call with BulkItem.class, PackedItem.class or null(ignores the class)
e.g. for cashew bulk items, call getItems(PRODUCT, null, BulkItem.class)

**Comment by litzvi** [comment]
i'll let you know when i push

**Comment by litzvi** [comment]
pushed in Version: 9.36

**Comment by mei309** [comment]
> BulkItem

isnt waste always bulk?

**Comment by mei309** [comment]
item dto is missing bag weight

**Comment by mei309** [comment]
we need item

**Comment by litzvi** [comment]
so what where you using until now? what method?

**Comment by litzvi** [comment]
> isnt waste always bulk?

probably.. but it's not forced in the structure; so you need to call with the other method (if you have a better way let me know).

**Comment by litzvi** [comment]
> item dto is missing bag weight

before you didn't use ItemDTO?

**Comment by litzvi** [comment]
Anyhow, I've changed it to ItemWithUnitDTO.
pushed Version: 9.37

**Comment by mei309** [comment]
i was using itemDto everywhere besides the setup table that there i was using item.
public List<Item> getAllItems()

**Comment by mei309** [comment]
i dont see no reason that i need the unit in more places so you can put back itemDto in most calls

**Comment by litzvi** [comment]
> i dont see no reason that i need the unit in more places so you can put back itemDto in most calls

it's the same method

**Comment by mei309** [comment]
ok. whatever
