### ISSUE TITLE
material use - move

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#312]
i implemented it in roasting and packing. its working well. i dont see any problem with it.
now we need to make a usage page for when they use materials not directly in production

**Comment by litzvi** [comment]
yes it's working.
No need to do it now, better to finish what we have

**Comment by mei309** [comment]
after we upload this version

**Comment by litzvi** [comment]
I added for general storage use:
com.avc.mis.beta.service.WarehouseManagement.addGeneralInventoryUse(InventoryUse)
com.avc.mis.beta.service.WarehouseManagement.getInventoryUse(int)
com.avc.mis.beta.service.WarehouseManagement.getInventoryUses()
and com.avc.mis.beta.service.WarehouseManagement.getInventoryUses(Integer poCodeId)

If you want to do it. or we leave the general?

**Comment by litzvi** [comment]
Also for relocation you can add another option if they just want to move stuff from place to place (don't need count).
All you need to do is to play around with the functionality change to GENERAL_STORAGE

**Comment by mei309** [comment]
> Also for relocation you can add another option if they just want to move stuff from place to place (don't need count).
> All you need to do is to play around with the functionality change to GENERAL_STORAGE

its a bit a problem if they do it for something with production functionality RAW_STATION so then you force them to do another relocation???

**Comment by mei309** [comment]
and where you think i should put the links to inventory use??

**Comment by mei309** [comment]
> I added for general storage use:
> com.avc.mis.beta.service.WarehouseManagement.addGeneralInventoryUse(InventoryUse)
> com.avc.mis.beta.service.WarehouseManagement.getInventoryUse(int)
> com.avc.mis.beta.service.WarehouseManagement.getInventoryUses()
> and com.avc.mis.beta.service.WarehouseManagement.getInventoryUses(Integer poCodeId)
> 
> If you want to do it. or we leave the general?

what about edit??

**Comment by mei309** [comment]
and com.avc.mis.beta.service.WarehouseManagement.getInventoryUses(Integer poCodeId)
**its for where? reports?**

**Comment by litzvi** [comment]
> > Also for relocation you can add another option if they just want to move stuff from place to place (don't need count).
> > All you need to do is to play around with the functionality change to GENERAL_STORAGE
> 
> its a bit a problem if they do it for something with production functionality RAW_STATION so then you force them to do another relocation???

that's the whole point, no? to force them to bring the product to the raw station/roaster in

**Comment by litzvi** [comment]
> what about edit??

forgot, will add

**Comment by litzvi** [comment]
> and com.avc.mis.beta.service.WarehouseManagement.getInventoryUses(Integer poCodeId)
> **its for where? reports?**

It's there because it's free, final report probably doesn't need it

**Comment by mei309** [comment]
java.lang.NullPointerException: No such process type
	at com.avc.mis.beta.dao.ProcessInfoDAO.lambda$0(ProcessInfoDAO.java:81) ~[classes/:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:401) ~[na:na]
	at com.avc.mis.beta.dao.ProcessInfoDAO.getProcessTypeByValue(ProcessInfoDAO.java:81) ~[classes/:

**Comment by mei309** [comment]
> > > Also for relocation you can add another option if they just want to move stuff from place to place (don't need count).
> > > All you need to do is to play around with the functionality change to GENERAL_STORAGE
> > 
> > 
> > its a bit a problem if they do it for something with production functionality RAW_STATION so then you force them to do another relocation???
> 
> that's the whole point, no? to force them to bring the product to the raw station/roaster in

yes but its becoming a lot. ok whatever

**Comment by mei309** [comment]
> > and com.avc.mis.beta.service.WarehouseManagement.getInventoryUses(Integer poCodeId)
> > **its for where? reports?**
> 
> It's there because it's free, final report probably doesn't need it

ok

**Comment by litzvi** [comment]
added edit in next version

**Comment by litzvi** [comment]
> java.lang.NullPointerException: No such process type
> at com.avc.mis.beta.dao.ProcessInfoDAO.lambda$0(ProcessInfoDAO.java:81) ~[classes/:na]
> at java.base/java.util.Optional.orElseThrow(Optional.java:401) ~[na:na]
> at com.avc.mis.beta.dao.ProcessInfoDAO.getProcessTypeByValue(ProcessInfoDAO.java:81) ~[classes/:

because you aren't rebuilding. you can run
INSERT INTO `process_types` (`name`, `process_name`) VALUES ('General Inventory Use', 'GENERAL_USE');

**Comment by mei309** [comment]
I forgot about it. and anyway you have the new version. I will check it only tonight

**Comment by mei309** [comment]
getInventoryUses  returning empty array result.
getInventoryUse not returning used items

**Comment by litzvi** [comment]
> getInventoryUse not returning used items

fixed

**Comment by litzvi** [comment]
getInventoryUses returning empty array result.

fixed but will need to rebuild the database

**Comment by mei309** [comment]
> Also for relocation you can add another option if they just want to move stuff from place to place (don't need count).
> All you need to do is to play around with the functionality change to GENERAL_STORAGE

done
