### ISSUE TITLE
mix po

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#315]
cant get the process even so its working to be used.
No production process with given process id in function getProductionProcess line 128

**Comment by litzvi** [comment]
don't know what happened. what about version 10.2

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/108016836-03e08700-7046-11eb-9fe8-bc6b377c3349.PNG">

**Comment by litzvi** [comment]
that's what it's supposed to look like in cleaning?

**Comment by litzvi** [comment]
also now any process doesen't show anything in edit

**Comment by mei309** [comment]
> that's what it's supposed to look like in cleaning?

no. its fixed by me already

**Comment by mei309** [comment]
its not supposed to disturb

**Comment by mei309** [comment]
it dose reduce the numbers as used items.

**Comment by mei309** [comment]
and it produces this error

java.lang.NullPointerException: null
	at com.avc.mis.beta.dto.process.PoProcessDTO.setPoProcessInfo(PoProcessDTO.java:53) ~[classes/:na]
	at com.avc.mis.beta.service.ProductionProcesses.getProductionProcess(ProductionProcesses.java:129) ~[classes/:na]
	at com.avc.mis.beta.service.ProductionProcesses$$FastClassBySpringCGLIB$$37b47871.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at com.avc.mis.beta.service.ProductionProcesses$$EnhancerBySpringCGLIB$$c0880a0d.getProductionProcess(<generated>) ~[classes/:na]
	at com.avc.mis.beta.controllers.ProductionController.addPackingTransfer(ProductionController.java:99) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]

**Comment by mei309** [comment]
adding is working

**Comment by litzvi** [comment]
version 10.3 
added String[] poCodes field in ProcessRow - should be used for display (after it's ok i'll remove the poCode field.
pay attention that i changed approvals to String[]

**Comment by mei309** [comment]
also added String[] suppliers. I DONT SEE IT

**Comment by mei309** [comment]
added String[] poCodes. YOU NEED TO GIVE THIS RESULT ALWAYS NOT ONLY WHEN ITS MIXED

**Comment by mei309** [comment]
IN MIX I DONT GET PRODUCED ITEMS. ONLY USED I GET

**Comment by mei309** [comment]
AND WE NEED POCODES IN ProductionProcessDTO ALSO

**Comment by litzvi** [comment]
> added String[] poCodes. YOU NEED TO GIVE THIS RESULT ALWAYS NOT ONLY WHEN ITS MIXED

yes. that's the plan

**Comment by litzvi** [comment]
> also added String[] suppliers. I DONT SEE IT

so maybe it's in the next update

**Comment by litzvi** [comment]
> AND WE NEED POCODES IN ProductionProcessDTO ALSO

it's in weightedPos (it's in PoProcess)

**Comment by litzvi** [comment]
> IN MIX I DONT GET PRODUCED ITEMS. ONLY USED I GET

yes. I need to fix it

**Comment by litzvi** [comment]
String[] poCodes also for ContainerPoItemRow (in LoadingRow and InventoryExportDoc)

**Comment by mei309** [comment]
> > added String[] poCodes. YOU NEED TO GIVE THIS RESULT ALWAYS NOT ONLY WHEN ITS MIXED
> 
> yes. that's the plan
> when you see somewhere it's missing let me know

its missing in some lines but i dont see an order.

**Comment by mei309** [comment]
suppliers is showing everywhere

**Comment by mei309** [comment]
> String[] poCodes also for ContainerPoItemRow (in LoadingRow and InventoryExportDoc)

no problem

**Comment by mei309** [comment]
i need the pos ids for edit

**Comment by mei309** [comment]
something like this
private int[] poIds;

**Comment by litzvi** [comment]
> i need the pos ids for edit

but you are getting it in the structure you are sending it

**Comment by litzvi** [comment]
> its missing in some lines but i dont see an order.

are you using the dump?
if so send me and i'll look

**Comment by litzvi** [comment]
when you send you're update version it will be easier for me to check

**Comment by mei309** [comment]
> > i need the pos ids for edit
> 
> but you are getting it in the structure you are sending it

in processRow

**Comment by mei309** [comment]
> > its missing in some lines but i dont see an order.
> 
> are you using the dump?

im using something i have

**Comment by litzvi** [comment]
> in processRow

when are you using processRow to edit?

**Comment by mei309** [comment]
uploaded version 17.6

**Comment by mei309** [comment]
> > in processRow
> 
> when are you using processRow to edit?

im getting from the table and according to that i know what storage to call

**Comment by litzvi** [comment]
no rush. i'm only going to work tomorrow

**Comment by mei309** [comment]
anyway i need the po codes also if not it will be a big delay in results (in edit)

**Comment by litzvi** [comment]
> anyway i need the po codes also if not it will be a big delay in results (in edit)

don't understand. what do ProcessRow have to do with edit??

**Comment by mei309** [comment]
> > anyway i need the po codes also if not it will be a big delay in results (in edit)
> 
> don't understand. what do ProcessRow have to do with edit??

i need to give them to use from available storages of the current pos

**Comment by litzvi** [comment]
oh didn't understand you are doing that.
If you want you can use: 
com.avc.mis.beta.service.ProductionProcesses.getProductionProcessWithAvilableInventory(int, ItemGroup, ProductionUse[], Integer)
com.avc.mis.beta.service.Loading.getLoadingWithAvilableInventory(int, ItemGroup, ProductionUse[], Integer)
for getting the process together with available inventory.

**Comment by litzvi** [comment]
anyway, I also added poCodeIds in ProcessRow and LoadingRow

**Comment by litzvi** [comment]
i changed com.avc.mis.beta.service.WarehouseManagement.getAvailableInventory(ItemGroup, ProductionUse[], Integer, int[])
to get an array of poCodeIds.

**Comment by mei309** [comment]
> oh didn't understand you are doing that.
> If you want you can use:
> com.avc.mis.beta.service.ProductionProcesses.getProductionProcessWithAvilableInventory(int, ItemGroup, ProductionUse[], Integer)
> com.avc.mis.beta.service.Loading.getLoadingWithAvilableInventory(int, ItemGroup, ProductionUse[], Integer)
> for getting the process together with available inventory.

so with this i will not need the po ids

**Comment by mei309** [comment]
for now im using the poids because of the reason mentioned above

**Comment by mei309** [comment]
and in my opinion you can delete the poCode and supplierName from all places you put pocodes and suppliers

**Comment by litzvi** [comment]
ok

**Comment by litzvi** [comment]
you are still showing with poCode in ProcessItemInventory. please change so I can remove it

**Comment by mei309** [comment]
all details are with one and an array. dont change that.
tables are only with the arrays

**Comment by mei309** [comment]
and by the way you giving only the first po in string[] poCodes

**Comment by mei309** [comment]
ProcessItemInventory Loading details, security doc, export doc DONE

**Comment by mei309** [comment]
normal inventory i didnt change

**Comment by litzvi** [comment]
> and by the way you giving only the first po in string[] poCodes

where?

**Comment by litzvi** [comment]
> normal inventory i didnt change

I think you should change, even though it's only one for now

**Comment by litzvi** [comment]
by the way, weight is mandatory in mixed po

**Comment by mei309** [comment]
> > and by the way you giving only the first po in string[] poCodes
> 
> where?

probably it didnt work because I had a old version

**Comment by mei309** [comment]
> by the way, weight is mandatory in mixed po

did by me too and also did max 1

**Comment by litzvi** [comment]
> > by the way, weight is mandatory in mixed po
> 
> did by me too and also did max 1

don't worry, i check if it's total adds up to 1

**Comment by mei309** [comment]
> > > by the way, weight is mandatory in mixed po
> > 
> > 
> > did by me too and also did max 1
> 
> don't worry, i check if it's total adds up to 1

good
