### ISSUE TITLE
findInventoryPoCodes

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#32]
findInventoryPoCodes in ObjectTablesReader not working

**Comment by litzvi** [comment]
which one of them? there are 3, give me the parameter

**Comment by mei309** [comment]
@RequestMapping("/getAllPosRoastPacked")
	public Set<PoCodeDTO> getAllPosRoastPacked() {
		return objectTableReader.findInventoryPoCodes(Arrays.asList(ItemCategory.ROAST, ItemCategory.PACKED));
	}

**Comment by mei309** [comment]
Message: unexpected AST node: {vector} [select new com.avc.mis.beta.dto.process.PoCodeDTO(poCode.code, ct.code, ct.suffix, s.name) from com.avc.mis.beta.entities.processinfo.ProcessItem pi join pi.item item join pi.process p join p.poCode poCode join poCode.contractType ct join poCode.supplier s join p.lifeCycle lc join pi.storageForms sf join sf.unitAmount unit join com.avc.mis.beta.entities.settings.UOM uom on uom.fromUnit = unit.measureUnit and uom.toUnit = item.measureUnit left join sf.usedItems ui where lc.processStatus = com.avc.mis.beta.entities.enums.ProcessStatus.FINAL and (item.supplyGroup = :supplyGroup or :supplyGroup is null)  and (:itemCategories_0, :itemCategories_1 is null or item.category in (:itemCategories_0, :itemCategories_1))  and (item.id = :itemId or :itemId is null)  group by sf, sf.numberUnits having (sf.numberUnits > sum(coalesce(ui.numberUnits, 0))) ]

**Comment by litzvi** [comment]
ok fixed in version 7
i changed the parameter back to an array so i don't need to check if it's empty
