### ISSUE TITLE
change pos and suppliers to list

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#320]
in UserMessageDTO and ApprovalTaskDTO. here i dont need po codes.

**Comment by litzvi** [comment]
don't understand?

**Comment by mei309** [comment]
i need string[] pocodes and i dont need private int[] poIds; here

**Comment by litzvi** [comment]
> i need string[] pocodes and i dont need private int[] poIds; here

I added ids - in case you will want it

**Comment by mei309** [comment]
ok
