### ISSUE TITLE
can't edit a mixed packing

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#322]

**Comment by mei309** [comment]
what edit you tried to make?
we can't change pos (im not giving the option) but all the rest works by me.

**Comment by litzvi** [comment]
> we can't change pos

why not?

**Comment by mei309** [comment]
> > we can't change pos
> 
> why not?

for now. like we cant change one po. later on we can change if necessary. even so its not really a good idea because then we need to check the used items etc.

**Comment by litzvi** [comment]
I meant to let them edit the weights

**Comment by mei309** [comment]
ok done
