### ISSUE TITLE
Loadings - meterial to load

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#323]
You should think of a way to call the available inventory once for all pos (now the method can receive a few pos).
Otherwise, you're going to get the mixed twice (or filter them by the id).
I understand the problem when they chose some stuff already, but think of a solution.

**Comment by mei309** [comment]
i can filter by id (i already do it for edit)

**Comment by mei309** [comment]
i can also do that we need to choose all in the beginning but if they would want to change it will delete all what they put already

**Comment by mei309** [comment]
so choose

**Comment by litzvi** [comment]
> i can also do that we need to choose all in the beginning but if they would want to change it will delete all what they put already

not good

**Comment by mei309** [comment]
i can give to choose a few and then call with them but it would not solve the problem of multiple

**Comment by mei309** [comment]
therefor i will filter by id

**Comment by litzvi** [comment]
ok
