### ISSUE TITLE
Inventory report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#324]
Should show amount for packed items

**Comment by mei309** [comment]
it shows in the report in Produced items and Used items right before the Wearhouse

**Comment by litzvi** [comment]
now you also have amount in ProcessItemInventoryRow (besides for the weight we where already using)
and totalAmount in ItemInventoryRow (besides for the totalStock we where already using)

**Comment by litzvi** [comment]
So you can show units for packed items. 
show only for total item (ItemInventoryRow  in inventory by item) - the other places might cause confusion.

**Comment by mei309** [comment]
if you just will put it with totalStock[] and with totalBalance[] it will be really easy to put it everywhere. if i use different variables it will be more columns

**Comment by mei309** [comment]
and i think the 3 together will be very useful

**Comment by litzvi** [comment]
only if you have a way to present it nice.
now they are all a list of everything

**Comment by litzvi** [comment]
still showing only weight. you need to fix it

**Comment by mei309** [comment]
> only if you have a way to present it nice.
> now they are all a list of everything

i will show as a list

**Comment by mei309** [comment]
> still showing only weight. you need to fix it

because i need to set it once you add it

**Comment by mei309** [comment]
for now i dont have a different way to show it. im thinking of a nicer way but only later

**Comment by litzvi** [comment]
Because I didn't push it.

**Comment by litzvi** [comment]
now ItemInventoryRow has totalAmount, totalWeight and totalStock.
So you can choose

**Comment by litzvi** [comment]
committed from Version: 10.9

**Comment by mei309** [comment]
im using totalStock and it goes by order so the first one always is without () and the rest are with. every place that you have an array of amountWithUnit you can add as much as you want just make sure the important one is first

**Comment by litzvi** [comment]
so i'll give you the same in ProductionProcessWithItemAmount of the ProcessRow lists.

**Comment by litzvi** [comment]
I pushed Version: 11.1
so check it now

**Comment by litzvi** [comment]
specially production reports

**Comment by mei309** [comment]
ok working
