### ISSUE TITLE
Reports -> Full po details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#329]
I think you should have a summary that's the information from all report tables.

I think it's more useful than the full details (at least in the way it's presented now).

**Comment by mei309** [comment]
thats final report

**Comment by litzvi** [comment]
final report is a a summary, not the details of every process.

**Comment by mei309** [comment]
i have no clue what you mean

**Comment by mei309** [comment]
create a function and i will show it

**Comment by litzvi** [comment]
it's ready!
all the reports, with one po

**Comment by mei309** [comment]
i dont find it or i have no clue what you talking about

**Comment by litzvi** [comment]
so call me

**Comment by litzvi** [comment]
by the way, this is an enhancement. 
Don't do before the upload

**Comment by mei309** [comment]
i need them to be public 
private List<ProcessRow> getProductionProcessesByTypeAndPoCode(ProcessName processName, Integer poCodeId) {
private List<ReceiptRow> findAllReceiptsByType(ProcessName[] processNames, ProcessStatus[] statuses, Integer poCodeId) {
for orders you dont have a like this function

**Comment by litzvi** [comment]
right click and 'copy qualified name' is more helpful next time

**Comment by litzvi** [comment]
i changed to private. for orders i'll build

**Comment by mei309** [comment]
let me know when you done

**Comment by litzvi** [comment]
com.avc.mis.beta.service.Orders.getAllOrdersByType(ProcessName, ProcessStatus[], Integer)
Version: 11.8 pushed

**Comment by mei309** [comment]
done look on the new version

**Comment by litzvi** [comment]
ok
