### ISSUE TITLE
times.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#33]
im giving you "HH:mm" for localtime we need to do some convemsion.
the error: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation:

**Comment by litzvi** [comment]
it's because it's missing the seconds?

**Comment by mei309** [comment]
no. its not putting in neither "hh:mm" and neither "hh:mm:ss"

**Comment by mei309** [comment]
cannot 24 for now

**Comment by litzvi** [comment]
what about the times? are they working ?

**Comment by mei309** [comment]
its working but its working on am pm system
