### ISSUE TITLE
Bottom Scroll bar

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#332]
Scroll bar should be floating(in the bottom of current screen), since can't see the right columns and need to scroll to the bottom of the data to see the Scroll bar.
see Cashew Receivings -> All in the cloud

**Comment by mei309** [comment]
if you on it and move to the side it workes

**Comment by mei309** [comment]
i dont find a way to do it floating

**Comment by mei309** [comment]
i checked more websites and they are like by me
