### ISSUE TITLE
numberAvailableUnits

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#336]
numberAvailableUnits is correct in ProcessItemInventory but not in ContainerLoadingDTO

**Comment by litzvi** [comment]
You mean in the method you get inventory with the process?
I thought you aren't using it.
It relies on poCode and weightedPo, in loading you don't set it, therefore you won't get it

**Comment by mei309** [comment]
no

**Comment by mei309** [comment]
in the dto

**Comment by litzvi** [comment]
where is numberAvailableUnits in the dto?

**Comment by mei309** [comment]
UsedItemBaseDTO

**Comment by litzvi** [comment]
interesting, it's the same function

**Comment by litzvi** [comment]
in what po?

**Comment by mei309** [comment]
po-14468 shippment 4567654

**Comment by litzvi** [comment]
send me the dump by email, can't get from here

**Comment by mei309** [comment]
do edit and you will see 706 available even so only 106 are

**Comment by mei309** [comment]
same dump as before

**Comment by litzvi** [comment]
I can't get it from here

**Comment by litzvi** [comment]
thank you. fixed

**Comment by mei309** [comment]
ok
