### ISSUE TITLE
GENERAL SCHEDULE

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#343]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/108942790-36affe00-768a-11eb-98e5-77ad2ab01b40.PNG">

**Comment by litzvi** [comment]
WHY IS IT 'NULL UNDIFINED'?

**Comment by litzvi** [comment]
Also fill in STATUS column in General Receivings -> All

**Comment by litzvi** [comment]
Also show receipt date in general inventory

**Comment by mei309** [comment]
> WHY IS IT 'NULL UNDIFINED'?

you changed it to an array. i fixed it

**Comment by mei309** [comment]
> Also fill in STATUS column in General Receivings -> All

done

**Comment by mei309** [comment]
> Also show receipt date in general inventory

done
