### ISSUE TITLE
Receiving general order - names

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#347]
should probably not be named 'bag weight' and 'number of bags'
perhaps unit amount and 'number of units'

**Comment by mei309** [comment]
they actually asked for it.

**Comment by litzvi** [comment]
yes. in cashew. I'm talking about general.
In general bag weight probably won't make sense

**Comment by mei309** [comment]
its not a problem in inventory and the form but it is in detailes

**Comment by mei309** [comment]
so its better i leave the same everywhere or show different ?

**Comment by litzvi** [comment]
show the correct names.
I think in cashew it can stay the same.
change the labels in general

**Comment by mei309** [comment]
like i said before in details i have no way to know if its cashew or general therefor i cannot change in details!! all the rest i can but then it will have different names

**Comment by litzvi** [comment]
i'm talking about the form for receiving an order
Receiving -> new -> general

**Comment by mei309** [comment]
ok done. but in order details it will still show as before
