### ISSUE TITLE
General items - unit amount

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#349]
unit amount is causing problems, since they can (and usually do) use parts of a unit.

The real fix should be that i allow in used items to have used units(e.g. used 2 bags of 50kg sugar)
and also used amount(the basic unit, e.g. kg).

@mei309 as a temporary solution you can remove the unit amount/bag weight from general receipt.

**Comment by mei309** [comment]
we dont need. thats one of the reasons you did all the change in the first place

**Comment by mei309** [comment]
now we can use part of a unit

**Comment by litzvi** [comment]
> now we can use part of a unit

not really.
for example, they add 10 tanks of 1000kg oil then they use 55kg. they could write 0.055 but i don't think it's nice

**Comment by mei309** [comment]
> > now we can use part of a unit
> 
> not really.
> for example, they add 10 tanks of 1000kg oil then they use 55kg. they could write 0.055 but i don't think it's nice

as a temporary solution its enough

**Comment by mei309** [comment]
i dont mind doing it i just dont think its a good solution since we will change it back so they should not get mixed

**Comment by litzvi** [comment]
let's discuss it

**Comment by litzvi** [comment]
@mei309 do you think we should do about this?
is it nice to allow them to use in weight units and we calculate for them? or just leave it like this?

**Comment by mei309** [comment]
i think its a great think and we definitely should do it. i just didnt find a good way yet. if you have a good suggestion for it please write.
adding a window to each box is a big overhead and will look strange. in the lines its definitely ok. so if you think we need only in the lines i will do it already. and you think i should do the calculations or you?

**Comment by litzvi** [comment]
> adding a window is good. and you think i should do the calculations or you?
If we are only doing calculation and not keeping the parts than you.

**Comment by mei309** [comment]
I think it's better to keep the parts because then it's consistent with what they put in on edit

**Comment by litzvi** [comment]
Now while reconsidering, I think you should just allow a popup window so they can fill the amount in kg (e.g. any process item measure unit) and directly calculate and display it in the amount and vice versa populate the window according to the amount (if filled). 
my reasons are:

- Anyway we shouldn't show 2 fields for used, so even if we would keep the amount in kg, would be too much to show both.
- Adding another filed for kg is somewhat redundant and error prone, because always need to calculate both
- Changing it now will probably make us lots of bugs in inventory, so not very desirable at this point.

**Comment by mei309** [comment]
done

**Comment by mei309** [comment]
please review

**Comment by litzvi** [comment]
1. It's showing on all items. e.g. jar
2. It's also showing in cases it's already in weight-not a very big deal, but probably not considering the packed content, see no.3.
3. Are you always showing in LBS? if so when the content is in kg will you make the conversion? if not, then you should do it by the weight of the packed item.

**Comment by mei309** [comment]
its by the weight of the item. 
the normal amount is number of units so eg. if we have 50lbs packs so in amount choosing 3 and choosing 150 in the popup is equal

**Comment by mei309** [comment]
i changed the name from amount => Amount of units

**Comment by mei309** [comment]
on packed item its always unitAmount 1? if so i will disable it in that case

**Comment by litzvi** [comment]
> its by the weight of the item.
it should be by the measure unit of the unit amount not by the measure unit of the item (otherwise you might need to convert).

**Comment by litzvi** [comment]
> on packed item its always unitAmount 1? if so i will disable it in that case

thar's true. unit amount -> amount is 1

**Comment by litzvi** [comment]
It's also not working. when we put in through the window, it doesn't save the used item - look in details or edit

**Comment by mei309** [comment]
> > its by the weight of the item.
> 
> it should be by the measure unit of the storage unit amount not by the measure unit of the item (otherwise you might need to convert).
> e.g. what if the unit amount 50kg but the item measure unit is lbs?

sorry meant by the storage

**Comment by mei309** [comment]
> > on packed item its always unitAmount 1? if so i will disable it in that case
> 
> thar's true. unit amount->amount is 1 in my current design.

ok. will be disabled whenever its 1

**Comment by mei309** [comment]
> It's also not working. when we put in through the window, it doesn't save the used item - look in details or edit

fixed

**Comment by litzvi** [comment]
> > It's also not working. when we put in through the window, it doesn't save the used item - look in details or edit
> 
> fixed

not fixed in the new version.

**Comment by mei309** [comment]
by me its working. no matter what i do

**Comment by mei309** [comment]
still not working by you?

**Comment by litzvi** [comment]
do I have the most update version. please upload the newest version +controllers

**Comment by mei309** [comment]
uploaded it

**Comment by mei309** [comment]
please check and close if its ok

**Comment by litzvi** [comment]
yes it's working
