### ISSUE TITLE
General Inventory - report with order (add supply category to item)

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#350]
report summarizing inventory and orders.

**Comment by litzvi** [comment]
com.avc.mis.beta.service.InventoryReports.getInventoryWithOrderByItem(ItemGroup)

It's for getting general inventory with the ordered amount, so they know if they need to order. I'll add a picture of the report

**Comment by litzvi** [comment]
currently it doesn't give the wanted result for cashew because it shows all items including the ones that are in process (never have an order for those)

**Comment by litzvi** [comment]
I think i'll add supply category to an item, so cashew items can also be fetched correctly.

**Comment by mei309** [comment]
I think we only need to show raw cashew order and inventory

**Comment by mei309** [comment]
if we show for all it will be very mixing

**Comment by litzvi** [comment]
yes exactly

**Comment by mei309** [comment]
i implemented it so you just need to change the cashew to raw only

**Comment by litzvi** [comment]
for now it's only for general

**Comment by mei309** [comment]
ok
