### ISSUE TITLE
Relocation -details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#351]
empty totals

**Comment by mei309** [comment]
fixed. just removed something from view no consequences

**Comment by litzvi** [comment]
sorry it was my mistake i fixed it.
please undo

**Comment by mei309** [comment]
because you gave one and not an array?

**Comment by litzvi** [comment]
yes

**Comment by mei309** [comment]
anyway i need to show also when its not an array.

**Comment by litzvi** [comment]
> anyway i need to show also when its not an array.

yes but i worry if you fix now it might have errors
