### ISSUE TITLE
total table schedule

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#353]
sum table should be in lots. just numbers if possible.
eli asked

**Comment by litzvi** [comment]
![2e09ed1e293d57f13917a21d38b7134e](https://user-images.githubusercontent.com/53637868/109100993-7d6c2980-7758-11eb-9034-a2cc450168fe.jpg)

**Comment by mei309** [comment]
i dont have that information in PoItemRow

**Comment by litzvi** [comment]
every line is 1

**Comment by mei309** [comment]
> every line is 1, think about it as number of expected receipts.
> you can assume every order is 1. (that's how it was before)
> you see, they don't even write the weight.

thats exactly what we need in a program

**Comment by mei309** [comment]
i did it but i really dont think it should be this way. if you want me to make the conversion i could

**Comment by litzvi** [comment]
Eli asked me for it, it's the only thing he was upset in the new version.
I suggest i give you lots, but you show in the lines only lbs, and use the lots for summary.
what do you say?

**Comment by mei309** [comment]
but you can give it to me separate? it's easier if you can if not give it as the 3Rd in the list. it's definitely better then writing always 1

**Comment by litzvi** [comment]
sure. i'll give it separate.
numberLots in every PoItemRow.
in version 11.9

**Comment by litzvi** [comment]
pushed version 11.9

**Comment by mei309** [comment]
ok done
