### ISSUE TITLE
divide container booking + and loading

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#355]
Now we have 2 parts (3)

- ContainerArrival
- ContainerLoading

arrival and loading reference a booking.
loading has ShipmentCode (Shipment codes are added separately)

arrival add/get/edit are in com.avc.mis.beta.service.ContainerArrivals

**Comment by litzvi** [comment]
so in arrival they need to choose the booking,
and in loading they need to choose the booking and shipment code

**Comment by litzvi** [comment]
pushed Version: 12.5 so you can see the structure.

i'll add com.avc.mis.beta.service.ObjectTablesReader.findFreeShipmentCodes() for shipmentCodes dropdown.
I need to add a getter for the bookings dropdown (so they can choose)

**Comment by litzvi** [comment]
com.avc.mis.beta.service.ContainerBookings.getNonArrivedBookings() - for arrival dropdown
com.avc.mis.beta.service.ContainerBookings.getNonLoadedBookings() - for loading dropdown

**Comment by litzvi** [comment]
I think will change ContainerLoading to reference ContainerArrival, so we will force all 3 processes to be done in order.

**Comment by mei309** [comment]
> I think will change ContainerLoading to reference ContainerArrival, so we will force all 3 processes to be done in order.

but that was their compline

**Comment by litzvi** [comment]
> but that was their compline

As you see now i left out the booking

**Comment by litzvi** [comment]
pushed Version: 12.8. container arrival and loading are ready

**Comment by mei309** [comment]
and also getAllArrivals

**Comment by mei309** [comment]
checked only basic

**Comment by litzvi** [comment]
> we need findAllShipmentCodes. and its better if you give it with the shipping port and not only this (it will be easier to do edit)
> String portOfDischargeCode;
> String portOfDischargeValue;

com.avc.mis.beta.service.ObjectTablesReader.findAllShipmentCodes()

**Comment by litzvi** [comment]
> and also getAllArrivals

com.avc.mis.beta.service.ContainerArrivals.getContainerArrivals()

**Comment by mei309** [comment]
ok done
