### ISSUE TITLE
packing produced items dropdown 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#356]
fetch only productionUse=roast (not both)
50 lbs is only used as part of roasting process

**Comment by mei309** [comment]
should i give in packing only packing?

**Comment by mei309** [comment]
for now i did it

**Comment by mei309** [comment]
if true just close the issue

**Comment by litzvi** [comment]
> should i give in packing only packing?

correct. for now they don't have anything in both.
If they will we will just add a union category
