### ISSUE TITLE
METRIAL TO LOAD

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#360]
STILL NOT SHOWING poCodes
I wrote  about it already

**Comment by litzvi** [comment]
used amounts in loading as well

**Comment by mei309** [comment]
> STILL NOT SHOWING poCodes
> I wrote about it already

i dont see it

**Comment by litzvi** [comment]
Shipping -> reports -> open MAC-10060A.
look at used amounts, they are from a mix as you can see in export doc

**Comment by litzvi** [comment]
same goes when you make a new loading. you can choose ABE-10230 and you'll see

**Comment by mei309** [comment]
in ProcessItemInventory you call it poCodes and you dont have suppliers.
in UsedItemBaseDTO you call it itemPoCodes and itemSuppliers.
i cannot guess each time that you put different names in different places. please be more aware of it. it took me about 40 minutes to find it

**Comment by litzvi** [comment]
yes sorry, because they have different meanings. it was itemPo all  the time, i didn't change it.
