### ISSUE TITLE
General Po Code

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#365]
I have a new Class GeneralPoCode - no need to add it in pos.
In General Order we won't add a poCode separately.
when they create a new order, let them choose supplier and contract type and build GeneralPoCode
Don't set the code, I will.

**Comment by litzvi** [comment]
pushed version 12.0.
You should rebuild the database

**Comment by litzvi** [comment]
>so there's no meaning for the code?

There is, it's just me who generates the code.
they have to add supplier and contract type (although might have a separate type for general)

**Comment by litzvi** [comment]
> and why they need the contractType in general?

for now  and they might want it, if they represent them differently.

1. so it's the same structure of cashew
2. so i can represent with po# where they need
3. they might want to represent different types of orders differently (they are doing it now).

**Comment by litzvi** [comment]
I added SupplyGroup supplyGroup to Contract type, so you can have a separate drop down for general ContractTypes.
com.avc.mis.beta.service.ValueTablesReader.getGeneralContractTypes()
com.avc.mis.beta.service.ValueTablesReader.getCashewContractTypes()
for fetching general and cashew Contract Types respectively.

**Comment by mei309** [comment]
you need to stop the mismatch naming 
contractTypeCode vs contractType and supplierName vs supplier
i cannot do edit this way

**Comment by mei309** [comment]
and also the table of pos is only cashew now. right?

**Comment by mei309** [comment]
> I added SupplyGroup supplyGroup to Contract type, so you can have a separate drop down for general ContractTypes.
> com.avc.mis.beta.service.ValueTablesReader.getGeneralContractTypes()
> com.avc.mis.beta.service.ValueTablesReader.getCashewContractTypes()
> for fetching general and cashew Contract Types respectively.

i dont see by me

**Comment by litzvi** [comment]
Sorry didn't push it yet. I'll push soon

**Comment by litzvi** [comment]
> i dont see by me

just pushed Version: 12.1

**Comment by litzvi** [comment]
> and also the table of pos is only cashew now. right?

When adding definantly, you only build PoCode (not GeneralPoCode)
About the table yes i think so, it doesn't matter much for now  - we can adjust it later if it shows all.

**Comment by litzvi** [comment]
> you need to stop the mismatch naming
> contractTypeCode vs contractType and supplierName vs supplier
> i cannot do edit this way

it's nothing new. i touched nothing regarding that. 
also they are different as the name applies 
supplier !!!= supplierName
contractType !!!!!!!= contractTypeCode

**Comment by mei309** [comment]
> > you need to stop the mismatch naming
> > contractTypeCode vs contractType and supplierName vs supplier
> > i cannot do edit this way
> 
> it's nothing new. i touched nothing regarding that.
> also they are different as the name applies
> supplier !!!= supplierName
> contractType !!!!!!!= contractTypeCode

so that means that we cannot edit the supplier and contract type in general order

**Comment by mei309** [comment]
> pushed version 12.0.
> You should rebuild the database

now that its working do a function to add to the old data so it fits

**Comment by litzvi** [comment]
> now that its working do a function to add to the old data so it fits

update contract_types set supply_group = "CASHEW" where id>0;

**Comment by litzvi** [comment]
> so that means that we cannot edit the supplier and contract type in general order

after we are sure general is going to stay this way we can fix it

**Comment by mei309** [comment]
> > so that means that we cannot edit the supplier and contract type in general order
> 
> after we are sure general is going to stay this way we can fix it

ok

**Comment by mei309** [comment]
i think this is done. if its something not directly connected to this open a new issue
