### ISSUE TITLE
report differences - add percentage 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#367]
percentage is important because 200lb on a lot might not be much, but substantial in a process of 2000lbs

**Comment by litzvi** [comment]
i added
com.avc.mis.beta.dto.view.ProcessRow.getProcessPercentageGain()
com.avc.mis.beta.dto.view.ProcessRow.getUsedCountPercentageDifference()

to get the percentage difference. you probably want it together with the weights, so to show together.
How do you sugest i do it, since i can't have '%' as the measure unit)

**Comment by litzvi** [comment]
NEVER MIND I'LL DO IT

**Comment by litzvi** [comment]
I added percentage in the next version.
You just need to fix the 'total difference' to show lbs too

**Comment by mei309** [comment]
> i added
> com.avc.mis.beta.dto.view.ProcessRow.getProcessPercentageGain()
> com.avc.mis.beta.dto.view.ProcessRow.getUsedCountPercentageDifference()
> 
> to get the percentage difference. you probably want it together with the weights, so to show together.
> How do you sugest i do it, since i can't have '%' as the measure unit)

in the weights of the difference is enough

**Comment by mei309** [comment]
and you already can see it by you

**Comment by mei309** [comment]
by you its missing lbs in the total but i fixed it

**Comment by litzvi** [comment]
yes i saw when i did it
