### ISSUE TITLE
item change during processing

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#370]
no need to change, the only change is Ly $ 340 considered 320.
In the factory it could be 340 only export document should change.

**Comment by mei309** [comment]
what you talking about?

**Comment by litzvi** [comment]
i meant to assign myself. 
We shouldn't allow to change item types in processes, specially not in relocation. It was a mistake.
But i need to prepare the item for it

**Comment by mei309** [comment]
they do it so its not a smart idea

**Comment by litzvi** [comment]
they claim they don't

**Comment by mei309** [comment]
ok when you finish the restructure let me know

**Comment by litzvi** [comment]
maybe one day, meanwhile allow edit also in relocation

**Comment by mei309** [comment]
ok

**Comment by litzvi** [comment]
For Product We need:

- ROAST/ROW
- S/NS/LS
- type: WHOLE/W320/H&P..
- brand(for bags): NICE/IMPERIAL ..
- code(for bags):
- weight/size(for bags): 30OZ/8.5OZ..
- box quantity(for bags): 

Should probably add a class BoxedBag

**Comment by litzvi** [comment]
@mei309  so now we have the method
com.avc.mis.beta.service.ValueTablesReader.getCashewItems(ItemGroup, ProductionUse, CashewGrade, PackageType)
So we can also filter the drop down by CashewGrade.
In the side we can add other items = the old drop down, same as what you did with AllPOs button.

of course this is all when the items are updated.
and in relocation, you should only allow the items they are moving.

**Comment by mei309** [comment]
we have another issue on it
