### ISSUE TITLE
should not allow cleaning before relocation

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#372]
they did cleaning without full relocation.
Should allow cleaning only from raw station, same goes with the second relocation.
It's causing a lot of mess and unclarity, specially when they have raw and clean items of the same po.

**Comment by litzvi** [comment]
1. I suggest we only allow the to clean items they already moved to the raw station.
2. split relocation into 2 separate processes for the raw and clean

**Comment by litzvi** [comment]
first let's deal with 1.
ProductionLine will have ProductionFunctionality that will group the 'lines' to there main function in the process.
e.g. roaster 4000 and roaster 2000 will have the same productionFunctionality = ROASTER
So for our purpose, we will have in Reloction a ProductionLine with productionFunctionality = RAW_STATION,
then in roasting you only look for inventory that is in raw station.
It will also serve for the purpose of choosing ProductionLines in processes. e.g. in roasting they only choose from ProductionFunctionality = ROASTER. 

have a look at 
com.avc.mis.beta.entities.values.ProductionLine
com.avc.mis.beta.entities.enums.ProductionFunctionality
com.avc.mis.beta.service.ValueTablesReader.getProductionLinesByFuncionality(ProductionFunctionality[])

**Comment by litzvi** [comment]
continued...
I will add ProductionFunctionality[] argument also for fetching the com.avc.mis.beta.service.WarehouseManagement.getAvailableInventory(ItemGroup, ProductionUse[], Integer, Integer[])
so you only get the relevant inventory for cleaning and roasting

**Comment by litzvi** [comment]
you can use this, just so you don't have to insert for testing
INSERT INTO `production_lines` (`id`, `active`, `name`, `production_functionality`) VALUES 
(1,1,'Raw Storage','RAW_STORAGE'),(2,1,'Raw Station','RAW_STATION'),
(3,1,'Screen Table','SCREEN_TABLE'),(4,1,'Roaster In','ROASTER_IN'),
(5,1,'Roaster','ROASTER'),
(6,1,'Roaster Out','ROASTER_OUT'),
(7,1,'Packing','PACKING'),
(8,1,'Final Product','FINAL_PRODUCT'),
(9,1,'Loading','LOADING'),
(10,1,'General Storage','GENERAL_STORAGE'),
(11,1,'Packing Station','PACKING_STATION');

**Comment by litzvi** [comment]
I'll also need to fix their data to have a ProductionLine and make productionLine mandatory.
I'll do it when everything else is working

**Comment by litzvi** [comment]
just PUSHED Version: 12.3

**Comment by mei309** [comment]
2 is easy.

**Comment by mei309** [comment]
about 1 we only need it in relocation so why to put it on the production line??

**Comment by litzvi** [comment]
> about 1 we only need it in relocation so why to put it on the production line??

I'm not sure yet about all uses, but it's a logical connection between ProductionLines by their functionality.
for example, dropdown only roasters in roasting etc.

**Comment by mei309** [comment]
you forcing to much

**Comment by mei309** [comment]
its the biggest problem

**Comment by mei309** [comment]
done very unhappily

**Comment by mei309** [comment]
we should talk about it. it looks a big mess for nothing

**Comment by litzvi** [comment]
> the production line is very unclear

we can discuss it

**Comment by mei309** [comment]
why not just to do 2 process that are required ???

**Comment by litzvi** [comment]
> its done and checked(not thoroughly) i added only in relocation the production line (i did it in the back without giving them to choose. because I don't think we need a production line in relocation. and in the new version we can clean only from RAW_STATION and roast only from ROASTER_IN

from the back is suitable here. you can call them 'relocation to raw station', 'relocation to roaster'

**Comment by litzvi** [comment]
> why not just to do 2 process that are required ???

[3/11, 07:09] Zvi Lieberman: We're not restricting things by what process they went through
[3/11, 07:11] Zvi Lieberman: The name isn't suitable - you can change it for relocation to relocation type or something. But the meaning of the item's location is accurate.
[3/11, 07:14] Zvi Lieberman: The only real restriction is by its location, not by the process it went through. I can do 10 relocations for the same item,what matters if it arrived to the raw station. If you think about it it's the same meaning as production line=the location where the process was done.
[3/11, 07:16] Zvi Lieberman: What you are suggesting is an ad hoc solution of restriction process sequence that will work for this exact scenario but will be messed up with every change in the way they record and process things.

**Comment by litzvi** [comment]
> and i also divided into 2 separate stuff in the tabs and in the report so we just need the functions for it


com.avc.mis.beta.service.ValueTablesReader.getProductionLinesByFuncionality(ProductionFunctionality[])
u can used this function for fetching suitable production lines in the relocation. if they will only have one, it will be filled automatically and they don't need to choose it.

**Comment by litzvi** [comment]
for fetching available pos:
com.avc.mis.beta.service.ObjectTablesReader.findAvailableInventoryPoCodes(ProductionUse[], ProductionFunctionality[])

**Comment by mei309** [comment]
it should not work by you now. why you dont give the productionFunctionality in ProductionLine???
calling a function each time isnt smart. i should have it and make my filter

**Comment by mei309** [comment]
and by the way should we give them the option to change production lines??

**Comment by mei309** [comment]
> > and i also divided into 2 separate stuff in the tabs and in the report so we just need the functions for it
> 
> com.avc.mis.beta.service.ValueTablesReader.getProductionLinesByFuncionality(ProductionFunctionality[])
> u can used this function for fetching suitable production lines in the relocation. if they will only have one, it will be filled automatically and they don't need to choose it.

what i need is this getStorageRelocations with ProductionFunctionality so i can show separate relocations

**Comment by mei309** [comment]
i need a function to get available pos for the relocation types

**Comment by mei309** [comment]
Could not write JSON: could not initialize proxy [com.avc.mis.beta.entities.values.ProductionLine#2] - no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException: could not initialize proxy [com.avc.mis.beta.entities.values.ProductionLine#2] - no Session (through reference chain: com.avc.mis.beta.dto.process.StorageRelocationDTO["productionLine"]->com.avc.mis.beta.entities.values.ProductionLine$HibernateProxy$mGFani17["active"])]

**Comment by mei309** [comment]
also this findAvailableInventoryPoCodes with ProductionFunctionality not giving results

**Comment by mei309** [comment]
same goes for getAvailableInventory

**Comment by litzvi** [comment]
> what i need is this getStorageRelocations with ProductionFunctionality so i can show separate relocations

you can show them in the same report, just as until now

**Comment by litzvi** [comment]
> it should not work by you now. why you dont give the productionFunctionality in ProductionLine???
> calling a function each time isnt smart. i should have it and make my filter

please be more specific. what function? where?

**Comment by litzvi** [comment]
> and by the way should we give them the option to change production lines??

within the same functionality. why not?

**Comment by litzvi** [comment]
> i need a function to get available pos for the relocation types

com.avc.mis.beta.service.ValueTablesReader.getProductionLinesByFuncionality(ProductionFunctionality[])

**Comment by litzvi** [comment]
> also this findAvailableInventoryPoCodes with ProductionFunctionality not giving results

of course. because nothing has a production line

**Comment by mei309** [comment]
> > what i need is this getStorageRelocations with ProductionFunctionality so i can show separate relocations
> 
> you can show them in the same report, just as until now

then it will be very hard to know if it's a raw or clean for edit

**Comment by mei309** [comment]
> > it should not work by you now. why you dont give the productionFunctionality in ProductionLine???
> > calling a function each time isnt smart. i should have it and make my filter
> 
> please be more specific. what function? where?

one function that gives all the production lines with the functionality so I can filter myself

**Comment by mei309** [comment]
> > and by the way should we give them the option to change production lines??
> 
> within the same functionality. why not?

so they can't change the functionality only the name. ok

**Comment by mei309** [comment]
> > also this findAvailableInventoryPoCodes with ProductionFunctionality not giving results
> 
> of course. because nothing has a production line

I put production line and still

**Comment by mei309** [comment]
> > i need a function to get available pos for the relocation types
> 
> com.avc.mis.beta.service.ValueTablesReader.getProductionLinesByFuncionality(ProductionFunctionality[])

I'm not with the computer so I can't check but what I need is pos not production line

**Comment by litzvi** [comment]
> it should not work by you now. why you dont give the productionFunctionality in ProductionLine???
> calling a function each time isnt smart. i should have it and make my filter

don't see why you don't get the functionality in the productionLines already.
anyway built these to make sure.
com.avc.mis.beta.service.ValueTablesReader.getAllBasicProductionLines()
com.avc.mis.beta.service.ValueTablesReader.getAllBasicProductionLinesByFuncionality(ProductionFunctionality[])

**Comment by litzvi** [comment]
> what i need is this getStorageRelocations with ProductionFunctionality so i can show separate relocations

I added 2 new process names RAW_STATION_RELOCATION,  ROAST_STATION_RELOCATION
and now adding and getting relocations will be done just as in production processes with the ProcessName

**Comment by litzvi** [comment]
> i need a function to get available pos for the relocation types

com.avc.mis.beta.service.ObjectTablesReader.findAvailableInventoryPoCodes(ProductionUse[], ProductionFunctionality[])

**Comment by litzvi** [comment]
> also this findAvailableInventoryPoCodes with ProductionFunctionality not giving results

I think it's fixed

**Comment by litzvi** [comment]
> > what i need is this getStorageRelocations with ProductionFunctionality so i can show separate relocations
> 
> I added 2 new process names RAW_STATION_RELOCATION, ROAST_STATION_RELOCATION
> and now adding and getting relocations will be done just as in production processes with the ProcessName.
> 
> We should leave the old relocation type for moving of inventory and add 2 new ones for these 'special' relocations.

sorry, better we don't do this. Stick only with the production line

**Comment by litzvi** [comment]
> what i need is this getStorageRelocations with ProductionFunctionality so i can show separate relocations

com.avc.mis.beta.service.WarehouseManagement.getStorageRelocations(ProductionFunctionality)
com.avc.mis.beta.service.WarehouseManagement.getStorageRelocationsByPoCode(Integer, ProductionFunctionality)

**Comment by litzvi** [comment]
pushed change in Version: 13.1

**Comment by litzvi** [comment]
> happens when trying to get a reloction that has a production line
> 
> Could not write JSON: could not initialize proxy [com.avc.mis.beta.entities.values.ProductionLine#2] - no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException: could not initialize proxy [com.avc.mis.beta.entities.values.ProductionLine#2] - no Session (through reference chain: com.avc.mis.beta.dto.process.StorageRelocationDTO["productionLine"]->com.avc.mis.beta.entities.values.ProductionLine$HibernateProxy$mGFani17["active"])]

fixed Version: 13.2 pushed

**Comment by mei309** [comment]
i think the prudction functanlty is a very bad design.
1) i have no way to find pos and inventory that didn't relocation yet therefor it will all be mixed and very unhelpful 
2)you forcing to put an object everywhere that isnt used not in relocation and not in receiving

**Comment by mei309** [comment]
i really dont see no gain from this mess. i spent more then 2 hours on it and i cannot figure out why you did it and how i need to implement it so its helpful, the only way is if you force everywhere to have it including receiving then i can implement it but i really dont see why you dont do 2 processes

**Comment by litzvi** [comment]
1.You can allow them to use all just as before. If production functionality
is set to null, it should work just as before.
2. Don't force it everywhere for now.

**Comment by litzvi** [comment]
Why can't you implement it so you only add production line in relocation?

**Comment by mei309** [comment]
so in a raw relocation I will allow them to transfer cleaned?

**Comment by mei309** [comment]
and in raw I allow them to do relocation also for rosted?

**Comment by mei309** [comment]
and you need to explain why in this way it's going to be clear

**Comment by mei309** [comment]
and we will have only pos that are raw in the raw and rosted in the rosted. it's also not good because we need only pos that didn't fully transfer in that category

**Comment by litzvi** [comment]
Why not filter raw and roasted just as before? The whole thing was for
cleaning and roasting not for relocation. Relocation only need to add the
production line.

**Comment by litzvi** [comment]
OK if it's gonna be like this never mind. Just leave/change it back to the
way it was before. Ignore this whole issue. Prepare everything else and we
will upload.

**Comment by mei309** [comment]
I will leave it with the new production funcnalty since I already implemented it and on like by you by me it's a lot of work to change back

**Comment by mei309** [comment]
you will see the problems I mean then you will change

**Comment by mei309** [comment]
but I definitely think it's not the right way to do it

**Comment by litzvi** [comment]
Don't understand what you are talking about. I don't need to change
anything. If you want to do it, do it. If not just cancel the whole thing.
Say for once what you want, come up with a solution instead of just
complaining.

**Comment by mei309** [comment]
I told 4 times very clear.
1) in raw relocation we need to get only raw un transfeed items if not it will still be messy because they will transfer cleaned as raw
and the same also for cleaned relocation. 
2) same for choosing pos.

**Comment by mei309** [comment]
and since we need that I don't see how the production line will help

**Comment by mei309** [comment]
once you will have the new version you will see for yourself

**Comment by litzvi** [comment]
Let them relocate only raw. No need untransferred.

**Comment by litzvi** [comment]
> I told 4 times very clear.
> 
> 1. in raw relocation we need to get only raw un transfeed items if not it will still be messy because they will transfer cleaned as raw
>    and the same also for cleaned relocation.
> 2. same for choosing pos.

WHY NOT CHOOSE RAW ITEMS FOR RAW RELOCATION. JUST AS YOU DID FOR CLEANING BEFORE?
THE SAME FOR CLEANED RELOCATION, CHOOSE ONLY CLEANED ITEMS

**Comment by litzvi** [comment]
For now, always allow relocation for raw or cleaned items respectively.
for some reason after doing both relocation on a lot, i can't relocate it again even though it wasn't roasted yet.

**Comment by mei309** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/58453503/112875271-91f46680-90f6-11eb-98c7-d3824c0eb7e1.png)
not by me

**Comment by mei309** [comment]
> > I told 4 times very clear.
> > 
> > 1. in raw relocation we need to get only raw un transfeed items if not it will still be messy because they will transfer cleaned as raw
> >    and the same also for cleaned relocation.
> > 2. same for choosing pos.
> 
> WHY NOT CHOOSE RAW ITEMS FOR RAW RELOCATION. JUST AS YOU DID FOR CLEANING BEFORE?
> THE SAME FOR CLEANED RELOCATION, CHOOSE ONLY CLEANED ITEMS

done

**Comment by litzvi** [comment]
> For now, always allow relocation for raw or cleaned items respectively.
> for some reason after doing both relocation on a lot, i can't relocate it again even though it wasn't roasted yet.

can you do another relocation at this stage??

**Comment by mei309** [comment]
> > For now, always allow relocation for raw or cleaned items respectively.
> > for some reason after doing both relocation on a lot, i can't relocate it again even though it wasn't roasted yet.
> 
> can you do another relocation at this stage??
> the screenshot you sent me means nothing

yes

**Comment by litzvi** [comment]
what can i do
