### ISSUE TITLE
Allow edit in all scenarios

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#376]
I had a case (issue 373) that a process managed to get recorded without processItems.
It showed details but couldn't open the edit. It should be allowed to edit in order to fix these problems if they accrued.
even though they aren't supposed to happen in the first place.

**Comment by litzvi** [comment]
[localhost-1614855333970.log](https://github.com/litzvi/avc-beta/files/6083009/localhost-1614855333970.log)

**Comment by litzvi** [comment]
this is the log i get

**Comment by mei309** [comment]
its adding a very lot of if else all over.
theres so much of stuff like this and it has no end.
like do i need to make it even if you have a usedItemGroups without usedItems?? its crazy

**Comment by mei309** [comment]
i did for it because for this its easy

**Comment by litzvi** [comment]
You don't have to do it, since it needs to be fixed when we have dtos both ways.

Anyhow, i think it's a big flaw in design if it can't display any part of the information it gets, regardless of the error it causes.

**Comment by mei309** [comment]
we need to display an error that's all

**Comment by mei309** [comment]
it's a flaw in design that my front end is taking care of stuff like this at all

**Comment by litzvi** [comment]
I disagree, even if everything is taken care of, the front end should still display what ever data it gets, even if partial or not legal.
It's a very weak front end in my opinion.

**Comment by mei309** [comment]
> I disagree, even if everything is taken care of, the front end should still display what ever data it gets, even if partial or not legal.
> It's a very weak and not robust front end in my opinion.

sorry to tell you but you have no clue what's a front end

**Comment by litzvi** [comment]
i have a clue about you and also on what's suppose to be

**Comment by mei309** [comment]
anyway this is fixed.
