### ISSUE TITLE
The lot still stay on pending Even though I confirm, unless I refresh the Browser. 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#377]
אשלח לכם סירטון

**Comment by mei309** [comment]
i have no clue what is it. next time send me a picture of f12 log

**Comment by mei309** [comment]
@litzvi according to what you give pending receipts the user or all required approval ???

**Comment by mei309** [comment]
@litzvi in the log you sent me you have an error that might be connected, do you remember where you got this error??
it happened while you were trying to approve a process but i need to know where you tried and got the error
:4200/api/api/approveTaskAndManagment/APPROVED:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by litzvi** [comment]
> @litzvi according to what you give pending receipts the user or all required approval ???

pending depends only on finalize.
for now i don't allow finalize if they it's not approved by all required approvals, so that's not the problem.

**Comment by litzvi** [comment]
> @litzvi in the log you sent me you have an error that might be connected, do you remember where you got this error??
> it happened while you were trying to approve a process but i need to know where you tried and got the error
> :4200/api/api/approveTaskAndManagment/APPROVED:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

send it in the issue of the log, maybe i'll remember

**Comment by mei309** [comment]
i didnt change anything. but you function now always returns an error that i cannot change from final to final

**Comment by litzvi** [comment]
so now what do you want??

**Comment by mei309** [comment]
java.lang.IllegalArgumentException: Can't change life cycle process status, from: FINAL to: FINAL
	at com.avc.mis.beta.dao.ProcessInfoDAO.setProcessStatus(ProcessInfoDAO.java:373) ~[classes/:na]
	at com.avc.mis.beta.dao.ProcessInfoDAO$$FastClassBySpringCGLIB$$b2f2b2b.invoke(<generated>) ~[classes/:na]

**Comment by mei309** [comment]
ok. i found the problem. it was by me sorry

**Comment by mei309** [comment]
and about that the page doesn't reload i have no clue why

**Comment by litzvi** [comment]
> i have no clue so i need f12 when it happens

i don't know what you are talking about

**Comment by mei309** [comment]
if you confirm and it stays in pending so send me f12

**Comment by litzvi** [comment]
so why don't you check yourself??
finalize a process and you will see

**Comment by mei309** [comment]
> so why don't you check yourself??
> finalize a process and you will see

it works correct by me

**Comment by mei309** [comment]
i never had that problem but you wrote that you had

**Comment by litzvi** [comment]
try on the cloud

**Comment by litzvi** [comment]
it's like you just trying to bump things back to me. I don't work by you

**Comment by mei309** [comment]
> it's like you just trying to bump things back to me. I don't work by you

it just doesn't happen by me. because I do stuff in a different way.

**Comment by mei309** [comment]
fixed

**Comment by mei309** [comment]
and the error before of final on the first time was because of jackson. i didnt even dream about it
