### ISSUE TITLE
General bulk item default measure unit can be a unit, box etc. 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#378]

**Comment by mei309** [comment]
what's the difference between bulk and packed in general?

**Comment by litzvi** [comment]
packed = has something inside, that can have a n amount etc. 
bulk is not packed. e.g. 10,000 empty boxes, 5,000 kg salt

we might not need the packed in general specially if i adjust used item structure for units and part of units,
but for now let it be the same

**Comment by litzvi** [comment]
anyway, the restrictions for default measure unit and also the packed inside measure unit are only for product because they want us to calculate weights everywhere. It's not an intrinsic restriction.

**Comment by litzvi** [comment]
the only real restriction is that default mu of a packed item can't be a weight or anything that's not a quantity.

**Comment by mei309** [comment]
or we cancel the packed in general or we stay that bulk is with a measure unit? 
you just mixing packed and bulk so why we need both??

**Comment by mei309** [comment]
otherwise i cannot do the restrictions on the measure unit used in general

**Comment by mei309** [comment]
whats the difference between packed and bulk in cashew??

**Comment by mei309** [comment]
ok its done

**Comment by mei309** [comment]
and in packed item in the unit amount the weight can also be a unit or only bulk measure unit?

**Comment by litzvi** [comment]
> and in packed item in the unit amount the weight can also be a unit or only bulk measure unit?

also in packed. try to put in items..

**Comment by mei309** [comment]
ok done
