### ISSUE TITLE
ERROR IN GENERAL INVENTORY

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#379]
CAN'T SEE ANY PRINTOUT SO DON'T KNOW

**Comment by litzvi** [comment]
[localhost-1614940068206.log](https://github.com/litzvi/avc-beta/files/6089849/localhost-1614940068206.log)

**Comment by mei309** [comment]
inventoryReports.getInventoryTableByItem(ItemGroup.GENERAL); returns null. probably the storage isnt in even so we did finalize

**Comment by mei309** [comment]
and just so you know this is chrome error that dosent really matter. it mostly happens when the internet is bad

**Comment by litzvi** [comment]
ok fixed it was only fetching with poCode not general
