### ISSUE TITLE
cleaning cashew

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#38]
I filled the first 'transfer to'
started to fill the second, but only the top fields - item, weight and left the table empty.
It will give an error and i have no way to clean that part.
decide if you should remove it automatically or give a clean/delete option

**Comment by mei309** [comment]
i have no way to clean that part. theres always the way to clean one one.
whats better? 
1 add a garbage
2 remove when submiting

**Comment by litzvi** [comment]
that is exactly what i was asking.
choose one of the ways, or both and then maybe we can remove one

**Comment by mei309** [comment]
i added a garabge

**Comment by litzvi** [comment]
the message for this mistake is ugly, we need a more informative message.
do you know why it's not showing my underlying message

**Comment by mei309** [comment]
you not consistent you giving a nested error. i sent you a photo on zalo.

**Comment by litzvi** [comment]
send on another app. cant see

**Comment by litzvi** [comment]
when you see ugly messages please send me the exact error so we can add it to  the ExceptionControler

**Comment by mei309** [comment]
ok. i sew it only now
