### ISSUE TITLE
Arrange the shipping part of the software

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#381]
1. divide loading for 2 part Independently. A, Arrival of the Container, B marerial to load. 

2.move the code*  to part B "meterial to load" 

3. At part A and B, add one more drup down, "container for" AVC, LY, or VIETNUTS 

The idea behind this, that there will be verification between the two of them on the final destination, so 
that you will be clear to everyone which materials are going up to where.

**Comment by litzvi** [comment]
it's clear from the poCode and supplier what company the shipping is for, no?

**Comment by litzvi** [comment]
> At part A and B, add one more drup down, "container for" AVC, LY, or VIETNUTS

@mei309  I added a ContainerArrival a productCompany (Supplier)
I added 2 more options in SupplyGroup: LOGISTICS (for shipping company - later), SHIPPED_PRODUCT (for this)
So in setup -> supply categories, update the dropdown.
then in ContainerArrival you can supply a dropdown for productCompany  filtered by SupplyGroup=SHIPPED_PRODUCT.

I added productCompany for com.avc.mis.beta.service.ContainerArrivals.getNonLoadedArrivals() (arrival drop downs), 
also for the ContainerLoadingDTO
and for com.avc.mis.beta.service.ContainerArrivals.getContainerArrivals() (arrivals report)

**Comment by litzvi** [comment]
Eli asked for it, Do it if you want

**Comment by mei309** [comment]
i want to do it. i just dont have a good feeling its the correct way, we using the supplygroup for to know if its cashew or general. this is creating new suppliers on suppliers that exist already

**Comment by mei309** [comment]
i think its more correct to add another parameter to the suppliers

**Comment by litzvi** [comment]
In retrospective, supplier wasn't a good word choice, Business contact would be more suitable (You didn't want to change).

Now think of it as business contact, in them we have suppliers, shipping companies, the company who owns the product that's processed and shipped (the one we are talking about) or any other service provider.
Then supply group is the type of function the company fulfills, either sell cashew, sell general stuff, give other service, product owner, logistics, law service etc.
This way they can manage all in one page.

The alternative would be to make another page for logistics (shipping) providers, product owner company etc.
I think it's just easier to change the name for less confusion.

**Comment by mei309** [comment]
its not true about ly and those stuff because ly also selles cashew and also is incharge of a few suppliers so its like a group and nothing to do with supplygroup of buying

**Comment by mei309** [comment]
and i have no problem to change just not now

**Comment by litzvi** [comment]
> its not true about ly and those stuff because ly also selles cashew and also is incharge of a few suppliers so its like a group and nothing to do with supplygroup of buying

yes, nothing to do with suppliers. they add LY and give her a supply group of SHIPPED_PRODUCT (she can also be cashew supplier), same with Viet Nuts they are a supplier and also SHIPPED_PRODUCT and later probably more stuff.

**Comment by mei309** [comment]
it so only one supplier ly and the other only a supply group?  I understand correctly?

**Comment by litzvi** [comment]
> it so only one supplier ly and the other only a supply group? I understand correctly?

don't understand what is and the other.
ly doesn't appear as a supplier, so a better example is viet nuts.

say we add 
INSERT INTO `supply_categories` (`name`, `supply_group`) VALUES ('ROAST PRODUCT', 'SHIPPED_PRODUCT');

Currently Viet Nuts has a supply category of RAW KERNEL which has a GENERAL supply group.
Now all we need is to add another supply group, say 'ROAST PRODUCT' which has a SHIPPED_PRODUCT supply group.

then for the drop down in the container you fetch the suppliers by SHIPPED_PRODUCT supply group. that's all

**Comment by mei309** [comment]
you need this 
public List<DataObjectWithName<Supplier>> getSuppliersBasicGroup(SupplyGroup group) {
		return getSupplierRepository().findSuppliersByGroupBasic(group);
	}

**Comment by mei309** [comment]
besides the function ready

**Comment by litzvi** [comment]
added
com.avc.mis.beta.service.ValueTablesReader.getSuppliersBasicByGroup(SupplyGroup)
mind the name difference

**Comment by mei309** [comment]
> added
> com.avc.mis.beta.service.ValueTablesReader.getSuppliersBasicByGroup(SupplyGroup)
> mind the name difference

done
