### ISSUE TITLE
Rearrange the toolbar

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#385]
After quite a bit of use, I noticed that the toolbar should be improved, in this order from left to right, CQ, SCADUDLES, PURCHAS ORDER, RECEIVING, PRODUCTION, SHIPPING, INVENTORY, REPORTS, MANAGEMENT, TASKS, MASSAGES.
Can Remove SUPLIRE from the toolbar at on of the dropdowns, maybe at PO, or MANAGEMENT setups

It's neither essential nor urgent, it's a matter of convenience only.

**Comment by mei309** [comment]
@litzvi where you think the suppliers is more suitable ?

**Comment by ELIPELET** [comment]
In my opinion, it could be on Purchase Orders. Dropdown. It doesn't really matter because we don't setup suplires every day.

**Comment by mei309** [comment]
ok done. suppliers at Purchase Orders
