### ISSUE TITLE
in ContainerLoadingDTO add arrival

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#389]
you arent returning ContainerArrival arrival.
i need it for details and edit

**Comment by mei309** [comment]
and also in ContainerArrivalBasic you return portOfDischarge null

**Comment by litzvi** [comment]
> you arent returning ContainerArrival arrival.
> i need it for details and edit

added ContainerArrivalBasic arrival in ContainerLoadingDTO

**Comment by litzvi** [comment]
> and also in ContainerArrivalBasic you return portOfDischarge null

ContainerArrivalBasic doesn't have portOfDischarge...

**Comment by mei309** [comment]
ok. my mistake.
