### ISSUE TITLE
Don't understand the numbers 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#391]
Lot no ABE-10228, software written that we received total quantity of 35,517 lbs, My question is, from Where did he take that amount?
![Screenshot 2021-03-22 170906.png](https://user-images.githubusercontent.com/76675352/111974890-891df680-8b32-11eb-983f-28b0b71ec090.png)

**Comment by litzvi** [comment]
there are 2 boxes. received which is 35000 and product count which is the weights (count) of the raw station.
We thought it belongs in receiving because it's weighing the received amount.

**Comment by ELIPELET** [comment]
That may be true when the cleaning count would have come out of that amount, but in  case of this lot, No amount of material came out for that amount. 
Here's a picture ![Screenshot_20210323-113521_OneDrive.jpg](https://user-images.githubusercontent.com/76675352/112093564-3b55cc80-8bcc-11eb-9309-596cbec12aeb.jpg)

**Comment by ELIPELET** [comment]
That may be true when the cleaning count would have come out of that amount, but in case of this lot, No amount of material came out for that amount.
Here's a picture
![Screenshot 2021-03-23 113353.png](https://user-images.githubusercontent.com/76675352/112093834-b7501480-8bcc-11eb-80c4-c9519a18132d.png)

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/112778877-b48f6c80-906f-11eb-8a45-e72122eb5417.PNG">

**Comment by mei309** [comment]
elis issue what we should do? 
about the total in the top I'm working on it

**Comment by mei309** [comment]
about the totals on top it was from when we uploaded this version (a month ago) or only started now??

**Comment by litzvi** [comment]
> about the totals on top it was from when we uploaded this version (a month ago) or only started now??

don't know. i didn't complain about that, was just showing Eli where 35,517lbs came from
