### ISSUE TITLE
Inventory -> reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#392]
after i did 1 relocation, sometimes shows in report for a second and than disappears.
If you dont see, try changing between the tabs

**Comment by litzvi** [comment]
start with a new database and do 1 relocation, you should see it

**Comment by mei309** [comment]
this a good case for a dump

**Comment by litzvi** [comment]
I don't have for a reason.
anyway, I encourage you to put in some data.

**Comment by mei309** [comment]
i put all the time.

**Comment by mei309** [comment]
i just removed a break; from a switch. with a dump it would take 3 minutes to solve. without 15

**Comment by litzvi** [comment]
I told you, I know but I had a reason.
