### ISSUE TITLE
Production line dropdown

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#393]
why do you allow to choose from all?
the functionality is exactly for that. 
e.g. for roasting u filter by roaster.

**Comment by litzvi** [comment]
Also in setup, add production line you need to allow to choose the functionality.

**Comment by mei309** [comment]
whats the difference between PACKING_STATION to PACKING?

**Comment by mei309** [comment]
and clean by SCREEN_TABLE??

**Comment by mei309** [comment]
why in ProductionLine productionFunctionality is jsonIgnore i need it for edit

**Comment by mei309** [comment]
and to show in the table

**Comment by mei309** [comment]
> Also in setup, add production line you need to allow to choose the functionality.

done

**Comment by mei309** [comment]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='Production functionality mandatory, links production line to it's production functionality', propertyPath=productionFunctionality, rootBeanClass=class com.avc.mis.beta.entities.values.ProductionLine, messageTemplate='Production functionality mandatory, links production line to it's production functionality'}
]]

**Comment by mei309** [comment]
cannot add a new one. its because of the jsonignore too

**Comment by mei309** [comment]
ok besides that its ready

**Comment by litzvi** [comment]
> and clean by SCREEN_TABLE??

yes

**Comment by litzvi** [comment]
> why in ProductionLine productionFunctionality is jsonIgnore i need it for edit

I don't see it's JsonIgnore anywhere. 
In what class? where?

**Comment by litzvi** [comment]
> why in ProductionLine productionFunctionality is jsonIgnore i need it for edit

i just removed it in
ProductionLine.java line 35

**Comment by mei309** [comment]
ok done
