### ISSUE TITLE
THE PAGE IS FLICKERING(JUMPING) IN REPORTS

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#395]
See for example Cashew Receiving
Receivings -> Cashew Reports

**Comment by litzvi** [comment]
I suggest the purple turning icon, shouldn't show right away.
Because it shows during the second it takes to load and just dazzling

**Comment by mei309** [comment]
i did it so now you first see a blank table. look if its better. only after a second it shows the progress bar.
i did it only on some tables till you tell me if its better or not. (production for example )

**Comment by mei309** [comment]
and also in the popups to do it???

**Comment by litzvi** [comment]
it annoyed me in the reports. didn't see a problem popups

**Comment by litzvi** [comment]
It's probably ok because it will take longer on the cloud, so won't be a problem anyway.
So sorry for bringing this up.

**Comment by mei309** [comment]
it's ok to do it. just decide what's correct. I already implemented it. so should I do it everywhere or cancel where I did?

**Comment by litzvi** [comment]
Leave one one and ask Eli what he prefers when he works with it on the
cloud.

**Comment by litzvi** [comment]
> it's ok to do it. just decide what's correct. I already implemented it. so should I do it everywhere or cancel where I did?

now it looks like it's empty in the first second :(
maybe shorten it.

**Comment by mei309** [comment]
i did half a second

**Comment by mei309** [comment]
lets see what they say and then decide. also on the cloud it might be totally different
