### ISSUE TITLE
Production table of processed items - default 30

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#397]
e.g. cleaned amounts. you show 15 by default

**Comment by mei309** [comment]
everywhere in the web its 15 and they can change in the bottom so its not a problem. if you anyway want i will do it.

**Comment by litzvi** [comment]
do you understand what i'm talking about??
<img width="666" alt="Capture" src="https://user-images.githubusercontent.com/53637868/112971329-4e8f0c00-9179-11eb-847c-2f8b182f4cc3.PNG">

**Comment by mei309** [comment]
ha ok. I was sure you mean the report tables

**Comment by litzvi** [comment]
> should i do in relocation too??

relocation it's already 30..

**Comment by mei309** [comment]
ok done
