### ISSUE TITLE
Need to refresh to do Cleaned Relocation Count

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#399]
the dropdown is empty until i refresh after cleaning

**Comment by mei309** [comment]
cannot duplicate. try explaining the steps

**Comment by litzvi** [comment]
- clean the whole lot
- do relocation to the roaster

**Comment by mei309** [comment]
by me its not working

**Comment by litzvi** [comment]
In the backup it's working but in a new one many things aren't working.
need to check a new one because their might be differences from the backup

**Comment by mei309** [comment]
just did a new one and everything is fine.
maybe it's something i fixed

**Comment by litzvi** [comment]
Now it's working. it happened when the dropdown was empty before.
need to check later

**Comment by litzvi** [comment]
seems ok now
