### ISSUE TITLE
Percentage bold in reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#400]
please make percentage bold, makes it easier to see errors

**Comment by litzvi** [comment]
Also amount and unit should not be in 2 lines
e.g. 
440 UNIT(2,245.32 
KG)(4,950 LBS)(D1)

**Comment by mei309** [comment]
its 2 hard stuff and i will do later

**Comment by mei309** [comment]
> Also amount and unit should not be in 2 lines
> e.g.
> 440 UNIT(2,245.32
> KG)(4,950 LBS)(D1)

done

**Comment by mei309** [comment]
why in usedItem/s you dont give total amounts?

**Comment by litzvi** [comment]
in reports? where do you need it?

**Comment by mei309** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/58453503/113344124-44306600-9363-11eb-9c95-e551151f516d.png)
for example here

**Comment by mei309** [comment]
in the top we dont have a sum

**Comment by mei309** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/58453503/113344243-65915200-9363-11eb-8608-fdf6ec1e89ae.png)
and here

**Comment by litzvi** [comment]
ok fixed in next version

**Comment by mei309** [comment]
added to frontend problems
