### ISSUE TITLE
REPORTS NOT SHOWING IF I CHANGE THE PO WHILE STILL IN THE REPORTS PAGE

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#404]
it's showing summary correctly at first than when changing a po it shows only order
[localhost-1617097749858.log](https://github.com/litzvi/avc-beta/files/6228077/localhost-1617097749858.log)

**Comment by litzvi** [comment]
here's the dump of the cloud i took down yesterday, so you can also check in general.
[Dump_report_summary_not_working.zip](https://github.com/litzvi/avc-beta/files/6228108/Dump_report_summary_not_working.zip)

**Comment by mei309** [comment]
ok fixed

**Comment by litzvi** [comment]
ABE-10366 only showing order in reports->summary
it's in the cloud backup i sent you

**Comment by mei309** [comment]
ok fixed
