### ISSUE TITLE
loading report slow and moving to arrivals tab gets the browser stock

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#405]
This is in the loading
[localhost-1617114275720.log](https://github.com/litzvi/avc-beta/files/6229726/localhost-1617114275720.log)

**Comment by litzvi** [comment]
arrivals doesn't work after loading can't even press F12

**Comment by litzvi** [comment]
you need to choose shipping -> reports -> loading and then on the arrivals tab

**Comment by mei309** [comment]
i already fixed it in the morning
