### ISSUE TITLE
Can't use software 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#407]
Today, when using the software, I received this message, below![Screenshot 2021-04-01 095945.png](https://user-images.githubusercontent.com/76675352/113237681-7b563700-92d1-11eb-91cf-ab52cc281458.png)

**Comment by mei309** [comment]
it was an amazon update. i dont know why its doing it.

**Comment by mei309** [comment]
its working now after i forced the update to finish.
