### ISSUE TITLE
Shipping reports -> loading not working well

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#409]
[localhost-1617327425500.log](https://github.com/litzvi/avc-beta/files/6247204/localhost-1617327425500.log)
doesn't load through the tab.

also qc->roast checks report doesn't work from the menu

**Comment by mei309** [comment]
about the loading its working correct by me from the tab and menu. and the errors you sent me are internet connection problems, besides that theres no information there. i suggests we see in the new version.

**Comment by mei309** [comment]
qc roast isnt working at all. you giving "Checked by is mandatory" error. so i cannot see that the report dose not work

**Comment by mei309** [comment]
i added this **check.setCheckedBy("avc lab");**  in QcController line 47 but im not sure its the correct place to do it.

**Comment by mei309** [comment]
and also qc reports are working for me

**Comment by litzvi** [comment]
I'm running on localhost

**Comment by litzvi** [comment]
> about the loading its working correct by me from the tab and menu. and the errors you sent me are internet connection problems, besides that theres no information there. i suggests we see in the new version.

now it's ok by me (although much slower than the other reports).
I have information. let me send you a dump i took yesterday

**Comment by litzvi** [comment]
[Dump_mei.zip](https://github.com/litzvi/avc-beta/files/6249005/Dump_mei.zip)

**Comment by litzvi** [comment]
> i added this **check.setCheckedBy("avc lab");** in QcController line 47 but im not sure its the correct place to do it.

I think you need checked by, because that's how you compare with a standard.
Also because they might send to a lab to check etc, so I wouldn't change it.

Therefore, I think you're solution is ok.

**Comment by litzvi** [comment]
> [localhost-1617327425500.log](https://github.com/litzvi/avc-beta/files/6247204/localhost-1617327425500.log)
> doesn't load through the tab.
> 
> also qc->roast checks report doesn't work from the menu

Oh I know why it's happening to me..
When you are already in the page of raw checks/arrivals corispondingly, navigating through the menu to Roast chacks/loadings doesn't respond

**Comment by mei309** [comment]
> > [localhost-1617327425500.log](https://github.com/litzvi/avc-beta/files/6247204/localhost-1617327425500.log)
> > doesn't load through the tab.
> > 
> > also qc->roast checks report doesn't work from the menu
> 
> Oh I know why it's happening to me..
> When you are already in the page of raw checks/arrivals corispondingly, navigating through the menu to Roast chacks/loadings doesn't respond

i will try to solve it tonight. I didn't think we need that ability

**Comment by mei309** [comment]
ok done
