### ISSUE TITLE
Storage Transfer

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#41]
Storage Transfer from warehouse to raw station, they don't use the pallets as input to cleaning.
They actually do processes with parts of a pallet (e.g. 150 bags of 50..). 
Also the hopper scale is less accurate - ahron wants it for reference but they actually consider the cleaning station weights.
Need to leave the same form in a transfer, only add the weights as a type of separate sample.

**Comment by litzvi** [comment]
should add sampled weights for every processItem.
so we have sampled weights for pallats or hopper etc. 
So we don't force the basic storage unit to be in units they measure.

**Comment by litzvi** [comment]
See what i wrote. 
let me know if it's ok with you and i'll change it.

**Comment by litzvi** [comment]
Another thought..
storage transfer if keeping the same form should only be recorded as a change of location.
so need to think where to write the sample and how to avoid writing the same storage data twice.

**Comment by mei309** [comment]
i dont understand

**Comment by litzvi** [comment]
let me know when you'r up, we can discuss
