### ISSUE TITLE
General order details not showing management

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#411]

**Comment by mei309** [comment]
you probably arent listed as someone that has management for this process. because by me its showing in eli but not in me mode. so change it in mamagments->notification

**Comment by mei309** [comment]
and also you would not manage to approve something you were not listed on before. just on the new ones you will manage.

**Comment by litzvi** [comment]
I know all this. I'm the only one listed and it's still not showing.

**Comment by litzvi** [comment]
And I set myself as manager before making the order.

**Comment by mei309** [comment]
you need approval. by me its showing and working. so send me the dump if you have approval permission

**Comment by litzvi** [comment]
[Dump20210405_mei.zip](https://github.com/litzvi/avc-beta/files/6255962/Dump20210405_mei.zip)

use zvi 050282 for general order

**Comment by mei309** [comment]
with the dump and you it shows by me. dose it happen always or only sometimes?

**Comment by litzvi** [comment]
always

**Comment by mei309** [comment]
so I really have no clue what it can be.

**Comment by mei309** [comment]
there's something in f12 related to it?

**Comment by litzvi** [comment]
lol in the new version it's working
