### ISSUE TITLE
Not allowing to drop tables or database from workbench

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#413]
you can add another user to the database (say 'user_remote ' instead of 'user').

I think then you can run to block the 'user_remote ' from dropping tables with 
REVOKE drop ON \*.\* FROM 'user_remote'@'localhost';

and we will use user_remote to login from the workbench

**Comment by litzvi** [comment]
actually i think the host is % not localhost

**Comment by mei309** [comment]
im checking and i hope i will manage today. i will try also to see if i can add a test db for free. so we can try all stuff on it

**Comment by litzvi** [comment]
it might be good but it's not going to solve this problem. it was an accident and didn't happen because of a test. I was in the wrong page by mistake.
for that we need to have a more protective user.

**Comment by mei309** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/duplicate-master-user-mysql/
decide what permissions you want to give the new user and create it if you dont manage give me to do it after you decide what permissions i should give him.

**Comment by mei309** [comment]
you do it on mysql workbench and omit **mysql>** and master_username is **user**

**Comment by litzvi** [comment]
I created 'workbench_user', revoked delete and drop.
we should log in from the workbench with that (if we need we can always change to user)

**Comment by litzvi** [comment]
password is the same

**Comment by mei309** [comment]
ok done
