### ISSUE TITLE
Clean transfer with weighing(relocation) - count

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#414]
remember to change the dropdown to clean items.

Actually, it should probably be default to the same item (later maybe block change)

**Comment by mei309** [comment]
for now you requested in a different issue to give edit option.

**Comment by mei309** [comment]
and fixed

**Comment by litzvi** [comment]
> for now you requested in a different issue (370) to give edit option.

off course because they often choose wrong by mistake. (if we wouldn't let them choose wouldn't be a problem)
For now, you can still give the default the same item.

**Comment by mei309** [comment]
only for now its not worth building it. it has quite a few consequences and its not simple like the rest since we can have a few items

**Comment by litzvi** [comment]
> only for now its not worth building it. it has quite a few consequences and its not simple like the rest since we can have a few items

for that you can allow to choose of those few items

**Comment by mei309** [comment]
closing since its part of 370 issue
