### ISSUE TITLE
navigating with back and refresh

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#415]
Not for now, just my opinion as an enhancement.
It's very bad that navigation doesn't consider the last tab but the last menu choice.
It happened to me a few times that because of this wrong navigation i edited the wrong things.

**Comment by mei309** [comment]
it's not really under my control. it's chrome. if you use it as an app it doesn't have the arrows at all because of that reason

**Comment by litzvi** [comment]
ok. what can i do

**Comment by mei309** [comment]
maybe i will implement my own some day. because its meant to be an app and not really on chrome

**Comment by mei309** [comment]
and i added it to frontend issues therefor im closing here
