### ISSUE TITLE
Eli asked to show only 2 points after the decimal point

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#416]
They are getting confused because of the Vietnamese way of showing thousands.
So if it's easy to change only in the final report, all the rest I change it already (reports, details etc.)

**Comment by litzvi** [comment]
Only in final report

**Comment by mei309** [comment]
so why you dont do also in the final report? i can do everywhere (all showing without inputs) to be 2 very easily. but i need to understand why you did only part

**Comment by mei309** [comment]
im only showing what you give me. nothing more

**Comment by litzvi** [comment]
In final report you where doing it yourself. Why? I don't know but it isn't
bad.

**Comment by litzvi** [comment]
yes i was wrong. let me fix

**Comment by litzvi** [comment]
ok done
