### ISSUE TITLE
getting waste items in order.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#419]
eli asked for it that 1. qc hold 2. screen 3. floor.
so that means we need to do an order for it i think.

**Comment by mei309** [comment]
for now i can do it by me if you think its ok

**Comment by litzvi** [comment]
> for now i can do it by me if you think its ok

i'll see later, better if i do it, so it's more general

**Comment by mei309** [comment]
just a note. in the db it's in order but it doesn't return it that way

**Comment by litzvi** [comment]
I think I'm giving by name order. I can change it. But for a real solution
it should have an ordinal, so it can be controlled.

**Comment by litzvi** [comment]
It's used for many value entities. e.g. items that we want by alphabetical order.

so as a temporary solution you can add this to Controller.java before line 115
		WasteItemsholder.sort(new Comparator<BaseEntityDTO>() {
			@Override
			public int compare(BaseEntityDTO o1, BaseEntityDTO o2) {
				return Integer.compare(o1.getId(), o2.getId());
			}
		});

(btw you can decapitalize the variable)

**Comment by mei309** [comment]
> It's used for many value entities. e.g. items that we want by alphabetical order.
> 
> so as a temporary solution you can add this to Controller.java before line 115
> WasteItemsholder.sort(new Comparator() {
> @override
> public int compare(BaseEntityDTO o1, BaseEntityDTO o2) {
> return Integer.compare(o1.getId(), o2.getId());
> }
> });
> 
> (btw you can decapitalize the variable)

it dosent work for some reason

**Comment by mei309** [comment]
just so you know it needs to be like this.
new Comparator<BaseEntityDTO>() {
			@Override
			public int compare(BaseEntityDTO o1, BaseEntityDTO o2) {
				return Integer.compare(o1.getId(), o2.getId());
			}
		}

**Comment by litzvi** [comment]
It worked by me.

**Comment by mei309** [comment]
now i see that also by me it removed the important part so probably also by you (the bigger and smaller arrows)

**Comment by litzvi** [comment]
don't understand. I put exactly that code and it showed fine.

**Comment by litzvi** [comment]
> now i see that also by me it removed the important part so probably also by you (the bigger and smaller arrows or diamonds)

don't understand
