### ISSUE TITLE
Roasting hopper

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#42]
Roasting hopper po drop down doesn't show of clean product.
I cleaned in a few stages, the can't choose that po (when choosing item it works).
also for cleaning the po drop down doesn't show well

**Comment by mei309** [comment]
objectTableReader.findCashewInventoryPoCodes() dose not give right results.
objectTableReader.findInventoryPoCodes(new ItemCategory[]{item}); im using this for roasing hopper and cleaning

**Comment by litzvi** [comment]
i fixed the first one - objectTableReader.findCashewInventoryPoCodes() 
in objectTableReader.findInventoryPoCodes(new ItemCategory[]{item}) for hopper are you using CLEAN LOOKS LIKE USING RAW.
ANYWAY PLEASE CHECK AFTER VERSION 9

**Comment by mei309** [comment]
I WAS USING RAW SORRY
