### ISSUE TITLE
double storages

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#420]
using part of a useditem creates new processItems and then im getting back double storages.

**Comment by litzvi** [comment]
double storages?! do you mean it's in different used items? that's the way you did it. If you send it in a new used item, it will be another one.

**Comment by mei309** [comment]
it creats new process items

**Comment by litzvi** [comment]
where? i looked and didn't see

**Comment by mei309** [comment]
edit relocation after using some table storage only part

**Comment by litzvi** [comment]
so say in relocation

**Comment by litzvi** [comment]
please write a full description.
what to add what to edit etc.

**Comment by mei309** [comment]
it looks like its working now so i will open again if i see again
