### ISSUE TITLE
when General inventory is empty has an error 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#421]

**Comment by mei309** [comment]
unlike all tables you returning null instead of empty array

**Comment by mei309** [comment]
and has a error or just shows endlessly the spinner?

**Comment by litzvi** [comment]
Yes

**Comment by mei309** [comment]
so you know why you returning null?

**Comment by litzvi** [comment]
I'll check tomorrow

**Comment by litzvi** [comment]
ok fixed
