### ISSUE TITLE
relocation new wearhouse.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#423]
in the table we dont show it. we need to show it so please give it

**Comment by mei309** [comment]
i think also storageMoves dose not have

**Comment by litzvi** [comment]
you mean only in the table we show it?

**Comment by litzvi** [comment]
in the table i see you are showing both.
in the list you show only the new one. you have another one inside the storageMove.Storage, that's the old one and you are just not showing it.

**Comment by mei309** [comment]
I'm talking about the report

**Comment by litzvi** [comment]
Ok added newWarehouses

**Comment by litzvi** [comment]
btw, Relocation without weighing is a bad name, the point isn't that it's without counts but that it's just a normal transfer to another warehouse not cleaning station or roaster in.
maybe storage transfer and It should probably be with inventory.

**Comment by litzvi** [comment]
Also i renamed GENERAL_STORAGE to PRODUCT_STORAGE

**Comment by mei309** [comment]
> Also i renamed GENERAL_STORAGE to PRODUCT_STORAGE
> use this to change
> update production_lines set production_functionality = 'PRODUCT_STORAGE' where production_functionality = 'GENERAL_STORAGE' and id > 0;

done

**Comment by mei309** [comment]
> btw, Relocation without weighing is a bad name, the point isn't that it's without counts but that it's just a normal transfer to another warehouse not cleaning station or roaster in.
> maybe storage transfer and It should probably be with inventory.

ok done

**Comment by mei309** [comment]
and It should probably be with inventory. i a little debate that. its a relocation like the title

**Comment by litzvi** [comment]
> and It should probably be with inventory. i a little debate that. its a relocation like the title

they will be confused. it's just a simple move from warehouse to warehouse

**Comment by mei309** [comment]
ok done

**Comment by mei309** [comment]
> Ok added newWarehouses

i dont see it in the new version

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/114388466-e9e2a100-9bbd-11eb-97a0-45b1aaab2775.PNG">

**Comment by litzvi** [comment]
is this what you need? if so maybe it's our versions. I'll upload now

**Comment by mei309** [comment]
i didnt have the correct version. and you cannot put it in the process because they all have the same warehouse?

**Comment by litzvi** [comment]
Not necessarily they have the same, so no.

**Comment by mei309** [comment]
ok i put it in the place where we have the old one

**Comment by mei309** [comment]
just need to find a way to show in the details (its for me)

**Comment by mei309** [comment]
ok done
