### ISSUE TITLE
Cashew/general orders table -> All

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#425]
No need to show red for delivery date, only for open.
Same goes by Reports -> summary -> order

**Comment by mei309** [comment]
the summary can also be open

**Comment by mei309** [comment]
i should remove it totally from thhose tables or its good to have it while it wasent received ?

**Comment by litzvi** [comment]
Look at it. Everything is red even the ones received

**Comment by litzvi** [comment]
Yes the open ones Can be red everywhere

**Comment by mei309** [comment]
ok done.
