### ISSUE TITLE
Total difference - production reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#427]
you can't add percentages

**Comment by mei309** [comment]
i do it. whats the problem?

**Comment by litzvi** [comment]
you have 2 lines every one lost 50% so total they lost 100%??

**Comment by mei309** [comment]
im removing also id and also the storage id.

**Comment by litzvi** [comment]
??????????
I don't understand what it has to do here.

**Comment by mei309** [comment]
> ??????????
> I don't understand what it has to do here.

it was a mistake

**Comment by mei309** [comment]
i did it according to the equation `percantage/100 = amout percantage/x` and therefor i dont really show the correct total. because the numbers are rounded

**Comment by litzvi** [comment]
if you didn't understand until now, call me.

**Comment by litzvi** [comment]
Now you fixed it. why don't you say so instead of me explaining??

**Comment by mei309** [comment]
i wrote that i did it (sorry it wasn't clear that im talking on my new version) but i left it open because the numbers arent exactly correct because of the rounding. i just wanted you to know that

**Comment by litzvi** [comment]
ok

**Comment by litzvi** [comment]
<img width="1281" alt="Capture" src="https://user-images.githubusercontent.com/53637868/114971965-a7fc7800-9ea7-11eb-9814-5e08ffe101f4.PNG">

**Comment by litzvi** [comment]
total difference percentage can't just be added when one is zero

**Comment by mei309** [comment]
i think its a good idea to give like a totals that will be like this in one measure unit (dose not matter which) instead of the 3 that you giving now that i need to check the MU
{used: 5000, loss: 200}

**Comment by litzvi** [comment]
ok. in ProcessRow i give you
com.avc.mis.beta.dto.view.ProcessRow.getUniformTotals()
which has the fields
BigDecimal used;
BigDecimal produced;
BigDecimal count;

I don't think you need the loss

**Comment by mei309** [comment]
instead of giving 3 fields that i need to check which one is correct for the calculation each time its way better if you give used and loss. im trying to make my code flexible too therefor each time checking isnt good.

**Comment by litzvi** [comment]
ok. I added loss as well

**Comment by mei309** [comment]
ok done.
