### ISSUE TITLE
Hello error

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#428]
<img width="1280" alt="Capture1" src="https://user-images.githubusercontent.com/53637868/114381523-6755e380-9bb5-11eb-8e55-6e6b6115dc36.PNG">

**Comment by litzvi** [comment]
there where only 317 originally..

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/114382139-388c3d00-9bb6-11eb-84ae-058a6234ff1f.PNG">

**Comment by litzvi** [comment]
now i already have 567

**Comment by mei309** [comment]
im removing also id and also the storage id.

**Comment by mei309** [comment]
on edit storagemove you arent giving the correct number Available units.
case: use some in a different process then doing a new one with some and editing its showing the full amount.

**Comment by mei309** [comment]
and in a new one it needs to show all because they different warehouse. and in edit

**Comment by litzvi** [comment]
You are confusing things that come from different classes, go back to the
issue you didn't want to change a name and try to understand.

**Comment by mei309** [comment]
im not going back to there, and i dont care whos fault is it. number available units should be the right one. thats all

**Comment by litzvi** [comment]
> im not going back to there, and i dont care whos fault is it. number available units should be the right one. thats all

I don't care who's fault it is either. I care about the bugs it's going to cause.

**Comment by litzvi** [comment]
Ok i think it's fixed. Hibernate doesn't always act as expected
