### ISSUE TITLE
Roasting Hopper - details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#43]
after cleaning in a few stages, wanted to move all to hopper - i chose all from all cleaning of that po.
worked correctly, but details show in used items only the bags of one cleaning process.

**Comment by mei309** [comment]
in TransactionProcessDTO you always giving me only one

**Comment by mei309** [comment]
only one used

**Comment by litzvi** [comment]
I need to fix the sets to multiSet (appache.commons.collectiion4 - like SampleReceipt)

**Comment by litzvi** [comment]
fixed.
was a good one made me change the equals structure in the DTOs, hope now the code is more rebust.
