### ISSUE TITLE
reloaction edit using the other part of a bag

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#433]
core.js:6157 ERROR Error Code: 400
Message: Cannot delete or update a parent row: a foreign key constraint fails (`ebdb`.`used_items_base`, CONSTRAINT `FK2in4mo75ugomepk17c7asvrs0` FOREIGN KEY (`storage_id`) REFERENCES `storages_base` (`used_item_base_id`))

**Comment by mei309** [comment]
case:
1. use a part of a table bag
2. do edit and try using the other part too

**Comment by mei309** [comment]
and for some strange reason i can do roasting on that part even so it didnt join the reloaction therefore it dose not have the right functionality

**Comment by litzvi** [comment]
seems ok to me. check the new version

**Comment by mei309** [comment]
now it gives 
java.lang.IllegalArgumentException: Process used item amounts exceed amount in inventory
	at com.avc.mis.beta.dao.ProcessInfoDAO.editGeneralProcessEntity(ProcessInfoDAO.java:223) ~[classes/:na]
	at com.avc.mis.beta.dao.ProcessInfoDAO$$FastClassBySpringCGLIB$$b2f2b2b.invoke(<generated>) ~[classes/:na]

**Comment by litzvi** [comment]
It should happen when something is not available for use.
What's exactly the case? did you use those items in another process?

**Comment by mei309** [comment]
no

**Comment by mei309** [comment]
first solve the other problem then i will see if it still happens

**Comment by mei309** [comment]
its still happening.

> * use a part of a table bag
> * do edit and try using the other part too

do this

**Comment by litzvi** [comment]
ok fixed

**Comment by mei309** [comment]
ok done
