### ISSUE TITLE
Sometimes when a adding  a new relocation it calls edit

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#440]
maybe it's when i was previously in a relocation and went directly to add from the toolbar.

**Comment by litzvi** [comment]
[localhost-1618486697167.log](https://github.com/litzvi/avc-beta/files/6317613/localhost-1618486697167.log)

**Comment by litzvi** [comment]
it happened already a few times

**Comment by mei309** [comment]
i see. i fixed it and suddenly its went back to be without. really strange. leaving open for myself

**Comment by mei309** [comment]
ok fixed
