### ISSUE TITLE
upload new version - let's call it 3.0

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#443]
[Dump20210416_fixed_cloud.zip](https://github.com/litzvi/avc-beta/files/6325344/Dump20210416_fixed_cloud.zip)

**Comment by litzvi** [comment]
[Dump20210416_fixed_dinal_data.zip](https://github.com/litzvi/avc-beta/files/6325347/Dump20210416_fixed_dinal_data.zip)

**Comment by litzvi** [comment]
the first is if you just dump the whole database back.
the second if you want to run empty and then add the data.

**Comment by litzvi** [comment]
use my latest Version: 15.5

**Comment by mei309** [comment]
ok done
