### ISSUE TITLE
Can't receive all parts of the lot

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#451]
Lot no po- 15104 CSV, mix lot, software writing error, what we do wrong ![Screenshot 2021-04-22 115058.png](https://user-images.githubusercontent.com/76675352/115657972-0f13a400-a362-11eb-9245-e819d9a069ed.png)

**Comment by ELIPELET** [comment]
It's not a issue, I fixed already, so can close this issue.

**Comment by mei309** [comment]
ok
