### ISSUE TITLE
Duplicate Information / reports 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#453]
I have a case of writing a QC report twice by mistake, How can we delete the duplicate report? , and how can we protect from such things like this in the future?

**Comment by mei309** [comment]
@litzvi if we show the id it will be very easy to do it but do you think its correct to show it always?

**Comment by litzvi** [comment]
> I have a case of writing a QC report twice by mistake, How can we delete the duplicate report? , and how can we protect from such things like this in the future?

You can just cancel the redundant one.

Do we want block from double checks? you might want to recheck sometimes, say different people check.
In my opinion, it's not a big error because it's only a check and easy to spot because you will see double in all reports.
