### ISSUE TITLE
hangout message

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#455]
>you're message on hangout

good morning. I truly don't understand what you think is the cause of the slow response for the tables?

look on the times. it's crazy
cleaning is 1mb
roasting 1.2mb
packing is 2.1mb
it's a size of a photo

**Comment by litzvi** [comment]
<img width="1008" alt="Capture" src="https://user-images.githubusercontent.com/53637868/115979783-1df09580-a5b2-11eb-8876-c87b2b55ed5c.PNG">

**Comment by litzvi** [comment]
my times. and here is the full log

[d34djkpi615opt.cloudfront.net-1619321684999.log](https://github.com/litzvi/avc-beta/files/6371191/d34djkpi615opt.cloudfront.net-1619321684999.log)

**Comment by mei309** [comment]
I know mostly it's fast. but because it's a lot of information when the internet is slow it takes a lot of time.

**Comment by mei309** [comment]
like I wrote the information is more than a mb for the processes

**Comment by mei309** [comment]
and I do think we should give back only by date

**Comment by litzvi** [comment]
I don't argue, just don't understand why it's urgent

**Comment by mei309** [comment]
because we can make everything a lot faster for almost free and especially when there's bad network

**Comment by litzvi** [comment]
Currently, we are talking about roughly 3 month of data, that should be supported on a regular basis.
Therefore, I think it's good we are running it with this traffic load.

**Comment by mei309** [comment]
ok
