### ISSUE TITLE
General PO 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#456]
Hi guys, Please do the General PO created same as Cashew Po. Thanks

**Comment by litzvi** [comment]
@mei309 just add a code field to the general order. they have to set the code directly.
I think it's the easiest, although they won't be able to cancel and use again, it's less critical in general where we are always forcing an order.

**Comment by mei309** [comment]
adeded

**Comment by litzvi** [comment]
it appears in edit not in a new one - should be the opposite of course

**Comment by mei309** [comment]
you dont have my last version. look even on the cloud it exists and i didnt update it from Friday night.

**Comment by mei309** [comment]
and removed it from edit
