### ISSUE TITLE
Add Status in QC and container arrivals reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#459]
QC i just added now

**Comment by mei309** [comment]
ok added

**Comment by mei309** [comment]
i need a function to get arrivals by po code

**Comment by litzvi** [comment]
arrivals aren't really associated with a po code. You have the info in loading

**Comment by mei309** [comment]
for final summary and full po details

**Comment by litzvi** [comment]
I'm giving (or at least mean to) the information with the loading, so i don't really think it's necessary.
Let's leave it for now. until they ask...lol

**Comment by mei309** [comment]
ok
