### ISSUE TITLE
Edit production process

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#46]
can't choose more used items from the same po.
Should have the option to choose more from other processItems or even from the same one

**Comment by mei309** [comment]
WE SAID EDIT IS ONLY FOR REDUCE

**Comment by litzvi** [comment]
we can't add processed items?

**Comment by mei309** [comment]
thats what we said. because of reducing by you
i can do it so think about yours

**Comment by litzvi** [comment]
Do you remember what the problem was?

**Comment by mei309** [comment]
it was because if its used afterwards

**Comment by litzvi** [comment]
I don't see why there should be a problem from my end. Adding is easier than reducing, off course only if it's available in the inventory.
So I think we should try again
