### ISSUE TITLE
Inventory use 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#461]
- dropdown should only be for available general inventory items. (maybe same in production)
- inventory use should record and show (also in reports) remarks/description so they can know for what it was used or sent.

**Comment by mei309** [comment]
on point 2 i dont find a function to get only items by availability

**Comment by mei309** [comment]
on point 2 i need to think about it so only later. (because I need to somehow put it in the table)

**Comment by litzvi** [comment]
> on point 2 i need to think about it so only later. (because I need to somehow put it in the table)

it was @ELIPELET request

**Comment by litzvi** [comment]
> on point 1 i dont find a function to get only items by availability

i added a bunch in com.avc.mis.beta.service.ValueTablesReader from line 249

**Comment by mei309** [comment]
ok done

**Comment by mei309** [comment]
on point 2 to put it in the top level or on every line of used?

**Comment by mei309** [comment]
ok done
