### ISSUE TITLE
Toffee process for cashew

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#462]
toffee could be done on roasted products.

You should add the process to the db
INSERT INTO `ebdb`.`process_types` (`name`, `process_name`) VALUES ('Cashew Toffee', 'CASHEW_TOFFEE');

I also added TOFFEE in ProductionUse enum - you should add accordingly

**Comment by litzvi** [comment]
I don't think you should start doing it before uploading (Tuesday)

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
fix adding cashew items so they can choose toffee.
then set the dropdown items correctly in toffee process.
and choose pos with roasted items, if i'm not mistaken.

**Comment by mei309** [comment]
done.
