### ISSUE TITLE
Can't cancel finalized process

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#466]
I'm trying to cancel a finalized process, but you leave finalized chosen (gray) and you are trying to make it final again instead of cancelled.
I'm doing save, not reject. 
If we always need a manager to have Approval, why the save? otherwise the save should work without sending an approval/rejection.

**Comment by litzvi** [comment]
For example try cancelling VAT-45037 raw relocation

**Comment by mei309** [comment]
i had a mistake therefore i was trying to do final again. fixed it.

**Comment by mei309** [comment]
and even so finalaized stays gray we can still cancel
