### ISSUE TITLE
scale 3 in price

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#469]
in new general order. eli asked for it

**Comment by mei309** [comment]
so i think we should change also in cashew

**Comment by litzvi** [comment]
in Vietnam dong you aren't showing anything after the decimal point.
e.g se an order price to 1.5 vnd and look in the details.

**Comment by mei309** [comment]
> in Vietnam dong you aren't showing anything after the decimal point.
> e.g se an order price to 1.5 vnd and look in the details.

angular removes it because its not money. if its important i will do my own currency implementation

**Comment by litzvi** [comment]
now money is 3 decimal points.
Not easy to check because need to change it by you

**Comment by mei309** [comment]
by me its ready for 3 also on your version. i think the problem is the db

**Comment by litzvi** [comment]
yes need to rebuild

**Comment by mei309** [comment]
leave it open for me because I dont think its a good idea to change the currency of angular so i need to think about it

**Comment by mei309** [comment]
the database always stays with 2 even by rebuilding it

**Comment by litzvi** [comment]
in order item?

**Comment by litzvi** [comment]
ok fixed

**Comment by mei309** [comment]
its working but before you used to give null in case theres no price now you give 
unitPrice: {amount: 0, currency: null, value: null, filled: false}

**Comment by litzvi** [comment]
fixed.

**Comment by litzvi** [comment]
you can remove "nullable = false," from OrderItem.java line 82
but you need to rebuild the database

**Comment by mei309** [comment]
ok done
