### ISSUE TITLE
Field for empty bags

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#47]
used to reduce the estimate weights

**Comment by litzvi** [comment]
dear IM
when they weigh the pallets before cleaning they don't take into account the empty bags weight.
it's not neglectable (318*.2=~64kg), so we will add another field for the stoageTransfer(present it as part of item count) that is the total empty bags weight.
so i added a field: BigDecimal accessWeight in StoageTransfer.
please add it

**Comment by mei309** [comment]
i dont find a fielid that name

**Comment by litzvi** [comment]
StorageTransfer line 47
StorageTransferDTO line 39
anywhere else needed?

**Comment by mei309** [comment]
im not using storage transfer but anyway i dont see it

**Comment by litzvi** [comment]
the field accessWeight in PoProcessDTO.
set in StorageRelocationDTO and also StorageTransferDTO

**Comment by mei309** [comment]
for now im using but i will not once i finish with storagerelocation

**Comment by mei309** [comment]
WHY YOU DONT PUT IT WITH ITEMCOUNT??
why you want it in the process???

**Comment by litzvi** [comment]
because it's for all the itemCounts together

**Comment by mei309** [comment]
ok done

**Comment by litzvi** [comment]
sorry you're correct, I'll put it in itemCount tommorow

**Comment by litzvi** [comment]
Sorry correct, I'll change accessWeight to ItemCount tomorrow

**Comment by litzvi** [comment]
I removed BigDecimal accessWeight from PoProcess(for relocation and transfer) and added it to ItemCount class.
Change accordingly
Hope I didn't but anything

**Comment by mei309** [comment]
ok changed
