### ISSUE TITLE
multiple approvals for the same user.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#471]
in full details of po 14630 in loading it gives eli a few times (added a new dump from yesterday
[Dump20210504.zip](https://github.com/litzvi/avc-beta/files/6425005/Dump20210504.zip)
)

**Comment by litzvi** [comment]
I fixed it, but you still need to wrap the text

**Comment by mei309** [comment]
> I fixed it, but you still need to wrap the text

done and thats the reason i know it shows multiple times

**Comment by litzvi** [comment]
it was going on top of the other text, it should break a line

**Comment by mei309** [comment]
thats exactly what i did
