### ISSUE TITLE
Exporting to excel

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#473]
Can you make it export merged cells correctly?
like the table of po with a few processes

**Comment by mei309** [comment]
[mat-table-exporter (3).zip](https://github.com/litzvi/avc-beta/files/6425126/mat-table-exporter.3.zip)
it dose here so please give a table

**Comment by litzvi** [comment]
i mean if you can merge A2 and A3 like you do on the web

**Comment by litzvi** [comment]
total difference doesn't show correctly

**Comment by mei309** [comment]
you mean because it shows only on one line? or the numbers arent correct?

**Comment by litzvi** [comment]
if it's on one line it isn't correct

**Comment by litzvi** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



PO-15104 | CSV | DW CUT: 9,072 KG(20,000 LBS)(B) | DW CUT CLEAN: 9,057.94 KG(19,969 LBS)(B)QC HOLD: 3.18 KG(7 LBS)SCREEN: 5.9 KG(13 LBS) | -0.055 % (-4.99 KG) (-11 LBS) | Apr 29, 2021, 7:32:21 AM | FINAL | 0.19 % (21.85 KG) (48.18 LBS) |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
PO-15104 | CSV | WS/LP: 2,404 KG(5,299.82 LBS)(B) | WS/LP CLEAN: 2,424.04 KG(5,344 LBS)(B)QC HOLD: 3.18 KG(7 LBS)SCREEN: 3.63 KG(8 LBS) | 1.117 % (26.84 KG) (59.18 LBS) | Apr 29, 2021, 6:29:59 AM | FINAL |   |   |  



</body>

</html>

**Comment by litzvi** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



ABE-14799V | HOANG KHAI THINH | 34,877.1 LBS (1 LOT) | 70390 - WHOLE - RNS - 12/8.5oz | 700 UNIT (2,024.19 KG) (4,462.5 LBS) | FINAL PRODUCT | 01-Jan-00 | 08-Mar-21
-- | -- | -- | -- | -- | -- | -- | --
ABE-14799V | HOANG KHAI THINH | 34,877.1 LBS (1 LOT) | 70389 - WHOLE - RS - 12/8.5oz | 1,000 UNIT (2,891.7 KG) (6,375 LBS) | FINAL PRODUCT | 01-Jan-00 | 08-Mar-21
ABE-14799V | HOANG KHAI THINH | 34,877.1 LBS (1 LOT) | 59639 - WHOLE - R/S - 16/10oz | 1,188 UNIT (3,610.47 KG) (7,959.6 LBS) | FINAL PRODUCT | 01-Jan-00 | 09-Mar-21
ABE-14799V | HOANG KHAI THINH | 34,877.1 LBS (1 LOT) | 84728 - WHOLE - RS - 12/16oz | 1,340 UNIT (7,293.89 KG) (16,080 LBS) | FINAL PRODUCT | 01-Jan-00 | 09-Mar-21



</body>

</html>

**Comment by litzvi** [comment]
this is from inventory, 3rd column isn't correct

**Comment by mei309** [comment]
for now i did that all the group ones should be empty besides the first line. doing merge for the rows isn't supported by the library im using so i will need to implement it myself or use a heavy library that has that functionality.
and i also need to remove the search somehow

**Comment by litzvi** [comment]
so if it's easy just remove the sum columns, the ones that are wrong

**Comment by mei309** [comment]
i did something else i think its better just look on the new version when i upload. if we sign a contract i will fix it

**Comment by litzvi** [comment]
ok

**Comment by mei309** [comment]
need to add also the totals of the bottom

**Comment by mei309** [comment]
i passed it to front end problems
