### ISSUE TITLE
edit general po supplier

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#475]
and contract type.
in cashew it's managed separately.

**Comment by mei309** [comment]
maybe we should do it the same as cashew

**Comment by litzvi** [comment]
Yes. We can

**Comment by mei309** [comment]
lets do it. its also good for uniform web

**Comment by mei309** [comment]
you have this function findAllPoCodes in ObjectTablesReader now it gives only cashew and we need one for general too

**Comment by mei309** [comment]
and i hope get add and edit poCode all work for general too

**Comment by mei309** [comment]
and also findFreePoCodes we need one for general and one for cashew

**Comment by mei309** [comment]
its ready i just need the function to make sure

**Comment by litzvi** [comment]
> findAllPoCodes

findAllGeneralPoCodes

**Comment by litzvi** [comment]
> and i hope get add and edit poCode all work for general too

as long as you send PoCode or GeneralPoCode for cashew and general respectively.

**Comment by litzvi** [comment]
> findFreePoCodes

findFreeGeneralPoCodes

**Comment by mei309** [comment]
working meanwhile only by me
