### ISSUE TITLE
relocation in summary

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#476]
@ELIPELET asked to revers the order , so you can do something like this

	    List<ProcessRow> relocation = warehouseManagement.getStorageRelocationsByPoCode(poCode, null);
	    Collections.reverse(relocation);
	    finalProcesses.put("relocation", relocation);

**Comment by mei309** [comment]
ok done

**Comment by litzvi** [comment]
maybe it's better to just divide them to 2.
So call with RAW_STATION and ROASTER_IN and place them before cleaning and roasting respectively.

**Comment by litzvi** [comment]
Yes of course

**Comment by mei309** [comment]
ok put it back
