### ISSUE TITLE
total for shipping

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#477]
eli requested total of all used items in loading so they see how much was uploaded. is it easy to add by you? if easy add if not i will do it by me

**Comment by litzvi** [comment]
I added totalWeight for all TransactionProcessDTO.
Pay attention it's only for weights, so not suitable for inventory use for example

**Comment by mei309** [comment]
> I added totalWeight for all TransactionProcessDTO.
> Pay attention it's only for weights, so not suitable for inventory use for example

so will you give something or null in that case?

**Comment by litzvi** [comment]
Null

**Comment by mei309** [comment]
done
