### ISSUE TITLE
Raw relocations PO-14391

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#478]
i just open for edit and it's giving an error before even sending

**Comment by mei309** [comment]
you mean on your local machine?

**Comment by litzvi** [comment]
no. on the cloud

**Comment by mei309** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/58453503/117117159-cb895300-adc1-11eb-8188-dbded1c4f2db.png)

**Comment by mei309** [comment]
please send me the f12 when it happens

**Comment by litzvi** [comment]
press edit

**Comment by litzvi** [comment]
[d34djkpi615opt.cloudfront.net-1620204770169.log](https://github.com/litzvi/avc-beta/files/6425973/d34djkpi615opt.cloudfront.net-1620204770169.log)

**Comment by mei309** [comment]
sorry missed the edit

**Comment by mei309** [comment]
its printing it here but im not managing to understand why

ProcessInfoDAO.getProcessDescendants(ProcessInfoDAO.java:392)

**Comment by mei309** [comment]
its when i call getAvailableInventory

**Comment by mei309** [comment]
and its also on local machine

**Comment by litzvi** [comment]
yes i know. forgot you call it

**Comment by litzvi** [comment]
ok fixed
