### ISSUE TITLE
mixing packed and bulk items

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#479]
it will be very hard to change it once we do therefor we should do it asap. they have a lot of packed items in bulk items and especially in general.
by me its ready to add so whenever its ready by you let me know

**Comment by litzvi** [comment]
do what? can you explain the problem? why are they putting packed as bulk?

**Comment by mei309** [comment]
they mixing because they didnt understand the meaning. but in general its because you told them to put bolk since they use by weight and not by number of units

**Comment by litzvi** [comment]
I only told them not to use unit amount in the receipt.

**Comment by mei309** [comment]
its not trying to blame you. the point is what they doing

**Comment by litzvi** [comment]
OK. So tell them not to do.

**Comment by litzvi** [comment]
Don't understand what you want to do about it?

**Comment by mei309** [comment]
i talked to him. hope it helped
