### ISSUE TITLE
Cashew Inventory date

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#48]
should have the production date otherwise dividing same po items of different processes makes no sense.

**Comment by mei309** [comment]
I DONT UNDERSTAND

**Comment by litzvi** [comment]
in cashew inventory: show the date of it was produced for every amount.

**Comment by mei309** [comment]
you only giving me receiptDate

**Comment by litzvi** [comment]
OK. I'll chack later. But I think I'm giving you receipt date because they want it too

**Comment by litzvi** [comment]
from version 2.0 you will have 
processDate and receiptDate.
I think you should display them both for now (only date, no need time)

**Comment by mei309** [comment]
ok solved.
