### ISSUE TITLE
load  /qc/ waste 50lbs

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#482]

**Comment by litzvi** [comment]
@mei309 as you can see in the export report, they have QC and C items (which are bad quality).
I think it should be separated from the waste, because it loaded to the container.
So I suggest, we they fill it in separately than waste and choose from QC items. So we will need:

1.  table for adding/editing qc items (it's a cashew item)
2. section in production for adding qc (before or after waste)
3. let them load it to the container

The problem is I'm not sure where they pack it, so another suggestion instead of section 2:

Leave qc hold in waste as it is
2. Let them pack qc in a separate form where they will choose from waste and put it in qc items

**Comment by mei309** [comment]
i think we dont need new items because its the same ones, we just need some sign in the shipping that will be from the process of packing qc and we can add a sign to bad quality too

**Comment by mei309** [comment]
it can be a part of the packing process

**Comment by litzvi** [comment]
> i think we dont need new items because its the same ones, we just need some sign in the shipping that will be from the process of packing qc and we can add a sign to bad quality too

then how will I exclude it or separate it in all inventory queries etc?
It's neater if it's a different item type, same way we handle waste, general etc.

**Comment by mei309** [comment]
thoses are actually different items. this is the same ones. i really dont mind doing it but its really copying all the packed items.

**Comment by mei309** [comment]
and what about the C items? its together with qc?

**Comment by mei309** [comment]
> > i think we dont need new items because its the same ones, we just need some sign in the shipping that will be from the process of packing qc and we can add a sign to bad quality too
> 
> then how will I exclude it or separate it in all inventory queries etc?
> It's neater if it's a different item type, same way we handle waste, general etc.

and i think that if a process row will have a sign if its qc or c or other it will be easy to filter them

**Comment by litzvi** [comment]
> thoses are actually different items. this is the same ones. i really dont mind doing it but its really copying all the packed items. if you sure its a better way and solves also c items i will do it.

don't copy. let them add the stuff they want. Actually it's different items (it's obviously a different quality), they just choose to name it similarly. 
About C, it's the same idea, we can add ItemGroup 'C' and they can choose to add items under this category.

**Comment by litzvi** [comment]
> and what about the C items? its together with qc?

look at previous reply

**Comment by mei309** [comment]
we need some way to differ between packing and qc packing for getting the production report

**Comment by mei309** [comment]
you have a way?

**Comment by mei309** [comment]
besids that its ready

**Comment by litzvi** [comment]
> we need some way to differ between packing and qc packing for getting the production report

off course, I'll just add a process name BAD_QUALITY_PACKING.
to add to db run (I'll do on the cloud)
INSERT INTO `process_types` (`name`, `process_name`) VALUES ('Bad Quality Packing', 'BAD_QUALITY_PACKING');

**Comment by mei309** [comment]
ok done

**Comment by litzvi** [comment]
the dropdown for qc packing is for waste items. otherwise, the way you decided to do it we can never get qc items.
and check it this time.

**Comment by mei309** [comment]
done and checked

**Comment by litzvi** [comment]
Since qc packing is in nature adding from many pos to pack, the current packing design isn't suitable.
Now they need to choose the pos in advance (can't edit and add po -should probably be changed in packing too).

I suggest you let them choose freely like in loading or perhaps even show all waste inventory always or by item like in ingredients.

**Comment by litzvi** [comment]
Also in loading adding qc should be separately , I think it would be clearer.

**Comment by litzvi** [comment]
> Since qc packing is in nature adding from many pos to pack, the current packing design isn't suitable.
> Now they need to choose the pos in advance (can't edit and add po -should probably be changed in packing too).
> 
> I suggest you let them choose freely like in loading or perhaps even show all waste inventory always or by item like in ingredients.

actually i'm not sure they pack qc of different lots together.
it might be only one lot

**Comment by mei309** [comment]
its definitely enough for now

**Comment by litzvi** [comment]
still,  what's the reason we don't allow in edit to add other pos? why not do it like loading for more flexibility?
Now they need to cancel the process if they mixed up pos

**Comment by mei309** [comment]
because its a big change by me

**Comment by mei309** [comment]
qc pack i left the same but in packing changed so they dont need to cancel and redo. it looks ok for me.
