### ISSUE TITLE
Material Inventory by time 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#483]
I added 
com.avc.mis.beta.service.report.InventoryReports.getReceiptInventoryRows(ItemGroup, ProductionUse[], OffsetDateTime, OffsetDateTime)
So you can show the material report they want. So you should use:

inventoryReports.getReceiptInventoryRows(ItemGroup.PRODUCT, new ProductionUse[] {ProductionUse.RAW_KERNEL}, start,end);

say you want to show a month, so start will be the beginning of the 1st day and end the beginning of the 1st day of the next month. p.a. Since we are using an offset date time it needs to have a time zone - probably wrong design in the first place.

**Comment by litzvi** [comment]
![Uploading IMG_20210520_152230.jpg…]()

**Comment by litzvi** [comment]
![IMG_20210520_152230](https://user-images.githubusercontent.com/53637868/118947058-2bb2f400-b981-11eb-9259-4f99d7299364.jpg)

**Comment by mei309** [comment]
but I really don't understand the meaning of a  month of inventory

**Comment by mei309** [comment]
what's the meaning of a month of inventory? 
is it recipient of the month?

**Comment by litzvi** [comment]
I'll find out with Eli when i can reach him.

**Comment by litzvi** [comment]
At the moment just use Vietnamese time for everyone.

**Comment by litzvi** [comment]
Eli was wrong, there is no date. But you could use the end date, because he get's it every morning and it doesn't include stuff that came that morning, so leave that option.

**Comment by litzvi** [comment]
Raw Inventory is a good name for it.

**Comment by litzvi** [comment]
I changed the recordedTime to LocalDate, because it makes everything easier. They can use the easy date calendar, time is not cluttering reports and recorded date is not ambiguous. 
As much as i can see it's working, just displaying 12am everywhere.

**Comment by mei309** [comment]
> I changed the recordedTime to LocalDate, because it makes everything easier. They can use the easy date calendar, time is not cluttering reports and recorded date is not ambiguous.
> As much as i can see it's working, just displaying 12am everywhere.

we need the time in most places

**Comment by mei309** [comment]
and i can remove the time in reports wherever we want to

**Comment by litzvi** [comment]
So I'll change it to LocalDateTime or we can add a time separately later?

**Comment by mei309** [comment]
local date time should be good. what you had before?

**Comment by mei309** [comment]
but some stuff would need zones. so I really don't see why you want to change it. also processes would need a time zone in the end of the day if not it will be very inconsistent

**Comment by mei309** [comment]
in my opinion change it back and in search we do according to the begging of the date with the time zone. thats what google dose (according to what i understand)

**Comment by litzvi** [comment]
>local date time should be good. what you had before?

offset date time (has a zone)

**Comment by litzvi** [comment]
> but some stuff would need zones. so I really don't see why you want to change it. also processes would need a time zone in the end of the day if not it will be very inconsistent

- Think of the data as a recording - like they write in excel.
- the zone can cause lot's of inconsistencies in showing reports that are a function of time.
- Don't forget i do automatically keep createdDate and modifiedDate besides for the recorded time.
- I can add the zone in a separate field if it's needed.

**Comment by litzvi** [comment]
> in my opinion change it back and in search we do according to the begging of the date with the time zone. thats what google dose (according to what i understand)

I'll change it to local date time

**Comment by mei309** [comment]
i still dont think its correct. if someone will add something from the us it will be in a really wrong date line

**Comment by litzvi** [comment]
I also changed to LocalDateTime pointOfTime, so it will give the inventory at the given time.
you can get from that the end of day/month/year report and also build corresponding reports of changes in inventory in that period - added/removed/changed

**Comment by litzvi** [comment]
> i still dont think its correct. if someone will add something from the us it will be in a really wrong date line

they choose the date to record. think as if they are writing in an excel from usa.
anyway, for now there are more chances they will use reports than record data.
as i said we can add zone separately later.

**Comment by mei309** [comment]
i think its a big mistake. later we will need to do a big change for no reason

**Comment by mei309** [comment]
ok done. look and review.
 i didnt implement yet the search by currency.

**Comment by litzvi** [comment]
Nothing is working for me to check

[localhost-1622085625764.log](https://github.com/litzvi/avc-beta/files/6550876/localhost-1622085625764.log)

**Comment by litzvi** [comment]
looks good, small comments:

1. why don't you show currency column?
2. add thousands comma for LBS
3. try to give there names. e.g. material instead of item description
4. keep their column order in these reports

**Comment by mei309** [comment]
1. its redundant information. im showing it with the price. i will add later a search by currency 
2. done
3. material i changed but location is a little mixing for example storages vs the multi options they have (warehouses location and storage) so we should stick to one in my opinion.
4. i just changed the pos with items because supplier and po are connected.

if they really want the crazy naming mismatch and the crazy order i will change it but i do think its better this way because its more consistent and all ui and ux papers i read say to keep on that in all price

**Comment by litzvi** [comment]
> its redundant information. im showing it with the price. i will add later a search by currency

it's different (it's about the type of contract, not price)

**Comment by litzvi** [comment]
> if they really want the crazy naming mismatch and the crazy order i will change it but i do think its better this way because its more consistent and all ui and ux papers i read say to keep on that in all price

no mismatch, just present it to them the way they are use to

**Comment by mei309** [comment]
> > its redundant information. im showing it with the price. i will add later a search by currency
> 
> it's different (it's about the type of contract, not price)

ok done

**Comment by mei309** [comment]
> > if they really want the crazy naming mismatch and the crazy order i will change it but i do think its better this way because its more consistent and all ui and ux papers i read say to keep on that in all price
> 
> no mismatch, just present it to them the way they are use to

i will chang po with item

**Comment by litzvi** [comment]
looks good. besides for fitting in screen.
defects we can add later

**Comment by litzvi** [comment]
[דוחות מלאי קשיו AVC_דף_1.pdf](https://github.com/litzvi/avc-beta/files/6674629/AVC_._1.pdf)
[דוחות מלאי קשיו AVC_דף_2.pdf](https://github.com/litzvi/avc-beta/files/6674630/AVC_._2.pdf)

**Comment by litzvi** [comment]
you can see the full report.
They have the total in lb for all in the warehouses, another sum for the ones that where moved for production and the sum of both.

I added productionFunctionality so you can distinguish them. I think  ProductionFunctionality = RAW_STATION is for what they call B and anything else (now they are typically null) is the rest.

**Comment by litzvi** [comment]
>email from Eli + examples

הי צבי.

הוספתי לך כאן עוד 3 דוחות שלמעשה הם חלק מהדוח מלאי היומי, אלא שכאן יש פירוט נוסף שאהרן רוצה לדעת ולכן זה מגיע בדפים נפרדים כי הגברת מה מה)(Whatwhat בלע"ז) מוציאה כל דבר בנפרד מהאקסאל.

אז ניכנס לפרטים של הדוחות.
כמו שאתה רואה,יש חלוקה ברורה בין LY, ABE, VIETNUTS.
חלוקה נוספת, USD/VND
חלוקה נוספת, WHOLE/WSLP

כאשר בעצם כבר דיברנו על כל הפילטרים הללו שאמורים להיות בתוכנה ונוכל לקבל את אותו המידע  מהתוכנה.

[דוחות מלאי קשיו AVC_דף_4.pdf](https://github.com/litzvi/avc-beta/files/6675751/AVC_._4.pdf)
[דוחות מלאי קשיו AVC_דף_5.pdf](https://github.com/litzvi/avc-beta/files/6675752/AVC_._5.pdf)

[דוחות מלאי קשיו AVC_דף_6.pdf](https://github.com/litzvi/avc-beta/files/6675749/AVC_._6.pdf)

**Comment by litzvi** [comment]
About the whole/wslp it's probably not for this report. I asked him.

**Comment by mei309** [comment]
we just need the ly abe vietnuts

**Comment by litzvi** [comment]
> we just need the ly abe vietnuts

so I'll add a field in PoCode

**Comment by litzvi** [comment]
I added a field productCompany for PoCode, So you should add it in add/edit cashew po code (same as you do in container arrival).
I also give you the name in this ReceiptInventoryRow (this report).

later I can add to more reports if needed and perhaps also filter pos in loading according to the container arrival productCompany.

**Comment by mei309** [comment]
> I added a field productCompany for PoCode, So you should add it in add/edit cashew po code (same as you do in container arrival).
> I also give you the name in this ReceiptInventoryRow (this report).
> 
> later I can add to more reports if needed and perhaps also filter pos in loading according to the container arrival productCompany.

the same one??? SupplyGroup.SHIPPED_PRODUCT);???

**Comment by litzvi** [comment]
Yes those are the options

**Comment by mei309** [comment]
done.
