### ISSUE TITLE
Finished product inventory report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#485]
![IMG_20210520_212430](https://user-images.githubusercontent.com/53637868/119090255-9887c600-ba35-11eb-973d-c9dda27f28c1.jpg)

**Comment by litzvi** [comment]
It's a report for all product that are roasted and after.
com.avc.mis.beta.service.report.InventoryReports.getFinishedProductInventoryRows(ItemGroup, ProductionUse[], LocalDateTime)
you should probably use it like this: 
inventoryReports.getFinishedProductInventoryRows(ItemGroup.PRODUCT, 
					new ProductionUse[] {ProductionUse.PACKED, ProductionUse.ROAST, ProductionUse.ROAST, ProductionUse.TOFFEE}, 
					LocalDateTime);

**Comment by litzvi** [comment]
I think the date is receipt date but we need to double check. anyway I gave both.

**Comment by mei309** [comment]
done but look because i think we need to make it nested. this way its very strange

**Comment by litzvi** [comment]
same as the others.

**Comment by litzvi** [comment]
> done but look because i think we need to make it nested. this way its very strange

I was probably wrong and need to do different pos separate (besides for qc)

**Comment by litzvi** [comment]
more comments:

1. where is the box column?
2. dates without time please.
3. add thousands comma for LBS
4. try to give there names. e.g. product instead of item description
5. keep their column order in these reports

**Comment by mei309** [comment]
done.
but i just think we dont need the total amount column and we need unit weight. thats what they have in the report

**Comment by litzvi** [comment]
> done.
> but i just think we dont need the total amount column and we need unit weight. thats what they have in the report

you don't need to use total amount.
She writes WEIGHT/LB because she does the calculation in excel.

I added a method getBoxWeight(), so you can display the box weight

**Comment by mei309** [comment]
ok. and we dont need boxweight we have already bagSize

**Comment by litzvi** [comment]
> ok. and we dont need boxweight we have already bagSize

NO. they are different
bagsize will give a single bag in case it's bagged items. what they have is the box

**Comment by mei309** [comment]
ok done

**Comment by litzvi** [comment]
you are not showing 
Box quantity and box weight

**Comment by litzvi** [comment]
This is data only backup of what i'm using
[Dump20210531.zip](https://github.com/litzvi/avc-beta/files/6567545/Dump20210531.zip)

**Comment by mei309** [comment]
Box quantity im not getting it
box weight i fixed

**Comment by litzvi** [comment]
you are "boxes"

**Comment by mei309** [comment]
ok done
