### ISSUE TITLE
Restructuring Item 2

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#487]
![items](https://user-images.githubusercontent.com/53637868/119227551-ac682080-bb38-11eb-90d3-807c14571394.gif)

**Comment by litzvi** [comment]
There are no classes PackedItem and BulkItem
Instead All Cashew items are CashewItem class and the rest just Item.
As you can see the Cashew has grade(they call type), salt level etc.
In Item I also added a code(the codes they have for bags and general inventory) and brand(e.g. NICE, IMPERIAL).

**Comment by litzvi** [comment]
In order to fix the cloud data you can run 

update items set dtype='cashew' where (item_group='PRODUCT' or item_group='QC') and id>=0;
update items set dtype='abstract' where (item_group='GENERAL' or item_group='WASTE') and id>=0;
update items set measure_unit = 'NONE' where default_measure_unit <> 'UNIT' and id>=0;

**Comment by litzvi** [comment]
Still show the items in the same breakdown, the only difference is that for Cashew you create CashewItem class.
I know if something is packed by the unit.measureUnit of the item.
I checked the cloud data with the changes (after some temporary changes to controller) and it seems to work fine.

**Comment by litzvi** [comment]
Here are the changes I made in the controller, just so you get the picture.

ManagementController
lines 216-220
`		if(setupTable.endsWith("packed")) {
			return refeDao.getItems(itemGroup, null, PackageType.PACKED);
		} else {
			return refeDao.getItems(itemGroup, null, PackageType.BULK);
		}
`
lines 234-241
`		if(setupTable.endsWith("packed")) {
			Item packed = mapper.readValue(newOne.toString(), Item.class);
			packed.setItemGroup(itemGroup);
			refeDaoWrite.addItem(packed);
		} else {
			Item packed = mapper.readValue(newOne.toString(), Item.class);
			packed.setItemGroup(itemGroup);
			refeDaoWrite.addItem(packed);
		}
`
301-316
`		if(setupTable.startsWith("C")) {
			itemGroup = ItemGroup.PRODUCT;
			CashewItem cashewItem = mapper.readValue(editOne.toString(), CashewItem.class);
			cashewItem.setItemGroup(itemGroup);
			return refeDaoWrite.edit(cashewItem);		
		} else if(setupTable.startsWith("G")) {
			itemGroup = ItemGroup.GENERAL;
		} else {
			itemGroup = ItemGroup.WASTE;
		}
		Item item = mapper.readValue(editOne.toString(), Item.class);
		item.setItemGroup(itemGroup);
		return refeDaoWrite.edit(item);
`
327-329
`			refeDaoWrite.remove(Item.class, deleteOne.get("id").asInt());
		} else {
			refeDaoWrite.remove(Item.class, deleteOne.get("id").asInt());
`
ReportsController
`	@RequestMapping("/getCashewInventoryPacked")
	public List<ItemInventoryRow> getCashewInventoryPacked() {
		List<ItemInventoryRow> allInventoryItem = inventoryReports.getInventoryTableByItem(ItemGroup.PRODUCT);
		Predicate<ItemInventoryRow> byClass = row -> row.getItem().getUnit().getMeasureUnit() != MeasureUnit.NONE;
		List<ItemInventoryRow> result3 = allInventoryItem.stream().filter(byClass)
                .collect(Collectors.toList());
		return result3;
	}
	
	@RequestMapping("/getCashewInventoryBullk")
	public List<ItemInventoryRow> getCashewInventoryBullk() {
		List<ItemInventoryRow> allInventoryItem = inventoryReports.getInventoryTableByItem(ItemGroup.PRODUCT);
		Predicate<ItemInventoryRow> byClass = row -> row.getItem().getUnit().getMeasureUnit() != MeasureUnit.NONE;
		List<ItemInventoryRow> result3 = allInventoryItem.stream().filter(byClass)
                .collect(Collectors.toList());
		return result3;
	}
`

**Comment by litzvi** [comment]
Version: 17.1

**Comment by litzvi** [comment]
Off course you need to adjust the changes, so for cashew you add and edit CashewItem class

**Comment by mei309** [comment]
i did it and hope it dosent have consequences that will make us work a long time

**Comment by litzvi** [comment]
pray hard

**Comment by litzvi** [comment]
Don't know if I wrote, but you have a method for fetching cashew items with CashewGrade as well, if we need for filtering drop downs. (we can still leave the option for others, same as you did for all pos)
com.avc.mis.beta.service.ValueTablesReader.getCashewItems(ItemGroup, ProductionUse, CashewGrade, PackageType, int)

**Comment by mei309** [comment]
ok done but i didnt remember what fields to add for the items by me

**Comment by mei309** [comment]
i didnt find the function to get the full cashew items so i can show it in the table

**Comment by mei309** [comment]
i will do tomorrow the full item change in the managment add and edit

**Comment by litzvi** [comment]
> i didnt find the function to get the full cashew items so i can show it in the table

com.avc.mis.beta.service.ValueTablesReader.getCashewItems(ItemGroup, ProductionUse, CashewGrade, PackageType)

**Comment by mei309** [comment]
ready in next version

**Comment by litzvi** [comment]
You aren't getting cashew items, therefore not working

**Comment by mei309** [comment]
by mistake i changed it

**Comment by mei309** [comment]
its working now

**Comment by litzvi** [comment]
still missing some fields in Cashew Items

**Comment by mei309** [comment]
the fields roast and toffee are there in prudoction use

**Comment by litzvi** [comment]
same question as issue 489

CashewItem has these boolean fields - It's not productionUse. It's for classifying in the reports if it's roasted or toffee.
e.g. a packed item can be packed but it's roasted and toffee.

**Comment by mei309** [comment]
ok added
