### ISSUE TITLE
Bagged Inventory items

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#488]
![IMG_20210524_194037](https://user-images.githubusercontent.com/53637868/119349246-22e75880-bcc8-11eb-9e66-70c24aef1677.jpg)

**Comment by litzvi** [comment]
com.avc.mis.beta.service.report.InventoryReports.getCashewBaggedInventoryRows(ItemGroup, ProductionUse[], LocalDateTime)

of course they will need to fill the cashew info for cashew items for it to show correctly.

I'll update the drive with insert drop downs file with full items

**Comment by mei309** [comment]
done

**Comment by mei309** [comment]
done see and review

**Comment by litzvi** [comment]
nothing to review, doesn't work. going round and round

**Comment by litzvi** [comment]
1. add thousand commas 
2. remove grade column
3. I don't see the code
4. use field whole to determine if it's WHOLE/H&P (i know it's confusing, but in bags they only have these 2 options).
5. CALL WITH ProductionUse PACKED ONLY

**Comment by mei309** [comment]
4. we have type that it says h&p or whole and im showing it

all the rest done

**Comment by litzvi** [comment]
4. yes correct
5. this one not. look at the picture, it's only the small bags

**Comment by litzvi** [comment]
also roasted is the finished product report

**Comment by litzvi** [comment]
Also, as you can see in the scan, there is a total line and then total of whole and h&p seperatly
It's important for them

**Comment by mei309** [comment]
is it ok if i group it by h&p and whole? it will help with the totals

**Comment by litzvi** [comment]
it's in order by brands. so don't change that.

**Comment by mei309** [comment]
ok done

**Comment by litzvi** [comment]
It's good. 
add totals of bags and boxes if you don't mind.

**Comment by mei309** [comment]
im thinking so it will take time

**Comment by mei309** [comment]
done
