### ISSUE TITLE
date/time range of reports - Added overloaded methods 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#490]
for production

com.avc.mis.beta.service.report.ProductionProcessReports.getProductionProcessesByType(ProcessName processName, LocalDateTime startTime, LocalDateTime endTime)
com.avc.mis.beta.service.report.ProductionProcessReports.getProductionProcessesByTypeAndPoCode(ProcessName processName, Integer poCodeId,  LocalDateTime startTime, LocalDateTime endTime)

**Comment by litzvi** [comment]
In com.avc.mis.beta.service.report.StorageRelocationReports you have methods for relocation

**Comment by litzvi** [comment]
In com.avc.mis.beta.service.report.InventoryUseReports for inventory use

**Comment by litzvi** [comment]
By the way, one of the parameters can be null.
so if end date is null it means no restriction on end date, same for start date.

e.g. say if you want to show from last 3 month, just need to set start date. if you want to show a report at a point of time, you can leave start null and set end date

**Comment by litzvi** [comment]
Version: 17.4
 * issue 490

**Comment by litzvi** [comment]
In com.avc.mis.beta.service.report.ContainerArrivalReports for arrivals

**Comment by litzvi** [comment]
getInventoryTableByItem and getInventoryTableByPo aslo have overloads with point of time in
com.avc.mis.beta.service.report.InventoryReports

**Comment by litzvi** [comment]
In com.avc.mis.beta.service.report.LoadingReports for loadings

**Comment by litzvi** [comment]
In com.avc.mis.beta.service.report.OrderReports for orders

**Comment by litzvi** [comment]
com.avc.mis.beta.service.report.QualityCheckReports for qc

**Comment by litzvi** [comment]
com.avc.mis.beta.service.report.ReceiptReports for receipts

**Comment by mei309** [comment]
will change all the reports after i finish the other stuff.

**Comment by mei309** [comment]
is there a good reason that we using also time?? its only causing trouble in my opinion.

**Comment by litzvi** [comment]
- You asked for it a while ago 
- Because it becomes heavy to process and send as the amount of transactions grow
- They aren't usually working with old data

**Comment by mei309** [comment]
sorry for the misunderstanding question. why you using in this date and time and not only date?? the hour and minutes is useless here

**Comment by litzvi** [comment]
Because we are recording the time with the date, so I'm comparing to that. 
Also  It's free.

**Comment by mei309** [comment]
ok looks good. 2 questions 
1) what about massages and tasks? there its really important 
2) i think it needs to be start<=date<end and not start<=date<=end

**Comment by litzvi** [comment]
2. not a biggie it's in seconds but I'll change it.

1. Maybe we should only call page page over there? just so we practice the real way we are supposed to do it?
Good you think about it because it will get large fast, so can be an indication when I need to Partition the database (or another solution).

**Comment by mei309** [comment]
2) it can be a big difference if they put all at 12:00 a very simple scenario but in general you right

**Comment by mei309** [comment]
3) we should but not now. we need to upload the version fast before they get crazy

**Comment by mei309** [comment]
in the evening today I will finish my changes and then we need to check basic so probably wouldn't be by them tomorrow

**Comment by mei309** [comment]
when you have the massages and tasks ready send it to me

**Comment by litzvi** [comment]
> 1. it can be a big difference if they put all at 12:00 a very simple scenario but in general you right

i changed it

**Comment by litzvi** [comment]
> when you have the massages and tasks ready send it to me

you said not now. no?

**Comment by mei309** [comment]
> > when you have the massages and tasks ready send it to me
> 
> you said not now. no?

just a normal range. not the advanced page by page

**Comment by mei309** [comment]
we also need to think about the receiving schedule because now we getting all and its not correct and its also a very lot of data

**Comment by mei309** [comment]
and also if you can make this 2 functions
1) getUserMassagesNumber
2) getUserTasksNumber
now for to get the number im calling all the tasks and massages that is definitely wrong. and just for basic knowledge eli already has 5000 tasks and 7500 massages

**Comment by litzvi** [comment]
I added LocalDateTime startTime, LocalDateTime endTime for messages and tasks.

**Comment by litzvi** [comment]
> we also need to think about the receiving schedule because now we getting all and its not correct and its also a very lot of data

You have com.avc.mis.beta.service.report.OrderReports.findAllCashewOrderItems(LocalDateTime, LocalDateTime) - in OrderReports not Orders

**Comment by litzvi** [comment]
> and also if you can make this 2 functions
> 
> 1. getUserMassagesNumber
> 2. getUserTasksNumber
com.avc.mis.beta.service.report.OrderReports.findAllCashewOrderItems(LocalDateTime, LocalDateTime)

that's bad.
Do you want all or only unread?
Do they really use it?

**Comment by mei309** [comment]
> > and also if you can make this 2 functions
> > 
> > 1. getUserMassagesNumber
> > 2. getUserTasksNumber
> com.avc.mis.beta.service.report.OrderReports.findAllCashewOrderItems(LocalDateTime, LocalDateTime)
> 
> that's bad.
> Do you want all or only unread?
> Do they really use it? 
> 
> Added In ProcessInfoReader

I think unread is enough.
I don't think they use it now but we will need it so we should leave it

**Comment by mei309** [comment]
> > we also need to think about the receiving schedule because now we getting all and its not correct and its also a very lot of data
> 
> You have com.avc.mis.beta.service.report.OrderReports.findAllCashewOrderItems(LocalDateTime, LocalDateTime) - in OrderReports not Orders

it's not good because in a schedule we want to show according to delivery date and not recording time

**Comment by litzvi** [comment]
Defiantly it's even sorted that way. mistake I changed it.

**Comment by mei309** [comment]
but I also need the all for the history of orders

**Comment by mei309** [comment]
so do another one.don't delete the one we have

**Comment by litzvi** [comment]
> I think unread is enough.

I made it flexible, so for unread messages you can call with Arrays.asList(MessageLabel.NEW)
and for not approved tasks with new DecisionType[] {DecisionType.EDIT_NOT_ATTENDED, DecisionType.NOT_ATTENDED}

**Comment by litzvi** [comment]
> but I also need the all for the history of orders

Just call with nulls it will give all (btw everywhere)

**Comment by mei309** [comment]
i mean i need the function of all with recorded dates for the history but you say its also by delivery date so never mind

**Comment by mei309** [comment]
ok done
