### ISSUE TITLE
block options 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#491]
One of the most common mistakes I've seen recently is the mistakes of material, for example, he reported that he put in a WSLP in roaster and take out of  W320  it can't happen and I would like to block any mistakes like that.

**Comment by litzvi** [comment]
Yes it's on my list

**Comment by litzvi** [comment]
@mei309 remember this after we fix the items

**Comment by mei309** [comment]
if you will give me the grade in itemDTO it will be a lot easier to do it

**Comment by litzvi** [comment]
> if you will give me the grade in itemDTO it will be a lot easier to do it

in com.avc.mis.beta.service.ValueTablesReader.getCashewItems(ItemGroup, ProductionUse, CashewGrade, PackageType) you can get by the grade.
CashewItemDTO has a grade.
ItemDTO is for all items - only CashewItem has a grade - so doesn't have a grade.

**Comment by mei309** [comment]
cannot use it because i need both packeage types
Cannot invoke "com.avc.mis.beta.entities.enums.PackageType.ordinal()" because "packageType" is null

**Comment by litzvi** [comment]
Sorry fixed, now you can give null

**Comment by mei309** [comment]
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "packageTypeOrdinal" is null
	at com.avc.mis.beta.service.ValueTablesReader.getCashewItems(ValueTablesReader.java:223) ~[classes/:na]

**Comment by litzvi** [comment]
Sorry put i wrote int instead of Integer in line 74 of com.avc.mis.beta.repositories.ValueTablesRepository.findCashewItems(ItemGroup, ProductionUse, CashewGrade, int)

I changed it

**Comment by mei309** [comment]
in ProcessItemInventory and UsedItemsGroupDTO and UsedItemTableDTO i need the grade so i can filter

**Comment by litzvi** [comment]
done. see if it's good.

**Comment by mei309** [comment]
done for production. for relocation i will do later

**Comment by mei309** [comment]
ok done
