### ISSUE TITLE
Production by time

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#493]
Now you can use my methods with the date.
I suggest you divide it, as in Reports -> Full PO details -> Full details

**Comment by mei309** [comment]
i really dont understand what you talking about?
if you talking about all the reports so i dont understand the second line

**Comment by litzvi** [comment]
you added 'Production by time'
you can divide cleaning/roasting/toffee/packing with expandable

**Comment by mei309** [comment]
it will be a problem with totals and searches. i will later add another search according to the type

**Comment by litzvi** [comment]
ok. wait for Eli or David to tell you.

**Comment by mei309** [comment]
we need to add the field of the process for the rows so then i can show what process is it

**Comment by mei309** [comment]
and i really dont understand why you want me to dived it, what eli aske for was a report with all. the diveded one they have in the normal report because we will add there dates range in the end

**Comment by litzvi** [comment]
ask him again. I just talked to him yesterday

**Comment by mei309** [comment]
i talked to him and they want one of all together. therefore in this one we need the process for each line. and the normal reports would also have times

**Comment by litzvi** [comment]
> we need to add the field of the process for the rows so then i can show what process is it

You are getting them separate.

**Comment by mei309** [comment]
> > we need to add the field of the process for the rows so then i can show what process is it
> 
> You are getting them separate.
> If you need me to add anything, please tell me for exactly what function. It already been a long time..

for now im getting separate but it should actually be from you. therefor we need a function that gets all production by time and therefor we need another filed to know what process is it

**Comment by litzvi** [comment]
Added in next version.
To call all just leave processName null.

**Comment by mei309** [comment]
still not uploaded

**Comment by litzvi** [comment]
> still not uploaded

It is. perhaps you aren't looking in the right place.
Just leave processName null

**Comment by mei309** [comment]
gives error.

**Comment by litzvi** [comment]
> gives error.

please show me the error or from what method are you calling?

**Comment by mei309** [comment]
ho sorry I'm on my way to bed so it will wait to the evening

**Comment by litzvi** [comment]
I think it's fixed

**Comment by mei309** [comment]
java.lang.NullPointerException: processName is marked non-null but is null
	at com.avc.mis.beta.service.report.ProductionProcessReports.getProcessesByTypeAndPoCode(ProductionProcessReports.java:73) ~[classes/:na]
	at com.avc.mis.beta.service.report.ProductionProcessReports.getProductionProcessesByTypeAndPoCode(ProductionProcessReports.java:59) ~[classes/:na]
	at com.avc.mis.beta.service.report.ProductionProcessReports.getProductionProcessesByType(ProductionProcessReports.java:50) ~[classes/:na]
	at com.avc.mis.beta.service.report.ProductionProcessReports$$FastClassBySpringCGLIB$$2afd2770.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]

**Comment by litzvi** [comment]
I fixed it

**Comment by litzvi** [comment]
pull the latest version

**Comment by mei309** [comment]
sorry didnt see the hangout
