### ISSUE TITLE
implemented the button shortcuts from reports to new ones.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#494]
i will be happy if you have a nicer suggestion.

**Comment by litzvi** [comment]
Seems like you can't manage the tabs well. so why don't you just separate them and add links from one to another.

Anyway, the way it is at least put it on top, not between the tabs and table (e.g. in production reports).

**Comment by litzvi** [comment]
It looks like a tooth grew on the nose

**Comment by litzvi** [comment]
WHAT'S WRONG WITH THE WAY YOU DID IN POS TABLE.
Maybe it's not always clear if it's for general or cashew

**Comment by mei309** [comment]
> Seems like you can't manage the tabs well. so why don't you just separate them and add links from one to another.
> 
> Anyway, the way it is at least put it on top, not between the tabs and table (e.g. in production reports).

it has nothing to do with he tabs. i wanted to show all the buttons all the time and it was only a mere suggestion and i asked for different ones

**Comment by mei309** [comment]
> It looks like a tooth grew on the nose

i agrree

**Comment by mei309** [comment]
> WHAT'S WRONG WITH THE WAY YOU DID IN POS TABLE.
> Maybe it's not always clear if it's for general or cashew

the problem is the space it takes. and then the tables are pushed down to out of sight

**Comment by mei309** [comment]
i changed it to the top but without space so look on the new version (when i upload and comment and suggest

**Comment by litzvi** [comment]
just do whatever you think

**Comment by mei309** [comment]
if you will give me the grade in itemDTO it will be a lot easier to do it

**Comment by mei309** [comment]
i did the best i know. once you have please comment if you have a better design idea otherwise close it

**Comment by litzvi** [comment]
In next version?

**Comment by mei309** [comment]
yup. I didn't upload yet

**Comment by litzvi** [comment]
It's ok with me, just move it to the side

**Comment by mei309** [comment]
ok done
