### ISSUE TITLE
filter QC item dropdown

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#496]
way to many not needed items.
You should filter by appropriate production uses and PackageType bulk.
If you're missing a method let me know

**Comment by mei309** [comment]
im filtering by appropriate production uses. for doing with package type too add a function like this with multi options for ProductionUse

public List<ItemWithUnitDTO> getItems(ItemGroup itemGroup, ProductionUse productionUse, PackageType packageType) {

**Comment by litzvi** [comment]
com.avc.mis.beta.service.ValueTablesReader.getItems(ItemGroup, ProductionUse[], PackageType)

**Comment by mei309** [comment]
let me know when you upload

**Comment by litzvi** [comment]
pushed Version: 17.8, Sorry thought it was up to date

**Comment by mei309** [comment]
ok done
