### ISSUE TITLE
Please reverse the visible order

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#498]
במלאי הכללי הסדר צריך להיות כמו קשיו, אחרונים החדשים למעלה ולאט מתדרדר למטה ולא ההפך[]()![Screenshot 2021-06-09 170114.png](https://user-images.githubusercontent.com/76675352/121336713-faa55e00-c945-11eb-9c11-e989067edff1.png)

**Comment by ELIPELET** [comment]
I see now that Many General reports are showing oldest on first. Scadule /inventory, please check all reports. Thanks.

**Comment by litzvi** [comment]
In Inventory the order is always older first. only in processes reports like receiving/cleaning/roasting etc. it's last first.

**Comment by ELIPELET** [comment]
You're right.
