### ISSUE TITLE
Add more columns on General.

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#499]
On the scadule of General inventory, I would like to have one more column of STATUS, open/receive.
On the way, you can Add APPROVALS too to general inventory. ![Screenshot 2021-06-09 171806.png](https://user-images.githubusercontent.com/76675352/121338258-88ce1400-c947-11eb-9d7a-61ff5bff2da4.png)

**Comment by mei309** [comment]
added STATUS and APPROVALS on schedules.
i have no clue what he means by this "On the way, you can Add APPROVALS too to general inventory."???

**Comment by litzvi** [comment]
in schedules I guess

**Comment by ELIPELET** [comment]
At the same general report add aprovle

**Comment by litzvi** [comment]
> At the same general report add aprovle

you mean in schedules? 
if not, please direct to the full address (e.g. Schedules -> Receiving General)
