### ISSUE TITLE
edit transaction of part

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#50]
say we had 317*50 bags and we choose part for the process used say 300.
in edit number of unit will only show 300 instead of 317 - have a look

**Comment by mei309** [comment]
WE SAID IN EDIT WE ONLY CAN REDUCE AND NOT ADD TAKING. IT HAD SOME PROBLEMS WITH YOU

**Comment by litzvi** [comment]
i know we will need to rethink how to do this. looks bad

**Comment by litzvi** [comment]
I think we should try again and fix if there is some problem by me

**Comment by mei309** [comment]
if its storageForms its fixed but for the table i didnt fix yet because its more difficult

**Comment by litzvi** [comment]
will you do it later?
