### ISSUE TITLE
Correct a mistake

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#500]
We accidentally wrote a shipping code with the wrong container, need to fix.
TAN-51655 goes with container no : CBHU5727571
TAN-51654 goes with container no:OOCU7060872

**Comment by litzvi** [comment]
@ELIPELET I don't see the second container

**Comment by litzvi** [comment]
@mei309 I don't see a reason not to be able to edit Shipment code and container in loading.
If you allow to edit, you need to add the current one to the drop down (and it's the default of course).

**Comment by ELIPELET** [comment]
Can't loading the second container because the mistake, just correct the first container.

**Comment by litzvi** [comment]
> Can't loading the second container because the mistake, just correct the first container.

fixed. check if it's ok

**Comment by mei309** [comment]
> @mei309 I don't see a reason not to be able to edit Shipment code and container in loading.
> If you allow to edit, you need to add the current one to the drop down (and it's the default of course).

ok done
