### ISSUE TITLE
Add containers arrive to schedule.


### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#501]
Hey guys. I would like to add "Receiving Containers" at the scadule Click button, please let me know if you can make it before the new version. 
And these are the columns 
1. Arrival date 
2. Container no' 
3. Seal no'
4. 20/40
5. Destination Port
6. Status, Arrivaed/not arrived yet. 
7. Approvals 

Thank you.

**Comment by mei309** [comment]
@litzvi its your decision if you want to do it. by me its easy to add

**Comment by ELIPELET** [comment]
Of course I want to, then I'll have the ability to see how much uploading and downloading we have every day/week.

**Comment by mei309** [comment]
> Of course I want to, then I'll have the ability to see how much uploading and downloading we have every day/week.

it was for zvi. and if its difficult to do it by him we wouldn't do it for this version

**Comment by litzvi** [comment]
You mean to add ordering containers, so you have a schedule?

**Comment by ELIPELET** [comment]
exactly, scadule of containers will make things easier for as to see what's happening on the run day

**Comment by litzvi** [comment]
when do you get the information what containers will come at what day?
And if so, do you get all the info you mentioned?

Arrival date
Container no'
Seal no'
20/40
Destination Port

**Comment by mei309** [comment]
its for when we do the booking

**Comment by litzvi** [comment]
Opened issue 529
