### ISSUE TITLE
Error in reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#504]
Can't be fixed with an edit, because report isn't showing.
need to display anyway with an error sign

**Comment by litzvi** [comment]
perhaps only return the error line for edit.

**Comment by litzvi** [comment]
or indicate a line has an error (maybe red)

**Comment by litzvi** [comment]
Should return the full data with information of the error, at least in table so mistakes could be edited.

**Comment by mei309** [comment]
> or indicate a line has an error (maybe red)

it will make stuff slower

**Comment by litzvi** [comment]
Ok so we leave it for now
