### ISSUE TITLE
Toffee is not working at all. 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#505]
When processing toffee production on software, it's Impossible  to submit.
Actually, all the toffee still isn't working.
![Screenshot 2021-06-23 095514.png](https://user-images.githubusercontent.com/76675352/123204549-8987ae00-d4e2-11eb-84ee-90ace9d8e528.png)

**Comment by litzvi** [comment]
I think it's ok now. please try again.

Also, you should change the toffee items (in item setup) production use = toffee; otherwise, in next version you won't see it in the dropdown.

**Comment by litzvi** [comment]
> Also, you should change the toffee items (in item setup) production use = toffee; otherwise, in next version you won't see it in the dropdown.

Sorry, you don't have production use toffee in the new version yet, so just ignore this comment.
Anyway, see if it works now.

**Comment by ELIPELET** [comment]
Right, still can't create toffee items yet, so I'll leave the toffee production for the next version. 
Thanks.

**Comment by litzvi** [comment]
No. you can still try.

**Comment by litzvi** [comment]
I checked and it working.
It doesn't show in the final report - I'll fix for next version.

**Comment by mei309** [comment]
its  working on the new version
