### ISSUE TITLE
fixes with eli 26/6

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#507]

**Comment by ELIPELET** [comment]
David sees production processes in the wrong day (because of the offset)

**Comment by ELIPELET** [comment]
From roasting everything in LBS

**Comment by ELIPELET** [comment]
packing process 1206 from 45055(was mixed with 10388) should be mixed with ABE-10239
Can't cancel because used, but don't see any use

**Comment by ELIPELET** [comment]
As in general, sometimes they pull a box/sample for checking. So need to take it out of inventory

**Comment by litzvi** [comment]
removed from TAN-51597 177 
<html>
<body>


ABE-10358,VAT-45055 | BAO NGOC,TRUNG NAM | 59639 - WHOLE - R/S - 16/10oz | Mar 3, 2021 | UNIT | 177 | 1 | FINAL PRODUCT | 177
-- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by litzvi** [comment]
After filtering in reports, should remove the paginating

**Comment by litzvi** [comment]
> From roasting everything in LBS

taken care of

**Comment by litzvi** [comment]
> As in general, sometimes they pull a box/sample for checking. So need to take it out of inventory

Open issue 514 for this
