### ISSUE TITLE
Recorded time LocalDateTime

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#508]
- When David looks for production recorded for a certain day, he finds stuff in the next day (say it was on 23th it displays on 24th).
- Users said they don't like filling the date in the given way, they rather type in.

All above reinforcing that it's better to simplify and set the date as filled/typed regardless of the time zone offset.

**Comment by mei309** [comment]
it will have major problems with the formats

**Comment by mei309** [comment]
we need to find a different way but just doing it as text isnt smart at all and in the us they talked to me about it too

**Comment by litzvi** [comment]
They won't be confused if everything is in Vietnam time. Being "smart" will confuse.

**Comment by mei309** [comment]
how will you solve the problem of that they count days from 6 to 6??

**Comment by litzvi** [comment]
what's the problem?

**Comment by mei309** [comment]
so we arent really showing by real date. we showing by half dates

**Comment by mei309** [comment]
from 6 to 6 is a day in our scenario not 12 to 12

**Comment by litzvi** [comment]
You mean when they search only by date like now? do from 12 to 12 (It's probably the same).
It will just give us flexibility in case they need it.

**Comment by litzvi** [comment]
> how will you solve the problem of that they count days from 6 to 6??

What's the problem to search from 6am to 6am from start day to day after end date?

**Comment by litzvi** [comment]
but I think we can show from 12 to 12, see if they complain

**Comment by mei309** [comment]
ok done
