### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#510]
When I run a search on the production process reports, why we need to Delete the Lot number And rewrite it again every time we move from one process to another, like from cleaning to roasting.
Is it possible that we could go through the tongues on the same search?. 

Here's an example. 
![Screenshot 2021-06-28 163023.png](https://user-images.githubusercontent.com/76675352/123615138-b05d2180-d80d-11eb-8751-65a67d3bec64.png)

**Comment by litzvi** [comment]
@mei309 I wrote about it in another issue

**Comment by mei309** [comment]
ok done
