### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#512]
Jun 28 09:38:44 ip-172-31-39-250 web: 2021-06-28 09:38:44.710  WARN 3489 --- [nio-5000-exec-5] c.a.mis.beta.security.JwtRequestFilter   : JWT Token does not begin with Bearer String
Jun 28 09:41:28 ip-172-31-39-250 web: 2021-06-28 09:41:28.618  WARN 3489 --- [nio-5000-exec-9] c.a.mis.beta.security.JwtRequestFilter   : JWT Token does not begin with Bearer String
Jun 28 09:41:48 ip-172-31-39-250 web: 2021-06-28 09:41:48.956  WARN 3489 --- [nio-5000-exec-9] c.a.mis.beta.security.JwtRequestFilter   : JWT Token does not begin with Bearer String
Jun 28 09:41:48 ip-172-31-39-250 web: 2021-06-28 09:41:48.968 ERROR 3489 --- [nio-5000-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause
Jun 28 09:41:48 ip-172-31-39-250 web: java.lang.OutOfMemoryError: Java heap space

seems to me like it starts here - it's the first time 'Java heap space' appears in the log.
why is requestTokenHeader null or not starting with "Bearer " ?
if so how does it impact ? does adding chain.doFilter(request, response) make some kind of recursion?

**Comment by mei309** [comment]
JWT Token does not begin with Bearer String
this is nothing. its a warning that someone didnt use the token.

**Comment by mei309** [comment]
chain.doFilter(request, response) is spring security function not mine so assume it doesn't. and it also has no reason to do it

**Comment by litzvi** [comment]
> JWT Token does not begin with Bearer String
> this is nothing. its my warning that someone didnt use the token.

So who isn't using the token and why is it causing the heap to explode?

**Comment by mei309** [comment]
if it will cause it the program wouldn't work even one minute

**Comment by mei309** [comment]
every time you log in it shows the warning. because the first call is always without the token

**Comment by litzvi** [comment]
Is there away you can display the heap content when it happens next?

**Comment by litzvi** [comment]
Now that I see it again, I was looking at the wrong place.
I think these are the relevant lines:

Jun 28 09:41:48 ip-172-31-39-250 web: java.lang.OutOfMemoryError: Java heap space
Jun 28 09:41:48 ip-172-31-39-250 web: at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68) ~[na:1.8.0_292]
Jun 28 09:41:48 ip-172-31-39-250 web: at java.lang.StringBuilder.<init>(StringBuilder.java:101) ~[na:1.8.0_292]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.descriptor.java.DataHelper.extractString(DataHelper.java:67) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.descriptor.java.DataHelper.extractString(DataHelper.java:267) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.descriptor.java.StringTypeDescriptor.wrap(StringTypeDescriptor.java:75) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.descriptor.java.StringTypeDescriptor.wrap(StringTypeDescriptor.java:22) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.hql.QueryLoader.getResultRow(QueryLoader.java:457) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.hql.QueryLoader.getResultColumnOrRow(QueryLoader.java:440) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:775) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.processResultSet(Loader.java:1008) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.doQuery(Loader.java:964) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.doList(Loader.java:2838) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.doList(Loader.java:2820) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2652) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.Loader.list(Loader.java:2647) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1404) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.hibernate.query.Query.getResultList(Query.java:165) ~[hibernate-core-5.4.15.Final.jar!/:5.4.15.Final]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:126) ~[spring-data-jpa-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88) ~[spring-data-jpa-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154) ~[spring-data-jpa-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
Jun 28 09:41:48 ip-172-31-39-250 web: at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142) ~[spring-data-jpa-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]

**Comment by litzvi** [comment]
If this is the reason, would be nice to know which query is causing it now. 
And need to find a solution.
Perhaps fetch with a limit of results etc. That would hurt the filters you made - will need advanced searches.

**Comment by mei309** [comment]
we will need to add a monitor for it. its happening all the time now

**Comment by mei309** [comment]
we need a monitor for the java heap. not eclipse heap. i will find one later today.

**Comment by litzvi** [comment]
it also uses ClobTypeDescriptor, so maybe it's saving a lot of space for one f the @Lob fields?

**Comment by litzvi** [comment]
Maybe it's caused by tasks?

**Comment by mei309** [comment]
i have no clue. lets see once i find a monitor

**Comment by litzvi** [comment]
I have a suspicion it's because of using 'in' clause in queries, but not sure why it only happens sometimes.

**Comment by litzvi** [comment]
Hibernate might be creating many queries for it, therefore thrashing the cache

**Comment by litzvi** [comment]
> Hibernate might be creating many queries for it, therefore thrashing the cache

If so adding this to the properties file might be a **temporary** solution.

spring.jpa.properties.hibernate.query.in_clause_parameter_padding = true

**Comment by litzvi** [comment]
hibernate.query.plan_cache_max_size – controls the maximum number of entries in the plan cache (defaults to 2048)
should probably cut this to half too.

**Comment by mei309** [comment]
its working a long time with none of this  problem so im closing it
