### ISSUE TITLE
Cashew/Product inventory use

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#514]
As in general, sometimes they pull a box/sample for checking or give away. So need to take it out of inventory.
So I'll add Inventory use for cashew in a seperate process.
Also add this info in final report. perhaps with inventory?

**Comment by mei309** [comment]
in inventory its the best

**Comment by litzvi** [comment]
I added 
com.avc.mis.beta.service.InventoryUses.addProductInventoryUse(InventoryUse)
com.avc.mis.beta.service.InventoryUses.editProductInventoryUse(InventoryUse)
for product/cashew inventory use

In
com.avc.mis.beta.service.report.InventoryUseReports
all the functions get a ProcessName (Similar to ProductionProcess) which are PRODUCT_USE or GENERAL_USE
(You should use this class instead of WarehouseManagement which I want to later depricate)

In order for it to work need to add the process type in the db:
INSERT INTO `process_types` (`name`, `process_name`) VALUES ('Product Use', 'PRODUCT_USE');

**Comment by litzvi** [comment]
> Also add this info in final report. perhaps with inventory?

I'll do later

**Comment by litzvi** [comment]
> > Also add this info in final report. perhaps with inventory?
> 
> I'll do later

Added inventoryUse in InventoryReportLine for final report

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
Allow to add remarks just as in general

**Comment by mei309** [comment]
done
