### ISSUE TITLE
No produced items in process doesn't show table 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#515]
[localhost-1625048802849.log](https://github.com/litzvi/avc-beta/files/6740110/localhost-1625048802849.log)

**Comment by litzvi** [comment]
Pay attention to third line (2), because it has no process items.
Still show it, so we can edit, Because it's a mistake that can happen - adding without produced items works.

**Comment by litzvi** [comment]
Or make number of units mandatory

**Comment by mei309** [comment]
i think i fixed it. but i dont get how we come to that situation? by me i dont allow it

**Comment by mei309** [comment]
can you send me a dump?

**Comment by mei309** [comment]
im not managing to reproduce it

**Comment by mei309** [comment]
and we cannot without at all it gives an error

**Comment by litzvi** [comment]
[Dump20210630.zip](https://github.com/litzvi/avc-beta/files/6740711/Dump20210630.zip)

**Comment by litzvi** [comment]
In cleaning report

**Comment by litzvi** [comment]
> Or make number of units mandatory

You add Item and weight unit but not number of units - that's the problem.

**Comment by mei309** [comment]
fixed it.
