### ISSUE TITLE
new order clear error

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#516]
when adding a new order without a item it gives "Internal server error, please contact system manager" is it possible to make it clear?

**Comment by litzvi** [comment]
that's the error they are getting?

**Comment by mei309** [comment]
500 and "internal error please contact system manager" in the evening when I run again my local I will send you the full error

**Comment by litzvi** [comment]
fixed.
I asked if it's all the time this one

**Comment by litzvi** [comment]
because there was one [object object]
