### ISSUE TITLE
Design issues version 22.1

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#518]
- Production buy time: not clear what happens when I choose a year and then a month, they still both show.
- Report new buttons: at least make some space between the buttons.

**Comment by litzvi** [comment]
If you meant to do the day | week | month | year everywhere I think It's not suitable.

**Comment by mei309** [comment]
I have a feeling you don't have the new version

**Comment by mei309** [comment]
in my new version there's only one drop down on production by time

**Comment by mei309** [comment]
and what's reports new buttons?? you mean the search?

**Comment by mei309** [comment]
maybe because I forget to give you to run this (run it before running the ng serve) one at a time
npm i moment
npm i @angular-material-components/moment-adapter
npm i @angular/material-moment-adapter

**Comment by litzvi** [comment]
> maybe because I forget to give you to run this (run it before running the ng serve) one at a time
> npm i moment
> npm i @angular-material-components/moment-adapter
> npm i @angular/material-moment-adapter

correct

**Comment by litzvi** [comment]
I'm getting 404 [object object] message

[localhost-1625371629631.log](https://github.com/litzvi/avc-beta/files/6759358/localhost-1625371629631.log)

**Comment by litzvi** [comment]
About the design, I think you only need a range

**Comment by mei309** [comment]
404 means you dont have the correct controllers. i think i uploaded a correct one but later today i will upload a new one so it should be fine tomorrow if you use the new controllers

**Comment by litzvi** [comment]
> 404 means you dont have the correct controllers. i think i uploaded a correct one but later today i will upload a new one so it should be fine tomorrow if you use the new controllers

ok

**Comment by mei309** [comment]
done
