### ISSUE TITLE
Reports results are getting too heavy

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#519]
2 solutions I can think of: 

1. get only for some period of time by default
2. get a page at a time

Pros of 2
Page at a time is more efficient - less data and all we display anyway.
Always be efficient (even if they search for a long period)
More free cache since queries are typically shorter.

Cons for 2
Filters won't work, everything will need to be requested from backend.
For a full report (say print all records of the month) will need to call multiple times or have a special method.

**Comment by litzvi** [comment]
I'm just putting it here for follow up but for now we are using option 1.

**Comment by mei309** [comment]
im showing 2 weeks as default for now in all pages

**Comment by litzvi** [comment]
Started implementing option 2
