### ISSUE TITLE
ItemCount extends AuditedEntity???????

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#52]
im forced to put to much stuff please remove it

**Comment by litzvi** [comment]
AuditedEntity has the following fields:
id, version - managed by hibernate
createdDate, modifiedDate, createdBy, modifiedBy - all managed by spring AuditingEntityListener
remarks - not required

**Comment by litzvi** [comment]
I changed the whole structure.
Now itemCounts belong to the transfer process.
So please review in version 1.4

**Comment by mei309** [comment]
Field 'process_item_id' doesn't have a default value
in itemcount why????

**Comment by litzvi** [comment]
Because it dosen't belong to the processItem anymore
rebuild the database!

**Comment by mei309** [comment]
ok
