### ISSUE TITLE
Angular version 22.1

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#520]
Schedules not working, getting the following.
This is right when I go in (if i check see all it shows

[localhost-1625384074569.log](https://github.com/litzvi/avc-beta/files/6759540/localhost-1625384074569.log)

**Comment by litzvi** [comment]
same for qc reports

**Comment by litzvi** [comment]
same for production by time.
[localhost-1625399027505.log](https://github.com/litzvi/avc-beta/files/6759828/localhost-1625399027505.log)

**Comment by litzvi** [comment]
Inventory by time
[localhost-1625399206337.log](https://github.com/litzvi/avc-beta/files/6759832/localhost-1625399206337.log)

**Comment by litzvi** [comment]
Export report also not showing

**Comment by litzvi** [comment]
Here is the full database I used in case it works by you.
[Dump20210704 (1).zip](https://github.com/litzvi/avc-beta/files/6759837/Dump20210704.1.zip)

**Comment by mei309** [comment]
404 errors alwaymean you dont have the right controllers

**Comment by mei309** [comment]
> Schedules not working, getting the following.
> This is right when I go in (if i check see all it shows
> 
> [localhost-1625384074569.log](https://github.com/litzvi/avc-beta/files/6759540/localhost-1625384074569.log)

because I changed the dates type. fixed

**Comment by litzvi** [comment]
ok
