### ISSUE TITLE
you removed kg in production reports

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#521]
only packing its nedded

**Comment by litzvi** [comment]
He actually asked from roasting.
Let's see and if he wants to change maybe I'll make it flexible

**Comment by mei309** [comment]
its better you leave everywhere then remove everywhere

**Comment by litzvi** [comment]
It's very easy to change. SO just leave it and we will see there feedback

**Comment by litzvi** [comment]
I will try give you the option to choose the measure units in a future version. So you can let them choose.

**Comment by litzvi** [comment]
Okay. It's pretty flexible , so I'll wait for there specific requests.
