### ISSUE TITLE
localDate conversation 

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#522]
im retuning a date in iso standard but its not succeeding to do the conversion.
localDateTime is working.
if you know about the conversion of eclipse/jackson it will be helpful.

**Comment by mei309** [comment]
this is the error i get
Text '2021-07-12T00:00:00.000Z' could not be parsed, unparsed text found at index 10

**Comment by litzvi** [comment]
Z is the offset (I think zero offset = UTC)
You need to give a time without a offset/zone

**Comment by mei309** [comment]
very very helpful

**Comment by mei309** [comment]
if you find a way to change from 2021-07-12T00:00:00.000Z to localdate it will be very helpful

**Comment by litzvi** [comment]
> if you find a way to change from 2021-07-12T00:00:00.000Z to localdate it will be very helpful

You should get it as a date without an offset, otherwise you need to change it back to the local time and then remove the Z or +-[hh][mm].
See ISO 8601 in Wikipedia or anywhere else

**Comment by mei309** [comment]
i know all that and i still want to change from this string to localdate

**Comment by mei309** [comment]
and i need to do it in the back and not in the front

**Comment by litzvi** [comment]
> i know all that and i still want to change from this string to localdate

not possible without knowing the time zone.

**Comment by litzvi** [comment]
We have a problem with tasks and messages
tasks I need to fix
messages is some null problem (I have no messages on my user)
[d34djkpi615opt.cloudfront.net-1625710611174.log](https://github.com/litzvi/avc-beta/files/6780989/d34djkpi615opt.cloudfront.net-1625710611174.log)
.

**Comment by litzvi** [comment]
that's on the cloud.

when I run locally both are causing the [object object]

**Comment by litzvi** [comment]
Besides it's not working because here I should be getting offsetDateTime.
I can change it or we we can experiment getting page page by limit - I think it's more suitable for messages.

**Comment by mei309** [comment]
> Besides it's not working because here I should be getting Instant (or OffsetDateTime if you can't) - I changed it to Instant.
> I can change it or we we can experiment getting page page by limit - I think it's more suitable for messages. (info in issue 530)

if you use instant or offset you wouldn't get the correct data

**Comment by mei309** [comment]
> that's on the cloud.
> 
> when I run locally both are causing the [object object] 

I don't think I uploaded to drive the new controllers

**Comment by litzvi** [comment]
> if you use instant or offset you wouldn't get the correct data because all the data is without offset. just local date and time

That's what we need over there, it's checking another field because we don't have recorded time, only created date (which the system fills)

**Comment by mei309** [comment]
i didnt change before to instant. now its changed.

**Comment by mei309** [comment]
about the null problem it looks ike in that version you returned null in case of no records. now you return empty array so its ok
