### ISSUE TITLE
VERSION 22.5

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#523]
In Purchase Orders -> #Pos 
Why are you showing the following columns:  contract type code, suffix ?

**Comment by litzvi** [comment]
In Purchase Orders -> Cashew Orders -> All
Error with local date

**Comment by litzvi** [comment]
p.a. Choosing dates, can't search from 1/1/2021 12:00 to 1/1/2021 6:00 - all those choices but doesn't cover all options?

**Comment by mei309** [comment]
> In Purchase Orders -> #Pos
> Why are you showing the following columns: contract type code, suffix ?

i dont know but i removed it now

**Comment by mei309** [comment]
> In Purchase Orders -> Cashew Orders -> All
> Error with local date

you comparing localDate with LocalDateTime.

**Comment by mei309** [comment]
> p.a. Choosing dates,
> 
> * can't search from 1/1/2021 12:00 to 1/1/2021 6:00
> * can't choose all time
> 
> all those choices but doesn't cover all options?
> 
> And why default to 6 am?

its just a day thing if they will really want to change it i will later.
6 is what he requested since thats the days in the factory

**Comment by litzvi** [comment]
It's very bad. You blocked options for no reason, just trying to be smart. Simple is the key.

**Comment by mei309** [comment]
> It's very bad. You blocked options for no reason, just trying to be smart. Simple is the key.

i cannot put it in the range picker so it needs to be separate so therefor i dont want to put 2

**Comment by litzvi** [comment]
> > It's very bad. You blocked options for no reason, just trying to be smart. Simple is the key.
> 
> i cannot put it in the range picker so it needs to be separate so therefor i dont want to put 2

It's bad, say they want to check shifts?
At least give a see all like last version in schedules

**Comment by litzvi** [comment]
Schedules isn't working  

[localhost-1625559166316.log](https://github.com/litzvi/avc-beta/files/6768426/localhost-1625559166316.log)

**Comment by mei309** [comment]
> Schedules isn't working
> 
> [localhost-1625559166316.log](https://github.com/litzvi/avc-beta/files/6768426/localhost-1625559166316.log)

its using the same function as all cashew

**Comment by mei309** [comment]
you are comparing localDate with LocalDateTime.

**Comment by mei309** [comment]
> > > It's very bad. You blocked options for no reason, just trying to be smart. Simple is the key.
> > 
> > 
> > i cannot put it in the range picker so it needs to be separate so therefor i dont want to put 2
> 
> It's bad, say they want to check shifts?
> At least give a see all like last version in schedules

so they choose a range and then sort by time

**Comment by litzvi** [comment]
> At least give a see all like last version in schedules

what about this

**Comment by litzvi** [comment]
Filter the item by grade in relocations too

**Comment by mei309** [comment]
> > At least give a see all like last version in schedules
> 
> what about this

how it would help the lack of times?? i think its not good its to much data

**Comment by litzvi** [comment]
> > > At least give a see all like last version in schedules
> > 
> > 
> > what about this
> 
> how it would help the lack of times?? i think its not good its to much data

I want to use it to check stuff

**Comment by litzvi** [comment]
> how it would help the lack of times?? i think its not good its to much data

exactly So make it simple!!!

**Comment by mei309** [comment]
i really dont understand your problem

**Comment by litzvi** [comment]
If difference (in reports) is 0, it's not null. Now you are leaving it empty in relocations report (before it was good)

**Comment by litzvi** [comment]
> i really dont understand your problem

try putting in old data and you will understand.
i.e. don't answer me please

**Comment by litzvi** [comment]
editing Storage relocation is giving the items twice. It was solved in Processes. why not in relocation?
Is there something I need to change?

**Comment by mei309** [comment]
adding the time would look strange and i know you and they will ask to change the design and i dont know of a way and i think this is good enough for normal use but i will add in the drop down all time as the last option

**Comment by mei309** [comment]
> If difference (in reports) is 0, it's not null. Now you are leaving it empty in relocations report (before it was good)

fixed

**Comment by litzvi** [comment]
> adding the time would look strange and i know you and they will ask to change the design and i dont know of a way and i think this is good enough for normal use but i will add in the drop down all time as the last option

make it a check box

**Comment by litzvi** [comment]
Packing and probably also toffee, doesn't have the grade filter. Packages aren't normally characterized by a grade only whole or not.

**Comment by litzvi** [comment]
> Packing and probably also toffee, doesn't have the grade filter. Packages aren't normally characterized by a grade only whole or not.

Also I see you didn't add an option to choose from other items. So it's  a bug that doesn't even have a temporary solution.

**Comment by mei309** [comment]
> editing Storage relocation is giving the items twice. It was solved in Processes. why not in relocation?
> Is there something I need to change?

i dont recall that i changed it but anyway i will redo it today so its similar to production. but in production you did that we dont get items that are used and in relocation you didnt but i was sure it worked the way i will check it again today

**Comment by mei309** [comment]
> > Packing and probably also toffee, doesn't have the grade filter. Packages aren't normally characterized by a grade only whole or not.
> 
> Also I see you didn't add an option to choose from other items. So it's a bug that doesn't even have a temporary solution.

added

**Comment by mei309** [comment]
for now also package and toffee have it

**Comment by litzvi** [comment]
> > In Purchase Orders -> Cashew Orders -> All
> > Error with local date
> 
> you comparing localDate with LocalDateTime.

If I change it to LocalDate will it be fine with you?

**Comment by mei309** [comment]
> editing Storage relocation is giving the items twice. It was solved in Processes. why not in relocation?
> Is there something I need to change?

seems like its working now

**Comment by mei309** [comment]
i didnt manage to make the date change to give only localdate without time so please do it by you and then we can upload

**Comment by litzvi** [comment]
> i didnt manage to make the date change to give only localdate without time so please do it by you and then we can upload

So just change in the controller
LocalDate i = startTime.toLocalDate() etc.

**Comment by mei309** [comment]
added end time when choosing range filter

**Comment by litzvi** [comment]
> Filter the item by grade in relocations too

What about this? Actually maybe this should be only one of the  same items.
So if they move one type they only have that choice.

**Comment by mei309** [comment]
> > Filter the item by grade in relocations too
> 
> What about this? Actually maybe this should be only one of the same items.
> So if they move one type they only have that choice.

working

**Comment by litzvi** [comment]
ok. I guess i can close it
