### ISSUE TITLE
put amount with units together 

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#524]
in ItemAmount you have weightAmount and amount and its better if its together. this is actually good if done now because it will save me a lot of time with the final report design

**Comment by litzvi** [comment]
I'll do it now but leave it for the next version please. I don't want to check again

**Comment by litzvi** [comment]
check if this is what you meant
com.avc.mis.beta.dto.report.ItemAmount.getAmountWithWeight()

**Comment by mei309** [comment]
not exactly. i think its the only place (you have it in 8 files that 4 of them finish with reportLine) you using it  therefor we dont need weightAmount and amount and AmountWithWeight if you can change to amountList so everywhere is consistent.

**Comment by litzvi** [comment]
So the problem is the name?
getAmounts() for everything?

**Comment by mei309** [comment]
> So the problem is the name?
> getAmounts() for everything?

1) that they are separated 
2) the name should be amountList then its consistent with everywhere

**Comment by litzvi** [comment]
It's not the same everywhere. They are very different

**Comment by litzvi** [comment]
give me an example of a place you want it to be the same?

**Comment by litzvi** [comment]
I can change it but you will start having errors. so give me a list.

**Comment by mei309** [comment]
in the final report i need to show product in and product out like in production used items and produced items

**Comment by mei309** [comment]
just changing the name will do a lot of good. the others are redundent if you really using it only here

**Comment by mei309** [comment]
i just want the amountWithUnit list to be the same name so i dont need to treat them differently

**Comment by litzvi** [comment]
Sorry don't understand. give me exact methods you are talking about

**Comment by mei309** [comment]
in ProductionProcessWithItemAmount you have List<AmountWithUnit> getAmountList()
but in ItemAmount even so its exactlythe same you did this List<AmountWithUnit> getAmountWithWeight()

**Comment by litzvi** [comment]
Ok. that I changed. anywhere else?

**Comment by mei309** [comment]
thats all
