### ISSUE TITLE
Deleting unnecessary data. 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#525]
We have reached the point where we have entered all relevant data for the year 2021, all other data in the software needs to be deleted, we will make a list of the annecessary in the coming days, let's see if we have same inventory like Whatwhat.

**Comment by litzvi** [comment]
Yes, let me know and I'll try.
Give me some thing you want to delete so I can start please.

**Comment by litzvi** [comment]
[Send Eli.xlsx](https://github.com/litzvi/avc-beta/files/6775616/Send.Eli.xlsx)

**Comment by litzvi** [comment]
I removed the following

ABE-10063 
VAT-45019 
VAT-45016 
ABE-10082
VAT-45027
PO-14797V
VAT-45034

**Comment by litzvi** [comment]
ABE-10263  you can empty out the left over inventory with cashew inventory use as you requested

**Comment by litzvi** [comment]
All the rest are green and yellow. so decide what exactly you want to do with it.

**Comment by ELIPELET** [comment]
I'll sit down with you this weekend. Basically, the part in yellow Was in use a part this year and a part last year.

**Comment by litzvi** [comment]
So you want to remove the rest from inventory?

**Comment by ELIPELET** [comment]
If it's was shipped before 2021 so yes

**Comment by litzvi** [comment]
So in the new version you can do it with inventory use
