### ISSUE TITLE
avoid giving empty results

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#526]
inventory:
inventory: null
inventoryUse: null
totalInventory: null
totalInventoryUse: null
 in final report

**Comment by litzvi** [comment]
Don't understand? Which one is the problem?

**Comment by mei309** [comment]
sorry it didnt copy correctly. it should be inventory: null and not 
inventory: {
inventoryUse: null
totalInventory: null
totalInventoryUse: null }

**Comment by litzvi** [comment]
ok fixed

**Comment by mei309** [comment]
thanks
