### ISSUE TITLE
all transfers with sample table

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#53]
so i can do edit and also becasue its different

**Comment by litzvi** [comment]
you mean the same as in processItem storage?
for the itemCounts right?

**Comment by mei309** [comment]
just a table spaciel for samples with the relevent fileds

**Comment by litzvi** [comment]
please explain yourself better

**Comment by litzvi** [comment]
WarehouseManagement#getStorageTransfersTable()
returns ProcessRow that now has itemCounts and getCountDifference()
hope it does the work
see if it suits you

**Comment by mei309** [comment]
i want to show sepretly the transfers and the samples

**Comment by litzvi** [comment]
WHAT SAMPLES?
