### ISSUE TITLE
Information is duplicate

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#531]
We may have a case where the same Lot number appears twice, one on pending and one in received. 
![Screenshot 2021-07-08 155908.png](https://user-images.githubusercontent.com/76675352/124894587-785f9680-dfe4-11eb-9b32-0bfbe12c1950.png)

**Comment by litzvi** [comment]
So cancel one of them.
Then fix the other one to 15876 kg not lbs.
The reason it allowed to happen is because they are filling lbs instead of KG

**Comment by litzvi** [comment]
I see they are making a this mistake a lot

**Comment by litzvi** [comment]
It's because you made the default for all these LBS, so that's the default they get when receiving

**Comment by ELIPELET** [comment]
Maybe because I changed all the Default measure weight to lb. Unless they change to KG.
But I see both of them was written in lb.
My question is, it's possible to write a Lot twice without receiving a rejection from software?.

**Comment by litzvi** [comment]
> Maybe because I changed all the Default measure weight to lb. Unless they change to KG.
> But I see both of them was written in lb.
> My question is, it's possible to write a Lot twice without receiving a rejection from software?.

It's possible to receive in parts, as long as it's not over the order.
since the order was 35000lb and you received only 15876lb so you can still receive 19124lbs more

**Comment by litzvi** [comment]
> Maybe because I changed all the Default measure weight to lb. Unless they change to KG.

exactly. It should be in KG

**Comment by ELIPELET** [comment]
Can we set up and control the measure weight on this part? Or only by your guys?

**Comment by litzvi** [comment]
> Can we set up and control the measure weight on this part? Or only by your guys?

that's what the default measure unit is for
