### ISSUE TITLE
Tasks & massage not working 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#532]
That's what software shows when you click  tasks.
Messages are not showing up too. 
![Screenshot 2021-07-08 145700.png](https://user-images.githubusercontent.com/76675352/124895992-b9a47600-dfe5-11eb-8156-037da5c218f5.png)

**Comment by litzvi** [comment]
thanks. we know

**Comment by mei309** [comment]
fixed

**Comment by ELIPELET** [comment]
I don't see it's fixed

**Comment by litzvi** [comment]
> I don't see it's fixed

He meant by us. You will see it when he uploads the next version
