### ISSUE TITLE
Totals Summary below

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#533]
When I ask for export report Every  period of time  I want to know the total of containers we send and total quantity Whole /H&P respectively to the report. Otherwise it doesn't give me all the information properly. 
![Screenshot 2021-07-07 163329.png](https://user-images.githubusercontent.com/76675352/124899021-61bb3e80-dfe8-11eb-8528-93c9ba52b3bc.png)

**Comment by mei309** [comment]
all your items aret considered whole so we need to change them in item setup

**Comment by mei309** [comment]
total containers done

**Comment by litzvi** [comment]
> all your items aret considered whole so we need to change them in item setup

@ELIPELET call me if you don't understand.

**Comment by mei309** [comment]
ok. we talked and im sure you also so i will close it
