### ISSUE TITLE
grades changeable

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#534]
grades need to be changable and now they missing lp but adding from db isnt enough i added by me too but anyway it should be changable

**Comment by litzvi** [comment]
> grades need to be changable and now they missing lp but adding from db isnt enough i added by me too but anyway it should be changable

Don't understand what you mean by changable, It is editable.
Added LP

**Comment by mei309** [comment]
eli says they add sometimes and remove sometimes. therefor i think its not supposed to be an enum

**Comment by litzvi** [comment]
> eli says they add sometimes and remove sometimes. therefor i think its not supposed to be an enum. if you think otherwise please close the issue

defiantly. I'll change it - will be like a city.

**Comment by litzvi** [comment]
Ok I changed it. so you need to add it to setup tables as well.
It's better if we upload it to the cloud before they fill the grades

**Comment by litzvi** [comment]
on the backup you can run

alter table items drop column grade;
alter table items add column `grade_id` int DEFAULT NULL;

**Comment by mei309** [comment]
its still an enum by me

**Comment by mei309** [comment]
sorry didnt have the correct version

**Comment by mei309** [comment]
done. didnt run it on the cloud db
