### ISSUE TITLE
po-16447

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#535]
need to cancel roasting process.

**Comment by litzvi** [comment]
you did it?

**Comment by mei309** [comment]
> you did it?
> Shouldn't be allowed to add without usedItems, no?

it gives a error trying

**Comment by mei309** [comment]
they did it. but i dont know how. when i try it throws an error

**Comment by litzvi** [comment]
> they did it. but i dont know how. when i try it throws an error

All I can see that it has a usedItemGroup with a table view but no used items in it.
Me cancelling it would be a coverup, you should allow to edit it. 
And we should try to understand how it happened. hint: it's in a table view

**Comment by mei309** [comment]
I'm not sure I allow to edit it (because I know I allow without process items and didn't check this yet) but the error right now is trying to get it from the backend

**Comment by litzvi** [comment]
btw if I use salt I can skip used produce part. also not correct

**Comment by mei309** [comment]
it's a 500 error so I need to see in my local machine so only tonight I will manage

**Comment by litzvi** [comment]
> I'm not sure I allow to edit it (because I know I allow without process items and didn't check this yet) but the error right now is trying to get it from the backend

I fixed the backend part

**Comment by litzvi** [comment]
> btw if I use salt I can skip used produce part. also not correct

I meant skip the roasting amounts (used item) - you can leave it empty if u use salt/sugar etc.

**Comment by mei309** [comment]
so keep it for me so I can download the dump from the cloud

**Comment by mei309** [comment]
its still a json converter error because used items cannot be null

**Comment by litzvi** [comment]
> its still a json converter error because used items cannot be null

Doesn't show any error by me. usedItems in UsedItemGroupDTO could be null by me.

**Comment by litzvi** [comment]
> so keep it for me so I can download the dump from the cloud

keep what?

**Comment by mei309** [comment]
> > so keep it for me so I can download the dump from the cloud
> 
> keep what?

it was that you dont change the db so i can dump. done

**Comment by mei309** [comment]
Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Cannot invoke "java.util.List.stream()" because "this.usedItemGroups" is null; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "java.util.List.stream()" because "this.usedItemGroups" is null (through reference chain: com.avc.mis.beta.dto.process.ProductionProcessDTO["totalWeight"])]

**Comment by mei309** [comment]
that is the error im getting its connected to json format and that that its null

**Comment by litzvi** [comment]
Why can't you have a list that's null?

**Comment by mei309** [comment]
i have a lot thats whats really strange. its probably something that forces it to be not null. i will try finding it soon

**Comment by litzvi** [comment]
Yes.You get null lists everywhere. probably because you are calculating
something with it.

**Comment by mei309** [comment]
im not doing anything with it. i will find it

**Comment by mei309** [comment]
in TransactionProcessDTO you have getTotalWeight() and there you arent checking if its null.

**Comment by litzvi** [comment]
> in TransactionProcessDTO you have getTotalWeight() and there you arent checking if its null.

thanks
Yes added a check, It started showing a json error instead of null pointer, so I missed it.
Now we can edit and fix it

**Comment by mei309** [comment]
great
