### ISSUE TITLE
Issue or not 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#536]
I wonder if what I'm seeing is part of the item set up or a issue problem. As you can see on the photo. It shows the 50 kg bags like 1kg only. ![Screenshot 2021-07-09 115335.png](https://user-images.githubusercontent.com/76675352/125025717-d7c4b180-e08b-11eb-9277-2821730157cf.png)

**Comment by litzvi** [comment]
a bug, it's all around

**Comment by ELIPELET** [comment]
I It's almost impossible to keep tracking the processes, please try to fixed for next week. Thank you

**Comment by litzvi** [comment]
sure.

**Comment by litzvi** [comment]
@mei309 you removed setting the unit amount right?

**Comment by mei309** [comment]
> @mei309 you removed setting the unit amount right?
> anyway I fixed it by me, after you will upload I'll fix the ones they did.

where i removed it??

**Comment by mei309** [comment]
this is the result of the relocation. i changed the relocation so i can eliminate the items. should i reset the unit amount or you doing it from now??

**Comment by litzvi** [comment]
I'll do it from now, we need to pay attention it doesn't cause errors.

**Comment by mei309** [comment]
ok.
