### ISSUE TITLE
Cloud display errors

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#537]
see what happens to the grouping and filtert

<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/125040857-4ae91a80-e0c2-11eb-9f90-61e8a56b4dfd.PNG">

**Comment by litzvi** [comment]
search all records

**Comment by mei309** [comment]
![2021-07-10](https://user-images.githubusercontent.com/58453503/125133938-c41f5680-e130-11eb-8d04-b03674617ef6.png)

**Comment by mei309** [comment]
i played with it a lot but nothing happened (above your situation) but anyway its a big error on my part so next time please send me the log.

**Comment by litzvi** [comment]
It was on the cloud. now it doesn't happen
