### ISSUE TITLE
trying to get full po details

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#539]
java.lang.NullPointerException: Cannot invoke "com.avc.mis.beta.entities.embeddable.AmountWithUnit.getAmount()" because "augend" is null
	at com.avc.mis.beta.entities.embeddable.AmountWithUnit.add(AmountWithUnit.java:82) ~[classes/:na]
	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123) ~[na:na]

**Comment by mei309** [comment]
Cannot invoke "com.avc.mis.beta.entities.embeddable.AmountWithUnit.getAmount()" because "augend" is null (through reference chain: com.avc.mis.beta.dto.process.ProductionProcessDTO["totalWeight"])]

**Comment by mei309** [comment]
its the same as what we had with used items

**Comment by mei309** [comment]
when you fix let me know so i can upload a new version

**Comment by litzvi** [comment]
It's not the same. I'm guessing what it is, check if it's fixed. If not, I
need to be able to reproduce the error.

**Comment by mei309** [comment]
fixed
