### ISSUE TITLE
process items have nothing to do here

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#54]
in loading and sample im just putiing something because they have no meaning

**Comment by litzvi** [comment]
LoadedItem is a ProcessItem - you have setLoadedItems(..) that actually calls setProcessItems, you shouldn't call setProcessItem, i just didn't find the right way to hide or structure it in java.
What do you mean by samples?? do you mean ItemCount? if so then it does have processItems, i just built you an helper method..

**Comment by mei309** [comment]
used items is the one we need loaded items im just putting a random thing

**Comment by litzvi** [comment]
how will i know what's in the container?

**Comment by mei309** [comment]
its exactly the used items

**Comment by litzvi** [comment]
also in storage transfer it's not necessarily needed but unfortunately with my current structure I don't know how else to do it.
about loading: if you look in loadedItem there is declaredAmount which is needed. also in case we will want to continue doing things with containers - say moving them to usa inventory etc. so i'm currently not sure if we can do without are i will need it.
What do you think?

**Comment by mei309** [comment]
i will do it for now

**Comment by litzvi** [comment]
i'm removing processItems

**Comment by litzvi** [comment]
i pushed version 1.8
removed processItem
probably not ready but just so you have a סקיצה

**Comment by litzvi** [comment]
now fetching of loading should also work

**Comment by mei309** [comment]
whats loadeditem now?
why we need it??? just pass the declerd amount

**Comment by litzvi** [comment]
there might be a mixed of a few items with different declaredAmount
look at their reports, it can have a few lines.

**Comment by mei309** [comment]
ok. i did
