### ISSUE TITLE
No Cashew Grade dropdown in item setup

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#541]
After I added a grade

**Comment by mei309** [comment]
ok fixed. and by the way i ran what you told me on the cloud but it didnt add no cashew grade

**Comment by mei309** [comment]
uploaded the fix also on the cloud. uploaded to git also

**Comment by litzvi** [comment]
> ok fixed. and by the way i ran what you told me on the cloud but it didnt add no cashew grade

It wasn't supposed to. They add cashew grades like they add countries

**Comment by litzvi** [comment]
Still don't see the dropdown. If you don't understand then call.

**Comment by litzvi** [comment]
> Still don't see the dropdown. If you don't understand then call.

ok
