### ISSUE TITLE
fixes needed - default date range plus others

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#545]
- grade dropdown is making trouble, by me I don't see the dropdown (after alt+f5 and shift+f5) and on the cloude can't add it to the item. 
- default date of 2 weeks. I suggest you leave the end date null, so it will give future also. they had this error, couldn't find a receipt they accidently put some days ahead. So since it usually doesn't exist better to show so they can fix it.
- a few of the filters specially in the new reports (in the reports tab) don't work - dropdown is empty.
- an old comment of Eli: when he finalizes a receipt you don't refresh the page, so he gets confused because he still sees it in pending.

**Comment by mei309** [comment]
1) you dont see the dropdown probably you dont have my correct versions.
and we cant do edit because of this 
Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: could not initialize proxy [com.avc.mis.beta.entities.values.CashewGrade#2] - no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException: could not initialize proxy [com.avc.mis.beta.entities.values.CashewGrade#2] - no Session (through reference chain: com.avc.mis.beta.entities.item.CashewItem["grade"]->com.avc.mis.beta.entities.values.CashewGrade$HibernateProxy$yRIKn2DV["active"])]

**Comment by mei309** [comment]
4) its fixed already in all known windows so if you see somewhere that not let me know

**Comment by litzvi** [comment]
I just went over the new reports on the cloud and not working in half of
fields.

**Comment by litzvi** [comment]
> 1. its fixed already in all known windows so if you see somewhere that not let me know

you mean the last comment about finalize?

**Comment by mei309** [comment]
> > 1. its fixed already in all known windows so if you see somewhere that not let me know
> 
> you mean the last comment about finalize?

yes

**Comment by mei309** [comment]
2) done

**Comment by litzvi** [comment]
In receipt when he finalizes.

**Comment by litzvi** [comment]
You go in pending and finalize.

**Comment by mei309** [comment]
3) all work for me. i went through one one and didnt find any problem. (i updated 2 of them now but they all worked)

**Comment by mei309** [comment]
about 4 it's happening when we close from outside and not from the close button. looking in to it

**Comment by mei309** [comment]
> 1) you dont see the dropdown probably you dont have my correct versions.
> and we cant do edit because of this 
> Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: could not initialize proxy [com.avc.mis.beta.entities.values.CashewGrade#2] - no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException: could not initialize proxy [com.avc.mis.beta.entities.values.CashewGrade#2] - no Session (through reference chain: com.avc.mis.beta.entities.item.CashewItem["grade"]->com.avc.mis.beta.entities.values.CashewGrade$HibernateProxy$yRIKn2DV["active"])]
> 

you know what it is?

**Comment by litzvi** [comment]
I think it's fixed. But can't check because do not get the dropdown

**Comment by mei309** [comment]
> about 4 it's happening when we close from outside and not from the close button. looking in to it

fixed.

**Comment by mei309** [comment]
Could not write JSON: could not initialize proxy [com.avc.mis.beta.entities.values.CashewGrade#2] - no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException: could not initialize proxy [com.avc.mis.beta.entities.values.CashewGrade#2] - no Session (through reference chain: java.util.ArrayList[1]->java.util.ArrayList[0]->com.avc.mis.beta.entities.values.CashewStandard["items"]->org.hibernate.collection.internal.PersistentSet[0]->com.avc.mis.beta.entities.item.CashewItem["grade"]->com.avc.mis.beta.entities.values.CashewGrade$HibernateProxy$n78usrMC["active"])]

**Comment by mei309** [comment]
please upload the new version where it works

**Comment by litzvi** [comment]
I did now

**Comment by mei309** [comment]
all working

**Comment by litzvi** [comment]
I pending orders should always show all - no need for the time range and 2 weeks default. He already called me he can't find something in pending because 2 weeks past..
Also reconsider the default in 'Production by time' - I think the default search he makes is the current day or current week.

**Comment by mei309** [comment]
pending done

**Comment by mei309** [comment]
about reconsider i dont agree because its better uniform

**Comment by litzvi** [comment]
ok. wait until he askes
