### ISSUE TITLE
COMMENTS VERION  23.2.4

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#547]
1. ADD CHECKED BY COLUMN IN QC REPORTS (otherwise won't be able to differentiate if they insert from vina control or supplier)
2. --ignore because it's pending -- Full po details -> summary is not showing receipts for some reason.
3. I'm getting google dropdowns again. after a while it didn't happen.
4. in relocations, the count item dropdown doesn't show in edit.
5. I suggest warehouse dropdowns act like items (not by prefix), since they are usually named with a letter first. e.g. C1,C2,..C10, difficult to find c10.
6. Final report design - I suggest the border of every part is different then the inside grid, easier for the eye to follow.

to be continued

**Comment by mei309** [comment]
1. added in qc reports. (in SupplierQualityRow you dont have it so i cannot add it in qc totals report)
3. please let me know the places it happens. i have to much places it can happen and each one is totally different 
4. fixed (it was when the item didnt have the same grade)
5. done
6. this is good?

**Comment by mei309** [comment]
[AvcVietnam.pdf](https://github.com/litzvi/avc-beta/files/6853111/AvcVietnam.pdf)

**Comment by litzvi** [comment]
> added in qc reports. (in SupplierQualityRow you dont have it so i cannot add it in qc totals report)

no need there

**Comment by litzvi** [comment]
> fixed (it was when the item didnt have the same grade)

it's the same item. how is it of different grades?

**Comment by litzvi** [comment]
> this is good?

yes

**Comment by mei309** [comment]
> > fixed (it was when the item didnt have the same grade)
> 
> it's the same item. how is it of different grades?

grade is null

**Comment by litzvi** [comment]
> > > fixed (it was when the item didnt have the same grade)
> > 
> > 
> > it's the same item. how is it of different grades?
> 
> grade is null.

not true. It happens with an item that grade was already set.

**Comment by mei309** [comment]
i had some error with it when i had null. its fixed. it might be that i don't understand the problem so see if its still there with the new version

**Comment by mei309** [comment]
pushed 23.2.5

**Comment by litzvi** [comment]
> pushed 23.2.5

no changes in this version

**Comment by litzvi** [comment]
> i had some error with it when i had null. its fixed. it might be that i don't understand the problem so see if its still there with the new version

now it shows

**Comment by mei309** [comment]
if you see the google thing again let me know where. besides that everything here is solved

**Comment by litzvi** [comment]
ok
