### ISSUE TITLE
more COMMENTS VERION 23.2.4

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#548]
1. container arrivals. please set loading port mandatory. (otherwise they get a non clear message from me).
2. QC totals - please change sum/total to average where that's what you mean.
3. Loading details - no need to show old/new warehouse - only old warehouse as warehouse.
4. QC totals - very important, you left out **loss** , **waist** and **QC** (bad quality) (and there averages). You can leave out the columns with damage/defects separately.
5. also qc totals is receipt date not 'check date'
6. in Export report why do you call everything at the bottom 'Total LBS by type'?

**Comment by litzvi** [comment]
7. QC totals report takes a long time. you can check for reference with all records. is it because of me or you? because I don't see anything different by me.

**Comment by mei309** [comment]
1. done
2. done
3. d
4. what is loss? what it represents? and is it percentage? it looks like all the qc(bad quality) and sum are always zero.
5.  done
6. what should i call them. it represents the whole and h&p

**Comment by mei309** [comment]
7. its backend. its taking crazy amounts of time to get it without me doing anything

**Comment by litzvi** [comment]
> what is loss? what it represents? and is it percentage? it looks like all the qc(bad quality) and sum are always zero.

loss the amount lost from receipt to end - yes in percentage.
qc(bad quality) is zero now because they didn't fill it yet (remember packing qc ?)
what sum??

**Comment by mei309** [comment]
sorry I mean loss

**Comment by litzvi** [comment]
> sorry I mean loss

loss isn't always zero

**Comment by litzvi** [comment]
> what should i call them. it represents the whole and h&p

just what you wrote in the parentheses for example. can add (LBS) if you don't write it with the number

**Comment by mei309** [comment]
> > what should i call them. it represents the whole and h&p
> 
> just what you wrote in the parentheses for example. can add (LBS) if you don't write it with the number

i dont really understand what should be written on top?

**Comment by mei309** [comment]
3. i didnt manage because i dont have a way to separate between realocation and loading so i will do it only after monday

**Comment by mei309** [comment]
can you please change the groupName like this and send me what to run on the db
meterialUsedPos => meterialUsed
in loading add suffix Loading
in relocation add suffix Relocation

**Comment by mei309** [comment]
its the only way i really could separate between the stuff

**Comment by litzvi** [comment]
> can you please change the groupName like this and send me what to run on the db
meterialUsedPos => meterialUsed

update process_groups set group_name = 'meterialUsed' where group_name = 'meterialUsedPos' and id>=0;

**Comment by litzvi** [comment]
by the way in inventoryUsed, some group name is normal and some materialUsed, this changes only for 'materialUsed'.
if you want foe everything just remove the the part in the where.

update process_groups as pg  
join INVENTORY_USES as cl on cl.process_id = pg.process_id
join storage_moves_group as uig on pg.id = uig.group_id
set group_name = 'meterialUsedRelocation' where group_name = 'meterialUsed';

**Comment by litzvi** [comment]
In loadign everything is normalPos. I assumed you want to change it to change it to 'normalPosLoading'. otherwise change and let me know so I can fix when I use a backup.

update process_groups as pg  
join container_loadings as cl on cl.process_id = pg.process_id
join storage_moves_group as uig on pg.id = uig.group_id
set group_name = 'normalPosLoading' where group_name = 'normalPos';

**Comment by litzvi** [comment]
for relocation

update process_groups as pg  
join storage_relocations as cl on cl.process_id = pg.process_id
join storage_moves_group as uig on pg.id = uig.group_id
set group_name = concat(group_name, 'Relocation');

**Comment by litzvi** [comment]
hope this is what you meant.
please let me know all the final commands you run, so I can add it to my changes file.

**Comment by mei309** [comment]
[fixes nedded.zip](https://github.com/litzvi/avc-beta/files/6903582/fixes.nedded.zip)

**Comment by mei309** [comment]
this is what i did in the end.

**Comment by litzvi** [comment]
ok added

**Comment by mei309** [comment]
done
