### ISSUE TITLE
Pacing prosses is not working 

### ISSUE THREAD

**Issue by ELIPELET** [litzvi/avc-beta#549]
Unable to enter packaging data, This whole process is unable on software.

**Comment by litzvi** [comment]
[d34djkpi615opt.cloudfront.net-1627035479093.log](https://github.com/litzvi/avc-beta/files/6868057/d34djkpi615opt.cloudfront.net-1627035479093.log)

**Comment by mei309** [comment]
fixed

**Comment by mei309** [comment]
on monday they will have it
