### ISSUE TITLE
Qc totals report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#550]
1. add supplier choice dropdown on top with the date because that's their normal, specially since this report is so heavy for now.
2. add other average for supplier on the bottom: loss, waste and qc.
3. number of lots per supplier could also be beneficial - so the average can get a better context.

**Comment by mei309** [comment]
2 and 3 done

**Comment by mei309** [comment]
1 i will do it only when i do a restructure of the searches. for now they have it in the table search

**Comment by litzvi** [comment]
> 1 i will do it only when i do a restructure of the searches. for now they have it in the table search

if it's a bother so forget about i thought it's simple.

**Comment by mei309** [comment]
it's simple but because of my design it will not be helpful at all

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
default is all suppliers, I hope. (anyway it's less important since I fixed the slow problem)
