### ISSUE TITLE
NullPointerException when cancelling CONTAINER_ARRIVAL process

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#552]
add missing process names to com.avc.mis.beta.service.ProcessReader.getProcess(int, ProcessName)
and I think you should return a clear message for default instead of null or if it doesn't matter than ignore, now i get NullPointerException.

**Comment by litzvi** [comment]
Another thing, add container to loading table. 
currently there is no way to see in the table the relation between arrival and loading
Or
we add the shipment code to the arrival if exists.

**Comment by mei309** [comment]
> Another thing, add container to loading table.
> currently there is no way to see in the table the relation between arrival and loading
> Or
> we add the shipment code to the arrival if exists (I already added shipment code in the new version).

added in loading table. i dont see a reason to put it in arrival

**Comment by mei309** [comment]
> add missing process names to com.avc.mis.beta.service.ProcessReader.getProcess(int, ProcessName)
> and I think you should return a clear message for default instead of null or if it doesn't matter than ignore, now i get NullPointerException.

i have no clue what you want me to do

**Comment by litzvi** [comment]
> added in loading table. i dont see a reason to put it in arrival

why not? so they have an indication if it was loaded or not while not many columns is this table anyway.

**Comment by litzvi** [comment]
> > add missing process names to com.avc.mis.beta.service.ProcessReader.getProcess(int, ProcessName)
> > and I think you should return a clear message for default instead of null or if it doesn't matter than ignore, now i get NullPointerException.
> 
> i have no clue what you want me to do

at least start with looking at the function and add the needed missing processes

**Comment by mei309** [comment]
> > > add missing process names to com.avc.mis.beta.service.ProcessReader.getProcess(int, ProcessName)
> > > and I think you should return a clear message for default instead of null or if it doesn't matter than ignore, now i get NullPointerException.
> > 
> > 
> > i have no clue what you want me to do
> 
> at least start with looking at the function and add the needed missing processes

its not my function. its your code

**Comment by mei309** [comment]
> > added in loading table. i dont see a reason to put it in arrival
> 
> why not? so they have an indication if it was loaded or not while not many columns is this table anyway.

ok added

**Comment by litzvi** [comment]
> > > > add missing process names to com.avc.mis.beta.service.ProcessReader.getProcess(int, ProcessName)
> > > > and I think you should return a clear message for default instead of null or if it doesn't matter than ignore, now i get NullPointerException.
> > > 
> > > 
> > > i have no clue what you want me to do
> > 
> > 
> > at least start with looking at the function and add the needed missing processes
> 
> its not my function. its your code

yes correct. sorry
