### ISSUE TITLE
comments version 23.2.8

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#554]
1. add a new button for cashew use in Inventory reports.
2. show warehouse (it's in storage) for Storage moved in Cashew usage details
3. you can change the header to used/loaded for the details of Loading/InventoryUse.
4. adding qc packed items is adding bulk. (at the same time change the button from 'add undefined').
5. normal packing process dropdown also shows qc items.
6. In Qc packing, remove the sections of table option(QC packd amounts) and Waste amounts.
7. I also suggest before using dropdown to choose between qc hold, screen, floor instead of showing them all (there can be 20 lines in a po..).
8. in qc packing, QC packd amounts should allow not packed items, so we can make bags of say 22lbs and no need to create an item for everyone. (It's because of the way we are doing it, that it only becomes a 'qc item' when it's packed)

**Comment by litzvi** [comment]
after you do all this, try doing a realistic packing and loading for qc

**Comment by mei309** [comment]
1. done
2. why its not like shipping and material use??
3. done
4. done
5. done
6. done
7. not for now because it has implactions
8. im giving all qc items bulk and packed. (checked)

**Comment by mei309** [comment]
> after you do all this, try doing a realistic packing and loading for qc.
> because I don't even see it showing up in loading

done and works

**Comment by litzvi** [comment]
> > after you do all this, try doing a realistic packing and loading for qc.
> > because I don't even see it showing up in loading
> 
> done and works

did you try edit?

**Comment by mei309** [comment]
yup. i did

**Comment by litzvi** [comment]
EDIT QC PACKING DOESN'T WORK

**Comment by litzvi** [comment]
Also we should change the qc item setup. 
I suggest only Qc bulk items (no packed - doesn't make much sense).
and when qc packing to give like in receiving so they can build there own constructs.
Otherwise 50lb and smaller amounts will show in separate lines.

**Comment by mei309** [comment]
> EDIT QC PACKING DOESN'T WORK

fixed

**Comment by mei309** [comment]
> Also we should change the qc item setup.
> I suggest only Qc bulk items (no packed - doesn't make much sense).
> and when qc packing to give like in receiving so they can build there own constructs.
> Otherwise 50lb and smaller amounts will show in separate lines.

i think we only need to add the table view

**Comment by litzvi** [comment]
It won't display well on the loading report. let's try.
Anyway i'll assume they aren't using it for next version. so we will check later.

**Comment by litzvi** [comment]
> > Also we should change the qc item setup.
> > I suggest only Qc bulk items (no packed - doesn't make much sense).
> > and when qc packing to give like in receiving so they can build there own constructs.
> > Otherwise 50lb and smaller amounts will show in separate lines.
> 
> i think we only need to add the table view

I'm not sure, but if it's easy then add the table option and we'll see how it looks.
If it's not to hard to allow bag weight and number of bags (like in receipt), it would be the best.

**Comment by mei309** [comment]
for now added table view

**Comment by mei309** [comment]
it looks great with table view and it dose the correct stuff in security and export reports

**Comment by litzvi** [comment]
See issue #573 on how qc needs to show in export report

**Comment by mei309** [comment]
7. done only in new qc packing. in edit it will cause another window on the way so i think its better this way

**Comment by mei309** [comment]
and about the qc in report we have issue 573

**Comment by mei309** [comment]
and on the qc items we have different places that we discussing the items so i will close the issue since all the major stuff of it re fixed

**Comment by litzvi** [comment]
> 1. done only in new qc packing. in edit it will cause another window on the way so i think its better this way

we need to be able to pack from a few pos, so a setup like loading is more suitable.

**Comment by mei309** [comment]
> > 1. done only in new qc packing. in edit it will cause another window on the way so i think its better this way
> 
> we need to be able to pack from a few pos, so a setup like loading is more suitable.

i will do like packing. only later if and when we can upgrade both together

**Comment by litzvi** [comment]
> i will do like packing. only later if and when we can upgrade both together

like packing is not suitable here, so no need. It's useless this way, they are just going to fabricate data.

**Comment by mei309** [comment]
i did it like packing so lets see how it goes

**Comment by litzvi** [comment]
ok. but it's bad, no doubt about that.
We worked so things are smooth and easy, but making esoteric things very complicated. 
esoteric but done often

**Comment by mei309** [comment]
its not esoteric by me. thats the reason i dont want to do it now

**Comment by litzvi** [comment]
> its not esoteric by me. thats the reason i dont want to do it now and also its not that difficult this way

esoteric in the process

**Comment by mei309** [comment]
we have a issue (597) about this so no point in this one open
