### ISSUE TITLE
Choosing from a dropdown with the mouse

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#556]
In the new version only. follow these instruction precisely:

1. open a new general order
2. go to the item field and type sa
3. use the **mouse** to choose salt from the dropdown.

see the weird reaction?

**Comment by mei309** [comment]
i dont see anything. it showes the 3 options that include salt and then i choose with the mouse and its all fine

**Comment by litzvi** [comment]
how do you video the screen?

**Comment by mei309** [comment]
i have one of samsung

**Comment by litzvi** [comment]
[AvcVietnam - Google Chrome 2021-08-05 21-23-38.zip](https://github.com/litzvi/avc-beta/files/6939374/AvcVietnam.-.Google.Chrome.2021-08-05.21-23-38.zip)

**Comment by mei309** [comment]
its fixed and checked but in a new implatation so it might have problems. so if you see something let me know
