### ISSUE TITLE
processRow

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#56]
countDifference and countItems not coming

**Comment by litzvi** [comment]
don't understand

**Comment by mei309** [comment]
its not showing up

**Comment by mei309** [comment]
in proccesRow

**Comment by litzvi** [comment]
what do you mean? not showing anything or showing null?

**Comment by mei309** [comment]
null

**Comment by litzvi** [comment]
I don't really know why.
can you check if all the information is in the database?
transfer has itemCounts
every itemCount references an item
every itemCount has amounts

**Comment by mei309** [comment]
transfer has itemCounts  i have no clue what you mean
every itemCount references an item yes
every itemCount has amounts yes

**Comment by litzvi** [comment]
StorageTransfer has itemCounts
look in the itemCounts and see if they are referencing the transfer process

**Comment by litzvi** [comment]
also does each itemCount have a measureUnit

**Comment by mei309** [comment]
StorageTransfer has itemCounts it dosenot

**Comment by mei309** [comment]
itemcount processid is equal to the id in storagetransfer

**Comment by litzvi** [comment]
so i don't know why it's not working.
I need to go home

**Comment by mei309** [comment]
im getting it with StorageTransferDTO

**Comment by litzvi** [comment]
ok. i'll try solving it tomorrow

**Comment by mei309** [comment]
solved. its giving only if i use it with getStorageTransfersTable

**Comment by mei309** [comment]
take my controlers tomowrow from drive. i will upload tonight

**Comment by litzvi** [comment]
off course, they are different for now
