### ISSUE TITLE
Why is container number divided to 2 rows? 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#560]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/128701615-239b8047-2ba8-4215-b91c-0d97a1e0a792.PNG">

**Comment by litzvi** [comment]
same goes for status. it's all one loading process over here

**Comment by litzvi** [comment]
ALSO CAN'T ADD LOADING

[localhost-1628511019032.log](https://github.com/litzvi/avc-beta/files/6954406/localhost-1628511019032.log)

**Comment by litzvi** [comment]
> ALSO CAN'T ADD LOADING
> 
> [localhost-1628511019032.log](https://github.com/litzvi/avc-beta/files/6954406/localhost-1628511019032.log)

IT DOES ADD BUT GIVES THIS 500 ERROR

**Comment by litzvi** [comment]
This is when i try opening the one i just added
[localhost-1628511218519.log](https://github.com/litzvi/avc-beta/files/6954427/localhost-1628511218519.log)

**Comment by litzvi** [comment]
and this is the db i'm using (has a different name: ebdb-pub1.1)

[Dump_ebdb-pub1.1.zip](https://github.com/litzvi/avc-beta/files/6954445/Dump_ebdb-pub1.1.zip)

**Comment by litzvi** [comment]
Why does security and export doc have [object object] on the top left corner?

<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/128707086-df8668ed-c7c5-4a33-8cd7-574791e3b02c.PNG">

**Comment by litzvi** [comment]
A different thing.. all around.
You are showing 'bag weight' as 1lbs or 1unit. the place we needed the bag weight was at the receipt or if it's from a table.
Probably better 'unit amount'

example:
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/128708301-75a250bb-db66-4fd2-8f3c-91e9f62ed569.PNG">

**Comment by mei309** [comment]
> > ALSO CAN'T ADD LOADING
> > [localhost-1628511019032.log](https://github.com/litzvi/avc-beta/files/6954406/localhost-1628511019032.log)
> 
> IT DOES ADD BUT GIVES THIS 400 ERROR [OBJECT OBJECT]

its not a frontend error and it works by me so i need the full error (that you have on eclipse) or the dump.

**Comment by litzvi** [comment]
> its not a frontend error and it works by me so i need the full error (that you have on eclipse) or the dump.

of course i looked on eclipse.
nothing there.

**Comment by mei309** [comment]
so please send me your dump

**Comment by litzvi** [comment]
what about the first comment over here?

**Comment by mei309** [comment]
all the rest fixed besides the one you asked not to do now

**Comment by litzvi** [comment]
yes because better not to change before a new version

**Comment by litzvi** [comment]
<img width="861" alt="Capture" src="https://user-images.githubusercontent.com/53637868/128715541-d8df50d5-b7bd-44f6-8796-d55e5dd1929d.PNG">

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/128876555-8f6a29c7-85a9-45ef-b6e2-95f4c14e471d.PNG">

**Comment by litzvi** [comment]
> all whats going on with the packed item i cannot understand. its very confusing. therefor they arent really using it too.
> for example: unit weight of packed item is it for the box or the bag?

You call it 'unit weight', but it's the unit(unitAmount in storage) that the number of units refers to.
So in a packed item it would just be UNIT/BOX etc
in bulk it's also most of the time just LBS/KG etc.
In receipt it's usually 50kg/26kg ..
Hope it explained

**Comment by mei309** [comment]
and what's box in packed item? it has connection to the unit weight?

**Comment by litzvi** [comment]
Let's go over it by phone

**Comment by litzvi** [comment]
> I suggest change **everywhere**
> 'bag weight' to **'unit'**
> 'number of bags' to **'number of units'**
> that way it should be neutral everywhere.
> Also keep them together - I saw in production processes details (used items) you stuck the 'warehouse' in middle.

this

**Comment by litzvi** [comment]
if you it's not clear Let's go over it by phone

**Comment by mei309** [comment]
done
