### ISSUE TITLE
Loading of non packed items

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#561]
shows wrong number of units in security doc.
because it's as if it's many bags of 1 lbs

**Comment by litzvi** [comment]
Should put a default of AmountWithUnit(null, LBS) when unitAmount is not specified.
Display should be 'LBS' in such a case.
won't count numberUnits as number of boxes in such a case, but rather the number of different storages to have a count of bags.

**Comment by litzvi** [comment]
@mei309 in

**Comment by mei309** [comment]
done
