### ISSUE TITLE
why are you allowing to pack packed items?

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#562]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/128718412-a4fab541-9c14-4c72-ad8f-86dbd7e1b4bd.PNG">

**Comment by mei309** [comment]
its toffee not packed

**Comment by litzvi** [comment]
production use = toffee
but it's a packed item, you need to account for that too.

**Comment by mei309** [comment]
its not true always about roasting. we talked about it once and we did want to repack in some cases

**Comment by mei309** [comment]
and i you anyway want to change it you need to change the functions warehouseManagement.getAvailableInventory and objectTableReader.findAvailableInventoryPoCodes

**Comment by litzvi** [comment]
> its not true always about roasting. we talked about it once and we did want to repack in some cases

I don't remember. Do you remember why?

**Comment by litzvi** [comment]
> objectTableReader.findAvailableInventoryPoCodes

those functions should be deprecated. You have the same functions in WarehouseManagement with PackageType packageType, leave it null for the previous result. If you choose bulk in packing you should get only non packed.

i.e. not an opinion, just an option. If you think we need to be able to pack packed items then just set to null.

**Comment by litzvi** [comment]
> warehouseManagement.getAvailableInventory

I added an overloaded method with packageType

**Comment by litzvi** [comment]
Again, If you think no need to filter packed, than leave null.

**Comment by litzvi** [comment]
> Again, If you think no need to filter packed, than leave null.

Eli also mentioned packed items shouldn't be in packing. 
But I agree there can be a scenario they want to take apart 50 lbs to small packing but seems like they don't so it now.
I should ask Ahron about it.

**Comment by litzvi** [comment]
I asked Ahron. He said very rare.

**Comment by mei309** [comment]
very rare is still needed. i suggest we leave it for now

**Comment by mei309** [comment]
i think its also very rare that they do half packing in toffe or roasting and half in packing so its not worth it the big change

**Comment by litzvi** [comment]
THAT'S NOT RARE  AT ALL. I already saw it in a few

**Comment by mei309** [comment]
for now i can change it to only packed or both always but i cannot give an option like by items. so you need to choose

**Comment by mei309** [comment]
added a checkbox for it
