### ISSUE TITLE
Inventory History Report time

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#563]
when I choose 6am it shows 1:00:14PM why is it changing display time to Israel?

**Comment by litzvi** [comment]
actually not israel  7 hours ahead

**Comment by litzvi** [comment]
Total all on the bottom change to **sum**.
You can also show the sum on the top or floating (not for printing)

**Comment by litzvi** [comment]
In Export Report add the date range.
Could be in a second header below Export Report
example:
### Export Report
july 1 2021 - august 1 2021

**Comment by litzvi** [comment]
QC  in final report. You are showing humidity: 0 but it's null. null is not zero - should be empty.

**Comment by mei309** [comment]
> when I choose 6am it shows 1:00:14PM why is it changing display time to Israel?

solved.

**Comment by mei309** [comment]
> actually not israel 7 hours ahead

the datapicker is in utc time and the date at top was in local date (vietnam is 7 hours ahead) but fixed now

**Comment by mei309** [comment]
> 'Total all' on the bottom change to **sum**.
> You can also show the sum on the top or floating (not for printing)

to change everywhere total all to sum?
about showing float it would stay for css people.

**Comment by mei309** [comment]
> In Export Report add the date range.
> Could be in a second header below Export Report
> example:
> 
> ### Export Report
> July 1 2021 - August 1 2021
> 
> or
> 
> ### Export Report
> July 2021

i have a special issue about it. i need to set it to all filters. so they dont think stuff are missing

**Comment by mei309** [comment]
> QC in final report. You are showing humidity: 0 but it's null. null is not zero - should be empty.

fixed

**Comment by mei309** [comment]
> After I print Inventory History Report (with you're print button) and go back to the report, I only see 10 of the rows.

its fixed on the cloud already

**Comment by mei309** [comment]
> > 'Total all' on the bottom change to **sum**.
> > You can also show the sum on the top or floating (not for printing)
> 
> to change everywhere total all to sum?
> about showing float it would stay for css people.

only on this i need your input

**Comment by litzvi** [comment]
> > actually not israel 7 hours ahead
> 
> the datapicker is in utc time and the date at top was in local date (vietnam is 7 hours ahead) but fixed now

So I hope now the datapicker is in vn time.

**Comment by mei309** [comment]
done
