### ISSUE TITLE
Please remove the need of setting unit amount to 1

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#565]
UnitAmount means the bag amount. so if they fill unit amount = 1, say in general receipt, it will mean that they have many bags of 1kg/lb..
So let them leave it empty.

i.e. I know before I asked for it but now I changed the structure a little.
<img width="1271" alt="Capture" src="https://user-images.githubusercontent.com/53637868/129435250-856cf7e9-1878-4474-b1af-ff8c30963e88.PNG">

**Comment by mei309** [comment]
removed in general

**Comment by mei309** [comment]
now i all the time getting  this error Column 'unit_amount' cannot be null
