### ISSUE TITLE
getTaskRows

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#566]
I added com.avc.mis.beta.service.ProcessInfoReader.getTaskRows(ProcessStatus[], Instant, Instant)

The processStatus is for choosing what task you want to see. I think we should show only for ones that the processes are Pending.
example in you're method:

	@RequestMapping("/getUserTasks")
	public List<TaskRow> getUserTasks(@QueryParam("begin")@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant begin, 
			@QueryParam("end")@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant end) {
		return processDao.getTaskRows(new ProcessStatus[]{ProcessStatus.PENDING}, begin, end);
	}

**Comment by litzvi** [comment]
You need to use this one because I changed the structure.

**Comment by litzvi** [comment]
I still need to fix the counts of the approvals

**Comment by mei309** [comment]
> I added com.avc.mis.beta.service.ProcessInfoReader.getTaskRows(ProcessStatus[], Instant, Instant)
> 
> The processStatus is for choosing what task you want to see. I think we should show only for ones that the processes are Pending.
> example in you're method:
> 
> ```
> @RequestMapping("/getUserTasks")
> public List<TaskRow> getUserTasks(@QueryParam("begin")@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant begin, 
> 		@QueryParam("end")@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Instant end) {
> 	return processDao.getTaskRows(new ProcessStatus[]{ProcessStatus.PENDING}, begin, end);
> }
> ```

it was in the beginning that way and we changed it.

**Comment by mei309** [comment]
also this we need to add DecisionType.EDIT_NOT_ATTENDED

**Comment by mei309** [comment]
so you changing it from DecisionType to ProcessStatus?

**Comment by litzvi** [comment]
this is for the counts.
com.avc.mis.beta.service.ProcessInfoReader.getUserTasksNumber(ProcessStatus[], DecisionType[])

you can use it like this 
	@RequestMapping("/getUserTasksNumber")
	public int getUserTasksNumber() {
		return processDao.getUserTasksNumber(new ProcessStatus[] {ProcessStatus.PENDING}, new DecisionType[] {DecisionType.EDIT_NOT_ATTENDED, DecisionType.NOT_ATTENDED});
	}

**Comment by mei309** [comment]
ok done
