### ISSUE TITLE
flexible order in reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#569]
Let user choose the order of the results.

**Comment by mei309** [comment]
he can do it with the sort and filters in the tables

**Comment by litzvi** [comment]
> he can do it with the sort and filters in the tables

I don't see you have sort in the tables.
the new version has?

**Comment by mei309** [comment]
all the versions have. its googles style so not everyone notice it.

**Comment by litzvi** [comment]
oh I see

**Comment by mei309** [comment]
https://user-images.githubusercontent.com/58453503/132867463-01be1278-ee0b-4132-bf94-6cbb3bc60257.mp4

**Comment by mei309** [comment]
i should put the video on zalo?

**Comment by litzvi** [comment]
It was my idea because I needed it for the inventory report

**Comment by litzvi** [comment]
Don't think they cared about it

**Comment by mei309** [comment]
i never really checked how its working on all fileds but it dose the basic
