### ISSUE TITLE
ShipmentCode com.avc.mis.beta.entities.process

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#57]
java.sql.SQLIntegrityConstraintViolationException: Column 'shipment_code_code' cannot be null
im giving a value. i thing theres a crash between 2 ids

**Comment by litzvi** [comment]
look what you did in when setting PoCode in an order.
it should be exactly the same.
please check the differences

**Comment by mei309** [comment]
im doing exactly the same

**Comment by litzvi** [comment]
what is the exception, give me something to work with.

**Comment by litzvi** [comment]
actually it probably didn't work for PoCode either...
I hope now it's fixed from version 2.1

**Comment by mei309** [comment]
version 2.3 not working 

java.sql.SQLIntegrityConstraintViolationException: Column 'shipment_code_code' cannot be null
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.20.jar:8.0.20]

**Comment by mei309** [comment]
poCode in a new order works fine

**Comment by litzvi** [comment]
ok sorry
add the following line in Services#Loading file between lines 70 and 71
		
dao.addEntityWithFlexibleGenerator(loading.getShipmentCode());

hope it solves the matter

**Comment by mei309** [comment]
java.lang.IllegalArgumentException: attempt to create saveOrUpdate event with null entity from line 71

**Comment by mei309** [comment]
2020-09-27 15:10:07.184  WARN 15700 --- [nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [javax.validation.ConstraintViolationException: Validation failed for classes [com.avc.mis.beta.entities.processinfo.LoadedItem] during persist time for groups [com.avc.mis.beta.validation.groups.OnPersist, javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=loading, rootBeanClass=class com.avc.mis.beta.entities.processinfo.LoadedItem, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]]

**Comment by mei309** [comment]
im giving pocode item and decleardamount what im missing?

**Comment by mei309** [comment]
it looks like the code is working

**Comment by litzvi** [comment]
sorry, should be fixed in version 2.5
