### ISSUE TITLE
add Inventory history for 'general inventory'

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#571]
David asked for inventory history for general too.
(make sense because that's how they get the report and hard to compare without it)

So I added point of time for all 3 general inventory reports
com.avc.mis.beta.service.report.InventoryReports.getInventoryTableByItem(ItemGroup, LocalDateTime)
com.avc.mis.beta.service.report.InventoryReports.getInventoryTableByPo(ItemGroup, LocalDateTime)
com.avc.mis.beta.service.report.InventoryReports.getInventoryWithOrderByItem(ItemGroup, LocalDateTime)

In the previous reports just put null.
in reports add these reports with a point of time. 
Should be separate in reports, not add point of time in inventory tab!

**Comment by mei309** [comment]
i dont see a reason for the last 2. i dont do it in cashew too. 
the first one is nedded

**Comment by mei309** [comment]
i added it with all inventory history in reports. 
if you want separate i just need names for them (thats the reason i put it together)

**Comment by litzvi** [comment]
> i dont see a reason for the last 2. i dont do it in cashew too.
> the first one is nedded

the last one they need most..

**Comment by litzvi** [comment]
In cashew we have other ones..

**Comment by mei309** [comment]
> In cashew we have other ones..

stages of the process.

**Comment by litzvi** [comment]
this is what they need in general

**Comment by mei309** [comment]
by item and by po and with order are all the same details just in different presentations

**Comment by litzvi** [comment]
Specially the last report of general inventory (with the order amount) they need by point of time, so can generate management reports.

**Comment by litzvi** [comment]
> by item and by po and with order are all the same details just in different presentations

yes. just by point of time

**Comment by mei309** [comment]
i added the order one. by po i didnt

**Comment by litzvi** [comment]
thanks
