### ISSUE TITLE
export report - sum containers.

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#573]
Sum by type and totals. 
e.g.

Size | Amount
-- | --
**40'** | 11
**20'** | 16
**Total** | 27

**Comment by litzvi** [comment]
- They load bags/rolls from general inventory to containers. So there should be a way to add from general in loading. After you do it we will check how it shows in the loading and export reports.
- QC needs to show separately in Export report.

Here's there Export report, so you can see the issues
[export-august.csv](https://github.com/litzvi/avc-beta/files/7112945/export-august.csv)

**Comment by litzvi** [comment]
here's our repot for comparison
[mat-table-exporter (18).csv](https://github.com/litzvi/avc-beta/files/7112947/mat-table-exporter.18.csv)
[export_report_august.pdf](https://github.com/litzvi/avc-beta/files/7112948/export_report_august.pdf)

**Comment by mei309** [comment]
> Sum by type and totals.
> e.g.
> 
> Size	Amount
> **40'**	11
> **20'**	16
> **Total**	27

done

**Comment by mei309** [comment]
we already can load them in the version on the cloud

**Comment by mei309** [comment]
QC needs to show separately in Export report.
by them it is because its the same item but by us its different ones, but the main problem is the separation without a real structure, checking by item type is a very nested operation in the front

**Comment by litzvi** [comment]
> > Sum by type and totals.
> > e.g.
> > Size	Amount
> > **40'**	11
> > **20'**	16
> > **Total**	27
> 
> done

Instead of 'container amount' change to 'Containers'

**Comment by litzvi** [comment]
> QC needs to show separately in Export report.
> by them it is because its the same item but by us its different ones, but the main problem is the separation without a real structure, checking by item type is a very nested operation in the front

you have a field 'itemGroup' for every row (not in the item)

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
> > QC needs to show separately in Export report.
> > by them it is because its the same item but by us its different ones, but the main problem is the separation without a real structure, checking by item type is a very nested operation in the front
> 
> you have a field 'itemGroup' for every row (not in the item)

what about this

**Comment by litzvi** [comment]
anyway leave open for me

**Comment by mei309** [comment]
sorry closed by mistake

**Comment by litzvi** [comment]
> we already can load general in the version on the cloud

should be separated to another group, searching by item. Similar to production process.

**Comment by litzvi** [comment]
> we already can load general in the version on the cloud

try loading a general item (e.g. carton, something that isn't measured by weight).
Doesn't display in report - probably because you aren't excluding it in totals.
now that it doesn't display, when I try opening the loading the whole tab gets stuck - shouldn't happen.

**Comment by mei309** [comment]
> > we already can load general in the version on the cloud
> 
> try loading a general item (e.g. carton, something that isn't measured by weight).
> Doesn't display in report - probably because you aren't excluding it in totals.
> now that it doesn't display, when I try opening the loading the whole tab gets stuck - shouldn't happen.
> [AvcVietnam - Google Chrome 2021-09-12 10-50-06.zip](https://github.com/litzvi/avc-beta/files/7148963/AvcVietnam.-.Google.Chrome.2021-09-12.10-50-06.zip)

fixed

**Comment by mei309** [comment]
> > we already can load general in the version on the cloud
> 
> should be separated to another group, searching by item. Similar to production process material used.

done

**Comment by litzvi** [comment]
> QC needs to show separately in Export report.

@mei309  this one is done?

**Comment by mei309** [comment]
> > QC needs to show separately in Export report.
> 
> @mei309  this one is done?

not yet still thinking how to implement it

**Comment by mei309** [comment]
done. if they need more sums open a new issue this one is to crowded
