### ISSUE TITLE
General stock and orders attach rolls and bags

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#574]
put in 2 columns or at least near each other

**Comment by litzvi** [comment]
@mei309  please add code field to other items (currently only in packed cashew).
I need it in general so I can manipulate the sorting order in reports. But you can add it in all items.

**Comment by litzvi** [comment]
After you do it, leave it open so I can remember to adjust.

**Comment by mei309** [comment]
> @mei309 please add code field to other items (currently only in packed cashew).
> I need it in general so I can manipulate the sorting order in reports. But you can add it in all items.

done and works

**Comment by mei309** [comment]
> put in 2 columns or at least near each other

i have no way to know the connection between them. (i can only guess by the name but it isnt right

**Comment by mei309** [comment]
maybe we should have an item that has the combonition of both

**Comment by litzvi** [comment]
> > put in 2 columns or at least near each other
> 
> i have no way to know the connection between them. (i can only guess by the name but it isnt right

that was for me.. that's why I need the code to manipulate it

**Comment by litzvi** [comment]
done
