### ISSUE TITLE
Cashew raw material stock - raw qc defects

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#575]
add a column with the raw qc of avc defects percentage

**Comment by litzvi** [comment]
@mei309 add defects column in 'Cashew raw material stock'.
it's the field rawDefectsAndDamage in ReceiptInventoryRow class.

**Comment by mei309** [comment]
added

**Comment by litzvi** [comment]
I need to change it to roast defects

**Comment by litzvi** [comment]
changed
