### ISSUE TITLE
fixes needed version 10 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#576]
1. in general and cashew PO#, allow text code (I think I already asked for it once).
2. General usage, searching an item should allow any substring. (It's true in must places but specially crucial for items, usually searched by number)

**Comment by mei309** [comment]
1. done

**Comment by mei309** [comment]
2. is connected to the table searchs that i have in different isuue

**Comment by litzvi** [comment]
> 1. is connected to the table searchs that i have in different isuue

I'm not sure you understood.
The item dropdown when choosing the item to "use".

**Comment by mei309** [comment]
i didnt understand. thanks. fixed now
