### ISSUE TITLE
general receiving avc-9 avc-8

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#578]
javax.persistence.NonUniqueResultException: query did not return a unique result: 2
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:128) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1588) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:196) ~[spring-data-jpa-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88) ~[spring-data-jpa-2.3.0.RELEASE.jar:2.3.0.RELEASE]

**Comment by litzvi** [comment]
Where and When does it happen?
I have no data on the queries causing this.

**Comment by mei309** [comment]
use the cloud dump and try receiving avc-8 or avc-9

**Comment by mei309** [comment]
use on your local and see on eclipse

**Comment by mei309** [comment]
you need the dump?

**Comment by litzvi** [comment]
It's all received from April by me. Not sure what dump you are talking about

**Comment by mei309** [comment]
i did a dump yesterday of the data on the cloud

**Comment by litzvi** [comment]
on the cloud it's also received.

**Comment by mei309** [comment]
avc-8 and avc-9 arent

**Comment by mei309** [comment]
avc--8 and avc--9

**Comment by mei309** [comment]
https://user-images.githubusercontent.com/58453503/132871748-8a100ea6-8249-460e-8505-7b554c8ffe4c.mp4

**Comment by mei309** [comment]
thats on the cloud

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/132871947-ad6ca5b9-1fe7-4898-a5ab-c0d0c0b5d55a.PNG">
<img width="1280" alt="Capture1" src="https://user-images.githubusercontent.com/53637868/132871953-ea28e825-0339-4eed-98d8-bd08c9e1514a.PNG">

**Comment by litzvi** [comment]
oh it's (-8)

**Comment by mei309** [comment]
its different  in the amount of "-"

**Comment by litzvi** [comment]
I will check tomorrow

**Comment by litzvi** [comment]
They have 2 orders for the same po. Shouldn't happen.
perhaps sent twice the same form - I need to make sure I block it by me.
Anyway I can't check easily, because 'Remove Management' doesn't work on the new version.

**Comment by litzvi** [comment]
it is process 7222 and 7224

**Comment by litzvi** [comment]
@mei309 fix 'Remove Management'

**Comment by litzvi** [comment]
The order was added twice in a difference of 1 to 3 milliseconds.
I would guess the browser sent the request twice, but still don't understand how it happened because the code doesn't allow adding twice for the same po.

**Comment by litzvi** [comment]
Here what's probably happened. the request was sent twice in a row and done concurrently.
The default isolation REPETABLE_READ therefore it can happen.
I changed the isolation to SERIALIZABLE in new orders but didn't change elsewhere for now because it's slower.
perhaps you are recalling to fast for there slow internet? because even after the fix it will confuse them with an error in case it's sent twice.

**Comment by mei309** [comment]
it was possible by me to press twice directly so in a case of double click it happened. i disabled it so now its not possible but you still need to give the error anyway

**Comment by mei309** [comment]
> it is process 7222 and 7224

7222 of course has a error because there's no such process (it says in the log on eclipse)
all the rest are working great

**Comment by mei309** [comment]
the mechanism to re run stuff waits for a answer therefor it cannot happen that fast

**Comment by litzvi** [comment]
> the mechanism to re run stuff (call again) waits for a answer therefor it cannot happen that fast

ok. so they press twice. If you disable it you can close the issue.
I fixed it on the cloud.

**Comment by mei309** [comment]
disabled it
