### ISSUE TITLE
VAT-45176 can't receive in 2 parts

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#579]
throwing error from
com.avc.mis.beta.service.Receipts.addCashewOrderReceipt(Receipt)
"Po Code of Product can only be received once, in order to correctly reference receipt date by po code");

**Comment by litzvi** [comment]
can't receive twice for the same order

**Comment by litzvi** [comment]
Second part is September 10th

**Comment by litzvi** [comment]
I removed the restriction com.avc.mis.beta.service.Receipts.addCashewOrderReceipt(Receipt) for another receipt on the same po code.
Now need to check where it causes problems with the receipt date. probably in some report.

**Comment by litzvi** [comment]
The problem is it is counted twice in inventory because of 'join Receipt'. 
In InventortRepository.java line 346

**Comment by mei309** [comment]
you already once did that they can receive twice, so why did you change it?

**Comment by litzvi** [comment]
now we can.
i won't close it, so I remember to help them fix it when we upload the next version.

**Comment by litzvi** [comment]
fixed second part to 9/9/2021
