### ISSUE TITLE
All options in management tab not responding

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#580]
in a cloud dump, but also o a different one.
user with ROLE_SYSTEM_MANAGER and ROLE_MANAGER

**Comment by mei309** [comment]
sorry i was checking something and forgot to return it.
it will show only for ROLE_SYSTEM_MANAGER

**Comment by litzvi** [comment]
> sorry i was checking something and forgot to return it.
> it will show only for ROLE_SYSTEM_MANAGER

so now it's fixed? if it is close
when it doesn't show, management should not appear in the menu - not like now that it doesn't respond.

**Comment by mei309** [comment]
> > sorry i was checking something and forgot to return it.
> > it will show only for ROLE_SYSTEM_MANAGER
> 
> so now it's fixed? if it is close
> when it doesn't show, management should not appear in the menu - not like now that it doesn't respond.

it dosent show
