### ISSUE TITLE
Raw report show cleaned too

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#581]
add pruduction use 'clean'.

I think that's what they mean in line 8 of the excel file they sent us.

Actually in there report it separated to 2 parts
Location factory B probably means that.

Attached is there report
[Material 9-21.xlsx](https://github.com/litzvi/avc-beta/files/7151177/Material.9-21.xlsx)

**Comment by mei309** [comment]
why not to do it 2 different ones like they have?

**Comment by mei309** [comment]
they anyway want it separate

**Comment by litzvi** [comment]
> they anyway want it separate

he sees it in one page. up to you

**Comment by mei309** [comment]
i did in 2 if he wants one i will change it later

**Comment by litzvi** [comment]
> i did in 2 if he wants one i will change it later

great
