### ISSUE TITLE
About search drop downs

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#583]
If we are choosing something from a drop down instead of a text field.
With the draw backs of not freely typing, we should expect the benefit of getting only the item we chose.

say we choose roaster from the drop down, see attached. shouldn't show 'roaster in' etc.
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/133023786-249343ab-2313-445d-9a6b-74cda8cb9154.PNG">

**Comment by mei309** [comment]
in the new version you can freely write too

**Comment by litzvi** [comment]
still should only show that option if they choose from the drop down.
It bothered me a few times, when I was trying to choose items by grade and more.

**Comment by litzvi** [comment]
We run into a problem in Purchase Orders ->..-> All
Rows can have a few statuses, now choosing one won't find the ones with a few.
A comma means it's a word for itself.

**Comment by litzvi** [comment]
same thing in suppliers table, supply category

**Comment by mei309** [comment]
it's all over in a multiple options in one cell

**Comment by litzvi** [comment]
Yes. I didn't realize before

**Comment by mei309** [comment]
fixed. if you see some more places let me i know. i checked a lot but still might be a surprise
