### ISSUE TITLE
Loadings of packaged items

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#584]
same as inventory but for loaded by range of dates.

![ef7f732e57ffa1a1f8ee](https://user-images.githubusercontent.com/53637868/133025320-ca7a544c-487f-49c3-ba02-a27a88013656.jpg)

**Comment by litzvi** [comment]
@mei309 whatwhat asked for loading of bagged items for a range of dates.
the display is as in inventory (probably the one they wanted in the first place..)

I added com.avc.mis.beta.service.report.LoadingReports.getCashewBaggedExportReportRows(ItemGroup, ProductionUse[], LocalDateTime, LocalDateTime)

add it in Export .
call it with ItemGroup.PRODUCT, new ProductionUse[] {ProductionUse.PACKED}

**Comment by mei309** [comment]
i think i should also do one of raw, what you think? i think its more consistent

**Comment by mei309** [comment]
so why to use this?
 new ProductionUse[] {ProductionUse.PACKED}
we can show for all cashew items

**Comment by litzvi** [comment]
> so why to use this?
> new ProductionUse[] {ProductionUse.PACKED}
> we can show for all cashew items

look at the picture.
She wants for bagged items

**Comment by mei309** [comment]
Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Cannot read field "scale" because "multiplicand" is null; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Cannot read field "scale" because "multiplicand" is null (through reference chain: java.util.ArrayList[0]->com.avc.mis.beta.service.report.row.CashewBaggedInventoryRow["bagQuantity"])]

**Comment by mei309** [comment]
its ready besides this error

**Comment by litzvi** [comment]
> Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Cannot read field "scale" because "multiplicand" is null; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Cannot read field "scale" because "multiplicand" is null (through reference chain: java.util.ArrayList[0]->com.avc.mis.beta.service.report.row.CashewBaggedInventoryRow["bagQuantity"])]

fixed

**Comment by mei309** [comment]
ok done
