### ISSUE TITLE
Reports -> Productions add info

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#585]
David asked..
start time, end time, down time, labor, 
process name -> production line

**Comment by litzvi** [comment]
![490432dee60d1053491c](https://user-images.githubusercontent.com/53637868/133068861-3814ff31-597f-4508-a6be-801391300292.jpg)

**Comment by litzvi** [comment]
I added to process row
production line, start time, end time, down time, num of workers.
duration will be down time, I'll change the name later.
put production line instead of process name. 

ONLY IN Reports -> Productions, NOT IN PRODUCTION REPORTS.

**Comment by mei309** [comment]
we need to take care of the details first we dont have a duration input. i will suggest soon a few options

**Comment by litzvi** [comment]
leave the duration for after the upload

**Comment by mei309** [comment]
> leave the duration for after the upload.
> we will change it to down time

just so you know town time isnt the correct word. it means the stopped time

**Comment by mei309** [comment]
and i left for now the process name because all production lines are empty

**Comment by litzvi** [comment]
I changed duration to downtime. so try to let them put it in and then show in productions.
I'll fix it in the database, so should work if you use a new dump.

**Comment by litzvi** [comment]
if you prefer 'interruption' over downtime let me know

**Comment by mei309** [comment]
we talked once about start time and end time that we need the actual times and therefor we should change it to choosing date and time for the start and the end and then the duration will be from that

**Comment by mei309** [comment]
> if you prefer 'interruption' over downtime let me know

i dont really care about the name but according to google downtime is the time a machine was broken

**Comment by mei309** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/58453503/134787460-6e6b8747-a7d0-4d82-bb91-9cf41365d37b.png)

**Comment by litzvi** [comment]
So let's speak about it again. 
I only remember saying it should be a local date (without a time and offset).
But leaving out the time they will lose the flexibility to search within a date.
The problem with the way you are suggesting that it forces them to choose it.

**Comment by litzvi** [comment]
about this date and time range.
It's nice, but I don't like that you need to scroll for the time. not suitable for a computer typing in the time is way better.
btw, the start and end time fields are very convenient. I just filled some data last week and liked it.

**Comment by mei309** [comment]
for now this is ok if we need to change it will be a new issue
