### ISSUE TITLE
Production functionality - small display issue

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#586]
one before last line in drop down.

also we should see which ones we aren't using and remove to avoid confusion.

**Comment by litzvi** [comment]
<img width="1280" alt="Capture1" src="https://user-images.githubusercontent.com/53637868/133188243-33f4f3d3-450a-42a7-a9a1-d7911f30660f.PNG">

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/133217927-bc3cd956-e457-47f8-a842-e61437164e0c.PNG">

**Comment by mei309** [comment]
fixed
