### ISSUE TITLE
raw inventory add h&p and whole

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#587]
since its bulk items they dont have it whole or not, so how can we give that infromation?

**Comment by litzvi** [comment]
היא הנותנת

**Comment by litzvi** [comment]
add whole field in bulk.
I added getType for ReceiptInventoryRow.

just add 2 columns and make the current column as total.

**Comment by mei309** [comment]
once i have the new version i will do the totals

**Comment by mei309** [comment]
ok done
