### ISSUE TITLE
a small fix.

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#589]
in storageMove do itemPoCodes like in storageMoves now in case of one it gives null

**Comment by litzvi** [comment]
I don't understand.

**Comment by mei309** [comment]
you have a field itemPoCodes in storageMove and its null in case of one po, unlike in storageMoves there its not null in case of one

**Comment by litzvi** [comment]
> you have a field itemPoCodes in storageMove and its null in case of one po, unlike in storageMoves there its not null in case of one

what class? what method? give me an example please

**Comment by mei309** [comment]
https://user-images.githubusercontent.com/58453503/134406501-849f7c7d-1852-4263-8835-aa88ab906457.mp4

**Comment by litzvi** [comment]
How is storage move connected to loading?
please give me the service/function/class you are calling?

**Comment by mei309** [comment]
ContainerLoading extends RelocationProcess

**Comment by mei309** [comment]
loading.getLoading(load.getId());

**Comment by mei309** [comment]
ContainerLoadingDTO extends RelocationProcessDTO

**Comment by litzvi** [comment]
thanks. added

**Comment by mei309** [comment]
ok done
