### ISSUE TITLE
version 23.4.6 check

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#590]
- Schedules are showing the last 2 weeks by default. cashew and general
- Edit Shipment Code doesn't show the previously chosen Destination port.
- Management tab is not working with my user (with eli it is working)
- We should see what production functionalities we aren't using and remove them to avoid confusion.
- seamless uploading of new data. e.g. try using Eli's user for messages and choosing all records. after a few long seconds it changes with out any affect unless you follow the number of rows.

**Comment by mei309** [comment]
1. what should we do we want to show all and therefor its a lot of information i suggest 1) to separate it to 2 different tabs one of receiving and one of received 2) to show only the open ones 3) like now to only show receiving by time (default 2 last weeks or today)

**Comment by mei309** [comment]
2. done
3. fixed
4. they all look reasonable to me. (im not using RAW_STATION and PACKING_STATION and im using TOFFEE THAT YOU DONT HAVE

**Comment by mei309** [comment]
5. fixed in all tables

**Comment by litzvi** [comment]
> 1. what should we do we want to show all and therefor its a lot of information i suggest 1) to separate it to 2 different tabs one of receiving and one of received 2) to show only the open ones 3) like now to only show receiving by time (default 2 last weeks or today)

they use the schedule for the future. I don't mind you leave the options. It's the default that's wrong.

**Comment by litzvi** [comment]
> Management tab is not working with my user (with eli it is working)

doesn't help me test if you don't send me the new version

**Comment by litzvi** [comment]
> they all look reasonable to me. (im not using RAW_STATION and PACKING_STATION and im using TOFFEE THAT YOU DONT HAVE

I added TOFFEE, make sure you add it's added in setup.

**Comment by mei309** [comment]
> > 1. what should we do we want to show all and therefor its a lot of information i suggest 1) to separate it to 2 different tabs one of receiving and one of received 2) to show only the open ones 3) like now to only show receiving by time (default 2 last weeks or today)
> 
> they use the schedule for the future. I don't mind you leave the options. It's the default that's wrong.

added from today

**Comment by litzvi** [comment]
if you did all close the issue
