### ISSUE TITLE
Value and null look merged in table

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#591]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/134174257-073999fe-0c3f-46d0-930c-d49d74b54e1b.PNG">

p.a. in case it causes problem somwhere.

**Comment by mei309** [comment]
fixed

**Comment by mei309** [comment]
i checked all the places i know of and it dose not seem to be a problem in more places
