### ISSUE TITLE
Cashew clean material stock - not showing

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#592]
pay attention. it won't work.

for now use getFinishedProductInventoryRows and display accordingly.

**Comment by litzvi** [comment]
maybe it won't display well either.. need to see what makes sense.

**Comment by mei309** [comment]
why this one isnt working?

**Comment by litzvi** [comment]
> why this one isnt working?
> inventoryReports.getReceiptInventoryRows(ItemGroup.PRODUCT, new ProductionUse[] {ProductionUse.CLEAN}, date);

I know. it only searches for receipt item.

**Comment by litzvi** [comment]
> pay attention. it won't work.
> 
> for now use getFinishedProductInventoryRows and display accordingly.

read this

**Comment by mei309** [comment]
i did it but i cannot do the summaries in the bottom with that info

**Comment by litzvi** [comment]
Just do like finished for now. let's see what they say

**Comment by litzvi** [comment]
I will try fixing it to be like receipt later. That's probably what they want.

**Comment by litzvi** [comment]
1.  David asked to add defects to the Cashew clean material stock (like in receipt). So I added it in the FinishedProductInventoryRow for clean(the one you are using).
2. Status is only applicable in Cashew raw material stock (ReceiptInventoryRow), all the rest are only final, so you can remove the status column from them. I'll make it @JsonIgnore too.

**Comment by mei309** [comment]
done done

**Comment by mei309** [comment]
i think we should remove  
Box quantity and Box weight
in cleaned what you think?

**Comment by litzvi** [comment]
> i think i should not show
> Box quantity and Box weight
> in cleaned what you think?

yes they are all null.

**Comment by mei309** [comment]
done

**Comment by mei309** [comment]
you know what sums they want on this report?

**Comment by litzvi** [comment]
They will ask..
