### ISSUE TITLE
Relocation - count section

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#593]
- I see more than 1 option when choosing the counted item. e.g I'm moving W320 but I see an option for W320,W340,..
- I suggest the measure unit in that section be KG for now regardless of the item or maybe better don't choose a default

**Comment by mei309** [comment]
1) by me its not happening so give me a po and i will try.
2) keep for after the upload (but i think its better by the default since they might count in that way)

**Comment by litzvi** [comment]
![Capture](https://user-images.githubusercontent.com/53637868/134364582-6f18997b-dd74-404f-b670-dee46d8d855a.PNG)

this is just editing a random 'cleaned relocation'

**Comment by litzvi** [comment]
![tempsnip](https://user-images.githubusercontent.com/53637868/134365351-6a06b5bb-bcbc-4dfb-957e-e25a6028e3a1.png)

Now they are using KG (We can always change) Better leave it empty, just to reduce mistakes.

**Comment by litzvi** [comment]
> 1. by me its not happening so give me a po and i will try.
> 2. keep for after the upload (but i think its better by the default since they might count in that way)

1. I guess it's working only in raw relocation, not cleaned
2. It wasn't a problem because they didn't fill count in 'cleaned relocation' (in raw, the default is KG)

**Comment by litzvi** [comment]
> now they starting to use it??

they got used not filling - but they should.

**Comment by mei309** [comment]
its working by me also raw and also clean

**Comment by mei309** [comment]
and put default kg always

**Comment by litzvi** [comment]
> its working by me also raw and also clean

sorry it's because that item wasn't set a grade.

**Comment by mei309** [comment]
so done.
