### ISSUE TITLE
Show time on used items

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#594]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/134273313-ec5f42f7-2e2a-4497-8dc3-950ffa22b6a9.PNG">

**Comment by litzvi** [comment]
Very Important!
Time is needed because unsynchronized time in the process will fail.

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
thank you but it became super ugly. maybe the time in a new line ?

<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/134456216-f9c1652b-fbeb-4109-801b-c0bd32687280.PNG">

**Comment by mei309** [comment]
fixed
