### ISSUE TITLE
Edit from Productions Report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#595]
You could allow edit from Productions Report, for making it easier for David

**Comment by litzvi** [comment]
> i allowed but after edit for now he wouldn't return there. if its necessary that he can return let me know and i will add a button of return but i dont have a real way to keep the filters like with normal edit

of course should to return to the same place, if it's not too difficult.

**Comment by mei309** [comment]
i could add a button but like i said i cannot keep the filters is it still useful?

**Comment by litzvi** [comment]
Yes

**Comment by litzvi** [comment]
> i could add a button but like i said i cannot keep the filters is it still useful?

what button? i meant double click and opens just like in other reports

**Comment by litzvi** [comment]
then when close he's back in the same page

**Comment by mei309** [comment]
thats what i mean.

**Comment by mei309** [comment]
ok done see if you like the way. it works only for manager

**Comment by litzvi** [comment]
I see you didn't change Duration name in reports->productions

**Comment by litzvi** [comment]
> ok done see if you like the way. it works only for manager

It good. only the edit I don't like but way better than nothing.

**Comment by mei309** [comment]
done
