### ISSUE TITLE
Security doc - loaded items

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#598]
bag amount -> unit amount
number of bags -> number of units

<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/134281045-2a14ca52-1581-4282-aef6-15288434091f.PNG">

**Comment by mei309** [comment]
changed but think its weird since we have number of units and number of boxes

**Comment by litzvi** [comment]
In packed items, they are practically the same.
But when you upload non packed item - say 1000 apples - boxes will be different (if its in 1 line it will show 1 box).
An example if you pack a bulk QC item in 3 bags of 500lb, number of units should be 1,500lb but 3 boxes.

**Comment by mei309** [comment]
ok done
