### ISSUE TITLE
Export Report -> Exported by container

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#599]
you aren't showing QC box column.
(I see you removed 'box quantity' from qc item, but you need it for displaying in QC box column)

**Comment by mei309** [comment]
> you aren't showing QC box column.
> (I see you removed 'box quantity' from qc item, but you need it for displaying in QC box column)

you mean bagQuantity?

**Comment by mei309** [comment]
and i do have boxQuantity in Export Report -> Exported by container

**Comment by litzvi** [comment]
<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/53637868/134362150-715e4158-5c25-4c2a-a836-3e24ef2dff44.PNG">

try loading a qc item on a container, then see it doesn't show in this table

**Comment by litzvi** [comment]
- create a qc item (you can try bulk and packed)
- pack qc to the previous item
- load it on container
- see if it shows qc box correctly (box quantity should be empty, instead should show on QC box)

**Comment by mei309** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/58453503/134372904-40250a61-7df2-4279-a1d4-93b88b51482e.png)

**Comment by litzvi** [comment]
> by me it dose show qc but only for packed items. not for bulk items.
> yyyyy => qc bulk
> gefgh => qc packed

yes I'm talking about the bulk

**Comment by mei309** [comment]
and im also not getting it from you

**Comment by mei309** [comment]
and it happens also in cashew bulk items because bulk has no meaning of box

**Comment by litzvi** [comment]
it counts the "bags".
e.g. 50*317 will be 317 "boxes'
or say they fill n fields in a table (n storages) will show n boxes.
If not clear enough then call.

**Comment by mei309** [comment]
i really have no clue what you want me to do? in packed item you giving me boxQuantity but in bulk you giving it null and i dont have in this report no information to determine it.

**Comment by litzvi** [comment]
sorry fixed boxQuantity (only did it in a different class)

**Comment by litzvi** [comment]
please add roast to item setup of cashew bulk and QC (both)

**Comment by mei309** [comment]
done done
