### ISSUE TITLE
Change of UsedItem field name 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#60]
UsedItem field: numberUnits changed to usedUnits.
please apply from version 2.2

e.g. it's an important change in case i'll want to have an Entity that's a UsedItem and a Storage (for solving the transfer problem), there can't be the same field in both.

**Comment by mei309** [comment]
i changed but it will have a lot of errors probably

**Comment by mei309** [comment]
its a very big error prone. because i have usedUnits

**Comment by mei309** [comment]
change one of the usedUnites to a differint name

**Comment by litzvi** [comment]
What about usedNumberUnits?

**Comment by mei309** [comment]
ok

**Comment by litzvi** [comment]
sorry numberUsedUnits.
i'll change it for version 2.4
