### ISSUE TITLE
Measure Unit TON added

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#600]
1 TON = 1000 KG.
Add it where necessary (It's a weight unit).

requires database UOM table to be updated.
attached is the new data.
[new_uom.csv](https://github.com/litzvi/avc-beta/files/7214950/new_uom.csv)

**Comment by litzvi** [comment]
If you prefer this format
[ebdb_uom.zip](https://github.com/litzvi/avc-beta/files/7214963/ebdb_uom.zip)

**Comment by mei309** [comment]
> If you prefer this format
> [ebdb_uom.zip](https://github.com/litzvi/avc-beta/files/7214963/ebdb_uom.zip)

definitely this one

**Comment by mei309** [comment]
added everywhere i know
