### ISSUE TITLE
Bill of materials more then one item

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#605]
I started to prepare bom - the materials needed to create a product. 
So you will be able to choose the appropriate items in a process, as requested by David.
And then we will use it for production plan too.

@mei309 Just started, it's not ready, but if you want you can look in BillOfMaterials, BomLine classes (in entities.item package)
and in BillOfMaterialService and see if you have some insight.

**Comment by litzvi** [comment]
added com.avc.mis.beta.service.ValueTablesReader.getProductBillOfMaterials(Integer, ItemGroup, ProductionUse)
to use in production form. I'm not sure how you will use it, so please tell me what you need. perhaps you only need the item ids etc.

**Comment by litzvi** [comment]
I built it with dtos both ways this time.

**Comment by mei309** [comment]
it looks ok but the defaults will be a big problem in the production form because of convesion

**Comment by litzvi** [comment]
> it looks ok but the defaults will be a big problem in the production form because of convesion

I don't think you need to play with the defaults. Probably should be done by the backend.

**Comment by mei309** [comment]
> > it looks ok but the defaults will be a big problem in the production form because of convesion
> 
> I don't think you need to play with the defaults. Probably should be done by the backend.

its always the same amounts or they can change it?

**Comment by litzvi** [comment]
THEY CAN EDIT.
Amounts is to calculate the needed inventory for the plan, that's later.
For now you need

- a place for them to add/edit data of bom.
- show the default items in production (it's only for reducing mistakes , they can still fill everything.)

**Comment by mei309** [comment]
ok

**Comment by mei309** [comment]
a function to get all would be helpful

**Comment by mei309** [comment]
once you do the function upload and let me know. its very hard to check it otherwise

**Comment by mei309** [comment]
and also restrict to one bom per product

**Comment by mei309** [comment]
otherwise its working

**Comment by litzvi** [comment]
> a function to get all would be helpful

of course. not sure what data to add.
is this ok?
com.avc.mis.beta.service.ValueTablesReader.getAllBillOfMaterials()

**Comment by litzvi** [comment]
> and also restrict to one bom per product

it is

**Comment by mei309** [comment]
> getAllBillOfMaterials

yup. just to show a table of it so we can edit

**Comment by mei309** [comment]
its done.

**Comment by mei309** [comment]
should i restrict the items to only roasted and packed?

**Comment by litzvi** [comment]
> > > a function to get all would be helpful
> > 
> > 
> > of course. not sure what data to add. is this ok? com.avc.mis.beta.service.ValueTablesReader.getAllBillOfMaterials()
> 
> now you only showing the product and the default mu why not the materials?

you want to show all materials in the table? and if so the amounts too?
I thought you will only show the product and they click and get full details.

**Comment by litzvi** [comment]
> > > a function to get all would be helpful
> > 
> > 
> > of course. not sure what data to add. is this ok? com.avc.mis.beta.service.ValueTablesReader.getAllBillOfMaterials()
> 
> now you only showing the product and the default mu why not the materials?

ok use this one.
com.avc.mis.beta.service.BillOfMaterialService.getAllBillOfMaterials()

**Comment by mei309** [comment]
done for first item not if more are added so leave it open

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
look on the cloud. the ring is turning, now that it's empty

**Comment by litzvi** [comment]
in a new production, you are giving a message that there isn't a bill of materials.

**Comment by mei309** [comment]
> look on the cloud. the ring is turning, now that it's empty

you arent giving back anything in this case so my code doesn't know if we still waiting

**Comment by litzvi** [comment]
> > look on the cloud. the ring is turning, now that it's empty
> 
> you giving back null vs everywhere else you giving empty array. if you change it let me know

not true. many places it's null

**Comment by litzvi** [comment]
So how do we solve it?
Can I return it in a map<Item, List<ProcessItemInventory>> for every item in bom? if the there is no list you know it's missing.

**Comment by mei309** [comment]
> > why not one map with 2 lists? if you give the storages list separately and the unfulfilled list it will be easier then starting to connect and etc... but if you think this is better its ok with me
> 
> okay. but then a map has no meaning. I'll just give u an array or list of lists.

no problem. let me know when up

**Comment by mei309** [comment]
did by me but just so you know this is the way to do it

ArrayList<Integer> itemsList = new ArrayList(Arrays.asList(itemIds)); if not we cannot remove from it
itemsList.removeAll(inventory.stream().map(i -> i.getItem().getId()).collect(Collectors.toList())); returns boolean 
return new Object[]{inventory, itemsList};

**Comment by mei309** [comment]
> you are ignoring the case that bill of materials wasn't defined. It's good - correct.

i didnt ignore. i put  a try catch
