### ISSUE TITLE
Choose a few options in table filters

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#609]
@David asked. they want to generate reports with a few items or say LY an AVC

**Comment by mei309** [comment]
> It will be super powerful. let me know what you think.

it will definitely be super powerful. its hard but i will try

**Comment by mei309** [comment]
> Another thing. Once we leave the selection - say choose a supplier - and then go back it doesn't respond.

can you tell me in which field? because its working by me

**Comment by litzvi** [comment]
> > Another thing. Once we leave the selection - say choose a supplier - and then go back it doesn't respond.
> 
> can you tell me in which field? because its working by me

choose 2 in items, then choose a supplier and try to change items

**Comment by litzvi** [comment]
for example
Cashew raw material stock
