### ISSUE TITLE
filters in production reports

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#614]
Don't remember where we ended up with this issue.
used items and produced items filters, can't search.
Also if can search, you should add materials and waste too

**Comment by mei309** [comment]
should i do it multiple or not?

**Comment by mei309** [comment]
> > should i do it multiple or not?
> 
> no. multiple only for reports for printing

i did multiple almost everywhere already

**Comment by litzvi** [comment]
> > > should i do it multiple or not?
> > 
> > 
> > no. multiple only for reports for printing
> 
> i did multiple almost everywhere already

So don't do more
I told you only reports
