### ISSUE TITLE
General Inventory History Report - amount and measure unit seperate

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#619]
she want's them in separate columns. so she can use it conveniently in excel.
e.g. 500 | KG

**Comment by mei309** [comment]
not possible. its totals with lbs and kg in some cases so which one i need to put? 
i dont think its a good change

**Comment by litzvi** [comment]
okay I added. only in "Inventory=>General Stock=> General Stock/oder"

**Comment by litzvi** [comment]
@david told me that. Anyway it's correct, so they can make calculations
etc. In excel.
Can you see what her problem is?

**Comment by mei309** [comment]
> Why didn't you do this before you upload?

because it wasn't simple

**Comment by mei309** [comment]
it looks like this was the only place they wanted it. so closing
