### ISSUE TITLE
StorageRelocation 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#62]
I added StorageRelocation  process which is basically a StorageTransfer without processItems and used..
it has StorageMoves (and ItemCounts like transfer)
a StorageMove is a UsedItem and also a Storage, so it functions as both. the forms can change therefore for now you have to set all. If you'll need an helper method to easily set it I'll build it.

the service for StorageLocation is WarehouseManagement (I'll probably separate them later)

**Comment by mei309** [comment]
why you doing it now?

**Comment by mei309** [comment]
nothing is working now

**Comment by mei309** [comment]
getting of prudoction and the tables

**Comment by litzvi** [comment]
It shouldn't really affect anything else.
probably just minor stuff.
Because it bothered me..

**Comment by litzvi** [comment]
you need to rebuild the database

**Comment by mei309** [comment]
it also dosent have itemcount

**Comment by mei309** [comment]
and it looks a big change when we want to show them

**Comment by litzvi** [comment]
it has itemCount (in PoProcess)
it's not a big change..
you don't have to use it now, I just prepared it

**Comment by litzvi** [comment]
didn't change anything in other processes

**Comment by mei309** [comment]
it dose a round error

**Comment by mei309** [comment]
at com.avc.mis.beta.entities.processinfo.StorageMove.toString(StorageMove.java:26) ~[classes/:na]
	at java.util.Arrays.deepToString(Arrays.java:4669) ~[na:1.8.0_171]
	at java.util.Arrays.deepToString(Arrays.java:4619) ~[na:1.8.0_171]
	at com.avc.mis.beta.entities.process.StorageRelocation.toString(StorageRelocation.java:31) ~[classes/:na]
	at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_171]
	at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_171]
	at com.avc.mis.beta.entities.processinfo.StorageMove.toString(StorageMove.java:26) ~[classes/:na]
	at java.util.Arrays.deepToString(Arrays.java:4669) ~[na:1.8.0_171]
	at java.util.Arrays.deepToString(Arrays.java:4619) ~[na:1.8.0_171]
	at com.avc.mis.beta.entities.process.StorageRelocation.toString(StorageRelocation.java:31) ~[classes/:na]
	at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_171]
	at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_171]

**Comment by litzvi** [comment]
StorageMove.java line 40 add

@ToString.Exclude

**Comment by mei309** [comment]
storageMove has a storage like usedItem? because its a basicUsedItem? im i correct ?
if yes why it has unitAmount and numberUnits

**Comment by mei309** [comment]
important. please try explaining it good if you could

**Comment by litzvi** [comment]
> storageMove has a storage like usedItem? because its a basicUsedItem? im i correct ?
yes!
> if yes why it has unitAmount and numberUnits
these are of the 'new' storage.

storageMove is a usedItem of the 'old' storage - that's what the storage field in BasicUsedItem refers to.
storageMove is a new storage, just like the storage you know - that's what all the fields  StorageMove class definition refer to.

**Comment by mei309** [comment]
i need it to support a table view

**Comment by litzvi** [comment]
otherwise it's working for you?

**Comment by mei309** [comment]
yes

**Comment by mei309** [comment]
i didnt yet try edit

**Comment by mei309** [comment]
edit isnt working today

**Comment by litzvi** [comment]
setStorageMove(UsedItemTableDTO usedItemTable), please try this for inserting first.
version 4.5 - uploaded already

**Comment by mei309** [comment]
> setStorageMove(UsedItemTableDTO usedItemTable), please try this for inserting first.
> version 4.5 - uploaded already

i need a few because i can have a lot of different processitems that are moved

**Comment by litzvi** [comment]
SO SHOULD I WRRAP THE storageMoves into groups like i did for usedItems?

**Comment by mei309** [comment]
just put 2 arrays one for tables and one for normal

**Comment by litzvi** [comment]
but it's one or the other, if you set by table you don't set by storage and vice versa.
It's not really the right way to do it

**Comment by mei309** [comment]
> It can't be done this way, because I have no way to gather the used storages together in a group for showing as a table.
> Even if I do it's one or the other, if you set by table you don't set by storage and vice versa.
> It's not really the right way to do it.
> 
> If you want it in this structure you need to give all in one table as you have it now, can only move 1 UsedItemTableDTO at a time.

so wrrap it up. because we need it to be correct and flexible and it will be the same as all so its ok

**Comment by litzvi** [comment]
ok done. version 4.8

**Comment by mei309** [comment]
its working now

**Comment by litzvi** [comment]
great
