### ISSUE TITLE
TOGGLE BUTTONS 

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#64]
SHOULD BE ABLE TO CANCEL TOGGLE BUTTONS.
e.g. in qc if i chose ok by mistake when didn't check.

**Comment by mei309** [comment]
toggles and radio buttons not supposed to cancel.

**Comment by mei309** [comment]
and putting 2 checkboxes would look silly

**Comment by litzvi** [comment]
ok just ignore it, if there isn't a way.
