### ISSUE TITLE
Small size should always be a number - also pay attention to the ugly error caused by parser

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#65]
Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `java.math.BigInteger` from String "5.6": not a valid representation; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.math.BigInteger` from String "5.6": not a valid representation

**Comment by litzvi** [comment]
never mind i'll change the BigInteger to a BigDecimal
only regard the part of the ugly error

**Comment by mei309** [comment]
in what case you get it??

**Comment by litzvi** [comment]
try giving a decimal number to an integer value

**Comment by mei309** [comment]
its a very clear error so its ok in my opinion and its something i need to not allow anyway

**Comment by mei309** [comment]
the major problem is that its a nested error so we only see object object so add it to your exption controller

**Comment by litzvi** [comment]
what exception? give me the exact exception

**Comment by mei309** [comment]
HttpMessageNotReadableException nested .InvalidFormatException

**Comment by litzvi** [comment]
I think that's outside of the scope of spring - it must be happening by the parser.
So never mind about it for now.
