### ISSUE TITLE
WHY NOT TO CHANGE ITEM IN QC?

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#66]
I KNOW IT'S NOT UPDATABLE. IS THERE A SPECIAL REASON WHY?

**Comment by mei309** [comment]
not by me

**Comment by litzvi** [comment]
Ok, so let's make the item editable in a QC form - i'll change it by me (need to rebuild the table)

**Comment by mei309** [comment]
i dont have version

**Comment by litzvi** [comment]
item is a valueEntity - doesn't have a version

**Comment by mei309** [comment]
it dose not work. check by you

**Comment by mei309** [comment]
@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemId", updatable = false, nullable = false)
	@NotNull(message = "Item is mandatory", groups = OnPersist.class)
	private Item item;

**Comment by mei309** [comment]
cant change

**Comment by litzvi** [comment]
in CashewItemQuality by me - you not updated

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "itemId", nullable = false)
@NotNull(message = "Item is mandatory", groups = OnPersist.class)
private Item item;

**Comment by mei309** [comment]
ok working

**Comment by litzvi** [comment]
STILL CAN'T CHANGE AN ITEM

**Comment by mei309** [comment]
ok working
