### ISSUE TITLE
Checked by in QC report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#68]
why are you showing: 
Checked by | CASHEW_RECEIPT_QC

Also when clicking the joint part of a line in QC#Reports#raw check, it only shows one when you have multiple checks.

**Comment by mei309** [comment]
clicking the joint solved

**Comment by mei309** [comment]
showing later

**Comment by mei309** [comment]
ok solved. please look at it

**Comment by litzvi** [comment]
so now you don't show Inspector and Sample Taker at all?

**Comment by litzvi** [comment]
now everything shows all, better if joint part shows all and separate part only one

**Comment by litzvi** [comment]
and now it doesn't compare to the standard

**Comment by mei309** [comment]
now everything shows all, better if joint part shows all and separate part only one? what you mean?

**Comment by mei309** [comment]
so now you don't show Inspector and Sample Taker at all? only whe you get to it from qc reports. look on po reports. because i want to change the way i show it

**Comment by mei309** [comment]
i want to show all togother always

**Comment by litzvi** [comment]
didn't understand

**Comment by mei309** [comment]
i know what you talking about. its better if you call for this
