### ISSUE TITLE
Inventory Report please show both times

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#70]
I have 2 times of interest
 - receipt time
 - process time (last process)

**Comment by mei309** [comment]
what about prudoction reports??

**Comment by mei309** [comment]
you dont have the fieids in processrow

**Comment by litzvi** [comment]
what do you need in processRow? 
you have recordedTime
I don't think you need anything else

**Comment by litzvi** [comment]
I SEE YOU FIXED THE TIMES IN INVENTORY REPORT BY ITEM. DO THE SAME FOR THE TABLE BY PO

**Comment by mei309** [comment]
ok solved
