### ISSUE TITLE
Transfer with samples not working

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#71]
it shows a message " ..no bags.."
also don't call it samples

**Comment by mei309** [comment]
you dont have the last version

**Comment by mei309** [comment]
removd it a long time ago

**Comment by litzvi** [comment]
dose not have bags for sample
is the error i get

**Comment by litzvi** [comment]
can you please tell me what function your calling for submitting that page

**Comment by mei309** [comment]
its because the transfer is working on storage and not on storageforms

**Comment by mei309** [comment]
i will fix tomoworw

**Comment by litzvi** [comment]
".. working on storage and not on storageforms" don't understand storageForms = storages, it's just a name of the variable.
private Set<Storage> storageForms;

**Comment by mei309** [comment]
storageforms is useditems.
storage is useditem

**Comment by litzvi** [comment]
no.
storageforms is storages in processItem
storage is the same represented as a table
