### ISSUE TITLE
 java.sql.SQLIntegrityConstraintViolationException: Column 'number_used_units' cannot be null

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#72]

**Comment by mei309** [comment]
in receiptitem

**Comment by litzvi** [comment]
can you look in the table- 'receipt_items', if there is a column number_used_units

**Comment by litzvi** [comment]
also can you send me via email your application.properties

**Comment by mei309** [comment]
theres no number_used_units in receiptitem

**Comment by litzvi** [comment]
of course not!
where is it? because there isn't by me
where is the error coming from?

**Comment by litzvi** [comment]
add this line to properties file

spring.jpa.properties.hibernate.validator.apply_to_ddl=false

you'll have to rebuild the database

**Comment by litzvi** [comment]
you say it's working
