### ISSUE TITLE
Number of bags in cleaning details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#73]
not showing

**Comment by litzvi** [comment]
also you aren't setting the numberUsedUnits (so it gets a default of one)

**Comment by litzvi** [comment]
ALSO IN EDIT YOU'RE NOT SHOUWING AMOUNT IN TRANSFER FROM THERFORE WRONGLY EDITTING TO DEFAULT 1

**Comment by mei309** [comment]
i cant know how much is used because numberusedunits is only in this production therefor its not correct

**Comment by mei309** [comment]
i need to show how much totel is used

**Comment by litzvi** [comment]
ok i'll add a field otherUsedUnits

**Comment by mei309** [comment]
not helpful. give a field of all used

**Comment by litzvi** [comment]
it is 'allUsed'(minus used by this process). I thought it's better because it's exactly like in the begining.
are you sure you want including - it will be confusing.
e.g. storage had 300 other processes used 100 and this process 50, if you show (300, 150, 50) it's confusing once you change the 50, that's why I excluded it. 
so what i'm giving you is (300,100,50)

**Comment by mei309** [comment]
ok.

**Comment by mei309** [comment]
you should have it in StorageInventoryRow also insted of numberUsedUnits

**Comment by litzvi** [comment]
not sure what you mean.
numberUsedUnits in StorageInventoryRow is all used.

**Comment by mei309** [comment]
its better if its the same name

**Comment by litzvi** [comment]
they have a different meaning
numberUsedUnits in StorageInventoryRow is everything used from this storage.
otherUsedUnits in the DTO all used by **different** UsedItems

**Comment by mei309** [comment]
ok. solved.
