### ISSUE TITLE
Add ordinal everywhere

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#74]
Added ordinal for all entites that are added as Collections.
e.g. usedItems, processItems, UsedItemsGroup etc. should have ordinals to be displayed correctly in lists, tables etc.

You don't need to do anything since the entity sets it automatically if you ignore it.
I tried to fetch everything by it's order.

please let me know if anything is not presented in the original order.
from version 3.0

**Comment by mei309** [comment]
ok

**Comment by litzvi** [comment]
perhaps need to recheck the sets in the DTO since it's not guaranteed to be in order

**Comment by litzvi** [comment]
done
