### ISSUE TITLE
Inventory reports or anywhere else

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#77]
Inventory reports or anywhere else please avoid calling warehouse storage.
call it warehouse or location to avoid confusion

**Comment by litzvi** [comment]
Also there is no such thing as 'continers'
it's misspelled and also should probably be shipping

**Comment by mei309** [comment]
ok. changed. if you see another please open and write

**Comment by litzvi** [comment]
sorry, export is probably better than shipping.
looks weird - shipping->loading

**Comment by mei309** [comment]
its really not true. we going to have also orders of containers

**Comment by litzvi** [comment]
ok
