### ISSUE TITLE
LOADING

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#78]
DON'T PUT A DEFAULT IN CONTAINER SIZE - FORCE TO CHOOSE

**Comment by litzvi** [comment]
ALSO LODING ISN'T WORKING
ERROR: Loaded item line has to contain at least one storage line
ARE YOU FILLING THE LOADED ITEMS CORRECTLY?

**Comment by mei309** [comment]
working by me. without po but working for now

**Comment by litzvi** [comment]
etd, eta - write in full capitals ETA, ETD
why do you have the destination port twice in the form?
edit not working.
About po code - it could be a few, we should show container and shipping information.

**Comment by litzvi** [comment]
in container loading 
if i fill only code, it will allow me to move to the next page of load, but than will give an error when loading items.
1. best if you can allow to go back to the previous page to add container details etc.
2. also show what's mandatory already in the first page.

**Comment by litzvi** [comment]
DECLARED AMOUNT DEFAULT IS IN LBS.
also, declared amount is only for Ly, so i might remove it, anyway in version 2.9 it's not mandatory, so don't send anything if it's not filled (that's what we did elsewhere right?)

**Comment by litzvi** [comment]
Shipping reports
should have shipmentCode, eta, containerSize
