### ISSUE TITLE
container details

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#79]
give container export doc
for security: (date of process, vehicle, driver, driver phone, driver id), lines->by boxes (item desc, unit_quntity(num of boxes), unit_type(box), purpose(sell), po#, accompanying documents(?)) + total gross weight
for inventory - item amounts: (date of process, vehicle, driver, driver phone, driver id), lines->by weight(lbs) (item desc, total weight, po#, weight-unit_type(lbs), number_unit(weight), shipping code)
for custom: by amounts, if Ly so also the original order amount

**Comment by litzvi** [comment]
service#Loading#getInventoryExportDoc(int processId) - get the export document they print for inventory.
add a link to get it in the Loading/shipments table or from a loading details (preferably both).

**Comment by mei309** [comment]
how exactly its a docs??? its just objects

**Comment by litzvi** [comment]
it's it's a slip they have - type of document they output.
you just show it like details (and would usually be printed).
I'll send you a picture of this slip

**Comment by mei309** [comment]
look at it tomorrow. the security is a bit strange because of the table view. let me know how we can fix it

**Comment by litzvi** [comment]
now it's not working
error: object object

**Comment by mei309** [comment]
you downloaded my new controllers??

**Comment by litzvi** [comment]
yes

**Comment by mei309** [comment]
for some reason immediately after adding its not working but afterwards its working

**Comment by mei309** [comment]
ok fixed
