### ISSUE TITLE
QC raw - inspector, sample taker

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#8]
Raw QC: add inspector, people who took the samples

**Comment by litzvi** [comment]
reopen..

**Comment by litzvi** [comment]
closing with message

**Comment by litzvi** [comment]
I added to QualityCheck class:
private String inspector;
private String sampleTaker;

**Comment by mei309** [comment]
added. also added qc raw percentage

**Comment by litzvi** [comment]
SMALL SIZE SHOULD ALSO BE PERCENTAGE.
ALLOW .6 FORMT (WITHOUT LEADING ZERO)

**Comment by litzvi** [comment]
ALSO, MIGHT BE NICER IF THEY CAN CHOOSE IN THE TAB IF THEY WANT WEIGHT OR PERCENTAGE.
NOT NECESSARY IF DIFFICULT

**Comment by litzvi** [comment]
QC REPORTS, WHEN OPENING DETAILS SHOWS SMALL SIZE AS PERCENTAGE, BUT IN PO#DETAILS SHOWS A NUMBER
(I PUT IN A NUMBER BECAUSE THAT'S WHAT IT SHOWED IN THE FORM)
ALSO IN QC REPORTS IT MIGHT BE NICE IF CLICKED ON THE PO PART OF THE ROW TO GET ALL CHECKS LIKE IN PO#DETAILS

**Comment by mei309** [comment]
ALSO, MIGHT BE NICER IF THEY CAN CHOOSE IN THE TAB IF THEY WANT. later i will do it.
ALLOW .6 FORMT. fixed
QC REPORTS, WHEN OPENING DETAILS SHOWS SMALL SIZE AS PERCENTAGE, BUT IN PO#DETAILS SHOWS A NUMBER. small size is input a number but its percantage of whole count

**Comment by litzvi** [comment]
small size is input a number but its percantage of whole count. 
WHY NOT ALLOW TO PUT IT IN AS PERCENTAGE?

**Comment by mei309** [comment]
or they put numbers or percentage so i will only change in the one of percentage

**Comment by litzvi** [comment]
EXACTLY
