### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#80]
build pieces of final report:
Po details: supplier, po#, received Quantity(kg, lbs)
Dates: Receipt, production (perhaps details)

**Comment by litzvi** [comment]
com.avc.mis.beta.service.ProcessInfoReader.getPoFinalReport(@NonNull Integer poCodeId) returns a PoFinalReport .
PoFinalReport should have the info needed to build the final report.
I'll send you an email with 2 Final report papers I have.

In version 5.1, I'll push it once i discuss the unitAmount issue

**Comment by mei309** [comment]
"id", "poCode", "supplierName" we dont need since i have it in the heder

**Comment by mei309** [comment]
ho really????? you didnt do anything. you giving me the same information i have already

**Comment by litzvi** [comment]
> "id", "poCode", "supplierName" we dont need since i have it in the heder

I know, it's because I'm reusing the same functions for the tables/reports. It's redundant, can be fixed later.

**Comment by litzvi** [comment]
> ho really????? you didnt do anything. you giving me the same information i have already

You don't have it in this form. Yes, I tried very hard to reused the DTOs and queries we already have, for more robust and flexible code.
You should have all the info they use in this class. If you're missing something, give a constructive comment.

**Comment by litzvi** [comment]
I looked at the final report, it would be nice if you will be more generous.
e.g. in order: item in separate column, order amount, receipt amount, extraAdded.
in QC: item, checked by
in relocation:  item in separate column, differences.
etc. etc.

**Comment by mei309** [comment]
I looked at the final report, it would be nice if you will be more generous. 
the full details

**Comment by mei309** [comment]
we need to show totales not all details. for that we have full details

**Comment by mei309** [comment]
i will change the item in a separate column and a row for each item and not all together

**Comment by mei309** [comment]
in relocation  i will add the difference and also add the checked by in qc

**Comment by litzvi** [comment]
yea that's what i said...

as much summery data in the room you are already occupying is better in my opinion. we can always remove if not needed.

**Comment by mei309** [comment]
in relocation i cant do difference because its not per item

**Comment by mei309** [comment]
see in version 8.2

**Comment by litzvi** [comment]
I don't really understand, so make it a joined column

**Comment by mei309** [comment]
ok i did it alone
