### ISSUE TITLE
loaded (loadedItems - leave for now)

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#83]
you arent giving all the fieleds

**Comment by mei309** [comment]
and loaded items is empty

**Comment by litzvi** [comment]
yes sorry just realized I didn't make a test for loading.
I'll make and let you know

**Comment by litzvi** [comment]
I'm making loadedItems not mandatory. 
perhaps I'll completely remove it later

**Comment by litzvi** [comment]
Ok I made a basic successful test without loadedItems.
see how it goes

**Comment by mei309** [comment]
we want loadeditems for the declerd amounts

**Comment by litzvi** [comment]
It's only in Ly's lots.
Maybe it's always the order amount or something like that.
I also think Ly's lots go in one separate container.

**Comment by mei309** [comment]
ok. lets leave for now

**Comment by mei309** [comment]
i think you should give it for consistency

**Comment by mei309** [comment]
unless it isnt easy

**Comment by litzvi** [comment]
it's very easy. I just plan to rethink the way we do it. you can totally remove it for now.

**Comment by mei309** [comment]
> it's very easy. I just plan to rethink the way we do it. you can totally remove it for now.

so meanwhile give it.

**Comment by mei309** [comment]
?

**Comment by litzvi** [comment]
not using it now. we need to ask them about it

**Comment by litzvi** [comment]
you can remove it for now

**Comment by mei309** [comment]
if we remove it we would not have the export page

**Comment by litzvi** [comment]
not sure what you mean by export page.
and why not?

**Comment by mei309** [comment]
getInventoryExportDoc and getSecurityExportDoc in loadings service

**Comment by mei309** [comment]
i think they using loaded for it

**Comment by litzvi** [comment]
not to my knowledge. did you check and it isn't working?

**Comment by mei309** [comment]
ok. its not dependent.
