### ISSUE TITLE
EDITING SUPPLIER

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#86]
When editing a supplier you don't show the name.
please show it and allow to edit - I changed it by me

**Comment by litzvi** [comment]
you are doing it everywhere. also editing an order you don't show po, supplier etc.

**Comment by mei309** [comment]
to give to edit the name? why?

**Comment by mei309** [comment]
showing is fixed

**Comment by litzvi** [comment]
OK. no need to edit a name for now.
Just because when I put in there data, I wanted to change a name.

**Comment by mei309** [comment]
i dont think changing a name is a good idea. they have no real way to find afterwards

**Comment by litzvi** [comment]
Eli asked me to allow to change a supplier for a po. He put in by mistake the wrong supplier in a po. So please change it.

**Comment by litzvi** [comment]
e.g. update po_codes set supplier_id = [supplier id] where code = [po code]

**Comment by mei309** [comment]
# @ELIPELET which po is it?

**Comment by litzvi** [comment]
I think you need to send him a message. he's not used to it yet

**Comment by mei309** [comment]
OK DONE
