### ISSUE TITLE
NEW CASHEW ORDER

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#88]
not special for this page but why is it showing contract date in USA format.
my computer is UK
if you need a default, it should be Vietnam

**Comment by litzvi** [comment]
cashew orders -> open
filters not working, specifically by supplier

**Comment by mei309** [comment]
the default is of angular. i will change to vietnam today

**Comment by litzvi** [comment]
what about the filters?

**Comment by litzvi** [comment]
now not convenient to write.
before i can just write 7, then it jumps to month say 11 then jumps to year.
now need to move the mouse, look in new order and see the difference between the dates.

**Comment by mei309** [comment]
what about the filters? working.
should i cancel the option for input?

**Comment by litzvi** [comment]
I was using the filters today and didn't encounter any problems for my use. They where great.
I used the input also, for searching POs by last digits.

**Comment by mei309** [comment]
ok. thanks. about the dates i will handle it later
