### ISSUE TITLE
Add shift and times for process

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#9]
shift, start time, finish time - mainly for productionProcess.
start time, finish time also for  QC, Receipt, ContainerLoading and StorageTransfer

**Comment by litzvi** [comment]
added startTime and endTime, left out the shift for now

**Comment by mei309** [comment]
start and end is with a date?? why? i think time alone is ok

**Comment by litzvi** [comment]
changed them to OffsetTime, will be in version 2

**Comment by mei309** [comment]
why not localtime??

**Comment by litzvi** [comment]
CORRECT

**Comment by litzvi** [comment]
changed version 4
