### ISSUE TITLE
Schedules

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#91]
the date chooser isn't a nice one.
it has no reaction after i choose the from date.
go into agoda.com or another to see nice ones

**Comment by litzvi** [comment]
also in the sums 

sum
--
null | 5.587 | 0.855 | 12 | 16.532 | 0.191 | 0.283 | 35.44800000000001

very long decimal and also not correct adding, since i'm giving you only 3 points

**Comment by litzvi** [comment]
can you please close with a comment

**Comment by mei309** [comment]
fixed. add this to styles.css
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
@import '~saturn-datepicker/bundle.css';

**Comment by litzvi** [comment]
it's not only style, it's actually doing a wrong calculation.
That's why I use BigDecimal and not double or float...

**Comment by mei309** [comment]
in next version the numbers are ok. since i put only 3 digits.

**Comment by mei309** [comment]
the styles is for the date range so its nicer

**Comment by mei309** [comment]
and i sent since styles isnt in src folder

**Comment by litzvi** [comment]
> in next version the numbers are ok. since i put only 3 digits.

it's not happening because of the digits, I'm giving you 3 points only.
It's because you using a floating point class number, so the results are not accurate.
cutting scale to 3 points is just a cosmetic cover up.

**Comment by litzvi** [comment]
> in next version the numbers are ok. since i put only 3 digits.

it's not happening because of the digits, I'm giving you 3 points only.
It's because you using a floating point class number, so the results are not accurate.
cutting scale to 3 points is just a cosmetic cover up.

**Comment by mei309** [comment]
officially typescript dont have bigdecimal so i think its ok since its only a show.
if you want i should make it correct i will download a library

**Comment by litzvi** [comment]
OK I see. as long as you don't use it for anything important.
