### ISSUE TITLE
Drop downs

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#92]
when searching in drop downs, it doesn't give the word you already typed.
e.g. i have D1, D10,D11
when i write d1 it only shows d10,d11

**Comment by litzvi** [comment]
also when you search in the tables, say bo po number that doesn't exist it displaces the table

**Comment by mei309** [comment]
the second one is fixed. some search in tables wouldnot work let me know if you see

**Comment by mei309** [comment]
when searching in drop downs, it doesn't give the word you already typed.
e.g. i have D1, D10,D11
when i write d1 it only shows d10,d11. 
where exactly please?

**Comment by litzvi** [comment]
any warehouse drop down, you can use my sql dump to see all these stuff

**Comment by mei309** [comment]
you dont read your massages and its very annoying. i cant find the dumps

**Comment by litzvi** [comment]
sorry I don't have my phone - sent hangout.
it's on the drive. I created a folder dumps

**Comment by mei309** [comment]
no problem thanks

**Comment by mei309** [comment]
> when searching in drop downs, it doesn't give the word you already typed.
> e.g. i have D1, D10,D11
> when i write d1 it only shows d10,d11

ITS WORKING BY ME WITH YOUR DUMP
