### ISSUE TITLE
locale types

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#95]
i have only those english. for now i put israel english
en_AS: "English (American Samoa)",
    en_AU: "English (Australia)",
    en_BE: "English (Belgium)",
    en_BZ: "English (Belize)",
    en_BW: "English (Botswana)",
    en_CA: "English (Canada)",
    en_GU: "English (Guam)",
    en_HK: "English (Hong Kong SAR China)",
    en_IN: "English (India)",
    en_IE: "English (Ireland)",
    en_IL: "English (Israel)",
    en_JM: "English (Jamaica)",
    en_MT: "English (Malta)",
    en_MH: "English (Marshall Islands)",
    en_MU: "English (Mauritius)",
    en_NA: "English (Namibia)",
    en_NZ: "English (New Zealand)",
    en_MP: "English (Northern Mariana Islands)",
    en_PK: "English (Pakistan)",
    en_PH: "English (Philippines)",
    en_SG: "English (Singapore)",
    en_ZA: "English (South Africa)",
    en_TT: "English (Trinidad and Tobago)",
    en_UM: "English (U.S. Minor Outlying Islands)",
    en_VI: "English (U.S. Virgin Islands)",
    en_GB: "English (United Kingdom)",
    en_US: "English (United States)",
    en_ZW: "English (Zimbabwe)",
    en: "English",

**Comment by litzvi** [comment]
sounds ok to me.
where does it matter?
I think UK is also pretty safe, unless it interferes with the keyboard.

**Comment by mei309** [comment]
dates and numbers.

**Comment by mei309** [comment]
I think UK is also pretty safe, unless it interferes with the keyboard. i dont think it dose

**Comment by litzvi** [comment]
what about the last one ? 
en: "English"
