### ISSUE TITLE
Inventory Report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#97]
I think we should split by item and po to different tabs, since it's requesting the data twice.
Also we would probably want to divide it later by raw, clean, roasted etc.

what do you think?

**Comment by mei309** [comment]
Also we would probably want to divide it later by raw, clean, roasted etc. definitely.

**Comment by mei309** [comment]
I think we should split by item and po to different tabs, since it's requesting the data twice.
its in 2 different tabs.
so what you mean??

**Comment by mei309** [comment]
i did like the orders in the main menu

**Comment by litzvi** [comment]
great

**Comment by mei309** [comment]
i should do it by me or by you?

**Comment by mei309** [comment]
doing by me means all i get all from the begining

**Comment by mei309** [comment]
doing by you its function with type in parmeter

**Comment by litzvi** [comment]
No. I basically have it already.

**Comment by mei309** [comment]
ok. i will use them

**Comment by litzvi** [comment]
it's lower priority now

**Comment by mei309** [comment]
i have a search in the top by category. i think its enough

**Comment by mei309** [comment]
later later we can change if it will be to much
