### ISSUE TITLE
Grouping in inventory by Item table

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#98]
I wrote about it already, but now i see it doesn't even group right, it's putting W320 item in the group of WS/LP.
I think you should remove it until it's fixed.

by the way, i have a dump of this data, if you want to see the bug as i see it..

**Comment by mei309** [comment]
i know this bug. im working on it.
but i will cancel also in this table the pangitor.
and i dont find the dump

**Comment by litzvi** [comment]
I uploaded to the drive again, sorry forgot to share :(
