### ISSUE TITLE
Inventory Report

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#99]
You should probably have a totals table, with a breakdown by item and by production stage etc.
Similar to what you did in schedules.

**Comment by mei309** [comment]
ok. i will try.

**Comment by mei309** [comment]
i dont really have it. 
we have totals for each item-productionStage 
doing the same table will require the change in item structure so i will leave it for now

**Comment by litzvi** [comment]
after we will divide the tables by production stage it will be easy

**Comment by mei309** [comment]
we actually have it already. i have filter by production stage and filter by item (includes therefor they can see all the totals.
later when we change item we might do it
